### ISSUE TITLE
CSS Override

### ISSUE THREAD

**Issue by snamstorm** [GwtMaterialDesign/gwt-material#10]
When we incorporated the library into our project, we noticed the css in the .jar overrides our existing css. Is there a work around for this?

**Comment by christianlacerda** [comment]
Are you referring to materialize.css being overridden or some of your own css classes?

**Comment by RLHawk1** [comment]
I'm not sure if this is something that the team is going to fix or not, but I experienced the same thing.

It seems you can't simply pull GWT-Material into your project and start using elements as you desire or converting screens one by one, because as soon as you pull it into your project, materialize.css overrides the default styling for a whole lot of stuff.

**Comment by asmaalej** [comment]
I'm newbie in both GWT framework and GWT_Material and I have experienced the same problem with my css file. So, when I add a css style to my Material widget in the UIbinder, I can't see the result in the screen, so I've understood that it's the override.css who is ovverriding my custom style, even when I tried to override other css files provided with the library (like materialize.blue.css).

So if someone could have any idea about this issue, I'll be very grateful

**Comment by asmaalej** [comment]
So what I ask about is how to make override.css of the gwt-material library take in account my css styling both into materialize.blue.css of the gwt-material library and my custom Css file referenced in my GWT project

**Comment by ledben** [comment]
Does the overridecss.css realy need to define selectors on such high level tag : 
table td {
	border: none !important;
	padding: 15px 5px !important;
}
Because of that, I can't use any table without pading.

**Comment by kevzlou7979** [comment]
@ledben  we have followed correctly the datagrid / datatable material design concepts so I think we strictkly used the css properties on material design

**Comment by ledben** [comment]
@kevzlou7979 Do you know a way to override it ?

**Comment by wassx** [comment]
remove the !important property of the tag style. Then you are able to add your custom resources/styles

**Comment by BenDol** [comment]
I have provided a GwtMaterialDesignBasic~ module you can use that doesn't load the materializecss.css and overridecss.css so you can manage it yourself.

**Comment by TDesjardins** [comment]
@BenDol For materializecss.css this is true but not for overridecss.css (anymore). GwtMaterialBasic~ module inherits gwt.material.design.ResourcesBasic which loads css/overridecss.css, css/animation.css and css/material-icons.css.

**Comment by kevzlou7979** [comment]
@TDesjardins We have updated the ```GwtMaterialBasic``` module to removed overridecss.css from it's resources https://github.com/GwtMaterialDesign/gwt-material/commit/9a0d69be3127f3b85405be72f1a6cd4cc12f1b39

**Comment by TDesjardins** [comment]
@kevzlou7979 Thanks!

**Comment by RLHawk1** [comment]
The problem with this solution is that using GwtMaterialBasic pretty stops any of GwtMaterialDesign's widgets from working at all in my experience. But pulling in overridecss.css breaks anything built with tables, etc.

If built from the ground up using GwtMaterialDesign, this is fine, but for adding it to existing projects neither of the above options are really feasible.
