### ISSUE TITLE
MaterialSlider onDetach error

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material#101]
If i add a MaterialSlider element inside a place, on PlaceChange, i get  the following error:
"Should only call onDetach when the widget is attached to the browser's document"

**Comment by kevzlou7979** [comment]
Yes I got the following issue also , I will take a look on the code

**Comment by kevzlou7979** [comment]
Ok I found out that when you use:

RootPanel.get().clear();
RootPanel.get().add(new MaterialSlider());

wont work.

Instead use this:
Your_Composite.this.removeFromParent();
RootPanel.get().add(new MaterialSlider());

this will work
