### ISSUE TITLE
MaterialGoogleIcon : Add google icons

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material#102]
https://www.google.com/design/icons/ is the icon set of Google Material Design, but in GWT porting some really important icons like, for example "star half" of "star bordered", are missing

**Comment by kevzlou7979** [comment]
Thanks for this @paulux84  we will add this implementation for the next release, this one is our previous target to include Google Material Design Icon lists. What we discussed is to use MaterialGoogleIcon that extends to Core MaterialIcon coponent :)
