### ISSUE TITLE
Fails to build | GWT 2.10.0 | Value 'ie10' in not a valid value for property 'user.agent'

### ISSUE THREAD

**Issue by michael-newsrx** [GwtMaterialDesign/gwt-material#1021]
```
Loading inherited module 'gwt.material.design.GwtMaterialWithJQuery'
      Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
         Loading inherited module 'gwt.material.design.jquery.JQuery'
            Loading inherited module 'gwt.material.design.jscore.JSCore'
               [ERROR] Line 27: Value 'ie10' in not a valid value for property 'user.agent'
```

**Comment by BenDol** [comment]
This should be resolved in the `2.6.0-SNAPSHOT`

**Comment by michael-newsrx** [comment]
I've come up with a work around of adding modified copies of the JQuery related *.gwt.xml files with the ie10 user-agent removed.

FYI:

I also had to exclude "gwt-user" and "gwt-dev" dependencies. Kept getting issues with gwt 2.9.0 showing up on the classpath.
(also had to do it for other dependencies)

**Comment by kevzlou7979** [comment]
You can check this commit https://github.com/GwtMaterialDesign/gwt-material-jquery/pull/36/commits/d403f10c97684d060076e64ee2431fa2904a79f4
