### ISSUE TITLE
MaterialIcons-Regular.woff2 and MaterialIcons-Regular.woff not found.

### ISSUE THREAD

**Issue by dieterblancke** [GwtMaterialDesign/gwt-material#1025]
Both the woff2 and woff versions of the material icons font give a 404.

When looking into it, it seems like neither is present in the resources: https://github.com/GwtMaterialDesign/gwt-material/tree/master/gwt-material/src/main/resources/gwt/material/design/public/font/material-icons

Yet both are mentioned / used in the material-icons.css file as can be seen here: https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/resources/gwt/material/design/public/css/material-icons.css#L8-L9

Should we just manually include these files then or is this a mistake?

**Comment by kevzlou7979** [comment]
The new update includes Manually adding the fonts , as Google recommend to import the fonts manually as it reduces only the needs you want for fonts.
