### ISSUE TITLE
Disable/Enable MaterialSwitch

### ISSUE THREAD

**Issue by petrosschilling** [GwtMaterialDesign/gwt-material#106]
Once the MaterialSwicth is set to disabled = true, there is no way to enable it again.

To apply the correction for the MaterialSwitch you must to modify the method setDisabled:

The actual Method:
```
public void setDisabled(boolean disabled) {
		this.disabled = disabled;
		cbBox.getElement().setAttribute("disabled", "true");
}
```
The new method with the correction:
```
public void setDisabled(boolean disabled) {
		this.disabled = disabled;
		cbBox.getElement().setAttribute("disabled", disabled);
}
```
If you watch closely you'll see that the value in the method setAttribute is always set to "true".

**Comment by kevzlou7979** [comment]
Yes its true there are bugs on disable and enable features . We are restructuring the code so that every widget will have the same functionality
