### ISSUE TITLE
navbar can not be collapsed ?

### ISSUE THREAD

**Issue by OrNot** [GwtMaterialDesign/gwt-material#11]
In the http://gwt-material.appspot.com, for the demo of navbar,  the "Custom Color" and "Wave" demo seems ok for the small screen but other demos can not see the collapsed menu .

**Comment by OrNot** [comment]
Furthermore, even for the "Custom color" and "Wave", when expanding on small screen, it is black blank

**Comment by kevzlou7979** [comment]
I just solved this bug, the data-activates attribute is undefined, so the only solution I just made is to create an automatic id using hashcode and set this to data-activates attribute.
