### ISSUE TITLE
MaterialDropDown does not show

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#111]
Hi! It seems that Material DropDown doesn't work, I mean it can't be seen when is it placed stand-alone in the UI. (I'm using the 1.3.4 version)
Any suggestions?

Below an example:

<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
             xmlns:g="urn:import:com.google.gwt.user.client.ui"
             xmlns:m="urn:import:gwt.material.design.client.ui">

    <ui:style>
        body{
            background: #fff;
        }
        .fieldPanel{
            padding-left: 1%;
            padding-right: 1%;
        }

    </ui:style>

    <m:MaterialPanel addStyleNames="{style.fieldPanel}">

        
        <m:MaterialPanel  ui:field="pnlHeader">
            <m:MaterialTitle title="XXX xx" description="" color="red"/>
        </m:MaterialPanel>

        
        <m:MaterialRow>
            <m:MaterialLink  icon="mdi-navigation-arrow-drop-down" iconPosition="right"  text="DropDown" textColor="white" activates="dropdown1"/>
            <m:MaterialDropDown  ui:field="dropdown1"  name="myDropDown" belowOrigin="false" constraintWidth="false" >
                <m:item><m:MaterialLink ui:field="lnkOne" text="One" /></m:item>
                <m:item><m:MaterialLink ui:field="lnkTwo" text="Two" /></m:item>
            </m:MaterialDropDown>
        </m:MaterialRow>

    </m:MaterialPanel>

</ui:UiBinder>

**Comment by BenDol** [comment]
This has been resolved in the up coming 1.4 release.
