### ISSUE TITLE
Feature request: MenuBar

### ISSUE THREAD

**Issue by anton-johansson** [GwtMaterialDesign/gwt-material#124]
Hi

I'd really like to see a MenuBar implementation in gwt-material. Here are some examples:
https://material.angularjs.org/latest/demo/menuBar
https://www.google.com/design/spec/components/menus.html#

I'd be happy to work on it myself, but I currently have no time, and a GitHub issue is in order anyway. :)

**Comment by kevzlou7979** [comment]
Its on process to release on gwt 1.5

**Comment by kevzlou7979** [comment]
http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#menubar This is the first version of menu bar
