### ISSUE TITLE
Feature request: progress bar/circle as standalone component

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#126]
Today we can use loaders (from http://gwt-material-demo.herokuapp.com/#loaders), which are good to show activity to the user at page scale... But sometimes a smaller, standalone component is needed to show some local progress (instead of whole page).

Here are the guidelines of what I mean: https://www.google.com/design/spec/components/progress-activity.html#progress-activity-behavior

**Comment by dlaunen** [comment]
Agreed.  I would also like to introduce the capability for certain widgets to support its own "loader", for example the DataTable may have a loading bar across the top of it.

Perhaps by adding a HasLoader interface and additionally a HasProgress extends HasLoader interface could also be defined which would allow the updating of the actual loading percentage (i.e. widget.getProgress().update(0.90);)

**Comment by BenDol** [comment]
Release 1.4 will have this functionality (if not already).

**Comment by kevzlou7979** [comment]
For stand alone I confirm it will be added on DOcument
