### ISSUE TITLE
DataGrid : Material Dropdown

### ISSUE THREAD

**Issue by foal** [GwtMaterialDesign/gwt-material#128]
How about Material Dropdown inside the DataGrid?

**Comment by wassx** [comment]
There was some similar in https://github.com/GwtMaterialDesign/gwt-material/commit/ea97a746426f73b88cbc0e9fa62d70a387a087e3#diff-383b05d14eb037d76b9a31bbcf879241 but was removed afterwards.

**Comment by foal** [comment]
And why? Will it be restored/re-implemented?

**Comment by kevzlou7979** [comment]
This will be implemented on gwt-material-datatable on 2.0
