### ISSUE TITLE
Card grid layout

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material#140]
In 1.4 version the card are not correcty layout using grid properties...for example if i set l3 i see only 3 element instead of 4. The problem is in the margin property vs old padding that work correctly.

This is what i see in setGrid method of card:

    removeStyleName("no-padding");
    addStyleName("no-padding");
    getElement().getStyle().setMargin(10, Unit.PX);

**Comment by kevzlou7979** [comment]
Ok let me check this part

**Comment by paulux84** [comment]
The grid styles "col sX mX lX" must be on a parent wrapper div like the old version

**Comment by kevzlou7979** [comment]
Yeah you may use MaterialColumn to wrap the card like This:
```xml
<m:MaterialRow>
<m:MaterialColumn grid="l3">
   <m:MaterialCard >
      <!-- Card Contents here -->
  </m:MaterialCard>
</m:MaterialColumn>

<m:MaterialColumn grid="l3">
   <m:MaterialCard >
      <!-- Card Contents here -->
  </m:MaterialCard>
</m:MaterialColumn>

<m:MaterialColumn grid="l3">
   <m:MaterialCard >
      <!-- Card Contents here -->
  </m:MaterialCard>
</m:MaterialColumn>

<m:MaterialColumn grid="l3">
   <m:MaterialCard >
      <!-- Card Contents here -->
  </m:MaterialCard>
</m:MaterialColumn>

</m:MaterialRow>

```

**Comment by paulux84** [comment]
simple workaround :+1:

**Comment by paulux84** [comment]
Sorry @kevzlou7979 , but i don't understand if this issue is definitevely solved in 1.4.1 milestone, Thanks

**Comment by BenDol** [comment]
I don't understand the problem can you provide an example implementation we could use to reproduce the problem?

**Comment by paulux84** [comment]
MaterialCard element nave set grid method, but if I set grid directly MaterialCad without a wrapping MaterialColumn the grid layout is incorrect.
