### ISSUE TITLE
MaterialModal works not multiple Times

### ISSUE THREAD

**Issue by mseele** [GwtMaterialDesign/gwt-material#141]
This is how i opened multiple dialogs (we have an edit dialog and need to display an error if something fails after editing) after each other in gwt-material 1.3.3:

		MaterialButton button = new MaterialButton();
		button.setText("Close Popup 1");
		button.addClickHandler(new ClickHandler() {
			@Override
			public void onClick(ClickEvent event) {
				MaterialButton button2 = new MaterialButton();
				button2.setText("Close Popup 2");
				button2.addClickHandler(new ClickHandler() {
					@Override
					public void onClick(ClickEvent event) {
						MaterialModal.closeModal();
					}
				});
				MaterialModal.showModal(button2, ModalType.DEFAULT, false);
			}
		});
		MaterialModal.showModal(button, ModalType.DEFAULT, false);

(I know i don't close the first dialog, but with clothing the first dialog in the first onClick, the second dialog never came up)

With gwt-material 1.4 after doing this, a "div" with class "lean-overlay" always remains infront of the ui. This is the bug i want to report.

Maybe i'm doing something wrong opening multiple dialogs after each other, but i found no other way than the above one.

**Comment by kevzlou7979** [comment]
Ok I am able to reproduce it, I will solve this one

**Comment by kevzlou7979** [comment]
This widget needs to be rewrite to have a multiple widget instances capability , because what we have now is just a static widget.

**Comment by mseele** [comment]
For now i use this as workaround:

	private static void removeOverlay() {
		BodyElement body = Document.get().getBody();
		NodeList<Element> divs = body.getElementsByTagName("div"); //$NON-NLS-1$
		for (int i = 0; i < divs.getLength(); i++) {
			Element element = divs.getItem(i);
			if ("lean-overlay".equals(element.getClassName())) { //$NON-NLS-1$
				element.removeFromParent();
			}
		}
	}

**Comment by BenDol** [comment]
Modal is only suppose to be static anyway. Perhaps non-static modals could be implemented, but currently materializecss doesn't support it.
