### ISSUE TITLE
JsInterop Implementation

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#142]
It might be good if we convert all JSNI to JsInterop

**Comment by kevzlou7979** [comment]
<b> JSInterop Start Document Guidelines </b>
[NextgenGWTJSInteropPublic.pdf](https://github.com/GwtMaterialDesign/gwt-material/files/42817/NextgenGWTJSInteropPublic.pdf)

**Comment by remarkNS** [comment]
I think it has to be done as widget will be abandoned completely in Gwt 3.0. The same is with UIBinder, Generators, Deferred binding, GWT-RPC. This will not happen tomorrow and it will not be deleted from gwt but nobody will invest or support this any more from version 2.8 which is coming in couple of weeks. For start, the most important is to replace all JSNI with JsInterop and make sure that all material widgets can be used from plain Java not only from UIBinder. Look at this info as a challenge and not as a bad luck and keep up the good work.

**Comment by kevzlou7979** [comment]
Yes I watch some videos on both GWT.Create() and GWT Con. We will try our best to implement this feature and will be available this coming month :)
