### ISSUE TITLE
Is there anyway to put the tab to the screen bottom ?

### ISSUE THREAD

**Issue by OrNot** [GwtMaterialDesign/gwt-material#144]
It is desired in a mobile device .

**Comment by kevzlou7979** [comment]
Material design specs does not intend to have a bottom tab. https://www.google.com/design/spec/components/tabs.html#
Double check and correct me if I'am wrong :)

**Comment by kevzlou7979** [comment]
But you can have a work around, just set your Tab's position to relative and set the bottom to 0.
e.g

```css
.tab-bottom{
 position: fixed;
 bottom: 0;
}
```
