### ISSUE TITLE
Calling the clear() method on MaterialTextBox on error state doesn't remove the error message.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#145]
To reproduce the problem:

Create a MaterialTextBox and 2 buttons: one that calls `setError()`, and one that calls `clear()` on the text box:

```java
final MaterialTextBox text = new MaterialTextBox();
text.setPlaceholder("Type something");

MaterialButton errorButton = new MaterialButton();
errorButton.setText("Error");
errorButton.addClickHandler(new ClickHandler() {
			@Override
			public void onClick(ClickEvent event) {
				text.setError("My error message");
			}
		});

MaterialButton clearButton = new MaterialButton();
clearButton.setText("Clear");
clearButton.addClickHandler(new ClickHandler() {
			@Override
			public void onClick(ClickEvent event) {
				text.clear();
			}
		});
```
When clicking on the Error button and then on the Clear button, the error message doesn't go away, and the component placeholder and bottom border stay colored in red.

That occurs when calling `setSucess()` before `clear()` as well.

**Comment by BenDol** [comment]
Hey thanks for the report, I have fixed the issue for 1.4.1 but I have opened an issue to improve the error handling of Material components. Something that will be more configurable and also respond better using value change handlers etc.
