### ISSUE TITLE
MaterialChip getText() is returning the text of the icon of the chip as a text prefix.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#147]
The current implementation of MaterialChip implements `getText()` as the following:
```java
public String getText(){
        return getElement().getInnerText();
}
```
The problem is that the text is not alone on the component: the close button is inside too, and every time the `getText()` is called, the text is returned with a "close" text as prefix.

That affects the the MaterialAutoComplete as well, since it uses MaterialChips internally. The method `getItemValues()` returns Strings with the "close" prefix. That can be seen on the online demo: http://gwtmaterialdesign.github.io/gwt-material-demo/#!autocomplete

![screenshot from 2015-11-18 22 09 31](https://cloud.githubusercontent.com/assets/7464735/11258542/307604b2-8e41-11e5-9b9b-d3c6a7ec16bc.png)

**Comment by kevzlou7979** [comment]
@gilberto-torrezan  Thanks for the issue, I am checking into it :)
