### ISSUE TITLE
When calling clear() on MaterialAutoComplete, the input box is removed as well.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#148]
When removing the chips of the auto complete, the `clear()` method also removes the input box as well, leaving the component unusable.

**Comment by kevzlou7979** [comment]
ok im checking your pull request

**Comment by kevzlou7979** [comment]
Ok I have implented the usage of clear function and its working fine.
<b>Result</b>
![autocomplete-issue-clear](https://cloud.githubusercontent.com/assets/3138071/11300425/ef570190-8fc9-11e5-9107-a6fff2b77d5e.gif)
<b>Code</b>
```java
         @UiField MaterialAutocomplete autocomplete;

         // to clear the autocomplete
         autocomplete.clear();
```
