### ISSUE TITLE
Material Icons not possible for intranet use only

### ISSUE THREAD

**Issue by mseele** [GwtMaterialDesign/gwt-material#149]
"ResourcesBasic.gwt.xml" has a reference to "https://fonts.googleapis.com/icon?family=Material+Icons". This is problematic if you want to use gwt-material in an intranet only (no internet access) application. A solution for that would be very helpfull.

I use
GwtMaterialBasicWithJQuery & GwtMaterialThemeBlue

**Comment by mseele** [comment]
My woraround is to patch the gwt-material-1.4.jar like it is descripted here: 
"http://google.github.io/material-design-icons/#icon-font-for-the-web" -> "Setup Method 2. Self hosting"

Change "ResourcesBasic.gwt.xml" -> stylesheet src="css/material-icons.css"
Add "gwt\material\design\public\font\material-icons" Folder with "MaterialIcons-Regular.woff2/woff/ttf/eot" files
Add gwt\material\design\public\css\material-icons.css with the following content

	@font-face {
	  font-family: 'Material Icons';
	  font-style: normal;
	  font-weight: 400;
	  src: url("../font/material-icons/MaterialIcons-Regular.eot"); /* For IE6-8 */
	  src: local('Material Icons'),
	       local('MaterialIcons-Regular'),
	       url("../font/material-icons/MaterialIcons-Regular.woff2") format('woff2'),
	       url("../font/material-icons/MaterialIcons-Regular.woff") format('woff'),
	       url("../font/material-icons/MaterialIcons-Regular.ttf") format('truetype');
	}

	.material-icons {
	  font-family: 'Material Icons';
	  font-weight: normal;
	  font-style: normal;
	  font-size: 24px;  /* Preferred icon size */
	  display: inline-block;
	  line-height: 1;
	  text-transform: none;
	  letter-spacing: normal;
	  word-wrap: normal;
	  white-space: nowrap;
	  direction: ltr;

	  /* Support for all WebKit browsers. */
	  -webkit-font-smoothing: antialiased;
	  /* Support for Safari and Chrome. */
	  text-rendering: optimizeLegibility;

	  /* Support for Firefox. */
	  -moz-osx-font-smoothing: grayscale;

	  /* Support for IE. */
	  font-feature-settings: 'liga';
	}

Here is the patched jar: 
https://drive.google.com/file/d/0B6e86GGLWDffVlhPN3RLVEZQdXc/view?usp=sharing

**Comment by wkok** [comment]
This workaround jar works for me too. Thanks for sharing.

**Comment by kevzlou7979** [comment]
Please provide a pull request into this thanks :)

**Comment by ronpx** [comment]
> Here is the patched jar:
> https://drive.google.com/file/d/0B6e86GGLWDffVlhPN3RLVEZQdXc/view?usp=sharing

Link not working. I took the complete font set here: https://github.com/apercova/material-icons-font
