### ISSUE TITLE
MaterialTabs no SelectionHandler

### ISSUE THREAD

**Issue by guibertjulien** [GwtMaterialDesign/gwt-material#15]
MaterialTabs have no SelectionHandler to indicate the selected tab has changed.

**Comment by OrNot** [comment]
Is it possible to provide a method to switch the tab just like selectTab(index)?

**Comment by kevzlou7979** [comment]
Hi,

On 1.3.3 we have added:
setTabIndex(index)to able to switch the tab.

Tutorial:
 http://gwt-material.appspot.com/#tabs

Regards,
GWT MAterial Design
