### ISSUE TITLE
Profile SideNav Component

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#151]
Adding a custom guideline on how to implement the profile sidenav element with image plus other components.

![image](https://cloud.githubusercontent.com/assets/3138071/11269508/4f918c52-8ef2-11e5-9903-2dc26d82b202.png)

**Comment by kevzlou7979** [comment]
Add this compoenent on 1.4.1

**Comment by kevzlou7979** [comment]
<b>Result</b>
![image](https://cloud.githubusercontent.com/assets/3138071/11274662/ccdb1e7c-8f14-11e5-821f-f88eb34ff438.png)
<b>Code</b>
```xml
            <m:MaterialSideNav type="OPEN" m:id="sideNav" closeOnClick="false" width="280">
                <m:MaterialSideProfile url="http://static1.squarespace.com/static/51609147e4b0715db61d32b6/521b97cee4b05f031fd12dde/5519e33de4b06a1002802805/1431718693701/?format=1500w">
                    <m:MaterialImage url="http://b.vimeocdn.com/ps/339/488/3394886_300.jpg" />
                    <m:MaterialLabel text="GWT Material" textColor="white"/>
                    <m:MaterialLink text="gwt-material@gmail.com" activates="dropProfile" iconType="ARROW_DROP_DOWN" iconPosition="RIGHT" textColor="white"/>
                </m:MaterialSideProfile>
            </m:MaterialSideNav>
```

**Comment by masterdany88** [comment]
How to do this with java. I've tried create this clas: MaterialSideProfile base on html above. But there is no class like that.

**Comment by gilberto-torrezan** [comment]
@masterdany88 You would do like this:
```java
MaterialSideNav sideNav = new MaterialSideNav();
sideNav.setType( //... sets everything you need
MaterialSideProfile sideProfile = new MaterialSideProfile();
sideProfile.setUrl( //... same here
sideNav.add(sideProfile);
```
In my opinion, if you are designing a new app, you really should consider doing it in a declarative way: it's way simpler to maintain in the long term, and is far more designer-friendly.

MaterialSideProfile is only available on 1.4.1 version as I know.

**Comment by kevzlou7979** [comment]
Yes I agree with Gilberto Torrezan, later we will do video tutorials who
are starting to learn gwt-material.

**Comment by masterdany88** [comment]
@gilberto-torrezan I've checked demo for 1.4 version. And there it is. By the way there is no such 1.4.1 version on maven
