### ISSUE TITLE
MaterialTextBox setText on UiBinder

### ISSUE THREAD

**Issue by paulux84** [GwtMaterialDesign/gwt-material#162]
Setting text directly on UiBinder produce no result.

**Comment by BenDol** [comment]
What component in particular? I haven't had this problem yet.

**Comment by kevzlou7979** [comment]
I confirm its working well with MaterialTextBox :) I tried it both UiBinder and Java .

**Comment by kevzlou7979** [comment]
Tried using Java / UiBinder -> Material Textbox, textArea , counter components are working
