### ISSUE TITLE
MaterialCutout : Avoid scrolling 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#165]
@gilberto-torrezan First, the MaterialCutout component is very very nice, I just saw some minor issues if we scroll up. Just take a look on the gif I attached.
![cutout](https://cloud.githubusercontent.com/assets/3138071/11354483/b638486e-9286-11e5-86fd-27072ff4128b.gif)

**Comment by gilberto-torrezan** [comment]
Ok, I'll intercept the scroll events when the CutOut is open to avoid that issue.

**Comment by kevzlou7979** [comment]
Ok thanks :)

**Comment by gilberto-torrezan** [comment]
Actually solved that by using the `Window.enableScrolling(boolean);` method from GWT.
