### ISSUE TITLE
Material CutOut : backgroundColor property not working and Target Element position is not correct

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#169]
@gilberto-torrezan thanks for the great job on Cut Out, I found some minor issues on the latest Material Cutout Component like the bakckground Color property is not working plus the position of the target element is not correct.

Here is my Code:
```xml
    <!-- Material CutOut -->
    <m:MaterialCutOut ui:field="cutout" backgroundColor="red" circle="true" opacity="0.5">
      <m:MaterialTitle title="New Feature" description="Description of new Feature" textColor="white"/>
      <m:MaterialButton ui:field="btnCutOutClose" text="Ok Got It" textColor="blue" backgroundColor="white"/>
    </m:MaterialCutOut>
```

My Java
``` java
   @UiHandler("btnCutOut")
    void onCutOut(ClickEvent e){
        cutout.setTarget(btnCutOut);
        cutout.openCutOut();
    }
```
Result Bug:
![cutout](https://cloud.githubusercontent.com/assets/3138071/11418067/5c7de31a-9457-11e5-9c25-4c803a1b5ca8.gif)

**Comment by kevzlou7979** [comment]
Hi , I just did a workaround about the color issue,
I think , if we get the computed color of the temp widget it does not recognize it because it wasn't added into the DOM.

So what I did is attached it then remove it until we get the converted rgba value:
This is the patch:
```java
        private void setupComputedBackgroundColor() {
        // temp is just a widget created to evaluate the computed background
        // color
        ComplexWidget temp = new ComplexWidget(Document.get().createDivElement());
        temp.setBackgroundColor(backgroundColor);
        add(temp);
        String computed = getComputedBackgroundColor(temp.getElement()).toLowerCase();
        // convert rgb to rgba, considering the opacity field
        if (opacity < 1 && computed.startsWith("rgb(")) {
            computed = computed.replace("rgb(", "rgba(").replace(")",
                ", " + opacity + ")");
        }
        temp.removeFromParent();
        computedBackgroundColor = computed;
    }
```

**Comment by gilberto-torrezan** [comment]
Well, it seems to be something browser-specific... on my tests I didn't need to add to the DOM to get the computed value.

**Comment by gilberto-torrezan** [comment]
I'll submit a pull request fixing the background color. The only thing I couldn't reproduce was the position issue (using the same code you provided, both on Chrome and Firefox).
