### ISSUE TITLE
MaterialTab: icons set on inner MaterialLinks don't show or are misplaced

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#171]
When setting icons on MaterialLinks inside a MaterialTab / MaterialTabItem, they don't show on Firefox (only the text is visible), and are misplaced on Chrome (they show on top left of the tab, instead of aligned to the text).

Test code:
```xml
<m:MaterialRow>
  <m:MaterialColumn grid="s12">
   <m:MaterialTab ui:field="tab" backgroundColor="blue" indicatorColor="yellow" waves="YELLOW">
    <m:MaterialTabItem waves="YELLOW" grid="s4">
     <m:MaterialLink text="Tab 1" href="#tab1" textColor="white" iconType="DESCRIPTION"/>
    </m:MaterialTabItem>
    <m:MaterialTabItem waves="YELLOW" grid="s4">
     <m:MaterialLink text="Tab 2" href="#tab2" textColor="white" iconType="BOOKMARK"/>
    </m:MaterialTabItem>
    <m:MaterialTabItem waves="YELLOW" grid="s4">
     <m:MaterialLink text="Tab 3" href="#tab3" textColor="white" iconType="GROUP"/>
    </m:MaterialTabItem>
   </m:MaterialTab>
  </m:MaterialColumn>
</m:MaterialRow>
```

**Comment by gilberto-torrezan** [comment]
I've found a workaround, not beautiful but it works:

```html
<ui:style gss="true">
    .tabAnchor > i {
        vertical-align: middle;
        padding-right: 10px;
    }
    .tabAnchor > span {
        vertical-align: middle;
    }
</ui:style>

<m:MaterialRow>
    <m:MaterialColumn grid="s12">
        <m:MaterialTab ui:field="tab" backgroundColor="blue" indicatorColor="yellow" waves="YELLOW">
            <m:MaterialTabItem waves="YELLOW" grid="s4">
                <m:MaterialLink text="Tab 1" href="#tab1" textColor="white" addStyleNames="{style.tabAnchor}">
                    <m:MaterialIcon textColor="white" iconType="DESCRIPTION" />
                </m:MaterialLink>
            </m:MaterialTabItem>
            <m:MaterialTabItem waves="YELLOW" grid="s4">
                <m:MaterialLink text="Tab 2" href="#tab2" textColor="white" addStyleNames="{style.tabAnchor}">
                    <m:MaterialIcon textColor="white" iconType="BOOKMARK" />
                </m:MaterialLink>
            </m:MaterialTabItem>
            <m:MaterialTabItem waves="YELLOW" grid="s4">
                <m:MaterialLink text="Tab 3" href="#tab3" textColor="white" addStyleNames="{style.tabAnchor}">
                    <m:MaterialIcon textColor="white" iconType="GROUP" />
                </m:MaterialLink>
            </m:MaterialTabItem>
        </m:MaterialTab>
    </m:MaterialColumn>
</m:MaterialRow>
```

**Comment by BenDol** [comment]
This only happens on the `MaterialTabItem`? If so perhaps we could search for MaterialIcon types when they are added to ensure it has the alignment style,

**Comment by gilberto-torrezan** [comment]
I think the problem is related to floats. When defining a standalone icon widget inside the `MaterialLink`, it doesn't inherit a `float: left` value - here is the catch.

The `vertical-align: middle` on my CSS is just to make the text and the icon to be aligned to each other.

**Comment by kevzlou7979** [comment]
I checked Material DropDown (Chrome) Its working fine :)

![image](https://cloud.githubusercontent.com/assets/3138071/11432014/aa075dea-94df-11e5-84a6-93aed2df4048.png)

I will take a look on that part to checked the MaterialLinks compatibility to other components.

**Comment by gilberto-torrezan** [comment]
Meanwhile on Firefox...

![screenshot from 2015-11-26 23 07 27](https://cloud.githubusercontent.com/assets/7464735/11432309/9eea2e8a-9492-11e5-8c2b-d0a241e1d430.png)

=(

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Ok now i see , Firefox is not ok. I will try to find a solution

**Comment by kevzlou7979** [comment]
I found which causes the error.
The order for the span and i elements are not correctly rendered

<b>Error</b>
![wrong](https://cloud.githubusercontent.com/assets/3138071/11432851/07636bb2-94f1-11e5-81bf-059ac7391e72.PNG)


<b>Correct</b>
![correct](https://cloud.githubusercontent.com/assets/3138071/11432871/5dee349e-94f1-11e5-830b-cc37c5a2634c.PNG)

**Comment by kevzlou7979** [comment]
Ok I fixed this issue

**Comment by kevzlou7979** [comment]
```xml
   @Override
    public void setIconType(IconType iconType) {
        icon.setIconType(iconType);
        insert(icon, 0);
    }
```

**Comment by kevzlou7979** [comment]
Follow this commit : https://github.com/GwtMaterialDesign/gwt-material/commit/d0f817a6d8cef1204813ec198985bf4bbed94c24 . Also I will add a showcase about using it on Material Tabs
