### ISSUE TITLE
Tabs : Support Icon plus link

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#173]
If Desktop:
Show Link + Icon

If Mobile:
Display only Icon

**Comment by kevzlou7979** [comment]
<b>Result on Desktop</b>

![tab-icon](https://cloud.githubusercontent.com/assets/3138071/11436527/7dd7276e-9520-11e5-985e-c6eda582bbfb.PNG)

<b>Result on Mobile</b>
![tab-icon-mobile](https://cloud.githubusercontent.com/assets/3138071/11436531/8731ec18-9520-11e5-9cb8-738eb1e6ec47.PNG)

**Comment by gilberto-torrezan** [comment]
That's nice, I had it implemented in my custom tabs (see #171), but it's good to have it native on the lib =)
