### ISSUE TITLE
Please provide an updated version of the navbar tutorial

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#175]
Still facing issues with the responsive sidebar.
thx

**Comment by kevzlou7979** [comment]
Yes I agree we need to improve the docs about the navbar and sidenav implementation.

**Comment by kevzlou7979** [comment]
Ok I updated the snapshot showcase site Sidenav documentation http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!sidenavs

**Comment by wassx** [comment]
Thank you very much!
