### ISSUE TITLE
Material NavBrand : setText is taking no effect

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#177]
After a MaterialNavBrand was drawn, is it possible to change the properties of the MaterialNavBrand? For example on button click I would like to call MaterialNavBrand.setText() to change the text to something else, however this has no effect.

**Comment by kevzlou7979** [comment]
@wkok This is available on 1.4.0,what version are you using?

**Comment by wkok** [comment]
Apologies, this happened due to my workaround I've put in place regarding the header html element that was missing from a MaterialNavBar.

After I've implemented the newly added MaterialHeader as described in #158, setText() on MaterialNavBrand is now working as expected.

This issue can be closed.

**Comment by kevzlou7979** [comment]
@wkok No worries :) Thanks
