### ISSUE TITLE
MaterialCard: MaterialLinks with icons are breaking the layout.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#180]
This is what's happening when you set MaterialLinks with icons inside MaterialCards:

![screenshot from 2015-11-30 22 17 59](https://cloud.githubusercontent.com/assets/7464735/11488829/bc1ccc6c-97b0-11e5-9ce3-1c3dcbc6bded.png)

To reproduce the bug:
```xml
<m:MaterialCard grid="s12">
    <m:MaterialCardContent>
        <m:MaterialCardTitle text="Something"/>
    </m:MaterialCardContent>
    <m:MaterialCardAction>
        <m:MaterialLink text="Option 1" iconType="LIST" />
        <m:MaterialLink text="Option 2" iconType="DASHBOARD" />
        <m:MaterialLink text="Option 3" iconType="GROUP" />
    </m:MaterialCardAction>
</m:MaterialCard>
```
Tested with Firefox and Chrome.

**Comment by BenDol** [comment]
Is this to do with the latest icon fixes?

**Comment by kevzlou7979** [comment]
I thought its an old issue. I just checked it .

**Comment by kevzlou7979** [comment]
Alright I solved the problem by adding display: inline-block; to action links.
