### ISSUE TITLE
MaterialTab: indicatorColor is a raw color, not a color class.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#181]
When using a material design color on `indicatorColor`, such as `green lighten-2`, you don't get the desired effect. That's because the `indicatorColor` parameter expects a raw color (such as `#fff` or `rgb(255,255,255)`), not a material color class.

```xml
<m:MaterialTab ui:field="tab" backgroundColor="green lighten-2" indicatorColor="green lighten-2">
    <m:MaterialTabItem>
        <m:MaterialLink text="My tab" href="#tab1" textColor="white" iconType="DESCRIPTION" />
    </m:MaterialTabItem>
</m:MaterialTab>
```
![screenshot from 2015-12-01 08 41 52](https://cloud.githubusercontent.com/assets/7464735/11498632/ab46bfea-9807-11e5-9559-32e8a0f353c7.png)

Note: that's the same issue I faced on MaterialCutOut. On that component I had to set a `box-shadow` color using material color classes. I solved the problem by creating a temporary Widget to evaluate the final, computed background color when using a material color class, and then applying that color on the `box-shadow`.

**Comment by BenDol** [comment]
Yeah, this is how it was designed to be. As you can see here http://materializecss.com/tabs.html don't apply individual indicator colors but instead control it via css, we just thought providing this in the widget would be easier.

But we could make setIndicatorColor apply the color like we do with setBackgroundColor I suppose.

**Comment by kevzlou7979** [comment]
Ok solved the issue , I created ColorHelper to calculate the Raw color of Material Color (e.g red lighten)

**Comment by kevzlou7979** [comment]
Fixed : https://github.com/GwtMaterialDesign/gwt-material/commit/34e260b7b0f59893c0963414808641d745ed58ed
