### ISSUE TITLE
Material Text Area getValue();

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#187]
It seems that textArea use textArea.getElement().getInnerHtml() instead of getValue() (from InputElement)

**Comment by BenDol** [comment]
shouldn't it be using `.getInnerText()`?

**Comment by gilberto-torrezan** [comment]
At `ValueBoxBase` from GWT we have this:
```java
public String getText() {
    return getElement().getPropertyString("value");
}
```
Which is used by the `getValue()` method.
