### ISSUE TITLE
Items in MaterialListBox do not display the first time

### ISSUE THREAD

**Issue by ye3i** [GwtMaterialDesign/gwt-material#19]
Items in MaterialListBox do not display the first time.

**Comment by kevzlou7979** [comment]
Hi,

Please submit your code so that we can reproduce you error. 

Best Regards,
Kevin

**Comment by ye3i** [comment]
I wrote sample code. It should illustrate what the problem is.
MaterialListBox not updated after the addition of items.

package test.client;

import gwt.material.design.client.ui.MaterialListBox;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.event.dom.client.ClickHandler;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.RootPanel;
import com.google.gwt.user.client.ui.VerticalPanel;

/**
 * Entry point classes define <code>onModuleLoad()</code>.
 */
public class Test implements EntryPoint {

  private MaterialListBox listBox;


  /**
   * This is the entry point method.
   */
  public void onModuleLoad() {
    listBox = new MaterialListBox();
    listBox.addItem("First");
    listBox.addItem("Second");
    listBox.addItem("Third");
    listBox.addItem("Fourth");
    listBox.addItem("Fifth");

    Button button = new Button("Add Six");
    button.addClickHandler(new ClickHandler() {
      public void onClick(ClickEvent event) {
        listBox.addItem("Six");
      }
    });

    VerticalPanel panel = new VerticalPanel();
    panel.setSpacing(10);
    panel.add(listBox);
    panel.add(button);

    RootPanel.get("gwtContainer").add(panel);

  }
}

**Comment by kevzlou7979** [comment]
Ok we just solved the issue, we digged into the Material ListBox it seems its not reupdating the items when you call addItem(). Now we fixed it by calling onInitMaterialListBox() once the user add an item.

**Comment by ye3i** [comment]
Thanks! Great Job :) but there is still one problem with MaterialListBox.
ChangeEvent does not work.

```java 
listBox.addChangeHandler(new ChangeHandler() {
      public void onChange(ChangeEvent event) {
        // Get the index of the selected Item
        Window.alert(listBox.getSelectedItemText());
      }
    });
```
