### ISSUE TITLE
MaterialTab: tabs with long texts and icons aren't centralized

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#194]
When you have a tab with a long text, and an icon set, the text don't get centralized inside the tab.

Here are some screenshots:

![screenshot from 2015-12-09 02 01 23](https://cloud.githubusercontent.com/assets/7464735/11676490/d08ce0b4-9e19-11e5-917b-28a0fc5a913e.png)

This is using the inspector, showing the boundary of the element:

![screenshot from 2015-12-09 02 01 47](https://cloud.githubusercontent.com/assets/7464735/11676483/b912d7ea-9e19-11e5-9af7-e7a1c5fb862f.png)

When you don't use icons, the text is centralized correctly:

![screenshot from 2015-12-09 02 03 13](https://cloud.githubusercontent.com/assets/7464735/11676489/cac2fbd2-9e19-11e5-9b53-29142d71a788.png)

I guess that occurs with small texts as well, but isn't as noticeable as when you use a large text.

Tested with Firefox and Chrome.

**Comment by BenDol** [comment]
Could be to do with the latest icon style changes.

**Comment by kevzlou7979** [comment]
![tab-fixed](https://cloud.githubusercontent.com/assets/3138071/11835838/59c45f2c-a411-11e5-8c55-8e83c5df5087.PNG)
Ok solved the problem, just the css styles issue.
