### ISSUE TITLE
DatePicker returns null-Date (Localization problem)

### ISSUE THREAD

**Issue by AScheuss** [GwtMaterialDesign/gwt-material#195]
If the locale is not set to English the MaterialDatePicker returns null-Date.

Concretely the method 
    onCalendarClose(Date date)
returns a null.

The problem lies probably in the getDatePicker-method:

    public Date getPickerDate() {
        try {
            DateTimeFormat sdf = DateTimeFormat.getFormat("d MMM, yyyy");
            date = sdf.parse(getDatePickerValue(id));
            return date;
        } catch(Exception e) {
            e.printStackTrace();
            return null;
        }
    }

The DateTimeFormat is dependent on the CurrentLocale. When, for example, the current Locale is GERMAN and one tries to get a date in December the parsing throws an error.
(Note that there is no problem with a date in September as it is written the same way in English and German)

So I think the problem is that the jQuery-method getDatePickerValue relies on English-locale.

**Comment by kevzlou7979** [comment]
With the new date functionality it will now be fixed.
