### ISSUE TITLE
MaterialCollectionItem: Can't use setVisible() method on item with waves

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#201]
Consider this code:

```xml
<m:MaterialCollection>
  <m:MaterialCollectionItem ui:field="item1" type="CHECKBOX" waves="DEFAULT">
   <m:MaterialLabel text="Item 1"/>
   <m:MaterialCollectionSecondary>
    <m:MaterialCheckBox value="false" type="FILLED"/>
   </m:MaterialCollectionSecondary>
  </m:MaterialCollectionItem>
  <-- Other collection items here -->
 </m:MaterialCollection>
```
If you set an item invisible by calling `item1.setVisible(false);` GWT adds a `display: none;` to the element inline style. The problem is when you set waves for a MaterialCollectionItem, the following style is applied (from overridecss.css):

```css
.collection-item.waves-effect {
    display: block !important;
    padding-bottom: 0px;
}
```
Because of the `!important`, the inline `display` style isn't applied, and the item remains visible.

The solution in this case is to set a inline `!important` style. To do so, you need to avoid the standard `setVisible(false);` method and call:

```java
item1.getElement().setAttribute("style", "display: none !important;");
```

... but, I don't see any need of the `display: block !important;` statement. When removing it, the waves effect still works without problems. Do you know why It was developed that way?

**Comment by kevzlou7979** [comment]
Ok now  the problem was solved by removing the !important on display: block property inside overridecss.
