### ISSUE TITLE
MaterialCard: Margin on component forces grid new lines when not needed

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#202]
Consider a MaterialRow with 3 MaterialCards:

```xml
<m:MaterialRow>
    <m:MaterialCard grid="l4">
      <m:MaterialCardContent>
            <m:MaterialCardTitle text="Card 1"/>
        </m:MaterialCardContent>
    </m:MaterialCard>
    <m:MaterialCard grid="l4">
      <m:MaterialCardContent>
            <m:MaterialCardTitle text="Card 2"/>
        </m:MaterialCardContent>
    </m:MaterialCard>
    <m:MaterialCard grid="l4">
      <m:MaterialCardContent>
            <m:MaterialCardTitle text="Card 3"/>
        </m:MaterialCardContent>
    </m:MaterialCard>
</m:MaterialRow>
```

When on a large screen, they should be aligned on the same row, side-by-side. But it's not what happens: 2 cards are aligned and the third is sent below:

![screenshot from 2015-12-12 16 12 35](https://cloud.githubusercontent.com/assets/7464735/11763306/08e679aa-a0ec-11e5-92e8-474405dedda4.png)

The reason is the margin of the card components. When using `box-sizing: border-box`, the content, padding and borders and accounted for the total width, but *not* the margins.

```java
//code from MaterialCard.java
@Override
public void setGrid(String grid) {
    super.setGrid(grid);

    removeStyleName("no-padding");
    addStyleName("no-padding");

    getElement().getStyle().setMargin(10, Unit.PX);
}
```
By removing the margins, we have the cards aligned on the row:

![screenshot from 2015-12-12 16 13 11](https://cloud.githubusercontent.com/assets/7464735/11763304/eb055a28-a0eb-11e5-8b39-1c4a44680fd6.png)

... but that way they are super ugly. To fix that, and to still allow the cards to be aligned on the row, we have to set the width of them, using CSS calc:

```css
/*Note: this is ignoring media queries for now, just to focus on the example*/
.card.l4 {
    width: calc(33.3% - 20px); /*where 20px is the sum of margin-right and margin-left
}
```

![screenshot from 2015-12-12 16 15 59](https://cloud.githubusercontent.com/assets/7464735/11763305/eb07bc50-a0eb-11e5-8a44-0b9eeeb16a3d.png)

My question is: where to put that css code? Which css file is maintained by GWT Material and which is maintained by the Materialize project (which GWT Material shouldn't touch)?

As a workaround, I'm maintaining a "override_again.css" file on my projects to deal with that case.

**Comment by BenDol** [comment]
Not sure why the margin was added to MaterialCard. This should be something the developer should decide to add. Thanks for spotting it.

**Comment by kevzlou7979** [comment]
Ok thanks for spotting that, I will change the card to let the user add margin into it. Thanks

**Comment by kevzlou7979** [comment]
http://materializecss.com/cards.html See this doc from Materializecss, the card requires a column component in order to make the grid works.
```xml
<m:MaterialColumn grid="l3">
   <m:MaterialCard>

   </m:MaterialCard>
</m:MaterialColumn>
```

Also I will remove now the hardcoded style margin and instead let the user decide

**Comment by gilberto-torrezan** [comment]
@kevzlou7979 The examples of MaterialCards on http://gwtmaterialdesign.github.io/gwt-material-demo/#!cards should be updated to follow that policy.

**Comment by kevzlou7979** [comment]
Ok I have updated the doc about Cards.
