### ISSUE TITLE
Whole browser content area is horizontally draggable when  MaterialRange is >0 && < 100

### ISSUE THREAD

**Issue by Kusig** [GwtMaterialDesign/gwt-material#203]
Encountered a very strange problem. The MaterialApp is properly working on a mobile device running Android 5.1 / Chrome Webview.  GWTMaterialDesign 1.5-SNAPSHOT

Once I add a MaterialRange control and move the Range to something eg. 50, the whole view becomes draggable horizontally.  If I set the value of the Range to 0 or 100, it doesn drag anymore.

Could reproducze this on Chrome DeveloperTools simulating a Nexus 5 vor example. Something simlar happens as well with the showcase when running in the simulator.

**Comment by kevzlou7979** [comment]
@Kusig can you provide me a screenshot because I can't replicate the issue on my side. Thanks

**Comment by Kusig** [comment]
It is somehow not possible to add videos here, I've copied them to GDrive:

This one uses my own applications styles, it is weired, as more as I move the slider, as more the area could be moved. But not if the value is 0 or 100:

https://drive.google.com/open?id=0B4A9PQVk5TVJS0NFY1pWeEhaWVE

This application was an early fork of the app template.

Could not reproduce this with the current showcase demo.

**Comment by kevzlou7979** [comment]
Fixed with Materializecss core files (0.97.5)
