### ISSUE TITLE
MaterialDatePicker placeholder text disappears after selecting date

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#207]
MaterialDatePicker.setPlaceholder("Date") correctly sets the placeholder text before a date is selected:
<img width="310" alt="screen shot 2015-12-18 at 11 45 17 am" src="https://cloud.githubusercontent.com/assets/5214136/11894046/4cea92fe-a57d-11e5-804d-e2e59b22de95.png">

However, after selecting a date, the placeholder text does not move to a heading on top as is the case with the other Material input fields:
<img width="229" alt="screen shot 2015-12-18 at 11 47 47 am" src="https://cloud.githubusercontent.com/assets/5214136/11894028/35e7b906-a57d-11e5-8ffa-ffb7485f917f.png">

**Comment by guaido79** [comment]
I've done a [PR](https://github.com/GwtMaterialDesign/gwt-material/pull/208) that fix it (release_1.5)

**Comment by wkok** [comment]
Excellent thanks
