### ISSUE TITLE
MaterialListBox placeholder text disappears after selecting 

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#210]
MaterialListBox.setPlaceholder("Select Category") correctly sets the placeholder text before a list item is selected:
<img width="384" alt="screen shot 2015-12-18 at 4 29 32 pm" src="https://cloud.githubusercontent.com/assets/5214136/11898982/99f9a342-a5a4-11e5-9872-39cb10440140.png">

However, after selecting a list item, the placeholder text does not move to a heading on top as is the case with the other Material input fields:

Selecting list item "Transport":
<img width="386" alt="screen shot 2015-12-18 at 4 31 35 pm" src="https://cloud.githubusercontent.com/assets/5214136/11899022/ff2b5ed6-a5a4-11e5-8425-d0a0fbfe0d1b.png">

The placeholder "Select Category" is lost so the field effectively has no title anymore:
<img width="382" alt="screen shot 2015-12-18 at 4 31 55 pm" src="https://cloud.githubusercontent.com/assets/5214136/11899050/2eeb252a-a5a5-11e5-99db-357407c095f1.png">

**Comment by BenDol** [comment]
Unfortunately this is not how materializecss handles list box placeholders.

http://materializecss.com/forms.html#select

You could make a feature request with them about it since it probably would be a nice feature.

**Comment by wkok** [comment]
Understood, thanks
