### ISSUE TITLE
MaterialListBox scrolling problem with a few items added

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#213]
When adding a few items to a MaterialListBox to cause it to start scrolling, the items move off of the screen and are un-selectable. 

For example the below MaterialListBox has 8 items added to select:
<img width="382" alt="screen shot 2015-12-23 at 1 15 51 pm" src="https://cloud.githubusercontent.com/assets/5214136/11975511/6f557914-a977-11e5-8149-f5ae887f6ac6.png">

But these items flow off the screen and are not visible or selectable:
<img width="385" alt="screen shot 2015-12-23 at 1 18 18 pm" src="https://cloud.githubusercontent.com/assets/5214136/11975536/b6aabe5a-a977-11e5-94b0-77ad53b88b98.png">

The scrolling stops prematurely as in the above example where it was scrolled all the way to the top

**Comment by kevzlou7979** [comment]
I think this one is a bug comming from Materializecss core files.

**Comment by gilberto-torrezan** [comment]
They have a fixed issue for that problem: https://github.com/Dogfalo/materialize/issues/2241

Maybe GWT Material is using an outdated Materialize css?

**Comment by kevzlou7979** [comment]
@Gilberto youre right we will include the fixes on gwt-material 1.4.1 to
include the recent files of Materialize

**Comment by kevzlou7979** [comment]
We updated now the Materialize source files from 0.97.2 to 0.97.5 (Latest) and fixed the listbox bug.
