### ISSUE TITLE
Floating Material SideNav comes out automatically

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#217]
With the last update of the 1.5 branch,  the "MaterialSideNav" comes out automatically rather than clicking the "MaterialNavBar"
![bug](https://cloud.githubusercontent.com/assets/13817916/11979234/019c8190-a992-11e5-82dc-a4f895908256.gif)

    <m:MaterialPanel >

        
        <m:MaterialNavBar backgroundColor="blue" activates="mysidebar">

            <m:MaterialNavBrand href="#PublicHome">Test</m:MaterialNavBrand>

        </m:MaterialNavBar>

        <m:MaterialSideNav width="300" m:id="mysidebar" type="FLOAT" closeOnClick="false">

            <m:MaterialLink iconType="ACCOUNT_CIRCLE" ui:field="lnk1" iconPosition="LEFT"  text="link1" waves="LIGHT"/>

            <m:MaterialLink iconType="LANGUAGE" ui:field="lnk2"   textColor="red"  text="link2" />

            <m:MaterialLink iconType="LANGUAGE" ui:field="lnl3"   textColor="red"  text="link3" />

        </m:MaterialSideNav>

    </m:MaterialPanel>

**Comment by kevzlou7979** [comment]
Hi @MarcoCucchi It is stated on material design spec that CARD, FLOAT are part of Permanent Types meaning by default the side nav is open.

**Comment by kevzlou7979** [comment]
Here is the reference : https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior

**Comment by MarcoCucchi** [comment]
Hi @kevzlou7979, thank you for reply, so the sidebar it can't be closed or hidden?

**Comment by kevzlou7979** [comment]
There is a specific type of it I am currently fixing some of those : MINI / CLOSE types

**Comment by MarcoCucchi** [comment]
Great!

**Comment by kevzlou7979** [comment]
I will Ping you once it is done.

**Comment by MarcoCucchi** [comment]
Thank You very much @kevzlou7979

**Comment by kevzlou7979** [comment]
Hi the type="CLOSE" now is available on 1.5.0 branch you can now check it out.

**Comment by MarcoCucchi** [comment]
Awesome! thank you @kevzlou7979

**Comment by kevzlou7979** [comment]
@MarcoCucchi Welcome
