### ISSUE TITLE
MaterialSideNav closes on click even if closeOnClick="false"

### ISSUE THREAD

**Issue by Kusig** [GwtMaterialDesign/gwt-material#218]
I have a MaterialSideNave on the right side (similar as in the Demo application). The difference is that I don't want the sidenav to close if an option is choosen, it shall stay open up until the menu button is pressed again.

Here is my definition. Working with latest 1.5 Snapshot:

<m:MaterialSideNav m:id="filterbar" type="OPEN" closeOnClick="false" edge="RIGHT" fixed="false"> 

Any idea what might be wrong here?

**Comment by kevzlou7979** [comment]
Can you share the code coz I cant reproduce on my side? Thanks

**Comment by Kusig** [comment]
There's no magic so far:
Here the menu button in the header:
         <m:MaterialLink iconType="MENU" addStyleNames="button-collapse" activates="filterbar" float="RIGHT" circle="true" waves="LIGHT" width="64px" textAlign="CENTER" iconPosition="NONE"/>

And here the SideNav:
       <m:MaterialSideNav ui:field="rightSideNav" m:id="filterbar" type="OPEN" closeOnClick="false" edge="RIGHT" fixed="false" addStyleNames="{appRes.styles.rightSideBar}"> 
          <m:MaterialLink><m:MaterialIcon iconType="POLYMER" circle="true" waves="LIGHT" padding="0" /></m:MaterialLink>
       </m:MaterialSideNav>

There is no Java code involved with this yet.

Checked the code of MaterialSideNav but I don't understand it yet. I don't see where I could hook in the debugger in chrome to see why it invokes the close anyhow.

I tried to set the property as well on initialisation phase in code:
rightSideNav.setCloseOnClick(false);
But debugging this showed that it doesn't have an effect at all. The property within the MaterialSideNav isn't used anymore, it is only used on Initialization. So manipulating this doesn't have any effect later on. This might as well be a small issue but isn't this one here as I have the property set as well in the markup.

**Comment by Kusig** [comment]
As soon as a click event in the MaterialSideNave happens, there is a style display:none applied to the <ul ..>  tag:

`<ul class="side-nav open ch-gbrain-app-resources-AppStyles-rightSideBar right-aligned" id="filterbar" style="right: 0px; width: 64px; position: absolute; top: 0px; opacity: 1; display: none;">`

**Comment by Kusig** [comment]
Very strange, My right sidebar is rendered inside the "nav" section although the left sidebar is rendered outside. It is defined equally to the demo showcase. 
![rightsidebarclose](https://cloud.githubusercontent.com/assets/11767529/12004595/46b59282-ab66-11e5-9d41-a2fe05b31242.JPG)

**Comment by Kusig** [comment]
Due to the problem I tried to use the MaterialSideNav autonomous, without a linked button and to handle show/hide myself. However, this starts to throw the exception from the initialize method in MaterialSideNav because it is quite bound strong to styles and forces an existsing "activates" and "button-collapse" style..

` protected void initialize(boolean strict) {
        if(activator == null) {
            activator = DOMHelper.getElementByAttribute("data-activates", getId());
            if (activator != null && activator.getClassName().contains("button-collapse")) {
...`

I think MaterialSideNav is too strong bound to styles which must exist which might be the source of the problem I have. This doesn't allow to use this component standalone without an attached MaterialLink.

**Comment by Kusig** [comment]
Catching the exception in the view at least is a workaround to use the MaterialSideNav without a bound activator:

  `@Override
  protected void onAttach(){
    try {
      super.onAttach();
    }catch(Exception ex) {
      logger.log(Level.WARNING,"Failure on Attach",ex);
    }
  }`

This way, the Sidebar could be invoked "manually" by the setVisible(true/false) method. and there is no need to have bound activator defined in the UiBinder anymore.

However, of course the initial problem, why the closeOnClick flag doesn't work,  is still not resolved.


Finally my conlusions are for MaterialSideNav:
- Allow to use the widget as well without a bound activator element by removing the exception.

- Make the widget less dependent on existing style button-collaps

- Make the rendering of the ul independent of the activator widget so it is outside the navbar (see screenshot above).

**Comment by kevzlou7979** [comment]
With the new implementation, we changed the sidenav implementation. See the documentation on new snapshot http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!sidenavs
