### ISSUE TITLE
No Callback in MaterialAnimator after animation completion

### ISSUE THREAD

**Issue by Kusig** [GwtMaterialDesign/gwt-material#223]
Tried to FadeIn / FadeOut an element with MaterialAnimator. The animation works perfect but the element disappears again afterwards (same behaviour as in the DemoShowcase. Looking at the code I see that after the timeout time given, the animation style is removed. Therefore I assume I have to react and to do something once the animation timeout trigger.

`MaterialAnimator.animate(Transition.FADEINRIGHT, filterSidebar,1000, new ShowAnimationComplete());
 private class ShowAnimationComplete implements Runnable {
    public void run()
    {
        filterSidebar.setVisible(true);
    }
}`

But the runnable is never invoked. From the code within MaterialAnimator I could not see how and if the Callback runnable is called at any time. Is this a bug or is it intended to be used in a different way?

**Comment by kevzlou7979** [comment]
Ok I found the problem , will ping you once its done

**Comment by kevzlou7979** [comment]
Ok fixed now

**Comment by Kusig** [comment]
Wow, that was quick! Thanks, I was still debugging on this one.

Wouldn't it be good if the Animator allows to keep an element "out" by default. Some of the animations (mainly all with "Out" in the name, eg FadeOut ) only make sense if the element isn't shown anymore afterwards. This is possible by hooking in a callback of course. 

Probably it would be good if one could give this as a parameter "showAfterAnimation" and the element stays invisible up until the next style is applied (eg. FadeIn). 
WDYT?
