### ISSUE TITLE
Multiple DataPickers 

### ISSUE THREAD

**Issue by matthew-dev** [GwtMaterialDesign/gwt-material#226]
Hi. I'm trying to have 2 datapickers to let user set birthdate and also hiredate, both datapickers are situated on the same view (this view is a content of a modal view). Strange thing is that if I try to set a value to hiredate picker, it'd be unsuccessfull (the value of hiredate picker would not change) and moreover the given value would be set to birthdate picker (setting a value for the first birthdate picker just works). Both datepickers are defined by UiBinder, the birthdate picker is defined first. I'm sorry if this issue has been resolved previously, but I haven't found any for this case.

Also I'd like to ask somebody in charge, which day is scheduled for a release of 1.4.1, couse there is some usefull staff for my application I actually need ASAP... Does anybody have any idea?

**Comment by gilberto-torrezan** [comment]
Can you provide a small, self-contained code that shows the problem?

**Comment by kevzlou7979** [comment]
please provide a code snippet including java and uibinder so that we can replicate it

**Comment by matthew-dev** [comment]
first I'd like to thank you for your quick response,

so here I've uploaded the [code with a few comments](http://pastebin.com/dNtQVZGL)

* This is a starting screen before pressing any key:
![image](https://cloud.githubusercontent.com/assets/16544141/12126316/ceaaea88-b3f0-11e5-8886-434f981db328.png)

* This is a screen after pressing + key:
![image](https://cloud.githubusercontent.com/assets/16544141/12126896/3c325138-b3f4-11e5-90c0-7ddae66964ef.png)

* This is the last screen after pressing - key:
![image](https://cloud.githubusercontent.com/assets/16544141/12126906/48718860-b3f4-11e5-894f-4e2794262733.png)

**Comment by kevzlou7979** [comment]
Ok I reproduce the same bug as you posted, Thank you for your clear bug Submission. I am working now to solved this issue

**Comment by kevzlou7979** [comment]
I have tried the 1.4.0 -> The bug occurs, but on 1.4.1 this one was solved.
