### ISSUE TITLE
Create simple Phonegap application using gwt-material framework 

### ISSUE THREAD

**Issue by Neotrixsx** [GwtMaterialDesign/gwt-material#23]
Hi Friends,
I need some example by which I can create my phonegap app. I saw many examples in a website, but all in xml format, please help me to create my simple phonegap application using the gwt - material framework.

**Comment by kevzlou7979** [comment]
You can checkout the github GwtMaterialPhonegap here https://github.com/GwtMaterialDesign/gwt-material-phonegap.
