### ISSUE TITLE
MaterialFloatBox not displaying values higher than 999

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#230]
```
MaterialFloatBox floatBox = new MaterialFloatBox();
floatBox.setValue(new Float(999));
```

Correctly results in:
<img width="375" alt="screen shot 2016-01-08 at 4 49 02 pm" src="https://cloud.githubusercontent.com/assets/5214136/12200518/e32f57d0-b627-11e5-8e89-05a0e8fecbd2.png">

But when setting the value to 1000 or more:
```
MaterialFloatBox floatBox = new MaterialFloatBox();
floatBox.setValue(new Float(1000));
```

The value in the box is empty:
<img width="376" alt="screen shot 2016-01-08 at 4 49 25 pm" src="https://cloud.githubusercontent.com/assets/5214136/12201065/ed295f9e-b62a-11e5-8ae4-8098bc351c27.png">

**Comment by wkok** [comment]
I've narrowed this problem down to gwt.material.design.client.base.FloatRenderer.render()

If I replace `NumberFormat.getDecimalFormat().format(object)` with `object.toString()` then the value gets set correctly.

However, I don't think this would be an acceptable fix as surely NumberFormat.getDecimalFormat() should be the more correct way to render the value?

Not sure if it's related to my locale

**Comment by kevzlou7979** [comment]
Ok I got the issue here, it seems that when you run ```NumberFormat.getDecimalFormat().format(object)``` it returns ```1,000``` then when you apply it a number textbox it will display it since there was ```,``` symbol so it needs to be removed when redering it

**Comment by gilberto-torrezan** [comment]
I guess this issue is related to  #231.

**Comment by kevzlou7979** [comment]
Reference http://www.gwtproject.org/javadoc/latest/com/google/gwt/i18n/client/NumberFormat.html, Im doing now on how we can format the String using the lists of regex patterns.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Yeah there's a possibility.

**Comment by kevzlou7979** [comment]
I think this one will solve the problem http://stackoverflow.com/questions/4713166/decimal-separator-in-numberformat

**Comment by gilberto-torrezan** [comment]
@kevzlou7979 The FloatRenderer and the FloatParser should use the same rule for formatting and parsing respectively. Currently, the FloatRenderer uses:

```java
public String render(Float object) {
    if (object == null) {
      return "";
    }

    return NumberFormat.getDecimalFormat().format(object);
  }
```

So I think that putting `NumberFormat.getDecimalFormat().parse(object);` on FloatParser will fix it.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Thanks for the response I will give it a shot :)

**Comment by gilberto-torrezan** [comment]
@wkok @kevzlou7979 I created a PR fixing this issue, but it changed a lot of the internals of the NumberBoxes. Basically, when dealing with `<input type="number">`, the browser is responsible for parsing and formatting the number - so the API shouldn't try to do it. To validate the implementation we need testing with several browsers and locales.

**Comment by wkok** [comment]
Thank you, I'll test it out
