### ISSUE TITLE
MaterialFloatBox throws undefined error when entering decimal operator

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#231]
When adding a GWT UncaughtExceptionHandler like the following:

```
        GWT.setUncaughtExceptionHandler(new GWT.UncaughtExceptionHandler() {

            @Override
            public void onUncaughtException(final Throwable err) {
                Window.alert(err.getMessage());
            }
        });
```

Then when entering a "." (full stop) or a "," (comma) to denote the cents part of an amount for example, the the following error gets thrown:
<img width="467" alt="screen shot 2016-01-08 at 5 22 25 pm" src="https://cloud.githubusercontent.com/assets/5214136/12201332/7284bd54-b62c-11e5-811a-ab3d094cb62f.png">

**Comment by gilberto-torrezan** [comment]
The internal implementation of the FloatParser looks suspicious:

```java
    public Float parse(CharSequence object) throws ParseException {
		if ("".equals(object.toString())) {
			return null;
		}

		try {
			return new Float(object.toString().replaceFirst(",", "."));
		} catch (NumberFormatException e) {
			throw new ParseException(e.getMessage(), 0);
		}
	}
```
It should use `NumberFormat.getDecimalFormat().parse()` to parse it. I don't know if that's the cause of the problem, but the current implementation looks strange.

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/12622395/0faaf5f2-c560-11e5-96b6-c1a470e58e8d.png)

Provided a screen about the resolved issue.

**Comment by wkok** [comment]
Excellent thank you
