### ISSUE TITLE
HasFlexBox: Error setting the display attribute on UiBinder

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#233]
The HasFlexBox interface defines two methods with the same name:
```java
void setDisplay(Style.Display display);

void setDisplay(Display display);
```
And that causes a problem when you define a `display` attribute on UiBinder on any MaterialWidget:
```xml
<m:MaterialPanel display="NONE" />
```
The error is:
```
[ERROR] Ambiguous setter requested: MaterialPanel.display
```

**Comment by gilberto-torrezan** [comment]
@chriswjones Do you have any suggestions on this matter (since you're the author of the interface)? I'm thinking on removing the `void setDisplay(Style.Display display);` method or changing its name to something like "void setGwtDisplay(Style.Display display);".

**Comment by chriswjones** [comment]
@gilberto-torrezan changing the method name for setting the Style.Display should work.

**Comment by gilberto-torrezan** [comment]
Well, it wasn't *just* HasFlexBox... the HasInlineStyle has reference to Style.Display too. That created a chain reaction all over the project. Please take a look on my PR.
