### ISSUE TITLE
Tab indicator color

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#234]
The tab's indicatorColor changes when I load another function. (es. in the last 1.5 Snapshot, by clicking from "Tabs" to "Scrollspy" and back to "Tabs", tabs' indicator color were originally yellow became bue)

![tabs](https://cloud.githubusercontent.com/assets/13817916/12229827/89d3f5bc-b84b-11e5-8c62-1f3182085c03.gif)

**Comment by kevzlou7979** [comment]
It seems there was an issue into the DOM, it creates another ```.indicator``` items automatically every init of the DOM for Tab component.

**Comment by kevzlou7979** [comment]
Fixed https://github.com/GwtMaterialDesign/gwt-material/commit/b7b566da1e539a4c53f4a8ca07a76da35049ebf9 both master and 1.5 branches
