### ISSUE TITLE
Time of MaterialTimePicker 

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#235]
The method getTime() of MaterialTimePicker doesn't return the selected value. (i'm using the last versione on 1.5 snapshot)

**Comment by kevzlou7979** [comment]
@MarcoCucchi Thanks for the catch, will ping you if everything is good

**Comment by kevzlou7979** [comment]
Fixed https://github.com/GwtMaterialDesign/gwt-material-addins/commit/c83bfb265ebdd9cc0968677486286886b6f6bf1c
