### ISSUE TITLE
MaterialCheckBoxCell into dataGrid

### ISSUE THREAD

**Issue by MarcoGervasoni** [GwtMaterialDesign/gwt-material#237]
In my application i've tried to use the datagrid and celltable and i've found some problems. The problems are all about MaterialCheckBoxCell and fieldUpdater:
- with DataGrid it's possible to unchecked the checkBox in the view but the filedupdate isn't fired
- with CellTable it's impossible to unchecked the checkBox  and the filedupdate is fired
To explain better i have implemented the test case GWtWithMaterial.

Otherwise in my application i use the DataGrid with dataProvider (like MaterialDemoSource) but i have found that:
- with DataGrid it's impossible to unchecked the checkBox and filedupdate is fired many times.
To explain better i have implemented the test case GWtWithMaterialWithDataProvider.

To solve these issues i have tried change the MaterialCheckBoxCell with MyMaterialCheckBoxCell that is attached here. The patches are:
- remove BrowserEvents.CLICK from super into constructor
- into onBrowserEvent  parent.getFirstChild().cast() with  parent.getFirstChild().getFirstChild().cast(); to get the input and not the span.

My patch doesn't solve the DataGrid without dataProvider because the fieldupdaer isn't fired.

**Comment by masini** [comment]
[testcase.zip](https://github.com/GwtMaterialDesign/gwt-material/files/87258/testcase.zip)

**Comment by gilberto-torrezan** [comment]
Another way to solve that is to just use the icon of the checkbox on the cell (`IconType.CHECK_BOX_OUTLINE_BLANK`). When clicked, switch the state of the object (or of the selection model) and use the icon of the checked checkbox (`IconType.CHECK_BOX`).

**Comment by wassx** [comment]
@MarcoGervasoni Thanks a million. Saved me from some headache

**Comment by BenDol** [comment]
Closing this for now, since the data table will be replaced with our in house table.
