### ISSUE TITLE
MaterialTextArea - getText() / getValue()

### ISSUE THREAD

**Issue by ARMistice** [GwtMaterialDesign/gwt-material#239]
getText() does not work and returns empty String.

getValue does not exist. What is the preffered way to get Values from input fields? 
getText/getValue?

I added to MaterialTextArea

    public String getValue(){
    	return textArea.getElement().getPropertyString("value");
    }
    public void setValue(String text) {
        textArea.getElement().setPropertyString("value",text);
        label.addStyleName("active");
    }

**Comment by kevzlou7979** [comment]
Thanks I am reproducing now the bug you had,

**Comment by kevzlou7979** [comment]
What version are you using?

**Comment by ARMistice** [comment]
I am using 1.4 (as it seemed to me (from the description) thats the best stable version)

**Comment by kevzlou7979** [comment]
On 1.4.1 the getText() is working fine? Anyone there can confirm that it works on 1.4.1?

**Comment by kevzlou7979** [comment]
By the way 1.4.1 is currently our master branch, will fixed the branching strategy after 1.4.1 will be released

**Comment by ARMistice** [comment]
Okay seems to work with the master branch .. I used the maven 1.4 which does not.

**Comment by kevzlou7979** [comment]
@ARMistice Yeah on 1.4.1 the bug fix release for 1.4
