### ISSUE TITLE
ChangeEvent in MaterializeListBox does not work.

### ISSUE THREAD

**Issue by ye3i** [GwtMaterialDesign/gwt-material#24]
There is still one problem with MaterialListBox.
ChangeEvent does not work.

```java 
listBox.addChangeHandler(new ChangeHandler() {
      public void onChange(ChangeEvent event) {
        // Get the index of the selected Item
        Window.alert(listBox.getSelectedItemText());
      }
    });
```

**Comment by ye3i** [comment]
Is there any way to be able to use it? Or maybe I am doing something wrong?

**Comment by anton-johansson** [comment]
+1

Also wondering why this doesn't work.

**Comment by anton-johansson** [comment]
I implemented a workaround for this. Note that I'm not extending ```MaterialListBox``` because all it does is call a ```.material_select()```.

```java
public class CustomListBox extends ListBox
{
	private final String id;

	public CustomListBox()
	{
		this.id = UUID.randomUUID();
		getElement().setId(this.id);
	}

	@Override
	protected void onLoad()
	{
		super.onLoad();
		createInternalChangeHandler(this.id, this);
	}

	private void onChangeInternal()
	{
		// Do your thing!
	}
	
	private static native void createInternalChangeHandler(String id, CustomListBox self)
	/*-{
		var callback = $entry(function()
		{
			self.@com.viskan.client.components.CustomListBox::onChangeInternal()();
		});
		
		$wnd.jQuery('#' + id).material_select();
		$wnd.jQuery('#' + id).change(callback);
	}-*/;
}
```

I could submit a pull request for fixing ```MaterialListBox``` this way, but I'd rather see a proper solution only using native GWT without using JSNI. Any ideas or thoughts?

**Comment by kevzlou7979** [comment]
@anton-johansson -> Thanks for this , Yes Im ok with your workaround just submit a pull request and we will merge it :).
We are happy that we have at least a solution on this part.

Regards,
kevzlou7979

**Comment by anton-johansson** [comment]
@kevzlou7979: Allright, I'll work on it. Hopefully I can get rid of the ```UUID.randomUUID()``` also. One question though. Should we make this work with ```addChangeHandler(ChangeHandler)```? I'm relatively new to GWT and I haven't investigated exactly how the event handlers work yet.

**Comment by kevzlou7979** [comment]
@anton-johansson - you can use DOM.createUniqueId() for better solution . Yes sure you, I tested your code running pretty well. Thank you

**Comment by anton-johansson** [comment]
Ahh, of course. Thanks!
