### ISSUE TITLE
MaterialCollectionItem - Dismissable

### ISSUE THREAD

**Issue by ARMistice** [GwtMaterialDesign/gwt-material#240]
The dismissable does not work, either on the demo page (1.4) nor in my Project .. 
materializecss is working

**Comment by gilberto-torrezan** [comment]
For reference: 

* [Materialize collections](http://materializecss.com/collections.html)
* [GWT Material collections (current version)](http://gwtmaterialdesign.github.io/gwt-material-demo/#!collections)
* [GWT Material collections (snapshot version)](http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!collections)

**Comment by kevzlou7979** [comment]
Thanks for the issue, we are on our way to resolve it

**Comment by kevzlou7979** [comment]
Do you have any idea on how can I debugged easily using my browser to reproduce it using the Swipe event functionality, because on my side everytime i test I just need to deploy it on external server to view it on mobile.

**Comment by gilberto-torrezan** [comment]
@kevzlou7979 When running the super dev mode on the machine, add this to the launch configuration:

```
-bindAddress 0.0.0.0
```

That way you can run the app on the development machine from any device that can access it on the local network.

I have this setting on one of my `gwt.xml` files, but I don't really know if it is really needed:

```xml
<set-configuration-property name="devModeUrlWhitelistRegexp" value="http://(localhost|127\.0\.0\.1|10\.10\.1\.100)(:\d+)?/.*" />
```
(In this case 10.10.1.100 is the local IP of my machine)

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Thanks for the information I will try this out

**Comment by ARMistice** [comment]
Other way: Use Chrome to debug and after pressing F12/Developer console you can toggle the "Smartphone Display" in the top left. and in the bottom next to "Console" is "Emulation" where you can emulate touch screen and geo location stuff ...

**Comment by gilberto-torrezan** [comment]
@ARMistice That can help to simulate screen sizes and some touch events, but still it is not as reliable as the device itself. For example, see #227.

**Comment by kevzlou7979** [comment]
@ARMistice Thanks for the information

**Comment by kevzlou7979** [comment]
I tried to debugged the app it seems that Materialize.js are not getting the list of .dismissable DOM elements.

You can paste this on Browser Console after the loading of the DOM :
``` javascript
jQuery('.dismissable').each(function() {
      jQuery(this).hammer({
        prevent_default: false
      }).bind('pan', function(e) {
        if (e.gesture.pointerType === "touch") {
          var $this = jQuery(this);
          var direction = e.gesture.direction;
          var x = e.gesture.deltaX;
          var velocityX = e.gesture.velocityX;

          $this.velocity({ translateX: x
              }, {duration: 50, queue: false, easing: 'easeOutQuad'});

          // Swipe Left
          if (direction === 4 && (x > ($this.innerWidth() / 2) || velocityX < -0.75)) {
            swipeLeft = true;
          }

          // Swipe Right
          if (direction === 2 && (x < (-1 * $this.innerWidth() / 2) || velocityX > 0.75)) {
            swipeRight = true;
          }
        }
      }).bind('panend', function(e) {
        // Reset if collection is moved back into original position
        if (Math.abs(e.gesture.deltaX) < (jQuery(this).innerWidth() / 2)) {
          swipeRight = false;
          swipeLeft = false;
        }

        if (e.gesture.pointerType === "touch") {
          var $this = jQuery(this);
          if (swipeLeft || swipeRight) {
            var fullWidth;
            if (swipeLeft) { fullWidth = $this.innerWidth(); }
            else { fullWidth = -1 * $this.innerWidth(); }

            $this.velocity({ translateX: fullWidth,
              }, {duration: 100, queue: false, easing: 'easeOutQuad', complete:
              function() {
                $this.css('border', 'none');
                $this.velocity({ height: 0, padding: 0,
                  }, {duration: 200, queue: false, easing: 'easeOutQuad', complete:
                    function() { $this.remove(); }
                  });
              }
            });
          }
          else {
            $this.velocity({ translateX: 0,
              }, {duration: 100, queue: false, easing: 'easeOutQuad'});
          }
          swipeLeft = false;
          swipeRight = false;
        }
      });

    });

```
This one will work, I therefore conclude that the initialization of the dismissable comes first before the setting of DOM elements which returns an empty list of dismissable collection item.

Is there any way to handle the initialization? I've tried to alter the Materialize.js file to wrap it into a function like 
``` javascript

function initDismissableCollection(){
    / ** code goes here for the dismissable login **/
}

```
just to make it works but its not a good workaround.

**Comment by gilberto-torrezan** [comment]
What about calling that function at `onLoad()` of MaterialCollection (or every time a new component is added after the initialization, like what is done at MaterialListBox) ?

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Yeah but the future problem is when Materialize guys will release a new version then we need to re-add again the method we add. Which is not a good solution.

**Comment by gilberto-torrezan** [comment]
Well, we could open an issue asking for them to use named functions instead of anonymous ones to initialize stuff. I don't know if they would implement it.

**Comment by kevzlou7979** [comment]
As for the moment I added a hook for the initDismissableCollection on separate js file. https://github.com/GwtMaterialDesign/gwt-material/commit/c2f1dc235510fce1f930abab3ba2e05e5bd488f8
