### ISSUE TITLE
MaterialWidget: Make it implement InsertPanel.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#244]
The methods from the com.google.gwt.user.client.ui.InsertPanel interface are already there (`add(Widget)`, `insert(Widget, int)`, `getWidgetCount()` and so on), but MaterialWidget doesn't implement it explicitly.

**Comment by kevzlou7979** [comment]
Im just thinking if we can implement HasWidget interface? Im not sure about it.

**Comment by kevzlou7979** [comment]
Please see this update https://github.com/GwtMaterialDesign/gwt-material/commit/72515de08a2c30cab0149be39de917dc2ffaa142
