### ISSUE TITLE
MaterialListBox: setting items from UiBinder.

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#248]
After the commit that changed the super class of MaterialListBox (from ListBox to MaterialWidget), isn't possible to add items on it through UiBinder, like this:

```xml
<m:MaterialListBox >
    <m:item>One</m:item>
    <m:item>Two</m:item>
    <m:item>Three</m:item>
</m:MaterialListBox>
```
The reason is that ListBox uses a custom parser, deep buried on the darkest dungeon of the internals of GWT ([see the code](https://gwt.googlesource.com/gwt/+/2.7.0/user/src/com/google/gwt/uibinder/elementparsers/ListBoxParser.java)).

When not using ListBox as super class, we lose the ability to use that custom parser for inner tags.

...So, it's just a matter of creating another custom parser, right?

... not so fast. According to [this e-mail thread](https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/TXn3KQMFJ8U), creating a custom parser was suggested, but not implemented. So we can't create a custom parser for MaterialListBox without hacking GWT itself.

But there's another way: [@UiChild](http://www.gwtproject.org/javadoc/latest/index.html?com/google/gwt/uibinder/client/UiChild.html). With this annotation you can add Widgets to your component using custom methods.

Like this:
```java
@UiChild
public void addItem(OptionElement element) {
///...
}
```
The UiBinder declaration would not be so nice, but still doable:
```xml
<!-- add the dom package -->
xmlns:dom="urn:import:com.google.gwt.dom.client" 
<!-- ... -->
<m:MaterialListBox >
    <m:item><dom:OptionElement text="One"/></m:item>
    <m:item><dom:OptionElement text="Two"/></m:item>
    <m:item><dom:OptionElement text="Three"/></m:item>
</m:MaterialListBox>
```
...except that it doesn't work for raw Elements. You *must* use Widgets.

So, the only way is to create a Widget wrapper for the OptionElement:

```java
public class MaterialOptionElement extends Widget implements HasText {
        public MaterialOptionElement() {
            setElement(Document.get().createOptionElement());
        }

        @Override
        public String getText() {
            return OptionElement.as(getElement()).getText();
        }

        @Override
        public void setText(String text) {
            OptionElement.as(getElement()).setText(text);
        }
        
        public String getValue() {
            return OptionElement.as(getElement()).getValue();
        }

        public void setValue(String value) {
            OptionElement.as(getElement()).setValue(value);
        }
    }
```
and then declare it on the `@UIChild` method:
```java
@UiChild
public void addItem(MaterialOptionElement element) {
    getSelectElement().add(OptionElement.as(element.getElement()), null);
    //...
}
```
...and on the UiBinder we'd have:
```xml
<m:MaterialListBox >
    <m:item><m:MaterialOptionElement text="One"/></m:item>
    <m:item><m:MaterialOptionElement text="Two"/></m:item>
    <m:item><m:MaterialOptionElement text="Three"/></m:item>
</m:MaterialListBox>
```
... which, in my opinion, is super ugly. If we can't escape from using a Widget, I think we could just override the `add(Widget)` method and do some `instanceof` checks:

```java
@Override
public void add(Widget child) {
    if (child instanceof MaterialOptionElement){
        getSelectElement().add(OptionElement.as(child.getElement()), null);
    }
    else {
        super.add(child);
    }
}
```
And the UiBinder becomes:
```xml
<m:MaterialListBox >
    <m:MaterialOptionElement text="One"/>
    <m:MaterialOptionElement text="Two"/>
    <m:MaterialOptionElement text="Three"/>
</m:MaterialListBox>
```

So what do you think about all this stuff?

Related: #247.

**Comment by dlaunen** [comment]
@gilberto-torrezan what happens if you override add method and include a new add(MaterialOptionalElement element) method?  Does that blow up UiBinder?  If so, I +1 your last solution, that just makes sense, MaterialListBox should inspect and handle the added widget appropriately IMO.

**Comment by gilberto-torrezan** [comment]
@dlaunen  Good idea, I thought it would really blow up the UiBinder (because of #233), but it actually don't: overloading the `add(Widget)` with `add(MaterialOptionalElement element)` works nicely. No more `instanceof` tests! =)

**Comment by gilberto-torrezan** [comment]
Guys, created this pull request for you to comment. I added the Option widget as an OptionElement wrapper (on html package, where there are lots of classes like this), and the final structure of the UiBinder declaration became:

```java
<m:MaterialListBox>
    <m:html.Option text="One" value="1"/>
    <m:html.Option text="Two" value="2"/>
    <m:html.Option text="Three" value="3"/>
</m:MaterialListBox>
```

Opinions?

**Comment by kevzlou7979** [comment]
+1
