### ISSUE TITLE
MaterialCollectionItem with checkbox has click event in padding leading to unwanted clicks

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#249]
The class ".collection .collection-item" has a padding:10px 20px which is causing a border on the top of the item, where the clickhandler is triggered and the checkbox activated. Should we change the padding to margin instead?
![box](https://cloud.githubusercontent.com/assets/3955210/12494430/69017b6a-c08a-11e5-97ba-091f41812779.png)

There is an additional issue with the item's clickhandler because it is setting the secondary's state. So when i try to add a MaterialSwitch as a secondary, the click inverts/resets the switch's state despite it's currently set value.

**Comment by kevzlou7979** [comment]
The clicking on items are desired to be there, its a clickable collection item as discussed here https://material.angularjs.org/latest/demo/list See on the checkbox part. For the border-top problem , I think its a default style provided by Materialize guys
