### ISSUE TITLE
Improvement for demopage: Search for component via tag or string

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#250]
There are so much items/components on the demo page, that i sometimes find myself searching for a component multiple times. A search for tags (e.g. input, form, selectable,...) would be very handy.
Just as an input for demopage improvements.

**Comment by kevzlou7979** [comment]
@wassx Thanks we will provide this feature :)

**Comment by kevzlou7979** [comment]
<b>Ongoing Development</b>
<br/>
Desktop View
![search_result_desktop](https://cloud.githubusercontent.com/assets/3138071/12529504/e614906e-c1f3-11e5-8dac-3175db77f0fd.gif)



Mobile View
![search_result_mobil](https://cloud.githubusercontent.com/assets/3138071/12529476/a668e560-c1f2-11e5-8737-defd567c2a7b.gif)

**Comment by BenDol** [comment]
:+1: great job Kevin

**Comment by wassx** [comment]
Wow. It's like x-mas. :) thx

**Comment by kevzlou7979** [comment]
Now you can take a look on it LIve : http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/
