### ISSUE TITLE
Submenu in dropdown

### ISSUE THREAD

**Issue by MercusChan** [GwtMaterialDesign/gwt-material#256]
Hi,

Seems submenu in dropdown is not support.
![d9220d65b5c4aa36459a23c6a2c62fa46783e6c2](https://cloud.githubusercontent.com/assets/17057914/12804442/3c172ce0-cb2e-11e5-8a61-38c3a0b90d37.png)

any possible way to implement?

Thanks.

**Comment by kevzlou7979** [comment]
Yes we will implement this

**Comment by kevzlou7979** [comment]
You can now wrap your multi-dropdown by menubar addin component.
<img src="https://lh3.googleusercontent.com/uW98M-Qqsu_LNpw0YUjA-FRfZxMw5h8qt2lHOOqYOGtT6BWq4c4FLzGILmPETPqe3aOy=w1107-h623-rw-no"/>
