### ISSUE TITLE
MaterialModal depth (z-index) management problem introduced by the bundled 3rd party JS dependency

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material#257]
Hi all,

today I noticed that there is a problematic impl. in the way the z-index is managed for layering modals.

MaterialModal widgets start at an z-index of 1000 and lower their z-index value whenever another is opened/closed. So essentially, after a lot of open/close operations, a modal would no longer be shown in front of other elements like a MaterialSideNav or MaterialNavBar. 

For example, the MaterialNavBar applies the CSS class "pinned" which itself has a hardcoded z-index value of 996 (override.css). See:

https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/resources/gwt/material/design/public/css/overridecss.css#L448

So after opening/closing a modal 3 times in sequence, the HeaderNavBar will show up in front of the modal's shadow. When I was looking for a solution I found that the problematic algorithm is baked into the 3rd-party JS library:

https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/resources/gwt/material/design/client/resources/js/materialize-0.97.5.js#L700

Well, I also found the setDepth() method where I could set the z-index of a widget -- but -- it turned out the z-index set operation in the JS library is implemented in a callback that is called deferred at runtime...

To fix the issue there are several ways (that I didn't want to go):
- I could fork the JS, change/fix it and use this resource but I would loose upstream compatibility.
- I could introduce a hack with long-deferred setDepth() calls for every modal I'm using.

Well, removing the static z-index 996 definition would solve the urgent problem. But my application runs in my users browsers for days without reloads and so... there will be a time when no modal works anymore.

Well, if gwt-material would not depend on such 3rd-party JS libraries, I could, in case of any bug or unexpected behaviour, just extend the widget, change the implementation by overriding a method or two and omit any introduction of such hacks... :)

So, next to the issue itself, what are your plans on this topic? 
Is there any goal to set the project free of 3rd-party JS dependencies?

Thanks, :)
Aron

**Comment by kyr0** [comment]
Another static z-index in 3rd-party materialize.css:

.fixed-action-btn {
  position: fixed;
  right: 23px;
  bottom: 23px;
  padding-top: 15px;
  margin-bottom: 0;
  **z-index: 998;**
}

**Comment by kevzlou7979** [comment]
Hi @kyr0 Thanks for catching that issue, Yes we are depending on Materializecss core files, we have also set Addins component for the standalone plugin for the project. 

For the layering issue, we have standard specs (Using Material Design specs) and Materialize does the layering also https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-elevation-android-. For the remaining issues we will try to navigate deeply to set the correct elevation of each component as stated on the Specs. But for modals I dont think , the overlapped modals are good UX maybe you can make use of <a href="http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#steppers">Steppers</a> inside Modal instead.

**Comment by kevzlou7979** [comment]
There was also an issue on NavBar Pinned elevation, we solve this asap.

**Comment by kevzlou7979** [comment]
@kyr0 Modal/Windows are a feature that GWD will be adding, and managing the zindex will be part of that also, we will see if materializecss already has this issue raised/fixed and double check that. We will provide an overview of the elevations of Material Widgets and post that on the showcase app also the usage of setDepth().

Also @kyr0 Can you provide a testcase or code samples so that we can determine the issue :)

Thanks :)

**Comment by kyr0** [comment]
@kevzlou7979 Thank you for the very fast response :) I think the root cause really is the materialize.js decreasing (because of a math miscalculation, the intention is a increase as L700 shows) the z-index value for any new modal creation instead of increasing that value -- so the same issue should be even reproducable when using materialize JS only and a fix of the JS library will fix "ours". I'm currently a bit in a hurry to finish a project here -- but as soon as I have a little spare time I will provide code samples, fix etc. :)

**Comment by kevzlou7979** [comment]
@kyr0 Yeah we will log an issue to materialize guys about the problem on layering of modals.

**Comment by kevzlou7979** [comment]
@kyr0 What gwt-material version are you using?

**Comment by kyr0** [comment]
@kevzlou7979 I'm using 1.5.0-SNAPSHOT

**Comment by kevzlou7979** [comment]
I am playing with Multiple modals on the showcase app, but it seems the calculation is on increasing order from 1003 -> 1009 . It's weird also on how they increment (+2). By the way for thorough checked I filed an issue with materialize about it so that they can test it also and reproduce it. https://github.com/Dogfalo/materialize/issues/2788

![multi-modals](https://cloud.githubusercontent.com/assets/3138071/13010106/2595a682-d1db-11e5-9188-22ec7e9c3f5e.gif)

**Comment by kevzlou7979** [comment]
@kyr0 Please check the way i reproduce it , if we have the same logic to reproduce the bug, i will be glad to help you :)

**Comment by kevzlou7979** [comment]
@kyr0 Mr Alvin Wang responded to the issue https://github.com/Dogfalo/materialize/issues/2788 and confirmed that its working. Please can you show us a little example and code snippet?

**Comment by kevzlou7979** [comment]
Any new @kyr0 ?

**Comment by kyr0** [comment]
Hi @kevzlou7979 I'm sorry, the issue still is reproducable here but I had no time yet to create some example, code snippet / record it etc. I just switched to use windows instead of modals for now. Windows are not adding a specific z-index so they are working fine here atm. I will investigate again if I find some spare time.

**Comment by kevzlou7979** [comment]
Ok we are also communicating with Materialize to reproduce the issue

**Comment by BenDol** [comment]
Can we get a status update on this?

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/aea52ac9a51fa4131a05fdac4d8c7426488af3e0
