### ISSUE TITLE
sidenavs (Card Permanent on 1.5 snapshot)

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#259]
Hi, it seems that the Sidebars icons and the related text, are moved on top of the item field and smaller compared to the previous version. (which is on the site)
Below the previous and the actual sidenav.

![actual](https://cloud.githubusercontent.com/assets/13817916/13016640/4f0d2492-d1c0-11e5-8776-acf04e302312.png)
![previous](https://cloud.githubusercontent.com/assets/13817916/13016642/514ae99c-d1c0-11e5-9d94-b332ce601571.png)

**Comment by kevzlou7979** [comment]
@MarcoCucchi Thanks for this validation, Fixed now on https://github.com/GwtMaterialDesign/gwt-material/commit/71f8a36282aaf9b4ec7c71d722c455664a75d74f

**Comment by MarcoCucchi** [comment]
@kevzlou7979  my pleasure to help You on your project.
