### ISSUE TITLE
no expand when clicked on MaterialCollapsible dynamically created

### ISSUE THREAD

**Issue by guibertjulien** [GwtMaterialDesign/gwt-material#26]
When i add dynamically item in MaterialCollapsible, there is no expand on click.

MaterialCollapsibleItem collapsibleItem = new MaterialCollapsibleItem();
collapsibleItem.addHeader( new MaterialLink("title", "blue"));
collapsibleItem.addContent( new MaterialLabel("label"));
MaterialCollapsible collapsible.addItem(collapsibleItem);

Thx.

**Comment by kevzlou7979** [comment]
Hi I run code it seems the code is working well (I modified your code like this):

MaterialCollapsibleItem collapsibleItem = new MaterialCollapsibleItem();
collapsibleItem.addHeader( new MaterialLink("title", "blue"));
collapsibleItem.addContent( new MaterialLabel("label"));
MaterialCollapsible collapsible = new MaterialCollapsible();
collapsible.addItem(collapsibleItem);


you can automatically make it expand by

**Comment by guibertjulien** [comment]
Yes it's OK like this but KO with uibinder:

	@UiField
	public MaterialCollapsible collapsible;

	<m:MaterialCollapsible ui:field="collapsible">
	</m:MaterialCollapsible>

Thx a lot.

**Comment by kevzlou7979** [comment]
Hi,

Below is the code which is a correct structure when you are adding an automatic Expanding behavior inside a MaterialCollapsible.

Regards,
Kevin
====================================================
	@UiField MaterialCollapsible collapsible;



	public HomePanel() {
		initWidget(uiBinder.createAndBindUi(this));
		MaterialCollapsibleItem collapsibleItem = new MaterialCollapsibleItem();
		MaterialLink link = new MaterialLink("title", "blue");
		link.setActive(true);
		collapsibleItem.addHeader(link);
		collapsibleItem.addContent( new MaterialLabel("label"));
		collapsible.add(collapsibleItem);
	}

======================================================
