### ISSUE TITLE
Add handlers on time and date picker

### ISSUE THREAD

**Issue by NP-85** [GwtMaterialDesign/gwt-material#262]
hi, what kind of handler can i add on timePicker?
for example, after setting hours and minute and click on 'OK', i need to clear setError message.
thanks.

**Comment by kevzlou7979** [comment]
Ok we will add an event handlers on it : Open Close Events

**Comment by kevzlou7979** [comment]
Ok we have now implemented the open/close events for TimePicker component :
https://github.com/GwtMaterialDesign/gwt-material-addins/commit/e563f8a26ef6f725c27f7376d64f64bbf34d02f2
``` java
// Open Handler
        tpEvents.addOpenHandler(new OpenHandler<String>() {
            @Override
            public void onOpen(OpenEvent<String> event) {
                MaterialToast.fireToast("Opened Time Picker");
            }
        });
        // Close Handler
        tpEvents.addCloseHandler(new CloseHandler<String>() {
            @Override
            public void onClose(CloseEvent<String> event) {
                MaterialToast.fireToast("Closed Time Picker");
            }
        });
```
