### ISSUE TITLE
HasPlaceholders: Wrong position of the placeholder label

### ISSUE THREAD

**Issue by gilberto-torrezan** [GwtMaterialDesign/gwt-material#263]
This can be seem on the [live demo](http://gwtmaterialdesign.github.io/gwt-material-demo/#!forms).

On GWT Material, the placeholder label of input fields are not aligned to the input itself:

![screenshot from 2016-02-16 16 59 11](https://cloud.githubusercontent.com/assets/7464735/13087479/4af56038-d4cf-11e5-96c0-799ecb5d330f.png)

![screenshot from 2016-02-16 16 59 23](https://cloud.githubusercontent.com/assets/7464735/13087480/4af7ff6e-d4cf-11e5-9dc3-b2d8bd377f90.png)

![screenshot from 2016-02-16 16 59 47](https://cloud.githubusercontent.com/assets/7464735/13087481/4afb3454-d4cf-11e5-8e5a-2ce8e3b3265f.png)

The label is slightly shifted to the right.

As you can see on [Materializecss](http://materializecss.com/forms.html), the labels are aligned correctly as they should be (according to the [spec](https://www.google.com/design/spec/components/text-fields.html#text-fields-labels)):

![screenshot from 2016-02-16 17 00 01](https://cloud.githubusercontent.com/assets/7464735/13087482/4b00e908-d4cf-11e5-921d-4e26e2f86123.png)

I tried to figure out what's wrong with the labels, but the CSS looks just right. I fixed it locally in my project by adding a rule to my own CSS:

```css
.input-field label {
	left: 0;
}
```
... but that's not ideal. Any ideas of what is causing the problem?

**Comment by kevzlou7979** [comment]
Hi @gilberto-torrezan ,

I found where the issue came from : 
I took time to study the Materializecss text fields. It seems that they are wrapping the text fields into Rows and columns like this :

```

<div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="Placeholder" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
          <input id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input disabled value="I am not editable" id="disabled" type="text" class="validate">
          <label for="disabled">Disabled</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
    </form>
  </div>

```

So what will be the solution is wrap your textfields / form fields into rows to provide a better view for your forms:

```

<m:MaterialRow>

   <m:MaterialTextBox grid="s12" placeholder="First Name" />
   <m:MaterialTextBox grid="s12" placeholder="Last Name" />
   <m:MaterialTextArea grid="s12" placeholder="About" />

</m:MaterialRow>

```

I will update also the showcase app :)

**Comment by gilberto-torrezan** [comment]
Do you think it should work outside MaterialRows?

**Comment by kevzlou7979** [comment]
No it will produce the error, but we can use the workaround you posted.

**Comment by kevzlou7979** [comment]
With this commit it will fixed the positioning on all input fields (Date Picker, Time Pickers, TextFields/Areas.
https://github.com/GwtMaterialDesign/gwt-material/commit/944a1fd7208b5e62c109ef60b4659eb680afb9eb
