### ISSUE TITLE
MaterialCheckBoxCell fixes

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material#267]
Hi all,

there are two issues with the MaterialCheckBoxCell and I would like to share the fixes quickly:

1. Issue: Multiple event handler calls

The FieldUpdater gets called 3 times instead of one time. This is because listening to the "click" event *and* the "change" event will result in multiple handler calls. Listening to the "change" event is enough.

Fix is:

    public CheckBoxCell(boolean dependsOnSelection, boolean handlesSelection) {
        super(new String[]{"change", "keydown"}); // removed "click"
        this.dependsOnSelection = dependsOnSelection;
        this.handlesSelection = handlesSelection;
    }

2. Issue: Wrong value provided in update() method of FieldUpdater

onBrowserEvent() never fetches the actual value of the < input > element but the "value" of the < span > element. So when working with a selection you never get the right selections but always an empty selection (value of < span > is always "false").

Fix is:

In onBrowserEvent() replace:

            InputElement input = (InputElement) parent.getFirstChild().cast();

    by:

            InputElement input = (InputElement) parent.getFirstChild().getFirstChild().cast();

-> parent.getFirstChild() returns the < span >, the first child of the < span > is the < input >.

This is because of render() returns: < span ... >< input ... / >< / span > and the "parent" is the cell container.

Best,
Aron

**Comment by kyr0** [comment]
This clearly is a duplicate of #237

**Comment by kevzlou7979** [comment]
Ok will close this and reference to #237
