### ISSUE TITLE
Assert exception when adding MaterialWidget to MaterialRow

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material#268]
I am using a `MaterialWidget` to wrap some other elements:

```java
private static class Day extends MaterialWidget implements HasError {
	// ...
}
```

However, it appears that I cannot add this widget to a `MaterialWidget`:

```java
	@UiField MaterialRow dayRow = new MaterialRow();
	// ...
	public HoursViewImpl() {
		this.initWidget(uiBinder.createAndBindUi(this));

		for (DayOfWeek dayOfWeek : DayOfWeek.values()) {

			MaterialTimePicker fromPicker = new MaterialTimePicker();
			fromPicker.setHour24(true);

			MaterialTimePicker toPicker = new MaterialTimePicker();
			toPicker.setHour24(true);
			
			Day day = new Day(dayOfWeek.name(), fromPicker, toPicker);
			
			this.dayRow.add(day);
			this.dayMap.put(dayOfWeek, day);
		}
	}
``` 

What I get is an assert exception:

```java
public com.google.gwt.user.client.Element getElement() {
    assert (element != null) : MISSING_ELEMENT_ERROR;
    return DOM.asOld(element);
}
```

**Comment by gilberto-torrezan** [comment]
Try extending Composite instead of MaterialWidget, or using the `public MaterialWidget(Element element)` constructor.

**Comment by silentsnooc** [comment]
Well I actually switched to a `SimplePanel`. I just thought that it should also be possible to extend `MaterialWidget` like this so I created the issue here. 

If this behavior is actually expected then we can close it of course :)

**Comment by kevzlou7979** [comment]
You can call the super contructor of MaterialWidget by having :

``` java 

private static class Day extends MaterialWidget implements HasError {
    public Day() {
         super(Document.get().createDivElement());
    }
}

```

This will avoid the assertion error

**Comment by BenDol** [comment]
As @kevzlou7979 mentioned the MaterialWidget wants you to tell it what HTML element it represents.

**Comment by silentsnooc** [comment]
Ah! Thanks for the info! I guess this issue can be closed then.
