### ISSUE TITLE
Cannot parse value: "mdi-social-whatshot" as type gwt.material.design.client.constants.IconType

### ISSUE THREAD

**Issue by antonio-dibacco** [GwtMaterialDesign/gwt-material#274]
Trying to build the starter project I get this error:

_Cannot parse value: "mdi-social-whatshot" as type gwt.material.design.client.constants.IconType_

at this line:

<m:MaterialLink  iconType="mdi-social-whatshot" textColor="white"  tooltip="Starter"/>

**Comment by kevzlou7979** [comment]
I think you are using the old repo, try to build this instead https://github.com/GwtMaterialDesign/gwt-material-template

**Comment by antonio-dibacco** [comment]
Thx for your help.

Is there a step by step guide to compile that or a tutorial for eclipse how to getting started?

Regards,
Antonio.

**Comment by kevzlou7979** [comment]
We are on our way to create a slot for Video tutorials. It will make the user integrate gwt-material easier. For now we will start creating a tutorial for InteliIdea

**Comment by kevzlou7979** [comment]
Refer to this issue discussion https://github.com/GwtMaterialDesign/gwt-material/issues/275

**Comment by antonio-dibacco** [comment]
Thx. Just for you to know, a mvn compile on the repo you told me gives this error:

[ERROR] Failed to execute goal on project gwt-material-starter: Could not resolve dependencies for project gwt.material.starter:gwt-material-starter:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.github.gwtmaterialdesign:gwt-material:jar:1.5-SNAPSHOT, com.github.gwtmaterialdesign:gwt-material-themes:jar:1.5-SNAPSHOT, com.github.gwtmaterialdesign:gwt-material-addins:jar:1.5-SNAPSHOT: Could not find artifact com.github.gwtmaterialdesign:gwt-material:jar:1.5-SNAPSHOT -> [Help 1]

**Comment by kevzlou7979** [comment]
try to use 1.5.0 in your pom.xml file

**Comment by kevzlou7979** [comment]
Will commit the fixes

**Comment by kevzlou7979** [comment]
Ok you can now pull it in to your repo

**Comment by antonio-dibacco** [comment]
Don't want to bother you, anyway, now I get:

parallels@ubuntu:~/gwt-material-template$ mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building GWTP Basic 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.github.gwtmaterialdesign:gwt-material:jar:1.5.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.github.gwtmaterialdesign:gwt-material-themes:jar:1.5.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.github.gwtmaterialdesign:gwt-material-addins:jar:1.5.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.374s
[INFO] Finished at: Thu Mar 03 18:02:29 CET 2016
[INFO] Final Memory: 7M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project gwt-material-starter: Could not resolve dependencies for project gwt.material.starter:gwt-material-starter:war:1.0-SNAPSHOT: The following artifacts could not be resolved: com.github.gwtmaterialdesign:gwt-material:jar:1.5.0-SNAPSHOT, com.github.gwtmaterialdesign:gwt-material-themes:jar:1.5.0-SNAPSHOT, com.github.gwtmaterialdesign:gwt-material-addins:jar:1.5.0-SNAPSHOT: Could not find artifact com.github.gwtmaterialdesign:gwt-material:jar:1.5.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
parallels@ubuntu:~/gwt-material-template$
