### ISSUE TITLE
Video Tutorial for gwt-material Getting Started 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#275]
Created a slot for video tutorial for gwt-material getting started. Will need to create a youtube channel for the tutorial and access to showcase site.

<b>Lists of tutorials to be implemented</b>

<ul>
<li> Importing gwt-material using Github </li>
<li> Importing gwt-material using Maven </li>
<li> Importing gwt-material using Jar Build Path </li>
<li> Introduction to themes </li>
</ul>

Please recommend more tutorials you like to be included into our video channel.

**Comment by antonio-dibacco** [comment]
Would it be possible that you export the IntelliJ IDEA project at https://github.com/GwtMaterialDesign/gwt-material-template to an eclipse project? 
It would be really useful to start.

**Comment by jllodra** [comment]
@antonio-dibacco tried File > Import > Maven in Eclipse? Just did it and worked

**Comment by youncta-dev** [comment]
I also tried but it didn't work, so sad. Attaching a screenshot with error:

<img width="833" alt="screen shot 2016-03-04 at 16 47 09" src="https://cloud.githubusercontent.com/assets/13467484/13531840/ded67e0c-e228-11e5-9c20-873c6bb1c3ee.png">

**Comment by jllodra** [comment]
@youncta-dev I think the correct procedure is to clone other repos as well (gwt-material, gwt-material-themes and gwt-material-addins) and built them with `mvn clean install` to add to the local maven repository. Then those dependencies would be cleared. Anyone please correct me if I'm wrong.

**Comment by youncta-dev** [comment]
Unfortunately a mvn clean install under gwt-material-addins repo gives:
_
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project gwt-material-addins: Compilation failure: Compilation failure:
[ERROR] /home/parallels/gwt-material/gwt-material-addins/src/main/java/gwt/material/design/addins/client/ui/MaterialStepper.java:[217,43] error: cannot find symbol
[ERROR] symbol:   variable FADEINUP
[ERROR] location: class Transition
[ERROR] /home/parallels/gwt-material/gwt-material-addins/src/main/java/gwt/material/design/addins/client/ui/MaterialStep.java:[123,17] error: cannot find symbol
[ERROR] symbol:   method addClickHandler(<anonymous ClickHandler>)
[ERROR] location: variable conCircle of type Div
[ERROR] /home/parallels/gwt-material/gwt-material-addins/src/main/java/gwt/material/design/addins/client/ui/MaterialWindow.java:[159,43] error: cannot find symbol_

**Comment by kevzlou7979** [comment]
Make sure you are using ``` gwt-material 1.5.0-SNAPSHOT ``` in order to be compatible with ``` gwt-material-addins 1.5.0-SNAPSHOT ```

**Comment by youncta-dev** [comment]
Thx for your help, this is what I did:
1) clone gwt-material
2) clone gwt-material-addins
3) clone gwt-material-themes
4) clone gwt-material-demo

then I issued a git checkout release_1.5 under gwt-material repo.

Then I built all repo with mvn clean install. 

Now how I run the demo?

**Comment by gilberto-torrezan** [comment]
A good tutorial would be one to help people migrate existing GWT applications to GWT Material.

I imagine some chapters or steps:

* Project setup
* What to do with your old CSS files
* Defining the overall layout of the app (menus, sidebar, headers, footers and so on)
* Replacing Vertical/Horizontal Panels and other table-based widgets for responsive layout
* Replacing GWT widgets with Material Widgets

**Comment by youncta-dev** [comment]
In addition I would also like to have a tutorial that suggests how to startup with a new project. In principle it shouldn't be so difficult.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan and @youncta-dev THanks for the suggestions

**Comment by kevzlou7979** [comment]
We have published our first GWT Material - Project Setup video tutorial.
https://www.youtube.com/watch?v=sEVqfqDUOpE

**Comment by mjrlgue** [comment]
Hey, I am new on GWT-Material, I followed your tutorial https://www.youtube.com/watch?v=sEVqfqDUOpE and when I start building server to compile the project, an error display:
``
HTTP ERROR 404

Problem accessing /index.html. Reason:

    Not Found
Powered by Jetty://
``

**Comment by mjrlgue** [comment]
I fixed my last problem, but I got a new problem here :(, when following your utorial: https://www.youtube.com/watch?v=e-XY4EGVIuc and adding this part of code: 
``
   <m:MaterialSideNav type="FIXED" width="280">
      
  </m:MaterialSideNav>
it display an error: 


> binding:

 

> user.agent=safari
> Compiling module com.gwtmaterial.tutorial.GwtMaterialBasic
>    Computing all possible rebind results for 'com.gwtmaterial.tutorial.client.application.ApplicationView.Binder'
>       Rebinding com.gwtmaterial.tutorial.client.application.ApplicationView.Binder
>          Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
>             [ERROR] Cannot parse value: "FIXED" as type gwt.material.design.client.constants.SideNavType: <m:MaterialSideNav type='FIXED' width='280'> (:44)
>    [ERROR] Errors in 'gen/com/gwtmaterial/tutorial/client/application/com_gwtplatform_mvp_client_DesktopGinjector_DesktopGinjectorGinjector_fragment.java'
>       [ERROR] Line 91: Failed to resolve 'com.gwtmaterial.tutorial.client.application.ApplicationView.Binder' via deferred binding
>    Unification traversed 415 fields and methods and 205 types. 3 are considered part of the current module and 3 had all of their fields and methods traversed.
> [ERROR] Compiler returned false

hope you'll reply soon !



>

**Comment by kevzlou7979** [comment]
@mjrlgue What version of GMD Are you using?
By the way the repository of the tutorials are here:
Part 1 - https://github.com/GwtMaterialDesign/gwt-material-tutorial/tree/tutorial_1
Part 2 - https://github.com/GwtMaterialDesign/gwt-material-tutorial/tree/tutorial_2
Part 3 - https://github.com/GwtMaterialDesign/gwt-material-tutorial/tree/tutorial_3

**Comment by mjrlgue** [comment]
Oh thank you @kevzlou7979 , i did not realized that was a specific version for each tutorial !!!
By the way can i deploy GMD on any web app (for example: mix GMD with an existing web app)?? if yes can you describe me how ? Thanks with best regards !
