### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#278]
Hi, there is a JS error  "VM183:14 Uncaught SyntaxError: Unexpected end of input"  during the application startup, (you can see it even in the demo Pattern # XX)
(see the attachaments)

![chrome](https://cloud.githubusercontent.com/assets/13817916/13915111/f623612e-ef52-11e5-9fe9-a52b79039b7c.png)
![firefox](https://cloud.githubusercontent.com/assets/13817916/13915117/fa143254-ef52-11e5-872f-1df9c7fb1965.png)

**Comment by kevzlou7979** [comment]
Yes its on the core js files. Will take alook on this one

**Comment by MarcoCucchi** [comment]
ok Mark!

**Comment by kevzlou7979** [comment]
Ok I resolved it 
![image](https://cloud.githubusercontent.com/assets/3138071/14444810/adf75408-007a-11e6-8690-b8303bd4b893.png)
