### ISSUE TITLE
MaterialTab labels disappear when changing screen to small

### ISSUE THREAD

**Issue by jamalromero** [GwtMaterialDesign/gwt-material#279]
I am using gwt-material-1.4.1 and I have a problem with MaterialTab. When I resize the screen to Small (Mobile) the labels on the Tabs disappear. On Chrome dev tools I see on overridecss.css the following:
```
@media only screen and (max-width: 992px) .tab a span {
       display: none !important;
}
```
Disabling this on dev tools all works fine.

**Comment by kevzlou7979** [comment]
Fixed with https://github.com/GwtMaterialDesign/gwt-material/commit/3c96d38b0594e1bd58b0b62b0b4e92cd04b0b513
