### ISSUE TITLE
Turn 894px to be 992px on Media queries

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#280]
Tablet Devices less than or equal 992px
Desktop Devices greater than 992px

**Comment by gilberto-torrezan** [comment]
There are mentions to the 894px value on CSS and Java files as well, like on MaterialSideNav.

**Comment by kevzlou7979** [comment]
Yeah e.g overridecss

**Comment by kevzlou7979** [comment]
Changed : Material Sidenav also https://github.com/GwtMaterialDesign/gwt-material/commit/62883cd9bdeab929ce0821517c60803c194bc685
