### ISSUE TITLE
MaterialSearch is broken in v1.4.1

### ISSUE THREAD

**Issue by ajaggi** [GwtMaterialDesign/gwt-material#282]
The Search Input Field is too small and in the upper corner.

As seen in the current Demo Application: http://wrenx2015.appspot.com/

I don't know weather the issue exists in v1.5?

I could help fixing it if its not yet done.

thnx and best regards

**Comment by kevzlou7979** [comment]
The Search component is best implemented here http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#search gwt-material 1.5.0-SNAPSHOT. Wait for release of 1.5.0 so that you can have a fully build search component.
