### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#284]
- open a Date picher.
- press Close
- open a new browser tab
- come back to Date picker page.
BUG: although I close the dp, it comes out again. (you can see it in the attached screen)

![date_picker](https://cloud.githubusercontent.com/assets/13817916/14348150/f1966816-fcba-11e5-817e-aa484a03883a.gif)

**Comment by kevzlou7979** [comment]
It's an issue i think on materialize. can you post it also on Materialize Github Issue https://github.com/Dogfalo/materialize/issues

**Comment by MarcoCucchi** [comment]
Ok, no problem Mark

**Comment by MarcoCucchi** [comment]
Mark, they say "try to remove the focus from it."
I've tried by setting focus on on another widget my it must be an edit box and in the same parent..
Any ideas?

**Comment by MarcoCucchi** [comment]
@kevzlou7979  they suggest these workarounds in JS

https://github.com/Dogfalo/materialize/issues/2067
https://github.com/amsul/pickadate.js/issues/160

**Comment by kevzlou7979** [comment]
@MarcoCucchi Thanks for the links : https://github.com/GwtMaterialDesign/gwt-material/commit/7597ef75415047ee45ac72d872c46cb5eef93e61 This is the commit :)
