### ISSUE TITLE
Navbar burger icon overlaps with brand logo

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material#287]
Check on smaller browser size http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!navbar

![image](https://cloud.githubusercontent.com/assets/18280223/14423264/31a6c3ba-ffdb-11e5-91b2-9d08228d8244.png)

**Comment by kevzlou7979** [comment]
Thanks for your test, will resolve this now :)

**Comment by kevzlou7979** [comment]
Fixed https://github.com/GwtMaterialDesign/gwt-material/commit/453394043d1a2650aace84ac34cc7ec2e13d4475

**Comment by mvanrobaeys** [comment]
Seems this bug is back!
