### ISSUE TITLE
Errors in 'gwt/material/design/client/constants/Display.java'

### ISSUE THREAD

**Issue by vsarinho** [GwtMaterialDesign/gwt-material#288]
The following code:

public class XXXX implements EntryPoint {
  public void onModuleLoad() {	
    MaterialSideNav sideNav = new MaterialSideNav(); 
    RootPanel.get().add(sideNav);
  }
}

provides these errors during compilation:

Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   [ERROR] Errors in 'gwt/material/design/client/constants/Display.java'
      [ERROR] Line 34: INLINE_TABLE cannot be resolved or is not a field
      [ERROR] Line 35: LIST_ITEM cannot be resolved or is not a field
      [ERROR] Line 36: RUN_IN cannot be resolved or is not a field
      [ERROR] Line 37: TABLE cannot be resolved or is not a field
      [ERROR] Line 38: TABLE_CAPTION cannot be resolved or is not a field
      [ERROR] Line 39: TABLE_COLUMN_GROUP cannot be resolved or is not a field
      [ERROR] Line 40: TABLE_HEADER_GROUP cannot be resolved or is not a field
      [ERROR] Line 41: TABLE_FOOTER_GROUP cannot be resolved or is not a field
      [ERROR] Line 42: TABLE_ROW_GROUP cannot be resolved or is not a field
      [ERROR] Line 43: TABLE_CELL cannot be resolved or is not a field
      [ERROR] Line 44: TABLE_COLUMN cannot be resolved or is not a field
      [ERROR] Line 45: TABLE_ROW cannot be resolved or is not a field
      [ERROR] Line 46: INITIAL cannot be resolved or is not a field

Any idea??

**Comment by kyr0** [comment]
I can only speak for myself, but when using UiBinder and following the code examples here, it works very well. I never saw those errors going this way.

Just take a look at:

    https://github.com/GwtMaterialDesign/gwt-material-demo/tree/master/src/main/java/gwt/material/design/demo/client/application/components/sidenavs

Or, just for convenience:

    http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!sidenavs

btw: Beware of copying code from the syntax-highlighted demo page code examples! You may copy invalid (and by default invisible) whitespace characters along with the code and GWT will end up in XML parsing errors. So do only copy XML code from GitHub...

**Comment by vsarinho** [comment]
Unfortunately I need to use the java layouting approach due to the dynamic structure of my web content.

**Comment by kevzlou7979** [comment]
@vsarinho Yes you can,  think you just forgot to use the right sidenav properties like the m:id type of sidenav etc.
