### ISSUE TITLE
IconType enum is missing "BUILD" or "WRENCH" for "build"

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material#289]
The icon is existing in the design but not in the enum:

    http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!icons

   type: "build", you will find a nice "wrench" icon.

...try to find a "BUILD" or "build" in:

    gwt.material.design.client.constants.IconType

Nothing :)

**Comment by kevzlou7979** [comment]
Ok just merged the PR regarding the missing icons https://github.com/GwtMaterialDesign/gwt-material/pull/285 :)
