### ISSUE TITLE
Demo on http://gwt-material.appspot.com/#about only works with 1.3.2-SNAPSHOT

### ISSUE THREAD

**Issue by xenji** [GwtMaterialDesign/gwt-material#29]
Using the UIBinder Code from http://gwt-material.appspot.com/bin/HomePanel.ui.xml with version 1.3.1 does not compile due not found methods and a missing MaterialContainer class.

**Comment by kevzlou7979** [comment]
Hi ,

If you are using the Maven Repo, we still not release the 1.3.2 in Maven GWT Material, which include a new Panel called "Material Container" and cause the compile issue.

But if you use Github Repo, you can easily Pull the repo and it will be automatically included the Material Container and current updates.

Regards,
Kevin

**Comment by kevzlou7979** [comment]
Ok we release 1.3.2
