### ISSUE TITLE
Focus not regained when using the Back button

### ISSUE THREAD

**Issue by KenMills** [GwtMaterialDesign/gwt-material#290]
Precondition:
Project has two or more places
Navigate to a place that contains a modal dialog with dismissable=false

Failure case:
Open the dialog
Press the Browser "Back" button

Result:
The screen does not have focus and you're unable to select anything within the browser window.

I can repro this 100% on IE and Firefox, windows 8.1

**Comment by BenDol** [comment]
Are there any error messages in the console?

**Comment by KenMills** [comment]
No error in the console until I press the Browser "Next" button to go back to the page with the dialog.

Then I see:
17:14:05.770 Thu Apr 14 17:14:05 GMT-700 2016 com.google.gwt.logging.client.LogConfiguration
SEVERE: Exception caught: Exception caught: Exception caught: Exception caught: (Error) : Dropzone already attached.com.google.web.bindery.event.shared.UmbrellaException: Exception caught: Exception caught: Exception caught: Exception caught: (Error) : Dropzone already attached.
	at Unknown.fillInStackTrace_0_g$(DataVUiDemo-0.js)
	at Unknown.Throwable_3_g$(DataVUiDemo-0.js)
	at Unknown.Exception_3_g$(DataVUiDemo-0.js)
	at Unknown.RuntimeException_3_g$(DataVUiDemo-0.js)
	at Unknown.UmbrellaException_3_g$(DataVUiDemo-0.js)
	at Unknown.doFire_0_g$(DataVUiDemo-0.js)
	at Unknown.fireEventFromSource_1_g$(DataVUiDemo-0.js)
	at Unknown.fireEvent_11_g$(DataVUiDemo-0.js)
	at Unknown.fire_31_g$(DataVUiDemo-0.js)
	at Unknown.revealInParent_0_g$(DataVUiDemo-0.js)
	at Unknown.forceReveal_0_g$(DataVUiDemo-0.js)
	at Unknown.manualReveal_0_g$(DataVUiDemo-0.js)
	at Unknown.execute_38_g$(DataVUiDemo-0.js)
	at Unknown.$execute[…]1 DataVUiDemo-0.js:38983:3
error_2_g$() DataVUiDemo-0.js:38983
publish_0_g$() DataVUiDemo-0.js:39012
log_14_g$() DataVUiDemo-0.js:39822
log_13_g$() DataVUiDemo-0.js:39807
log_21_g$() DataVUiDemo-0.js:108440
onUncaughtException_1_g$() DataVUiDemo-0.js:39160
reportUncaughtException_1_g$() DataVUiDemo-0.js:12424
reportUncaughtException_0_g$() DataVUiDemo-0.js:10196
runScheduledTasks_0_g$() DataVUiDemo-0.js:12768
flushPostEventPumpCommands_0_g$() DataVUiDemo-0.js:12853
execute_6_g$() DataVUiDemo-0.js:12992
execute_5_g$() DataVUiDemo-0.js:12729
apply_0_g$() DataVUiDemo-0.js:12224
entry0_0_g$() DataVUiDemo-0.js:12280
entry_1_g$/<() DataVUiDemo-0.js:12260
callback_0_g$() DataVUiDemo-0.js:12780

**Comment by BenDol** [comment]
The issue might not be to do with this library. Can you confirm that it is?

**Comment by KenMills** [comment]
I think the exception is a separate issue.

I crated a new project in eclipse.
Presenter1 has a single button that launches Presenter2
Presenter2 has a button that launches a dialog

When I launch the dialog, press the Back button I see the same behavior that I do in my app (Focus Lost, can't press anything).

In this test app, I can press Next and dismiss the dialog.

**Comment by BenDol** [comment]
Okay, perhaps a screen gif would be good to show exactly how to reproduce the issue, might speed things up for us. Thanks for the report.

**Comment by KenMills** [comment]
![focus](https://cloud.githubusercontent.com/assets/12837618/14548733/adf15030-026e-11e6-944c-d75215be5cf0.gif)

**Comment by BenDol** [comment]
Thanks for all the informtion @KenMills it will be looked into.

**Comment by BenDol** [comment]
Progress on this?

**Comment by BenDol** [comment]
I believe this has been resolved in 2.0, feel free to reopen if you are still having this issue (when I tested it was working).
