### ISSUE TITLE
File Uploader preview widget not selectable when FileUploader is withing a dialog

### ISSUE THREAD

**Issue by KenMills** [GwtMaterialDesign/gwt-material#291]
Precondition:
Place a File Uploader widget inside a modal dialog with dismissable=false

Steps to repro:
Drop/add a file for download

Result:
The preview widget will display, but will not have focus and is not selectable.

Notes:
1:
When the dialog is dismissed, the preview widget will also be dismissed. If the dialog is reopened, sometimes the preview widget will not be displayed. (If I shrink the window so that the preview window is within the dialog view you can see it)

2:
This occurs in IE. In IE the preview widget displays in the lower right corner of the screen, outside of the modal dialog.

I tried this in Firefox and the preview widget displays in the lower right corner of the dialog and this issue doesn't occur.

Could this be a setting in my IE browser?

**Comment by KenMills** [comment]
![fileupload](https://cloud.githubusercontent.com/assets/12837618/14547765/e4c073ba-0265-11e6-8007-78557c67f4a6.png)

**Comment by kevzlou7979** [comment]
I will see deeper on the solution, I think it's on Dropzone.js. Will update you :)

**Comment by kevzlou7979** [comment]
Transferred to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/53. The right place for this issue is on gwt-material-addins :)
