### ISSUE TITLE
Multiple MaterialDatePicker valuechangehandler firing

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#293]
Hi, i just experienced a new issue, that when i have multiple date pickers, the value change handler fires multiple times for each picker.
This occurs when i open 2+ date pickers and on value change, the event is fired for each time a picker was opened before. Removing the handler registration does not take effect.
Is there a trick to register the handler which i have overseen?

**Comment by kevzlou7979** [comment]
https://github.com/GwtMaterialDesign/gwt-material/pull/294 This is the fixed. Thanks again for the PR>
