### ISSUE TITLE
Error:  MaterialTab:Not Screen apea

### ISSUE THREAD

**Issue by LeonVlad** [GwtMaterialDesign/gwt-material#295]
Win7SP1,jre7, gwt-2.7.0,GAE-1.9.34.,gwt-material 1.5.0
My GWT -Project:  <inherits name='gwt.material.design.GwtMaterialWithJQuery'/>
MaterialTab mtab=new MaterialTab();
mtab.setSize("800px", "40px");
mtab.setBackgroundColor("green");
mtab.setIndicatorColor("green");
MaterialTabItem mti=new MaterialTabItem();
mti.setWaves(WavesType.GREEN);
mti.setGrid("s4");
MaterialLink     mlink1=new MaterialLink("One");
mlink1.setTextColor("white");
mti.add(mlink1);
mtab.add(mti);

RootLayoutPanel rtp= RootLayoutPanel.get()
rtp.add(mtab):

I not esed UI Binder,
I used plain Java in eclipse 4.5.2
 
Thanks.

**Comment by gilberto-torrezan** [comment]
Can you improve your description of the bug (including the title)? I can't figure out what's going on.

**Comment by LeonVlad** [comment]
Hello Gilberto

MaterialTab is not visible on the screen
I not used UI bind.
I used plain JAVA in IDE Eclipse 4.5.2

Leon.

**Comment by kevzlou7979** [comment]
I've tried your   code, I also tried in Errai because it's fully java.
![image](https://cloud.githubusercontent.com/assets/3138071/14698445/6fc9954e-07c1-11e6-81cd-a35fde41a29c.png)

Everything works fine
