### ISSUE TITLE
Update dependencies 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#296]
Update related dependecies :
- Java 8
- GWT 2.8-beta1
- JSInterop

**Comment by paulux84** [comment]
This is really important for furhter usage.
Another things i think is a must is the deprecation of GWT Widget in favour of GWT Element...but this is out of topic

**Comment by kevzlou7979** [comment]
@paulux84 Yeah true, we are making some experimentation on widgetless base class.

**Comment by paulux84** [comment]
@kevzlou7979 can i help you in some way?

**Comment by kevzlou7979** [comment]
Yeah feel free to share ur ideas, if you have an experimental project about
widgetless element or a better way to use jsinterop in materialize on it
that will be awesome

**Comment by paulux84** [comment]
Ok great :D

Il 25/05/2016 17:01, kevzlou7979 ha scritto:
> Yeah feel free to share ur ideas, if you have an experimental project 
> about
> widgetless element or a better way to use jsinterop in materialize on it
> that will be awesome
>
> On Wed, May 25, 2016, 10:56 PM paulux84 <notifications@github.com> wrote:
>
> > @kevzlou7979 <https://github.com/kevzlou7979> can i help you in some 
> way?
> >
> > —
> > You are receiving this because you were mentioned.
> >
> >
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/GwtMaterialDesign/gwt-material/issues/296#issuecomment-221602587>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/GwtMaterialDesign/gwt-material/issues/296#issuecomment-221603908>
>

-- 
Paolo Pino
CTO | 3Cube S.r.l.

Corso Italia 104
95129 Catania

P.Iva: 04300750876

Mobile: +39 095.8997943
Tel: +39 095.8997942
Web Contact: http://paolo.pino.mtalk.net/
Mail: paolo.pino@3cube.it

**Comment by kevzlou7979** [comment]
Ok the conversion of JSNI -> JSInterop , usage of labdas on Java 8 is now being developed. https://github.com/GwtMaterialDesign/gwt-material/tree/release_2.0.

Note: We are just waiting for com.workingflows.jquery to release there Maven as of the moment to make it more stable and also for the RC of GWT 2.8.0
