### ISSUE TITLE
When constructing a MaterialTab from a UiBinder file, the element in the indicator Widget is null.

### ISSUE THREAD

**Issue by roland36** [GwtMaterialDesign/gwt-material#297]
This is true in 1.5, but I did not have this problem 1.4.

I have: `<m:MaterialTab ui:field="navtabs" backgroundColor="blue" indicatorColor="RED">.`

This fails with Uncaught com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: This UIObject's element is not set; you may be missing a call to either Composite.initWidget() or UIObject.setElement()

When I look at the indicator object in the debugger, it's null. See the attached images.

Removing the indicatorColor attribute works around the problem.

Cheers,
Roland

![hrrrgwtmaterial - -ideaprojects-hrrrgwtmaterial - -ideaprojects-hrrrgwtmaterial-lib-gwt-material-1 5 0 jar -gwt-material-design-client-ui-materialtab java - intellij idea 2016 1 1_221](https://cloud.githubusercontent.com/assets/11654905/14645715/6808b0b6-061c-11e6-9d5c-9bde3bf18fbc.png)
![hrrrgwtmaterial - -ideaprojects-hrrrgwtmaterial - -usr-local-gwt-2 7 0-gwt-user jar -com-google-gwt-user-client-ui-uiobject java - intellij idea 2016 1 1_222](https://cloud.githubusercontent.com/assets/11654905/14645736/7bb0a0d8-061c-11e6-9d42-a163b802c988.png)

**Comment by kevzlou7979** [comment]
I checked your code, there is a mistake on your indicatorColor="RED" it must be only "red".

**Comment by kevzlou7979** [comment]
Is this bug occuring on 1.5.2 or 1.5.3?

**Comment by roland36** [comment]
This was an issue with 1.5.0.

I'm pretty sure the IDE suggested "RED" as the value and not "red" based the XML schema, I'm pretty sure "YELLOW" worked, but "yellow" did not, but in the end you can probably close the issue.
