### ISSUE TITLE
MaterialRichEditor toolbar popups are hiding immidiately after being shown.

### ISSUE THREAD

**Issue by zlov** [GwtMaterialDesign/gwt-material#299]
Noticed in our project and reproduced in Demo application v 1.5.0

On [this](http://gwtmaterialdesign.github.io/gwt-material-demo/#richeditor) page for all instances of MRE where setHTML was called when I click any toolbar icon with popup menu it (the popup) becomes hidden right after display.

![richeditorpopups](https://cloud.githubusercontent.com/assets/18423465/14739289/71896750-08a8-11e6-927d-bdf149ee21ca.gif)

**Comment by BenDol** [comment]
Since its potentially an addin problem should probably report it in that repository https://github.com/GwtMaterialDesign/gwt-material-addins

**Comment by zlov** [comment]
Sorry.. indeed wrong repo. Fixed.
