### ISSUE TITLE
navbar 's   sidebarwidth  once set,  the other navbar has been affected

### ISSUE THREAD

**Issue by OrNot** [GwtMaterialDesign/gwt-material#30]
Suppose we set a navbar with fixed sidebarwidth, say, 300px, as demoed in starter template, it works fine.  In another webpage in the same webapp, we use another navbar without setting the sidebarwidth 
in Uibinder,  but the 300px offset is there.  That's , the sidebarwidth seems a global thing.  It is not good.

Pls take a look and thanks a lot

**Comment by kevzlou7979** [comment]
Hi,

First of all, we added sideBarWidth as required attribute when you are setting a MaterialNavBar because it needs to be declared to be able to set the dragged area when swiping it on mobile phones. Only the sideBar="TYPE" will be only optional for different displays as discussed in Google MaterialDesign

**Comment by OrNot** [comment]
Sorry I don't  tell the thing clearly.  It is OK to set the sideBarWidth . But it should be instance scope but not  global scope.  Once I set one navbar instance 's width,  other navbar instance is set too.  

What I observe is When setting  the first navbar instance 's sidebarwidth,  this navbar offset from the left with the width .  This is acceptable.   but the second navbar instance in another page  also get the same offset even I don't set its sidebar width.  


Hope this is clear

**Comment by kevzlou7979** [comment]
Hi,

THank you for the clarification, now we support multi side bar in GWT MAterial, The I manage to be able to support is to create a unique class on SideBar.

Regards,
Kevin
