### ISSUE TITLE
MaterialChip auto-close on icon click with no overwrite

### ISSUE THREAD

**Issue by ahtremblay** [GwtMaterialDesign/gwt-material#301]
```
MaterialChip materialChip = new MaterialChip();
materialChip.setIconType(IconType.EMAIL);
```

Using, the browser click on the materialChip's icon. The materialChip will be removed from the dom. There doesn't seem to be a way to override this behavior. Adding a clickHandler will not prevent the auto-close "feature".

**Comment by kevzlou7979** [comment]
Will create now a demo showcase in our documentation site.

**Comment by pandurangpatil** [comment]
I am facing the same issue, I don't want item to be removed automatically when user click on icon. I tried with recent SNAPSHOT version, by expecting recent changes made will resolve the issue. However it seems the resolution is limited to chips displayed with search widget I guess.

**Comment by BenDol** [comment]
What is the status on this issue?

**Comment by kevzlou7979** [comment]
The PR has beed merge it's ready now for 1.5.1-SNAPSHOT.
