### ISSUE TITLE
small bug at MaterialDatePicker

### ISSUE THREAD

**Issue by magway77** [GwtMaterialDesign/gwt-material#302]
Hello guys, you done perfect work.
i want report about small bug at MaterialDatePicker, version 1.5.0
in you code
        this.setDateMin(this.dateMin);
        this.setDateMax(this.dateMin);
most probably need to change 
        this.setDateMin(this.dateMin);
        this.setDateMax(this.dateMax);

**Comment by kevzlou7979** [comment]
Please elaborate and explain more about your bug.

**Comment by magway77** [comment]
sorry, i don't know what's more details i have describe: there are simple misprint:
setDateMax(this.date**Min**); instead setDateMax(this.date**Max**);

**Comment by kevzlou7979** [comment]
@magway77 Ah ok I understand :)

**Comment by kevzlou7979** [comment]
Check this commit https://github.com/GwtMaterialDesign/gwt-material/commit/f5e9d07e9eda8c866d64e4d551477d77cba053e6.

**Comment by magway77** [comment]
thank you
