### ISSUE TITLE
bug with MaterialSearch

### ISSUE THREAD

**Issue by magway77** [GwtMaterialDesign/gwt-material#305]
Hello, guys

at MaterialSearch method
```java
public void onLoad() {
...
    this.searchResult = new MaterialSearchResult();
    this.addKeyUpHandler(new KeyUpHandler()
....
}
```

and no method onUnload()

searchResult and handlers are private members, so i can't extend you class and implement it, 
when i place MaterialSearch on MaterialModal for axample, and show it then i close modal when dropdownlist for searchResult is down. then i show this modale ans again then i have a few dropdown list for html (few div) and exteptions with firing keyUp events

so i have to do something like this:
```java
class CMaterialSearch
        extends MaterialSearch {
boolean initialized = false;
 @Override
    public void onLoad() {
        if (!initialized) {
            super.onLoad();
            initialized = true;
        }
    }

    @Override
    protected void onUnload() {
        clear();
        setCurSel(-1);
        super.onUnload();
/*
        NodeList<Element> childs = this.getElement().getElementsByTagName("div");
        for (int i = childs.getLength() - 1; i > -1; i--) {
            Element element = childs.getItem(i);
            if (element.getClassName().matches("(?i)search-result")) {
                getElement().removeChild(element);
            }
        }
*/
    }
```
Could you check it

Have a nice day and thank you in advance

**Comment by BenDol** [comment]
Good catch, thanks @magway77
