### ISSUE TITLE
Request for implement setFocus for MaterialSearch

### ISSUE THREAD

**Issue by magway77** [GwtMaterialDesign/gwt-material#306]
Hello, guys
could you implement method setFocus for MaterialSearch
something like:
```java
    @Override
    public void setFocus(final boolean focused) {
        Scheduler.get().scheduleDeferred(new Scheduler.ScheduledCommand() {
            @Override
            public void execute() {
                ((TextBox)CMaterialSearch.this.getWidget(0)).setFocus(focused);
            }
        });
    }
```

thank you and have fun

**Comment by kevzlou7979** [comment]
@magway77 Let's hear from other users for this implementation.

**Comment by gilberto-torrezan** [comment]
@magway77 Why the need of a ScheduledCommand to set the focus?

**Comment by BenDol** [comment]
If I remember correctly focus changes must be deferred to ensure it works properly.

**Comment by magway77** [comment]
@gilberto-torrezan 
exmple  & explanation for scheduler when setFocus
https://vcfvct.wordpress.com/2014/02/21/event-loop-gwt-scheduledeferred/
A browser event loop is a thread started by the browser that is constantly scanning for and running different events, just like it sounds. As events occur they are put in the event queue and run in turn by the one event thread. Your javascript should not create its own loops waiting for it to complete or anything like that…it will block that one continuous event loop thread. Instead you would use something like setTimeout or setInterval and check for whatever conditions you are waiting for so the browser can do work while it ‘waits’.

**Comment by gilberto-torrezan** [comment]
Related to it: https://github.com/gwtproject/gwt/issues/1855

**Comment by magway77** [comment]
i think it doesn't mean if it will be deffered method or not. This request about implementation method setFocus by any way. Now MaterialSerarch not contains any method for focused. For example i programmaticaly set MaterialSerarch to "active" state and want to focus it on input, but now such method

**Comment by BenDol** [comment]
Yeah I understand the request. It will be resolved when we get around to it. Feel free to help speed this up by creating a pull request with this fix. Thanks
