### ISSUE TITLE
Cumbersome MaterialCheckbox value change handling

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#307]
Just recognized, that the value change event does not represent the selection state. There war formValues and Values and so on...
Are there any plans regarding this control? I consider refactoring the control to get a simpler api.

**Comment by BenDol** [comment]
The ValueChangeEvent does represent its selection state? Tested this just now.

```java
checkBox.addValueChangeHandler(new ValueChangeHandler<Boolean>() {
    @Override
    public void onValueChange(ValueChangeEvent<Boolean> event) {
         GWT.log("Checkbox value: " + event.getValue());
    }
}
```
