### ISSUE TITLE
Problems with the UI on Safari (mac & iPad)

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#309]
Hi, with the version 1.5 (and also 1.5.1) we have serious problems with all the UI components on Safari. (tested on osx El capitan and on iPad2)

See the attached screenshots.

Can you check it please? 

PS please notice that on the old version (1.4) it works well.

Thank you very much

![scr1](https://cloud.githubusercontent.com/assets/13817916/15075791/7aceeb74-13a6-11e6-9fda-24d01c3443c8.png)
![scr3](https://cloud.githubusercontent.com/assets/13817916/15075793/7bab5a64-13a6-11e6-8e85-6591a410092e.png)
![scr2](https://cloud.githubusercontent.com/assets/13817916/15075797/812c8d82-13a6-11e6-8d4f-23ace4770381.png)

**Comment by BenDol** [comment]
Any console errors?

**Comment by MarcoCucchi** [comment]
@BenDol I see, i have attached the JS errors, If it can help I can test the fixes on Mac OS.
![scr1_1](https://cloud.githubusercontent.com/assets/13817916/15080768/f6d26b4c-13bf-11e6-96c7-33f2453c045e.png)

![scr1_2](https://cloud.githubusercontent.com/assets/13817916/15080772/f93bcdba-13bf-11e6-8519-d0ed387bbbe4.png)

**Comment by BenDol** [comment]
What version of Safari are you using?

**Comment by MarcoCucchi** [comment]
Version 9.0.3 (11601.4.4)

**Comment by kevzlou7979** [comment]
@MarcoCucchi Thanks for fast response, I am able to reproduce the style problems on Safari, will fixed this asap. This bug priority is high :)

**Comment by BenDol** [comment]
I guess find out what changed in 1.5 from 1.4 (when it was working). Might help identify the issues.

**Comment by MarcoCucchi** [comment]
@BenDol  Good!!

**Comment by dejia-meng** [comment]
we noticed the same issue on iPad. It worked in Chrome on iPad for most of the time but was always broken in Safari. 

Also, the layout was messed up when i rotated the iPad into a different mode in Chrome. This might be a different issue.

**Comment by MarcoCucchi** [comment]
to @BenDol  / @kevzlou7979  Hi guys, any news about this issue? I think that should be solved because ipad and safari are used by a wide range of users.
Thanks

**Comment by kevzlou7979** [comment]
It seems that safari throws some error http://toddrothe.com/blog/find-variable-mutationobserver-safari/

**Comment by terry007** [comment]
I have the same problem with safari (Versión 9.1 (11601.5.17.1)) and package app with phonegap for iphone (iphone 6s plus / iOS 9.3)



![problema_iconos](https://cloud.githubusercontent.com/assets/2302411/15424540/81fa3e48-1e83-11e6-856c-15a8dccc93bb.png)
![problema_iconos_iphone2](https://cloud.githubusercontent.com/assets/2302411/15424995/ee745a20-1e85-11e6-9871-c69f4d01a320.png)
![problema_icons_iphone](https://cloud.githubusercontent.com/assets/2302411/15424996/ee7473c0-1e85-11e6-9654-824980d5b4b4.png)

**Comment by MarcoCucchi** [comment]
guys we should find a solution to this issue, it is getting critical for such type of target

**Comment by BenDol** [comment]
I understand the sense of urgency. We will look into this issue ASAP, this is an open source project which means contributions from the community are welcomed. If anyone has the time to help contribute to this issue it is greatly appreciated.

If you need information on how to contribute we have a wiki guide to help get started https://github.com/GwtMaterialDesign/gwt-material/wiki/Contributing

**Comment by MarcoCucchi** [comment]
@BenDol you're right, I'm sorry for my harassment.

**Comment by terry007** [comment]
I've been looking for the problem but I could not find it.

When I refresh the page, sometimes the icons see correctly and so I could not see what the problem is.

Any idea to know where to investigate?

**Comment by BenDol** [comment]
Try tweaking the css attributes, it seems to me like its a css issue.The issue will be isolated around the override.css file we use in this project as the base project materializecss.com doesn't have these kinds of problems with Safari (last I checked). If you can identify what css overrides are causing the issues within our project that would be a good start to finding the solution.

**Comment by kevzlou7979** [comment]
@terry007  can we have team viewer session, because I dont have safari on my Windows PC only the old version which is 2012 (Out to date). Just give your email

**Comment by terry007** [comment]
@kevzlou7979  joseluis dot i2e at gmail.com

**Comment by BenDol** [comment]
I managed to test the demo on Safari version 7.x and it worked perfectly. I am installing the updates now to test version 9.x. Can you please re-test this to check if it has helped some of the issues? http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/

**Comment by MarcoCucchi** [comment]
@BenDol  it works on my Mac, great job!

**Comment by BenDol** [comment]
Great to hear! So 1.5.1 will get its Safari support back :+1:

**Comment by MarcoCucchi** [comment]
@BenDol  ok even with Ipad :)

**Comment by terry007** [comment]
With 1.5.1-snapshot I have the same problem!!!!

The problem on menu its ok but the other problems no.

Is it possible missing some property in the CSS to change?

![with_snaphsot_1_5_1](https://cloud.githubusercontent.com/assets/2302411/15432665/89cf019a-1eaf-11e6-813b-7bedc107ef14.png)

**Comment by BenDol** [comment]
You need to configure some of that to position it. But the button icon positioning is broken there, what version of Safari are you using?

**Comment by terry007** [comment]
Safari Versión 9.1 (11601.5.17.1)

**Comment by BenDol** [comment]
I've tested on this latest version and the FAB components are working fine. You might have some CSS in your project that is interfering with the icons. Check the setup of these components and double check your CSS declarations.

**Comment by terry007** [comment]
This is my generated code.

![image](https://cloud.githubusercontent.com/assets/2302411/15435675/012c6896-1ebe-11e6-92e9-0eafaeb53807.png)

![image](https://cloud.githubusercontent.com/assets/2302411/15435682/0b3b2ae8-1ebe-11e6-959d-6263894be8b6.png)

![image](https://cloud.githubusercontent.com/assets/2302411/15435689/10840d9e-1ebe-11e6-9b2d-29db9c05ad00.png)

![image](https://cloud.githubusercontent.com/assets/2302411/15435694/14b48bc8-1ebe-11e6-968d-8a57d9fa5ab0.png)

**Comment by BenDol** [comment]
The problem is that the offenders could be outer wrapping elements. You would have to see if you could fix the issue by toggling declarations or changing elements etc. Hard to see the issue at face value unfortunately.

If it is an issue on our end I'll need a sample of the code to help me reproduce it.
