### ISSUE TITLE
Responsive Table

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#31]
Resize your browser on desktop to a small size and you will see that table is broken in two columns. First column will have table header with no rows and second one will have table content (rows) with no header.
![err1](https://cloud.githubusercontent.com/assets/9980558/8131862/8d93b56e-111d-11e5-8acc-7d191d071ce1.png)

**Comment by kevzlou7979** [comment]
Hi,

Ok we fixed it , you can fetch now to get the modification.

Regards,
kevzlou7979
