### ISSUE TITLE
navbar type fixed not working

### ISSUE THREAD

**Issue by rsallar** [GwtMaterialDesign/gwt-material#310]
Hi. In 1.5.0 this seems not to work:

`<m:MaterialNavBar type="FIXED" backgroundColor="blue" activates="mysidenav" >
`
It ignores the FIXED type.

Workaround: adding this to css works.

```
@external navbar-fixed;

.navbar-fixed{
    top: 0px;
    position: fixed !important;
}
```

**Comment by kevzlou7979** [comment]
Thanks for catching this problem will start fixing this now

**Comment by kevzlou7979** [comment]
Fixed wiith https://github.com/GwtMaterialDesign/gwt-material/commit/d4d45e4eb62a2c049eebe03838567b37f72f18f3

**Comment by kevzlou7979** [comment]
Tested with Chrome , Firefox, Safari, Opera and Edge
