### ISSUE TITLE
MaterialNavBar: responsive menu not opening

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material#311]
After unsuccessfully trying to get it to work in my application I noticed that the responsive menu collapse button in the MaterialNavBar doesn't work at all. Even in the gwt-material-starter snapshot the menu button doesn't work after the window is resized so that the button becomes visible (even tried it on several  browsers).

**Comment by BenDol** [comment]
It is working properly in the demo application, is this the case for you? http://gwtmaterialdesign.github.io/gwt-material-demo/ Also check the demo repository to see if you can identify the issue you are having, https://github.com/GwtMaterialDesign/gwt-material-demo/blob/master/src/main/java/gwt/material/design/demo/client/application/ApplicationView.ui.xml#L114

**Comment by kevzlou7979** [comment]
Can you please submit a code snippet about ur problem.

**Comment by kevzlou7979** [comment]
Hi I found the problem on starter project, I will commit soon the fixed

**Comment by kevzlou7979** [comment]
Ok it's fixed the starter , you just need to set ``` activates="sidenav" ``` into your navbar component and ``` m:id="sidenav" ``` for Sidenav. 

Fixed starter menu icon :
http://gwtmaterialdesign.github.io/gwt-material-starter/snapshot/
Fixed Commit :
https://github.com/GwtMaterialDesign/gwt-material-starter/commit/8b698d6fe3ef172546e6e55d152d871e4234967b
