### ISSUE TITLE
cant get the basic cards sample to compile

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#312]
Hi
I am just trying this Material design wrapper, so i have a created a simple like this

i copied the UiBinder content from the following link - Basic Cards -
http://gwtmaterialdesign.github.io/gwt-material-demo/#!cards

`public class LoginDialogViewImpl extends Composite implements LoginDialogView {

	
	private static LoginDialogViewImplUiBinder uiBinder = GWT.create(LoginDialogViewImplUiBinder.class);
	
	interface LoginDialogViewImplUiBinder extends UiBinder<Widget, LoginDialogViewImpl> {
	}
	
	
	Widget root;
	
	public LoginDialogViewImpl() {
		root=uiBinder.createAndBindUi(this);
		initWidget(root);
	}

    @Override
    public Widget get() {
		return root;
    }

    @Override
    public void show(RootPanel parent) {
		RootPanel.get().add(this);
    }

    @Override
    public void hide() {
		this.removeFromParent();
    }

}`

i have added the maven dependency for version 1.5.0, and the inherits, and updated the html file for responsivness.
but now when ever i try to compile it gives me the following error 
`Unexpected text in element: "   ": <m:MaterialRow> (:7)`

**Comment by kevzlou7979** [comment]
This issue is copy pasting issue, I also encounter this when having copy pasting from the demo showcase this was cause by hidden text ``` &emsp ``` inside the code blocks. And i think there's a connection with the CodeMirror we are using.

**Comment by vegegoku** [comment]
Thats is true, i figured it out after few hours after i decided to type the snippet myself and it worked, now i am using the code from the download sample project which works.

thanks.

**Comment by rsallar-axa** [comment]
Anyway, it should be nice if you can change the code snippet formatting in documentation because I think a lot of us had the same problem. :+1:

**Comment by kevzlou7979** [comment]
OK will add this to my list.
