### ISSUE TITLE
MaterialCollapsible, memory leak.

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [GwtMaterialDesign/gwt-material#315]
MaterialCollapsible appears to have a memory leak or unnecessary duplicate code.   For every widget added and in the `onLoad` function, either an `AttachEvent.Handler` is added or `onInitCollapsible(Element)` is called directly. The function `onInitColapsible(Element)` registers a "ready" handler with jQuery.   This appears, at first blush, to at least be unnecessarily duplicative.  IE, the call in `onLoad` should perform the same functionality as the call in `add(Widget)` and it should only ever need to be added once.  Also, depending on how jQuery handles the ready functions, with which I am not familiar, these multiple calls may lead to a memory leak of the element.

```
    @Override
    protected void onLoad() {
        super.onLoad();

        onInitCollapsible(getElement());
    }

    @Override
    public void add(final Widget child) {
        if(child instanceof MaterialCollapsibleItem) {
            ((MaterialCollapsibleItem) child).setParent(this);
        }

      if(!this.isAttached()) {
            addAttachHandler(new AttachEvent.Handler() {
                @Override
                public void onAttachOrDetach(AttachEvent event) {
                    if(event.isAttached()) {
                        onInitCollapsible(getElement());
                    }
                }
            });
        }else {
            onInitCollapsible(getElement());
        }


        super.add(child);
    }

    /**
     * Initialize the collapsible material component.
     */
    protected native void onInitCollapsible(final Element e) /*-{
        $wnd.jQuery(document).ready(function(){
            $wnd.jQuery(e).collapsible();
        })
    }-*/;

```

**Comment by BenDol** [comment]
Sorry for the late response, we will check this out soon. Thanks!
