### ISSUE TITLE
Improve using snapshot release in Readme.mf

### ISSUE THREAD

**Issue by rsallar** [GwtMaterialDesign/gwt-material#316]
Hi, in Readme.MF there's a maven snapshot dependency available that is not working as it's not published in Maven Central.

I'm wondering if you could clarify in the Readme.MF the maven repo you are using to publish snapshots versions of future releases (in case you are using some kind of con. integration) or removing this dependency in Readme.MF to clarify that we need to check out the project in order to use latest bug fixes and enhancements. 

I reckon this clarification could help other devs to make user testing of future releases and maybe they decide de help contribuiting with Pull Requests. 

Thanks!

**Comment by kevzlou7979** [comment]
This is the latest 1.5.1-SNAPSHOT https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/gwt-material/1.5.1-SNAPSHOT/
