### ISSUE TITLE
when setting the field focus programmatically using setFocus(true) then the user typed characters overlap with the placeholder

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#317]
to reproduce:
in a MaterialBoxElement use setFocus(true)
run the app then when the UI shows up the field will be focused.
start typing.
what you type will overlap with the place holder on the field.

the active css class is not being set on the label when setFocus is called.
providing a method like setActive(Boolean active) can solve the issue.

**Comment by BenDol** [comment]
Thanks for the report, we will check this out asap. If you wouldn't mind putting together a pull request with a fix that would be greatly appreciated.

**Comment by vegegoku** [comment]
Actually i would really like to do so, i want to contribute to this project and to support it, so ill be glad to help

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/379
