### ISSUE TITLE
EnabledMixin leaks state and listeners

### ISSUE THREAD

**Issue by christianbauer** [GwtMaterialDesign/gwt-material#318]
This logic leads to problems when a widget is reattached:

```
 private void setEnabled(final UIObject obj,final boolean enabled) {
        Widget widget = (Widget) obj;
        if(!widget.isAttached()) {
            widget.addAttachHandler(new AttachEvent.Handler() {
                @Override
                public void onAttachOrDetach(AttachEvent event) {
                    if(event.isAttached()) {
                        applyEnabledProperty(enabled, obj);
                    }
                }
            });
        } else {
            applyEnabledProperty(enabled, obj);
        }
    }
```

Put a MaterialButton with some setEnabled(true|false) logic in a PopupPanel. Because of the attached handler, the button will revert to some old state every time the popup is attached/detached. Does this also leak listeners?

**Comment by BenDol** [comment]
Yeah there are a number of cases where this happens. We need to comb through the widgets and fix these problems. Thanks for raising this issue @christianbauer

**Comment by kevzlou7979** [comment]
@BenDol Thanks for the fix

**Comment by GuidoReith** [comment]
The bug is still not fixed in version 2.4.2.
If #setEnabled is called several times before the widget is attached to the dom the value of the first invocation of #setEnabled is applied to the widget. This is obviously wrong, because it should set the value of the last invocation before attaching it to the dom.
We overwrite it this way:

public void setEnabled(final boolean enabled) {
		if (!uiObject.isAttached()) {
			if (handler != null) {
				handler.removeHandler();
				handler = null;
			}

                         handler = uiObject.addAttachHandler(event -> {
				if (event.isAttached()) {
					applyEnabled(enabled, uiObject);
				} else if (handler != null) {
					handler.removeHandler();
					handler = null;
				}
			});
		} else {
			applyEnabled(enabled, uiObject);
		}
	}

**Comment by kevzlou7979** [comment]
Will be patching this on 2.5.0 release, I will be adding also a JUnit test for this usecase.

**Comment by kevzlou7979** [comment]
Ok tested the code you have provided and can reproduce the issue.

**Comment by kevzlou7979** [comment]
Patched via https://github.com/GwtMaterialDesign/gwt-material/commit/639cdcd30c07a6cb3951b7f9a77ee16b5f27d7d7 and added JUnit test case.
