### ISSUE TITLE
MaterialNavSide closing weird behaviour

### ISSUE THREAD

**Issue by rsallar** [GwtMaterialDesign/gwt-material#322]
I have this:
```
<m:MaterialNavBar ui:field="navBar" type="FIXED" backgroundColor="blue" activates="mysidenav">
...
<m:MaterialSideNav ui:field="sideNav" m:id="mysidenav"  type="CLOSE" width="300" closeOnClick="true">
```

When window is **not maximized** everything works fine. Pressing the close button on the navBar open and closes the bar and a grey overlay appears on main content. Pressing on sideNav links emulates the function of the navBar button.

![example1](https://cloud.githubusercontent.com/assets/505217/15433522/fbf5f8a2-1eb2-11e6-9a01-dab97b9a5a4a.png)

By the other hand, when window is **maximized** Pressing the close button on the navBar open and closes the bar just fine again but no grey overlay appears and the main bug: the navBar closes but the main content does not come back to the original position.

![examle2](https://cloud.githubusercontent.com/assets/505217/15433640/718ce774-1eb3-11e6-8cf1-1105915cb1d7.png)

**Comment by BenDol** [comment]
Can you create a GIF demonstrating the issue? Having trouble understanding how to reproduce it. Thanks!

**Comment by rsallar** [comment]
Sure:

Normal behaviour when small window clicking menu button on bar.
![normal](https://cloud.githubusercontent.com/assets/505217/15454301/39f59c10-2035-11e6-9953-40085b789b4a.gif)

Normal behaviour when small windows clicking on side menu button.
![normal2](https://cloud.githubusercontent.com/assets/505217/15454302/39f846c2-2035-11e6-908a-b6cf673341b6.gif)

Weird behaviour when large window and click side menu button.
![weird](https://cloud.githubusercontent.com/assets/505217/15454310/7346b440-2035-11e6-82b4-d8ca68589ba7.gif)

The same combining first click side menu and then click on bar menu.
![weird2](https://cloud.githubusercontent.com/assets/505217/15454312/7347ff30-2035-11e6-8faf-bc11cb7f281f.gif)

Finally no problems when only clicking bar menu.
![normal3](https://cloud.githubusercontent.com/assets/505217/15454311/73477808-2035-11e6-89f7-da163f881a70.gif)

You can check the code in:

https://github.com/rsallar/contesencatala

Thanks!!!

**Comment by BenDol** [comment]
Please test the fix and confirm its working for you. Thanks for your thorough explanation and sample code.

**Comment by rsallar** [comment]
It works now! thanks!!! :+1:

**Comment by rsallar** [comment]
Oh well... another bug with this... 
When you are in maximized window. With an opened menu the scrolling of the main area does'nt work...

**Comment by rsallar** [comment]
More info I can see there is an injected style in body tag

element.style {
    overflow: hidden;
}

Maybe this is the normal behaviour.

**Comment by kevzlou7979** [comment]
The overflow hidden must be removed i think by default.

**Comment by BenDol** [comment]
This was fixed in the latest version, can you retest it? Thanks!

**Comment by BenDol** [comment]
Note that you need to use allowBodyScroll = true on the side nav.

**Comment by rsallar** [comment]
Amazing work. Thanks.
