### ISSUE TITLE
Search bar is not rendered correctly on chrome

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#325]
the search bar is not rendered correctly on chrome for all demo sites and samples.
please check the screen-shot
![gwt material design - google chrome_002](https://cloud.githubusercontent.com/assets/5379625/15467233/15f2af2c-20e6-11e6-82f0-73518ba65173.png)

**Comment by kevzlou7979** [comment]
This is fixed on 1.5.1 snapshot

**Comment by vegegoku** [comment]
Thats awesome , thank you for the reply, ill close the issue then.

**Comment by vegegoku** [comment]
as mentioned above this is fixed in 1.5.1-SNAPSHOT
