### ISSUE TITLE
Text overlay problem when using MaterialTextBox as password input

### ISSUE THREAD

**Issue by emptyeye** [GwtMaterialDesign/gwt-material#328]
Well, I found some really annoying bug, when I use MaterialTextBox on my login page.  As you know all modern browsers has autocomplete feature, so when I just open my app textBox label overlays password "dots".  Is it possible to fix it in new release ?

**Comment by kevzlou7979** [comment]
@emptyeye  Can you please have an image attached to illustrate where the problem is.

**Comment by emptyeye** [comment]
Sure, here it is. Also I found  that overlay disappear on mouse move or something like that.
![untitled](https://cloud.githubusercontent.com/assets/19545363/15528095/4afcb532-2262-11e6-9c43-8026c141e3a8.png)

**Comment by kevzlou7979** [comment]
What browser are you using?

**Comment by emptyeye** [comment]
Google Chrome

**Comment by kevzlou7979** [comment]
I suggest you can create PR then use the css attribute below.
```css
input:-webkit-autofill {
     // some of your style here to fix the overlap issue   
}
```

**Comment by emptyeye** [comment]
Well, ok. I will try it.

**Comment by masterdany88** [comment]
I've met same problem. I use chrome. I will try catch when this occur.
