### ISSUE TITLE
Is there any way to collapse the navbar if there are many sub material links in big screen?

### ISSUE THREAD

**Issue by OrNot** [GwtMaterialDesign/gwt-material#33]
Now the material links ( suppose  align="left") will be truncated and not all the links will be  shown or not clickable any more.

**Comment by kevzlou7979** [comment]
You can use the code below, to integrate a Collapsible item on sidebar links.

<m:sidebaritem>
					<m:MaterialCollapsible>
						<m:item>
							<m:MaterialCollapsibleItem>
								<m:header><m:MaterialLink text="Style and Layout" icon="mdi-image-color-lens" textColor="blue"/></m:header>
								<m:content>
									<m:UnorderedList>
										
										<m:ListItem>
											<m:MaterialLink href="#colors" text="Colors" textColor="blue"/>
										</m:ListItem>
										<m:ListItem><m:MaterialLink href="#grid" text="Grid" textColor="blue"/></m:ListItem>
										<m:ListItem>
											<m:MaterialLink href="#helper" text="Helper" textColor="blue"/>
										</m:ListItem>
										<m:ListItem>
											<m:MaterialLink href="#icons" text="Icons" textColor="blue"/>
										</m:ListItem>
										<m:ListItem>
											<m:MaterialLink href="#shadow" text="Shadow" textColor="blue"/>
										</m:ListItem>
										<m:ListItem>
											<m:MaterialLink href="#theme" text="Theming" textColor="blue"/>
										</m:ListItem>
									</m:UnorderedList>
								</m:content>
							</m:MaterialCollapsibleItem>
						</m:item>
					</m:MaterialCollapsible>
				</m:sidebaritem>
