### ISSUE TITLE
Localization for MaterialDatePicker

### ISSUE THREAD

**Issue by emptyeye** [GwtMaterialDesign/gwt-material#331]
Hello again, when we started using MaterialDatePicker we faced with problem, that we can't translate labels on it's UI. Is it a bug or a feature ? =)

**Comment by kevzlou7979** [comment]
Its a feature. You can do PR and study this
http://amsul.ca/pickadate.js/date/.

**Comment by kevzlou7979** [comment]
Duplicate of this https://github.com/GwtMaterialDesign/gwt-material/issues/320
