### ISSUE TITLE
NavBar affects other component behavior

### ISSUE THREAD

**Issue by ManOfGod** [GwtMaterialDesign/gwt-material#332]
I'm using gwt-material for 3 days already and I stumbled upon the NavBar behavior. When ever I declare a button inside the NavBar and set a icon for that button, the icon goes down same case with MaterialLink. This happend only whenever I add the components to the NavBar. I'm not using UI Binder. See the attached image:
![screenshot from 2016-05-25 22 32 44](https://cloud.githubusercontent.com/assets/19547368/15543532/d4213846-22c7-11e6-8a38-cf91e08fdb49.png)
This is my sample code:
`public class UserPanel extends MaterialContainer{
    
    private MaterialNavBar navbar;
    private MaterialNavSection section;
    private MaterialRow mrow;
    private MaterialNavBrand navbrand;
    private MaterialContainer container;
    private MaterialButton dropdownTitle;
    private MaterialPanel panel;
    private MaterialDropDown dropdown;
    
    public UserPanel(){
        
        initModule();
        
    }
    
    private void initModule(){
          
        dropdownTitle = new MaterialButton();
        dropdownTitle.setText("User Account");
        dropdownTitle.setLayoutPosition(Style.Position.RELATIVE);
        dropdownTitle.setFloat(Style.Float.RIGHT);
        dropdownTitle.setIconType(IconType.SETTINGS);
        dropdownTitle.setIconPosition(IconPosition.RIGHT);
        dropdownTitle.setMargin(15);
        dropdownTitle.setWaves(WavesType.TEAL);
        dropdownTitle.setType(ButtonType.RAISED);
        dropdownTitle.setActivates("dp-1");
        
        dropdown = new MaterialDropDown("dp-1");
        dropdown.setBelowOrigin(true);
        dropdown.setWidth("180px");
        dropdown.add(new MaterialButton(ButtonType.FLAT, "User Info",new MaterialIcon(IconType.FACE)));
        dropdown.add(new MaterialButton(ButtonType.FLAT, "Privacy Policy",new MaterialIcon(IconType.FLAG)));
        dropdown.add(new MaterialButton(ButtonType.FLAT, "Log out",new MaterialIcon(IconType.EXIT_TO_APP)));
        
        panel = new MaterialPanel();
        panel.add(dropdownTitle);
        
        container = new MaterialContainer();
        container.setLayoutPosition(Style.Position.RELATIVE);
        container.setFloat(Style.Float.RIGHT);
        container.setPaddingRight(25);
        container.add(panel);
        container.add(dropdown);
        
        navbrand = new MaterialNavBrand();
        navbrand.setText("User Account");
        navbrand.setPosition(Position.LEFT);
        
        section = new MaterialNavSection();
        section.add(container);
        section.setPosition(Position.RIGHT);
        
        navbar = new MaterialNavBar();
        navbar.setBackgroundColor("blue");
        navbar.setGwtDisplay(Style.Display.INLINE_BLOCK);
        navbar.setType(NavBarType.FIXED);
        navbar.setWidth("100%");
        navbar.add(navbrand);
        navbar.add(section);
        
        this.setMarginTop(-23);
        this.setPadding(0);
        this.add(navbar);
        
    }
    
}`

**Comment by kevzlou7979** [comment]
Hi @ManOfGod ,

Thanks for catching the issue.
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/af891be8498cd8b296e8375a965d1c6879a138eb
![image](https://cloud.githubusercontent.com/assets/3138071/15731475/f5639ac2-28a7-11e6-91d5-24aadb723578.png)

Best Regards,
Kevin
