### ISSUE TITLE
MaterialStepper#getCurrentStep() bug?

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material#333]
I think there is a bug in `MaterialStepper#getCurrentStep()`
```java
if(currentStepIndex >= getWidgetCount() - 1 || currentStepIndex < 0){
    return null;
}
```
should actually be
```java
// > instead of >=
if(currentStepIndex > getWidgetCount() - 1 || currentStepIndex < 0){
    return null;
}
```
because in the first version being at the last step will cause `getCurrentStep()` to return `null`

```java
((MaterialStep)this.stepper.getWidget(this.stepper.getCurrentStepIndex())).clearErrorOrSuccess();
```

**Comment by kevzlou7979** [comment]
Good catch

**Comment by kevzlou7979** [comment]
Will move this to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/70 because its an addin issue :)
