### ISSUE TITLE
Sidenav - Mobile - Hide it on onload

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#335]
Sidenav must be hidden when first load on mobile browser / small browser.

![image](https://cloud.githubusercontent.com/assets/3138071/15562770/c7c0a114-2334-11e6-9b4a-69decd4a7d6f.png)

**Comment by BenDol** [comment]
This is because the setting `showOnAttach = true` we want to disable that setting when using mobile?

**Comment by kevzlou7979** [comment]
Yeah , we must hide as regular apps do :)

**Comment by kevzlou7979** [comment]
Also on tablet view
