### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material#344]
I feel like missing a decent combobox component.

Request features:
-  Holds an arbitrary object (`ComboBox<T>` )
-  Autocomplete support (list of arbitrary object suggestions), remote query or fixed list
-  Ability to customize view of these suggestions
-  Editor support `LeafValueEditor<T>`

Example of gxt combobox:
![image](https://cloud.githubusercontent.com/assets/18280223/15626923/3c30b9fe-24d3-11e6-825f-24e37442eeb2.png)

I feel like existing widgets as MaterialListBox, Search, Autocomplete have some overlap that could be merged to this component.

**Comment by mvanrobaeys** [comment]
https://select2.github.io/examples.html  seems very complete, how hard would this be to integrate with material design?

**Comment by kevzlou7979** [comment]
I will close this because the issue might be placed better on addins https://github.com/GwtMaterialDesign/gwt-material-addins/issues/95
