### ISSUE TITLE
MaterialTextArea can not be resized / does not resize initially

### ISSUE THREAD

**Issue by david2411** [GwtMaterialDesign/gwt-material#348]
Hey there,
when i open a form, i fill the text fields and text areas with the values of my given object. I tried this by using MaterialTextArea.setText("text") and MaterialTextArea.setValue("text", true) - where true means: yes, fire ValueChangeEvent!!!
So, but if the text i am setting into the MaterialTextArea is long and has many lines, the area will not be resized.
If you click into the area and begin changing the text, the area is suddenly resized to the size of the content.
I would like to have a method or a setting in order to control the resizing of the MaterialTextArea. Actually i don't know how to find a compromise, so that users can see, that there is more content in the area.

Kind regards,
David

![materialdesign_textarea](https://cloud.githubusercontent.com/assets/19424469/15745409/01398d46-28d2-11e6-87e9-7adfabdb2d32.gif)

**Comment by BenDol** [comment]
You need to manage the size of the text area within your application. Not sure if materializecss is suppose to resize the text area upon focusing the text area but it wouldn't be a bad idea to handle this upon focusing an editable field.

**Comment by BenDol** [comment]
Can you show me how you are configuring the `MaterialTextArea` uibinder etc?

**Comment by BenDol** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/467725c1124b347e4072cf2e952a68a9dd046c07
Note that this is targeting 1.6.0 release so the snapshot will need to be used.

**Comment by BenDol** [comment]
Working like so:

![resize-policy-sample](https://cloud.githubusercontent.com/assets/1935706/15797556/ea00fed4-2a70-11e6-8973-b799c29e6892.gif)

**Comment by kevzlou7979** [comment]
Ok tested the feature http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!forms
