### ISSUE TITLE
Adding widgets without the UI binder

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#349]
Hi,
i am trying to add a material link inside MaterialSideNav using sideNav.add(materialLinkWidget) below is my code 
`@Override
	public void addMenuItem(IsWidget menuItem) {
		sideNavigation.add(menuItem);
	}`

where the menuItem being passed is a MaterialLink, but it is not being added,
i even did this 
`MaterialLink materialLink=new MaterialLink("Dashboard", new MaterialIcon(IconType.DASHBOARD));
		materialLink.setIconPosition(IconPosition.LEFT);
		sideNavigation.add(materialLink);`
then the Material link was added but without the icon

when i add it statistically using the UIBinder it works super fine but when i do it from code it fails.

any one know of this problem?

**Comment by vegegoku** [comment]
I was able to fix this issue like this:
i add @UiField on the material link that i pass to the addMenuItem then it worked.

and for the second part when i try to create the MaterialLink like this
 `MaterialLink materialLink=new MaterialLink("Dashboard", new MaterialIcon(IconType.DASHBOARD));`
i found that the icon does not show up in the UI, but if i call the materialLink.setIconType(IconType.DASHBOARD); it works
so now i wonder what is the use of passing the icon in the constructor if i have to call setIconType method.

and i dont know if i should fix this and create a pull request in this case
so please i need a confirmation on this bug before i decide.

**Comment by BenDol** [comment]
Will look into this, thanks!

**Comment by kevzlou7979** [comment]
Ok Tested and working great.
