### ISSUE TITLE
Navbar works not as expected ( or as before )?

### ISSUE THREAD

**Issue by OrNot** [GwtMaterialDesign/gwt-material#35]
I update to the latest version from github. For navbar, the type  is set to "left" and the sidebarwidth is set to ,say, 250. In previous version, the sidebar won't shown until collapse in small screen and click the collapse menu. but in current version, a  white rectangle will be shown anyway. 

Pls take a look.

**Comment by kevzlou7979** [comment]
Hi,

There's no left as a Type in NavBar, its only "Fixed".

Regards

**Comment by OrNot** [comment]
so what if I ignore this property without set any value to it ?

**Comment by kevzlou7979** [comment]
Hi I just implement what you asked on MaterialNavBar, Just add the attribute sideBar="hidden" in to your NavBar and everything will work fine.

**Comment by OrNot** [comment]
wow, you are my hero. Thanks for your quick response. I have tried, it is good. 
Two minor problems : 
1.  when the align="right" , the collapse menu button will overlap with the logo text.
2.  when the sidebar="hidden" ,can put the nav buttons near the most of the left side without the padding ? Now it  looks in the screen center  especially in a laptop . 

Thanks a million anyway

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/8246304/f890975a-166e-11e5-8549-42d0c2c209c6.png)

**Comment by kevzlou7979** [comment]
Okay this is the preview before I will commit, follow the code below:

<m:MaterialNavBar wave="light" align="right" color="blue" text="Starter" type="no-padding" sideBar="hidden" sideBarWidth="300">

**Comment by kevzlou7979** [comment]
<m:MaterialNavBar wave="light" align="right" color="blue" text="Starter" type="no-padding" sideBar="hidden" sideBarWidth="300">

**Comment by OrNot** [comment]
Yeah. perfect!
