### ISSUE TITLE
MaterialButton shows no icon inside a DataGrid

### ISSUE THREAD

**Issue by chrho** [GwtMaterialDesign/gwt-material#350]
If I add a MaterialButton at runtime to a datagrid, the icon is not visible.

Column<ObjectRowType, MaterialButton> editColumn = new Column<ObjectRowType, MaterialButton>(new MaterialButtonCell())
{
	@Override
	public MaterialButton getValue(ObjectRowType object)
	{
		MaterialButton mb = new MaterialButton();
		mb.setIconType(IconType.EDIT);
		return mb;
	}
};

dataGrid.addColumn(editColumn, "edit");

**Comment by kevzlou7979** [comment]
This will solved on new data grid :)

**Comment by chrho** [comment]
ok thanks
