### ISSUE TITLE
MaterialSideNav handles clicks on MaterialSideProfile

### ISSUE THREAD

**Issue by throwable** [GwtMaterialDesign/gwt-material#351]
Hi,
When MaterialSideNav has a MaterialSideProfile object inside, it also handles clicks on it as if it is a side menu link. It adds class to the profile 'active' and desactivates current selected MaterialLink item.
Salu2,
Antón

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/e73fa6d748f7f42b59874ecb765b6475c4b049ab
