### ISSUE TITLE
MaterialSwitch should provide a text attribute

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material#359]
The `MaterialSwitch` widget should implement `HasHTML` or at least `HasText` to allow adding a text to switches. That would make this widget more versatile. As a side note, the method `setLabel(Label)` of this widget makes no sense as it doesn't add the argument to the DOM so that it will never be displayed. I would suggest to remove this method (and 'getLabel()')  completely in favor of the `HasHTML` implementation.

**Comment by kevzlou7979** [comment]
@esoco Thanks for catching this up, will do a fix about your request :). For the set/getLabel() we will not delete it as we have used it some of our apps or other;s app

**Comment by kevzlou7979** [comment]
I think instead of having ``` HasHTML ```, we will define a so called ```setOnLabel(String) ``` and ```setOffLabel(String) ```. This will be great for future proof concept on gwt-material 2.0

**Comment by kevzlou7979** [comment]
Ok I have implemented it :
<b>Code</b>
```<m:MaterialSwitch offLabel="Off" onLabel="On"/> ```
<b>Preview</b>
![image](https://cloud.githubusercontent.com/assets/3138071/16401065/c355a45a-3d13-11e6-966c-fe47ff4c8709.png)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/05f5edd840d54bcf54f1b85319af5a0b05b93f93
