### ISSUE TITLE
Floating buttons are invisible in lists

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material#360]
`overridecss.css` contains the style `ul li button.btn-floating { opacity: 0; }`. This actually renders floating buttons invisible in lists like MaterialCollapsible unless this style is overridden (again).

**Comment by BenDol** [comment]
This is correct, the materializecss library sets the opacity of the floating button `ul` for the FAB lists as exampled here http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#fabs

**Comment by esoco** [comment]
Ok, I see how that is used for the `MaterialFAB` widget. But this style also renders MaterialButtons with the `ButtonType.FLOATING` invisible in lists. I think this style needs to be more specific to achieve only the desired purpose.
