### ISSUE TITLE
Core Animations, support for infinite animation time

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#363]
I am gonna add to `MaterialSideProfile` icons for: Notifications, Messages. If user will get new message or notification I would like icon to animate until user will check it. 

So I need an animation to work in infinitive loop.

![image](https://cloud.githubusercontent.com/assets/1161910/16007562/8d082414-3173-11e6-8c84-953dbb6a89a2.png)

**Comment by masterdany88** [comment]
I think we just need a boolean infinite , then if its true then we can add it, we need some method stopInifiniteAnimation to stop it

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/5ac0a36a6e2c2501df5947139ffe1071820fdd4d
