### ISSUE TITLE
Toast statuses

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#364]
I wonna ask did You consider to add statuses to MaterialtToast? Like in the example:
![image](https://cloud.githubusercontent.com/assets/1161910/16073745/b6669528-32e7-11e6-8509-59a3dc81c944.png)
http://ned.im/noty/#/about

**Comment by kevzlou7979** [comment]
Sorry but Material Design does not support it
https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-specs
