### ISSUE TITLE
MaterialSideNav insert() not wrapping added widgets into <li>...</li>

### ISSUE THREAD

**Issue by silentsnooc** [GwtMaterialDesign/gwt-material#365]
Compared to `MaterialSideNav#add`

```java
this.sideNav.add(link);
```
The method `MaterialSideNav#insert`

```java
this.sideNav.insert(link, index);
```

is not working as expected. `MaterialSideNav#add` will simply add another `<li>` element to the wrappring `<ul>`

```html
<ul>
  <li></li>
  <li></li>
  <li></li> <!-- the added one -->
</ul>
```

but using `MaterialSideNav#insert` will leave you with

```html
<ul>
  <li></li>
  <a>...</a>  <!-- the inserted one -->
  <li></li>
</ul>
```

and unfortunately breaking the menu in the sense that the inserted `MaterialLink` will not have the mouse-over effect like the other links in the list.

**Comment by BenDol** [comment]
Ah seems insert was forgotten about. Thanks for the catch!

**Comment by silentsnooc** [comment]
@BenDol No problem :)

**Comment by kevzlou7979** [comment]
Ok tested and it's working great. Thanks to @BenDol
