### ISSUE TITLE
What is the purpose of activator in MaterialDropDown

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#367]
I know that the purpose of this activator is to show widget (MaterialDropDown) when user click on element that activates- so it is just hide/display trigger.

What about rest of widgets? Why do they don't have that parameter? Wouldn't be better if we would create Interface `hasActivator` that have methods: set and get activator?

**Comment by kevzlou7979** [comment]
For now the Dropdown component would be greater look on button, icon and link components.

**Comment by BenDol** [comment]
We will leave this open, the enhancement could be good. `HasActivator` could be a valid approach in the future.

**Comment by BenDol** [comment]
I believe this has been resolved in 2.0, feel free to reopen if you are still having this issue (when I tested it was working).
