### ISSUE TITLE
A coupe of issues on the latest demo

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#37]
- Desktop: When you hover on Components, both menu options "Component" and "Style and Layout" are marked.

![menucomponents](https://cloud.githubusercontent.com/assets/9980558/8256014/573fa9c8-16a4-11e5-8217-6f2c8f10537f.png)

- Desktop & Mobile: When you select Dialogs: SHOW MODAL, dialog does not show at all (and after this point we need to reload the page because we can not do anything on the page) if pressed before any other option on the right (MODAL WITH FIXED FOOTER etc). If you select any other option on the right like MODAL WITH FIXED FOOTER and after that press SHOW MODAL, dialog will be shown as expected.

- Desktop & Mobile: When you select NavBar it does not change header text, it will be "Media" if that was the last place you have been.

- Mobile: Paralax scroll is not smooth (images are jumping up-down) on mobile when you scroll the page.

- Mobile & Desktop: Menu button should be left aligned ? Not really sure that this is an issue because it's the same as on http://materializecss.com/ as well, but I think left aligned would look better that this. At least it should be aligned with header text if it's not left aligned.

![menubutton](https://cloud.githubusercontent.com/assets/9980558/8256012/531b31e6-16a4-11e5-823a-76c2731a2f28.png)

- Desktop & Mobile: Badges in Dropdown : Badge is not vertically aligned with as it should be. Scroll bar is also there but it should not be shown for only 3 options.(It's probably because of badge that is not on the place it should be).

![errbadgesindd](https://cloud.githubusercontent.com/assets/9980558/8256018/5c110622-16a4-11e5-94d6-f63627df4879.png)

BTW, great job done !

**Comment by gilberto-torrezan** [comment]
I could not replicate the first issue (I'm using Firefox 38.0 and Chrome 43.0.2357.130, both x64 on Linux).

The second one happens in both browsers.

**Comment by kevzlou7979** [comment]
Thank for the detailed feedback,

All the issues are solved on the next release :)
