### ISSUE TITLE
MaterialTextBox - KeyPress Handler not working in Firefox

### ISSUE THREAD

**Issue by ManOfGod** [GwtMaterialDesign/gwt-material#370]
I used Firefox version 47.0 for linux mint.

**Comment by kevzlou7979** [comment]
Can you post some codes and screenshot so that I can study deeper, I tested it with FF 47.0 on Browserstack but its working well.

**Comment by ManOfGod** [comment]
This is my sample code:
`@UiHandler("txtsearch")
    void onKeyPress(KeyPressEvent event) {        
        if(event.getUnicodeCharCode() == KeyCodes.KEY_ENTER && !txtsearch.getText().isEmpty()){
            gridContainer.clear();
            gridContainer.add(new CustomerDataGrid(txtsearch.getText().trim()));
        }
    }`

![materialtextbox](https://cloud.githubusercontent.com/assets/19547368/16220973/c0c76cba-37c2-11e6-9816-ea581fb7a802.png)

**Comment by kevzlou7979** [comment]
This is a prior info about the issue 
https://groups.google.com/forum/#!topic/google-web-toolkit/HBWgEY-fp_g

**Comment by kevzlou7979** [comment]
Please use ``` event.getNativeEvent().getKeyCode() ``` instead of event.getUnicodeCharCode().
