### ISSUE TITLE
MaterialWidget sets wrong FocusableMixin

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#375]
The way **MaterialWidget.focusableMixin** is being set in **getFocusableMixin()** provides no way of customizing which element should be used as **focusableMixin** in given Widget type.
(That results in [stuff like this](https://github.com/GwtMaterialDesign/gwt-material-addins/issues/92), i.e. non-focusable elements used for setFocus())
Exposing **getFocusableMixin** as **protected** would make it possible to fix this by way of overriding.

**Comment by dlaunen** [comment]
Agreed, talked to Mark, all non public methods should be by default be protected vs private as this allows easier extension of widgets.

**Comment by kevzlou7979** [comment]
@jzaruba Ok will convert all private methods to protected on Milestone 1.6.0

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/376

**Comment by kevzlou7979** [comment]
Ok the PR has beed merged, after I think you can freely submit PR for the fixed of the issue as now you can override some protected issues I've fixed. Let's remain this issue open and wait for you to have the PR submitted.

**Comment by kevzlou7979** [comment]
Ok I will now close this issue and now you can override protected methods for solving the problem cause. Feel free to submit PR to fixed https://github.com/GwtMaterialDesign/gwt-material-addins/issues/92

**Comment by jzaruba** [comment]
Wilo do! :)
