### ISSUE TITLE
MaterialButton Icon not showing in DataGrid 

### ISSUE THREAD

**Issue by ManOfGod** [GwtMaterialDesign/gwt-material#380]
I have encountered a problem in my application wherein I added a MaterialButton in my DataGrid:
`Column<Batch, MaterialButton> btnCol = new Column<Batch, MaterialButton>(new MaterialButtonCell()) {

            @Override
            public MaterialButton getValue(Batch object) {
                MaterialButton mb = new MaterialButton(ButtonType.FLAT);
                mb.setIconType(IconType.LIST);
                mb.setWidth("48px");
                mb.setIconPosition(IconPosition.LEFT);
                mb.setWaves(WavesType.LIGHT);
                return mb;
            }
        };
existingBatchGrid.addColumn(btnCol, "  ");`

When I run my application, this is what happened. Instead of a list icon, a letter L appears. 
![datagrid](https://cloud.githubusercontent.com/assets/19547368/16355863/2c02a404-3af7-11e6-8e7a-098354e4b3c1.png)

**Comment by kevzlou7979** [comment]
@ManOfGod 
Try this
```
MaterialButton mb = new MaterialButton();
mb.setType(ButtonType.FLAT);
mb.setIconType(IconType.LIST);
mb.setIconPosition(IconPosition.LEFT);
mb.setWaves(WavesType.LIGHT);
return mb;
```

**Comment by kevzlou7979** [comment]
This is the same with https://github.com/GwtMaterialDesign/gwt-material/issues/350.
We will publish soon new Data Table.

**Comment by ManOfGod** [comment]
Still not good. when i perform inspect element i found a problem. the button added in datagrid doesn't call the button style for the icon.
