### ISSUE TITLE
MaterialSwitch don't work in version 1.5.2

### ISSUE THREAD

**Issue by AlessandroCopler** [GwtMaterialDesign/gwt-material#382]
I updated GWT Material version from 1.5.0 to 1.5.2 and now MaterialSwitch don't work anymore and gives me this error:

HandlerManager.java:129 Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: (TypeError) : Cannot read property 'length' of undefined

I noticed that in the showcase is not working either:

http://gwtmaterialdesign.github.io/gwt-material-demo/#!forms

It's just me or someone else is having this problem?

**Comment by kevzlou7979** [comment]
Ok thanks for catching this error. I reviewed and we have some problems with updates on switch. If you didn;t put the on/off labels there are problems. But we will push the fix on 1.6.0.

**Comment by kevzlou7979** [comment]
We will do an emergency fix 1.5.3

**Comment by lostandfoud** [comment]
Great! I have the same problem with MaterialSwitch. Wait for the fix.
Thanks

**Comment by kevzlou7979** [comment]
Here is the fix for the switch component https://github.com/GwtMaterialDesign/gwt-material/pull/383. Will announce it on Gplus and Gitter about the said emergency release.

**Comment by kevzlou7979** [comment]
The demo of the fix is ready now http://gwtmaterialdesign.github.io/gwt-material-demo/#!forms

**Comment by AlessandroCopler** [comment]
Thanks for the fix!

**Comment by kevzlou7979** [comment]
I will merge this and deploy the release to Maven. Take note that you might need to use the following into your dependencies.

```xml

      <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-themes</artifactId>
            <version>1.5.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-addins</artifactId>
            <version>1.5.2</version>
        </dependency>

**Comment by kevzlou7979** [comment]
Ok I have deployed the gwt-material 1.5.3 in Maven , will be available later today in maven central.
