### ISSUE TITLE
setVisible vs setVisibility

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#384]
What is the difference between those 2 parameters:
`visibility` and `visible`? Why do they both exists? Witch one should I use and in what purpose?

**Comment by kevzlou7979** [comment]
It's a css attributes 
1. <b>Visibility</b> ``` visibility: hidden/visible; ``` 
2. <b>Visible</b> ``` display: none/block```

**Comment by gilberto-torrezan** [comment]
Also, `setVisible()` is a method inherited from the [GWT Widget library](http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/client/ui/UIObject.html#setVisible(boolean)), so we have to maintain the compatibility with it.
