### ISSUE TITLE
FAB does not open again after closing programmatically

### ISSUE THREAD

**Issue by mcaap** [GwtMaterialDesign/gwt-material#385]
1. Programmatically close an FAB on tap of any of the MaterialButton. FAB closes as expected
2. Now tapping on the FAB does not open it again.
Need to tap the outside area to "close" and then tap the FAB again.

**Comment by kevzlou7979** [comment]
Can you provide a screenshot for this? As I cant reproduce the bug itself

**Comment by mcaap** [comment]
Hi, not sure a screenshot would convey the issue. And I had to change the programmatic auto close FAB behavior on my site because of the issue. So cant provide a link to the issue either.
But you can try this easily on a mobile browser:
1. Tap on the fab to open up some menu items
2. Tap on the sub menu item and then programmatically close it.
3. Next time you try to tap on the FAB, it wont open.

**Comment by kevzlou7979** [comment]
Ok the only solution to workaround is to make your FAB Click_Only.
Also make a report to Materialize guys about the problem on this issue.

**Comment by kevzlou7979** [comment]
Also another workaround which i tested is, 
1. Add Hover event into your FAB to openFAB().
2. Then When you close it, using each FAB Item call closeFAB().

Then these series will work fine.
