### ISSUE TITLE
MaterialListBox: enabled state cannot be changed

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material#388]
Changing the enabled state of a MaterialListBox instance is not possible after values have been added. The new state will be ignored. In the example below clicking the button has no effect, the enabled state remains the same as after creation. If the commented line is included the list box remains disabled and cannot be activated afterwards. The only workaround I found is to invoke `setOld(true)`. 

```
final MaterialListBox lb = new MaterialListBox();
MaterialButton		  bt = new MaterialButton();

panel.add(lb);
panel.add(bt);

// lb.setEnabled(false);

lb.addItem("TEST 1");
lb.addItem("TEST 2");
bt.setText("Toggle");

bt.addClickHandler(new ClickHandler() {
	public void onClick(ClickEvent rEvent) { lb.setEnabled(!lb.isEnabled()); }
});
````

**Comment by kevzlou7979** [comment]
Ok the issue was merge, we can now close this issue.

**Comment by david2411** [comment]
Yaaay, its working :D  Thank you!
