### ISSUE TITLE
MaterialSwitch registers click handler too late

### ISSUE THREAD

**Issue by esoco** [GwtMaterialDesign/gwt-material#389]
MaterialSwitch registers it's internal state-change click handler in the `onLoad()` method but that is too late if an application registers it's own click handler earlier, e.g. directly after widget construction. Such event handlers then see the old state of the switch as it is changed later by the switch event handler. I would recommend to add the internal handler in the constructor. This works, I just tried it with a local copy.

**Comment by kevzlou7979** [comment]
Hi @esoco ,

Thanks for the suggestion , We will test it and see if thats a good workaround.

Regards,
Kevin

**Comment by BenDol** [comment]
Already tested this and it doesn't work properly in the constructor as its too early to serve its intended purpose. However if you think I may have misunderstood feel free to submit a PR for review. I think until then we will leave this issue.

**Comment by esoco** [comment]
What exactly is not working then? I'm using my modified version without problems so far and other GwtMaterial classes also set click handlers in their constructor (e.g. MaterialSearch). Not solving this issue would make MaterialSwitch inconsistent with typical GWT widgets.

**Comment by BenDol** [comment]
I've found a solution to the issue I was having. Will submit the fix to `release_1.6.0` asap. Thanks for the catch!
