### ISSUE TITLE
MaterialCheckBox not working

### ISSUE THREAD

**Issue by invader35** [GwtMaterialDesign/gwt-material#396]
The MaterialCheckBox is not recognizing any clicks, this can easily be reproduced in the demo application.
https://gwtmaterialdesign.github.io/gwt-material-demo/#!forms

This also affects the MaterialListBox with mutli select

**Comment by masterdany88** [comment]
It works for me. I've checked this on chrome browser.

**Comment by kevzlou7979** [comment]
Can you provide a code snippet for better debuging

**Comment by invader35** [comment]
I just rechecked and it seems only the non filled checkboxes are affected. All non filled checkboxes do not accept the click in my browser window. Again tested on the demo website. So no special code snippet that i could post, except the one from the demo page.

```
<m:MaterialCheckBox text="Blue" value="true" />
```

Using Chrome v53.

**Comment by kevzlou7979** [comment]
This will be solved on new Data Table.

**Comment by kevzlou7979** [comment]
Tested with Browserstack
Chrome v53  and other chrome versions.
![animation](https://cloud.githubusercontent.com/assets/3138071/17584429/071d89e4-5fe9-11e6-9693-e4cd1acc2584.gif)

Maybe it solves on our changes on events specially on 1.6.0 and 2.0-SNAPSHOT. You can check it out.
