### ISSUE TITLE
MaterialDatePicker has problems in firefox

### ISSUE THREAD

**Issue by ManOfGod** [GwtMaterialDesign/gwt-material#398]
I created a MaterialDatePicker and set enabled = "false" then tested it on chrome and it works fine but when I tested it on firefox, it didn't work. And when I close the Calendar modal without selecting a date by clicking outside the modal, the DatePicker won't animate back.

**Comment by ManOfGod** [comment]
It worked fine after making this
`date.addCloseHandler(new CloseHandler<MaterialDatePicker>() {

            @Override
            public void onClose(CloseEvent<MaterialDatePicker> event) {
                if(date.getDate() == null){
                    date.clear();
                }
            }
        });`
but you still need to fix the problem.

**Comment by kevzlou7979** [comment]
Hi there, I just tested on Firefox 40 & 47 both on Windows and Mac using Browserstack but the problem doesnt reproduce. Can you give us the specific version it.

**Comment by ManOfGod** [comment]
Try it in a normal PC with firefox 47 or 48. I still encounter this even after updating my browser to the latest version.
