### ISSUE TITLE
MaterialTimePicker open , but none button does not clickable

### ISSUE THREAD

**Issue by danielpazeto** [GwtMaterialDesign/gwt-material#399]
Hi, I'm using MaterialTimePicker but none button is clickable.
I already change z-index to try, but nothing happen, the hover happen normally.
Apparently the click handle isn't called.

![nova imagem 10](https://cloud.githubusercontent.com/assets/5786917/16935294/8557b004-4d34-11e6-9f65-1a07fb0427fc.jpg)

I would like to use this component, it's very nice and android UI friendly.

**Comment by kevzlou7979** [comment]
I tried to reproduce your issue but the problem does not persist. I used the demo app -> Mobile and Desktop. Can you please ellaborate your code or even an existing demo.

Best Regards,
Kevin
