### ISSUE TITLE
Endless loop in MaterialDesignBase.onModuleLoaded() since update to 1.5.3

### ISSUE THREAD

**Issue by Kusig** [GwtMaterialDesign/gwt-material#401]
I updated my project from dependency 1.5.0 to 1.5.3. Since then I have my app in an endless loop on startup. It loops in this one forever:

MaterialDesignBase.java

    protected void onModuleLoaded() {
        if(futureResources != null) {
            for (FutureResource res : futureResources) {
                injectJs(res.resource, res.removeTag, res.sourceUrl);
            }
        }
    }

Any idea how to debug or to fix this?

**Comment by Kusig** [comment]
Stepped back to 1.5.2. With this one I can't reproduce so far.

**Comment by BenDol** [comment]
Can you list all the addins you are using? Since a FutureResource will either be an addin or internal resource. If you could add a breakpoint and provide the futureResources list that would also help. Thanks!

**Comment by Kusig** [comment]
Very strange, After going back to 1.5.0 to confirm that it doesn't occure there, I can't reproduce this anymore. Created new Eclipse Workspace, built whole project new ant it's gone for now. 
Sorry for this false alarm.  Will close the issue.
