### ISSUE TITLE
MaterialSideNav closes if tapped or clicked on mobile device

### ISSUE THREAD

**Issue by Kusig** [GwtMaterialDesign/gwt-material#402]
I have defined a simple panel which is populated with some dynamically added controls. On desktop browser, everything works as expected.

    <m:MaterialSideNav ui:field="filterSidebar" m:id="rightSideBar" type="FIXED" closeOnClick="false" edge="RIGHT" fixed="false" addStyleNames="{appRes.styles.rightSideBar}"> 
    </m:MaterialSideNav> 

However, on mobile browser (or Chrome mobile emulator), the panel closes as soon as it is tapped somewhere.  It seems to react on the tap events even if closeOnClick=false. 

Is this as it should be?

**Comment by kevzlou7979** [comment]
Hi there,

> Is this as it should be?

Yes the current implementation of Sidenav in Mobile view behaves like that.

Regards,
Kevin

**Comment by Kusig** [comment]
Is there a chance to get around this behaviour?
I think this behaviour changed since 1.5.0

**Comment by Kusig** [comment]
Looks like I found a way to prevent this behaviour. Just called the following method on the sidebar:

      filterSidebar.stopTouchStartEvent();
