### ISSUE TITLE
MaterialSearch must have one selected object.

### ISSUE THREAD

**Issue by g9164313** [GwtMaterialDesign/gwt-material#403]
This happened when search list is empty or no selected object.

'tempSearches' may be a empty list.

Developer can ask server to get search list. I think populating data is not a necessary function.

----------------------------------------------------------------------------

Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at gwt.material.design.client.ui.MaterialSearch$2.onKeyUp(MaterialSearch.java:180)
    at gwt.material.design.client.ui.MaterialValueBox$2.onKeyUp(MaterialValueBox.java:293)
    at com.google.gwt.event.dom.client.KeyUpEvent.dispatch(KeyUpEvent.java:56)

----------------------------------------------------------------------------

  // Apply selected search
 if(event.getNativeEvent().getKeyCode() == KeyCodes.KEY_ENTER){
               if(getCurSel()==-1){
                    'setSelectedObject(tempSearches.get(0));
                     setSelectedLink((MaterialLink) searchResult.getWidget(0));
                    }else{
                        'setSelectedObject(tempSearches.get(curSel));
                    }

----------------------------------------------------------------------------

**Comment by g9164313** [comment]
I use below code to work around
---------------------------------------
                // Apply selected search
                if(event.getNativeEvent().getKeyCode() == KeyCodes.KEY_ENTER &&
                   tempSearches.isEmpty()==false
                ){

**Comment by kevzlou7979** [comment]
Hi there thanks for this workaround we will review this and fix for next release 1.6.0

**Comment by kevzlou7979** [comment]
Ok there is a revision to be improve instead of using ```tempSearches.isEmpty() == false``` , the best way is to use ```!tempSearches.isEmpty()```

**Comment by kevzlou7979** [comment]
Fixed via - https://github.com/GwtMaterialDesign/gwt-material/commit/7185f22c762b6daa4ad181c11533cf8f560ca43c
