### ISSUE TITLE
Floating MaterialButton shows no icon inside a DataGrid

### ISSUE THREAD

**Issue by RRosss** [GwtMaterialDesign/gwt-material#404]
Icon is not visible if I had a Column with a Floating Button in a DataGrid

Column<Book, MaterialButton> close = new Column<Book, MaterialButton>(new MaterialButtonCell()) {
    @Override
    public MaterialButton getValue(final Book  object) {
        MaterialButton mb = new MaterialButton();
        mb.setIconType(IconType.EDIT);
        mb.setType(ButtonType.FLOATING);
        return mb;
    }
};
table.addColumn(close);

**Comment by kevzlou7979** [comment]
Try our new Data Table instead
