### ISSUE TITLE
GWT Material overwrite the text box of GWTBootstrap?

### ISSUE THREAD

**Issue by darkcomet** [GwtMaterialDesign/gwt-material#405]
I'm using both GWTMaterial and GWTBootstrap.I'm using bootstrap's textbox but instead it shows Material's textbox.

<b:TextBox placeholder="Username"  ui:field="username" />
<b:TextBox placeholder="Password" ui:field="password"/>
<m:MaterialButton ui:field="loginsubmit" text="Button" waves="DEFAULT" backgroundColor="white" textColor="black"/>

**Comment by BenDol** [comment]
Probably because the CSS is overwriting text input elements. Its not advised to use two UI frameworks. Since there will be a lot of CSS cross overs.

**Comment by darkcomet** [comment]
Still any way to use it and counter it?

**Comment by BenDol** [comment]
There is no easy solution right now other than to create some kind of hacky CSS mash up between bootstrap and materialcss resources. In the future this might be possible, but the idea of Material Design is that it is used as a standalone framework. Mixing pure CSS UI frameworks (which is what bootstrap and materialcss both are) right now isn't intended as a use case.

**Comment by BenDol** [comment]
Note that you can load GWTMaterial without its resources using `GwtMaterialBasic~` module.

**Comment by darkcomet** [comment]
I totally switched to GM. Thanks @BenDol
