### ISSUE TITLE
Change TextBox in GWTMaterial

### ISSUE THREAD

**Issue by darkcomet** [GwtMaterialDesign/gwt-material#406]
How to change TextBox in GWTMaterial?

Like I need to have a http://screencast.com/t/2xweXmBhqm

Please help to resolve this Issue.

**Comment by kevzlou7979** [comment]
You can modify but it needs a hacky css to overwrite GMD TextBox Design.

**Comment by mrafsyam** [comment]
Can we overwrite it by using inline styling within the ui binder file itself? any example?

Note : quite new to GWT myself.

**Comment by kevzlou7979** [comment]
You can add to your css file , or inside UiBinder <ui:style>
```
input[type="text"] {
    background: white;
    border: 1px solid #e9e9e9;
    border-radius: 10px;
}
```
This turns your textbox to 
![image](https://cloud.githubusercontent.com/assets/3138071/19507876/359551da-9608-11e6-8bb4-20ed4f5fa732.png)

**Comment by mrafsyam** [comment]
thanks. Needed this.
