### ISSUE TITLE
MaterialCollapsible's setActive method is broken

### ISSUE THREAD

**Issue by ddenton** [GwtMaterialDesign/gwt-material#409]
The method `setActive` in MaterialCollapsible purports to be the approach to procedurally opening a collapsible item ([gwt-material-demo/#!collapsible](http://gwtmaterialdesign.github.io/gwt-material-demo/#!collapsible)).  However, it contains at least two bugs:

1) The method's documentation indicates that it takes a one-based index as its argument.  It also chooses the active widget in accordance to this indexing `activeWidget = getWidget(index - 1)`.  However, elsewhere the method assumes the argument is zero-based.

`if(index < getWidgetCount()) {`

Thus `setActive` cannot be used to select the last item (or any item if the collapsible has cardinality one).

2) This method, even when avoiding the previously described bug, only adds the `active` class to the MaterialCollapsibleItem and to the MaterialCollapsibleHeader.  It doesn't make the body visible.

As nearly as I can tell, this is supposed to be accomplished by the `expand` method in MaterialCollapsibleItem, but that method is never called.

**Comment by BenDol** [comment]
Thanks for catching these issues, will be resolved for 1.6.0 release.
