### ISSUE TITLE
MaterialCard background-color attribute not working

### ISSUE THREAD

**Issue by darkcomet** [GwtMaterialDesign/gwt-material#412]
I'm struggle for getting background-color through materialCard but failed everytime.

`final MaterialCard materialCard = new MaterialCard();
materialCard.setBackgroundColor("blue");
htmlpanel.add(materialCard, view.getElement());`

Is this a bug?

**Comment by kevzlou7979** [comment]
Try inspecting also the card-content, see if it has a bgcolor set. If here
is try also to have cardConent.setBacgroundColor...

**Comment by darkcomet** [comment]
Through inspecting It seems that there is no background-color set.

**Comment by darkcomet** [comment]
Anything to say on this? @BenDol

**Comment by BenDol** [comment]
Are you also calling backgroundColor="..." on the uibinder declaration? I'm unable to reproduce the issue.

**Comment by BenDol** [comment]
Ah just realized you are attaching it manually. Not sure what the issue is here since I am unable to reproduce the issue.

**Comment by darkcomet** [comment]
I'm making it as dynamic field so that by using some looping,I can create various field automatically without using ui:field at ui.xml

**Comment by BenDol** [comment]
can you paste a screenshot of the inspected card div element?

**Comment by darkcomet** [comment]
By inspecting,I can see no card div is being created there.
http://screencast.com/t/vFSemNF98ie

**Comment by BenDol** [comment]
Well you need to ensure the card actually exists and has content or you won't see the cards background since its got no width/height dimensions.

**Comment by darkcomet** [comment]
Even adding width,height no card is being shown.
