### ISSUE TITLE
setStyleName not working

### ISSUE THREAD

**Issue by darkcomet** [GwtMaterialDesign/gwt-material#413]
I need to add style to one of the widget.But what happen is while inspecting it,it shows css selector name(e.g; boxes) in div but doesn't created in CSS. [ref:. Screenshot]

Example:
`materialLink.setStyleName("boxes");`

Css : 
```
.boxes{
width:500px;
}
```

Screenshot : http://screencast.com/t/15nlmQK8UoDZ

**Comment by kevzlou7979** [comment]
I tried to reproduce the issue but the ```setStyleName``` is working fine.
![image](https://cloud.githubusercontent.com/assets/3138071/17474168/3c06913c-5d87-11e6-91c4-b30a731560d4.png)

Please make sure you added your css file as client resource. If you wrap it thru ```UiStyle``` the stylename will be autogenerated which may cause problem.

**Comment by darkcomet** [comment]
Do client resource means in "war" folder? @kevzlou7979
