### ISSUE TITLE
MaterialDropDown's setActivator doesn't function correctly

### ISSUE THREAD

**Issue by ddenton** [GwtMaterialDesign/gwt-material#416]
MaterialDrop down has a `setActivator` method designed to allow the user to proceedurally change the activator id on the element.  However, `setActivator` only saves the given id to a field, it doesn't write this to the element.  Contrast this with the use of the activator argument in the UiConstructor.

**Comment by kevzlou7979** [comment]
Hi @ddenton  Thanks for the report,
Can you please provide some code snippet for us to reproduce the issue.
Best Regards,
Kevin

**Comment by ddenton** [comment]
Sure.  

TestWidget.java:

	public class TestWidget extends Composite  {
		
		interface TestWidgetUiBinder extends UiBinder<Widget, TestWidget> {}
	
		private static TestWidgetUiBinder uiBinder = GWT.create(TestWidgetUiBinder.class);
		
		
		protected @UiField MaterialButton dropDownButton;
		protected @UiField MaterialDropDown dropDown;
	
		
		public TestWidget() {
			initWidget(uiBinder.createAndBindUi(this));
			dropDownButton.setActivates("constructorId");
			dropDown.setActivator("constructorId");
		}
	}

TestWidget.ui.xml:
```
	<m:MaterialPanel>
		<m:MaterialButton ui:field="dropDownButton" text="Dropdown" activates="uiBinderId" />
		<m:MaterialDropDown ui:field="dropDown" activator="uiBinderId" >
			<m:MaterialLink text="First" />
			<m:MaterialLink text="Second" />
			<m:MaterialLink text="Third" />
 		</m:MaterialDropDown>
	</m:MaterialPanel>
```

The activates property of the button will be changed from `uiBinderId` to `constructorId`, but the id of the drop-down element remains `uiBinderId`.

![drop_down_activator_1_5_3](https://cloud.githubusercontent.com/assets/1202952/17750048/55c7ef04-648e-11e6-941c-137f4aa2e515.png)

**Comment by kevzlou7979** [comment]
Hi there, 

I reproduce the problem, It seems that the id is not set when calling setActivator(). And my solution is to make sure that every time we call ```setActivator()``` we must set the id of the dropdown not only on initialization process.

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/ae779e72900134bb1750cc3375c81123dd0c5a36

Best Regards,
Kevin
