### ISSUE TITLE
MaterialCheckBox UiBinder visible="false" Not Working

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#418]
Setting a MaterialCheckBox's visibility to "false" when initially loading in UiBinder does not working. Also, does not work consistently in code either. 

A reasonable work-around is to wrap the MaterialCheckBox in a MaterialContainer and setting the MaterialContainer's visibility to false in UiBinder.

**Comment by kevzlou7979** [comment]
HI @washowasho ,

Good catch, I check deeply what causes the problem, I found out that https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialCheckBox.java#L134 this line overriding the setVisible() functionality. So I did a check and solve the issue.

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/a8f5698f5547eaa0c7a03b8a78718239b019a648
