### ISSUE TITLE
Icon on MaterialButton shows only Enum name

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#419]
Visible in the datagrid demo for 1.6

**Comment by wassx** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3955210/17748819/75879150-64bb-11e6-9bfe-6187f455e894.png)

**Comment by kevzlou7979** [comment]
It looks like the Material Icon does not add Initial class as ``` material-icons ``` related to https://github.com/GwtMaterialDesign/gwt-material-table/issues/2. Its happening only to widget cells because it appended as regular html.

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/17914067/a423c0e0-69d1-11e6-9e4e-27bf602fdbcc.png)

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/a8fdc678edb963211af807f055ae8f08fb72668d

**Comment by wassx** [comment]
cool thx
