### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#42]
1. Desktop all browsers: Dots missing

Open demo with charts, re-size browser window to the certain point when tree dots will be missing from cards:

![dots](https://cloud.githubusercontent.com/assets/9980558/8349611/8c5f07c4-1b1e-11e5-8a65-f89b25ee06ea.png)

2. Desktop IE browser: Big empty space on top of each card:

![ie](https://cloud.githubusercontent.com/assets/9980558/8349626/a56784d0-1b1e-11e5-87f2-ed3f93f17c67.png)

BTW Charts demo (at least on Chrome) is really awesome.

**Comment by kevzlou7979** [comment]
With new Coding scheme on MaterialCard now it supports multiple browser for the bug padding fixed.
![image](https://cloud.githubusercontent.com/assets/3138071/11335502/a1ca9d9c-9217-11e5-9489-4c5c591939c1.png)
