### ISSUE TITLE
MaterialDoubleBox Enabled=False Doesn't Disable Up/Down Buttons (v1.5.3)

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#420]
MaterialDoubleBox Enabled=False Doesn't Disable Up/Down Buttons

Enabled=False works for the text field, but not for the up/down buttons on a MaterialDoubleBox. I didn't test other widgets similar to this, but I would assume it's the same.

**Comment by kevzlou7979** [comment]
Ok this will be solve on 1.6.0-SNAPSHOT , check the demo showcase  http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!forms
