### ISSUE TITLE
GWT 2.8 support

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#421]
Are there any plans?

**Comment by BenDol** [comment]
2.0 is already based on 2.8.0rc1, so yes it will be supported :yum:

**Comment by wassx** [comment]
oh, i missed that one. just found the 1.6_snapshot on maven. Thx!

**Comment by wassx** [comment]
Sry, but where i can find 2.0?

**Comment by BenDol** [comment]
https://github.com/GwtMaterialDesign/gwt-material/tree/release_2.0

**Comment by wassx** [comment]
Thanks a million. I have to get more familiar with github.

**Comment by BenDol** [comment]
No problem
