### ISSUE TITLE
Date and Time picker

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#427]
Hey. I've noticed that we have DatePicker and TimePicker, but I did not found those two integrated. And basically all date formats can handle time also.

I think that We have to create Date and Time hybrid picker:
![image](https://cloud.githubusercontent.com/assets/1161910/17832540/bf40b208-6705-11e6-8ace-c048fb422731.png)
or
![image](https://cloud.githubusercontent.com/assets/1161910/17832568/6c47052e-6706-11e6-8059-a3f49b699f0c.png)
for one single input.

Or maybe we should develope another js wrapper, for example:
https://simeonc.github.io/sc-date-time/bootstrap.html (MIT)
https://ripjar.github.io/material-datetime-picker/ (MIT)

Also according to those inputs, please look on the form layout:
![image](https://cloud.githubusercontent.com/assets/1161910/17832777/76341bd0-670b-11e6-8532-ce3a30071533.png) - it is not looking good.

here is uibinde code for this:
```
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
	xmlns:g="urn:import:com.google.gwt.user.client.ui" xmlns:m="urn:import:gwt.material.design.client.ui"
	xmlns:ma="urn:import:gwt.material.design.addins.client"
	>
	
	<m:MaterialRow>
		<ma:window.MaterialWindow ui:field="window" width="70%" title="Event">
			<m:MaterialPanel padding="32" textAlign="CENTER">
				<m:MaterialTextBox placeholder="Title" ui:field="title" iconType="EVENT" />
				<m:MaterialTextBox placeholder="Description" ui:field="description" iconType="DESCRIPTION" />
				<m:MaterialCheckBox text="All day" ui:field="allDay"/>
				<m:MaterialDatePicker ui:field="startDate" placeholder="Start Date" />
				<ma:timepicker.MaterialTimePicker ui:field="startTime" placeholder="Start Time" />
				<m:MaterialDatePicker ui:field="endDate" placeholder="End Date" />
				<ma:timepicker.MaterialTimePicker ui:field="endTime" placeholder="End Time" />
			</m:MaterialPanel>
		</ma:window.MaterialWindow>
	</m:MaterialRow>

</ui:UiBinder> 
```

and in verticaly:
![image](https://cloud.githubusercontent.com/assets/1161910/17832792/f89d9b5a-670b-11e6-886f-15dfdc810d46.png)

	<m:MaterialRow>
		<ma:window.MaterialWindow ui:field="window" width="70%" title="Event">
			<m:MaterialPanel padding="32" textAlign="CENTER">
				<m:MaterialTextBox placeholder="Title" ui:field="title" iconType="EVENT" />
				<m:MaterialTextBox placeholder="Description" ui:field="description" iconType="DESCRIPTION" />
				<m:MaterialCheckBox text="All day" ui:field="allDay"/>
				<m:MaterialRow>
					<m:MaterialColumn grid="s6">
						<m:MaterialDatePicker ui:field="startDate" placeholder="Start Date" />
					</m:MaterialColumn>
					<m:MaterialColumn grid="s6">
						<ma:timepicker.MaterialTimePicker ui:field="startTime" placeholder="Start Time" />
					</m:MaterialColumn>
				</m:MaterialRow>
				<m:MaterialRow>
					<m:MaterialColumn grid="s6">
						<m:MaterialDatePicker ui:field="endDate" placeholder="End Date" />
					</m:MaterialColumn>
					<m:MaterialColumn grid="s6">
						<ma:timepicker.MaterialTimePicker ui:field="endTime" placeholder="End Time" />
					</m:MaterialColumn>
				</m:MaterialRow>
			</m:MaterialPanel>
		</ma:window.MaterialWindow>
	</m:MaterialRow>

**Comment by kevzlou7979** [comment]
We still dont have a goal to implement the dual implementation as it is not included in Material Design spec. what would be good is to separate it into different fields. We have solved also the input fields alignment on 1.6.0-SNAPSHOT. https://github.com/GwtMaterialDesign/gwt-material/issues/428

**Comment by masterdany88** [comment]
So what is Yours propose. What type of variable should I use to store only Date and second for only time?
Should it be `java.util.date`? What about time only?

**Comment by kevzlou7979** [comment]
Just add the date and time using external Client Library.

**Comment by masterdany88** [comment]
Can You give me a concrete data type?

**Comment by kevzlou7979** [comment]
You can use the ```java.util.date```
