### ISSUE TITLE
Icon for Date and Time picker

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#429]
Did You consider to add icons for input of types: Date, Time? Look how bad it looks without an icon here:
![image](https://cloud.githubusercontent.com/assets/1161910/17883912/a0837c1c-6915-11e6-8891-e222b250adba.png)

I think that all inputs should have Icon parameter.

**Comment by kevzlou7979** [comment]
Hi there, 

Yeah youre right. I will do those inputs to have an icon.
       - Date Picker
	- Time Picker
	- Autocomplete
	- ListBox
	- ComboBox

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/17891013/fe34bf64-696b-11e6-9898-6ac085adc6c9.png)

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/66e290adc3f701d431493ed9001da1be8d836f48 (DatePicker)
and https://github.com/GwtMaterialDesign/gwt-material-addins/commit/8b9a7ed4641b058c72f9dd8d7e3a11ba67d109a6 (Time Picker)
