### ISSUE TITLE
set two dropdown elements among each other

### ISSUE THREAD

**Issue by GerhardFr** [GwtMaterialDesign/gwt-material#43]
if you set two dropdown elements among each other with <m:MaterialDropDown text="Selection" color="blue" waves="light"...
the second dropdown hides parts of the first dropdownmenue. 

It's because waves-light add z-index=1 and the class dropdown-content else has z-index=1

**Comment by BenDol** [comment]
Need to confirm this issue, I haven't been able to reproduce it.

**Comment by kevzlou7979** [comment]
Is this still valid?

**Comment by GerhardFr** [comment]
it's fixed.
