### ISSUE TITLE
Wrong value for MaterialCheckBoxCell isChecked

### ISSUE THREAD

**Issue by leforthomas** [GwtMaterialDesign/gwt-material#430]
In my app the check value of MaterialCheckBoxCell is always false. It seems that the line
InputElement input = parent.getFirstChild().cast();
is wrong, and should be replaced by
InputElement input = parent.getFirstChild().getFirstChild().cast();
to catch the actual input element.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/2158ad621cbf8925d391d4ca22ce7e4655af2b85
