### ISSUE TITLE
Masonry display error on window resize

### ISSUE THREAD

**Issue by lostandfoud** [GwtMaterialDesign/gwt-material#431]
Follow the Masonry addins in 
http://gwtmaterialdesign.github.io/gwt-material-demo/#masonry

when i resize the window to a phone dimension and after restore the window to the initial size i have a display bug in Masonry internal components

![schermata del 2016-08-24 16-39-34](https://cloud.githubusercontent.com/assets/16701250/17934748/5f1b1cb2-6a19-11e6-8e01-7758afd03e22.png)

I also have this problem with my application, how can i fix that?

Thanks

**Comment by kevzlou7979** [comment]
I didn't saw any issue on my side. 
Can you please tell what kind of browser are you using and it's version?

**Comment by kevzlou7979** [comment]
Also will move this on to gwt-material-addins.

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/130
