### ISSUE TITLE
MaterialSwitch won't display updated labels if original label text was empty

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#434]
The method `MaterialSwitch.onLoad()` only adds the on and off labels if already a text is present in the corresponding span elements. If not the labels will be omitted from the DOM resulting in a switch without label(s) which cannot be set later. This makes it difficult to use it in lazily initialized UIs, e.g from database queries. I think the easiest way to fix this would be to remove the empty text checks. If no labels are set the switch would then just contain two empty spans that don't occupy additional layout space.

**Comment by kevzlou7979** [comment]
Ok yeah, thanks for catching this issue. Will patch it on 1.6.2.

**Comment by kevzlou7979** [comment]
I tested also in errai it solved the problem with labels. 
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/72b131a042587bb4a5e66452a430bcaac5e05e6a on 1.6.2 Release (On going)
