### ISSUE TITLE
Missing Feature : Alert,Confirm,Prompt box 

### ISSUE THREAD

**Issue by darkcomet** [GwtMaterialDesign/gwt-material#435]
I think there must be some alert,confirm,prompt box. 

@BenDol and all.

**Comment by kevzlou7979** [comment]
I will move this to gwt-material-addins. Which is the right place for new addins.

**Comment by kevzlou7979** [comment]
Ok moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/136
