### ISSUE TITLE
Links to demo site in source files incorrect

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [GwtMaterialDesign/gwt-material#436]
In many source files, the link to the demo site is gwt-material-demo.herokuapp.com.  This is of course incorrect.  The information on gwt-material-demo.herokuapp.com is outdated and the app is sometimes down.  Please update the links to the correct demo app https://gwtmaterialdesign.github.io/gwt-material-demo for proper reference in the documentation.

**Comment by kevzlou7979** [comment]
Can you elaborate the source files specifically? where it is? Thanks

**Comment by jonl-percsolutions-com** [comment]
I did a search of the repo and there appear to be at least 72 references throughout the code base to the old demo site.

https://github.com/GwtMaterialDesign/gwt-material/search?utf8=%E2%9C%93&q=gwt-material-demo.herokuapp.com

**Comment by kevzlou7979** [comment]
Great that helps us to find it :) Will do this now on 2.0

**Comment by kevzlou7979** [comment]
Also base from the search results , other results are comming from old versions, maybe on the future when testing it, it will be better to filter just for 2.0 release :)

**Comment by kevzlou7979** [comment]
I used Intelijidea to filter out and find the wrong link.
