### ISSUE TITLE
MaterialListBox and MaterialDoubleBox render with different heights

### ISSUE THREAD

**Issue by volgin** [GwtMaterialDesign/gwt-material#438]
See attachment: MaterialDoubleBox in this screenshot is 60px, while MaterialListBox is 44.5px, which breaks form alignment.

I could not pinpoint which CSS rule is responsible for this difference.

<img width="516" alt="screen shot 2016-08-28 at 8 24 19 pm" src="https://cloud.githubusercontent.com/assets/297748/18037977/df242f10-6d5d-11e6-8625-c10ead1ebe37.png">

Here is the UiBinder code:

```
<m:MaterialColumn grid="s6 m4 l4">
	<m:MaterialListBox placeholder="Company A" marginTop="36"/> 
	<m:MaterialListBox placeholder="Company B" marginTop="36"/> 
</m:MaterialColumn>
<m:MaterialColumn grid="s6 m2 l2">
	<m:MaterialDoubleBox placeholder="radius" marginTop="36"/>
	<m:MaterialListBox placeholder="Map type" marginTop="36"/> 
</m:MaterialColumn>
```

**Comment by kevzlou7979** [comment]
The code seems to be wrong. Please make use of built in ```grid``` module of the gwt-material
I fixed your code to be like this:
```
   <m:MaterialRow>
      <m:MaterialListBox grid="s6 m4 l4" placeholder="Company A"/>
      <m:MaterialListBox grid="s6 m4 l4" placeholder="Company B"/>
    </m:MaterialRow>
    <m:MaterialRow>
      <m:MaterialDoubleBox grid="s6 m4 l4" placeholder="radius"/>
      <m:MaterialListBox grid="s6 m4 l4" placeholder="Map type"/>
    </m:MaterialRow>
```

**Comment by volgin** [comment]
Your code produces exactly the same result as my code, so I don't understand why you closed this issue.

**Comment by kevzlou7979** [comment]
Always take note:
All input fields can use grid system.

Are you saying that forms always must consist of rows?
- Yes, because that is the better way to align it and apply the grid system.
