### ISSUE TITLE
API for MaterialListValueBox and MaterialListBox is complicated, confusing and broken.

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [GwtMaterialDesign/gwt-material#441]
Problems:

**MaterialListValueBox** appears to be typed for any occasion, but it has three sets of methods to add items that do not work correctly:

addValue(T value)
addItem(String, ....)
insertItem(String, ...)

Using the *Item methods, the item is not added to the list of values, which causes an exception in onChangeInternal() when the value of the drop down changes.

Also, other methods do that manipulate the listbox, ex. clear(), do not keep the values list and the listbox in sync.

This can be seen from the insertItem code:
  
```
    //there is no call to values.add in this method!!
    public void insertItem(String item, Direction dir, String value, int index) {
        listBox.insertItem(item, dir, value, index);
        if (initialized) {
            // reinitialize
            initializeMaterial(listBox.getElement());
        }
    }

```

Using the addValue method, items are added directly to the widget and not to the list box, causing them to appear outside of the listbox.

![image](https://cloud.githubusercontent.com/assets/6088906/18102865/0435b520-6ea9-11e6-8d88-d1795f3315a2.png)

**MaterialListBox** appears to "fix" this by creating a method add(Option), which allows addValue() to work correctly, but is still broken for the addItem methods.  this extension is rather pointless for the majority of the real world use cases.

To fix the API and make the class useful, I would suggest either making MaterialListValueBox abstract and creating extension points or using a renderer delegate provided to the class for properly rendering the value in the box, 

IE: 
```
public abstract class MaterialListValueBox<T> ....

    public void addValue(T value) {
        if(!values.contains(value)) {
            values.add(value);
             OptionElement opt = Document.get().createOptionElement();
             opt.setInnerSafeHtml(render(value).);
             getSelectElement().add(opt, null);
        } else {
            GWT.log("Cannot add duplicate value: " + value);
        }
    }

   protected abstract SafeHtml renderValue(T value);
}

```
OR

```
public interface ValueRenderer<T> {

    public void renderValue(T value, int index, SafeHtmlBuilder builder);
}

public abstract class MaterialListValueBox<T> ....

private ValueRenderer<? extends T> valueRenderer;

    public void setValueRenderer(ValueRenderer<? extends T> valueRenderer) {
        this.valueRenderer = valueRenderer;
    }
    public void addValue(T value) {
        if(!values.contains(value)) {
            values.add(value);
            SafeHtmlBuilder builder = new SafeHtmlBuilder();
            valueRenderer.render(value,values.indexOf(value),builder);
            OptionElement opt = Document.get().createOptionElement();
            opt.setInnerSafeHtml(builder.toSafeHtml());
            getSelectElement().add(opt, null);
        } else {
            GWT.log("Cannot add duplicate value: " + value);
        }
    }
}
```

I would also remove the *Item methods from the API update them to use the the type T, implement them similarly to addValue described above and delegate addValue/addItem methods to insertItem methods.

Would also like to see methods for check if a value is selected or not and clearing the selected item.  Also, would like to see the placeholder text if no item is currently selected and selection is not required, but the first item is what shows initially at this time.

**Comment by BenDol** [comment]
This has already be fixed in 1.6.1. Thanks!

**Comment by BenDol** [comment]
In regards to the value renderer, this could be be added, for the time being we are using `KeyFactory` interface to generate the lists key value.

**Comment by jonl-percsolutions-com** [comment]
There appear to still be some issues for MaterialListValueBox in 1.6.1 not addressed in the latest patch.  Like "clear()" does not clear the values, just the listbox.  There are also inconsistencies with the way that "value" is treated as a String in getSelectedIndex, setSelectedValue, setValueSelected, removeValue,getItemsSelected(), etc.

```
    /**
     * Removes all items from the list box.
     */
    @Override
    public void clear() {
        listBox.clear(); **<---- Need to clear values here or inconsistent state will arise**
        if (initialized) {
            // reinitialize
            initializeMaterial(listBox.getElement());
        }
    }

    @Override
    public void setValue(T value, boolean fireEvents) {
        int index = getIndex(value.toString()); **<----  Shouldn't this use the new ketFactory to determine the index, or shouldn't getIndex take a type T instead?**
        if(index > 0 && values.contains(value)) {
            T before = getValue();
            setSelectedIndex(index);

            if (fireEvents) {
                ValueChangeEvent.fireIfNotEqual(this, before, value);
            }
        }
    }
```
