### ISSUE TITLE
MaterialDatePicker returning null values (2.0-SNAPSHOT version)

### ISSUE THREAD

**Issue by muirfer** [GwtMaterialDesign/gwt-material#442]
Problem found with MaterialDatePicker. Methods getDate() and getValue() are returning null despite a date is selected and rendered correctly. Both methods call   @#protected method getPickerDate()

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/443/commits/30a71740df867eb77052568def99b7b7acad54cf
