### ISSUE TITLE
add method in MaterialStepper isn't called

### ISSUE THREAD

**Issue by StefanPlehn** [GwtMaterialDesign/gwt-material#444]
Hey guys,

if you use GWTP and MaterialStepper/MaterialStep and use setInSlot(...) from GWTP to add a MatertialStep to a MaterialStepper the add(MaterialStep) method in MaterialStepper isn't called. This results in some bugs, e.g. no SelectionEvent gets registered and therefore another step isn't opened when you click on it.

I think the add method in MaterialStepper has to overwrite the add method from its super class (Material Widget) and check if a widget is an instanceof MaterialStep.

Thank you for your great work :+1: 
(It's now possible to click on the title and description as well to open a step. Perfect.)

**Comment by kevzlou7979** [comment]
Ok thanks for catching it, I will move this one to addins issue because Stepper component is an addin. https://github.com/GwtMaterialDesign/gwt-material-addins/issues

**Comment by kevzlou7979** [comment]
Moved https://github.com/GwtMaterialDesign/gwt-material-addins/issues/137
