### ISSUE TITLE
NavBar does not handle window resize correctly.

### ISSUE THREAD

**Issue by volgin** [GwtMaterialDesign/gwt-material#445]
This is the code I tested:
```

<m:MaterialNavBar backgroundColor="blue" activates="mysidebar">
	<m:MaterialNavBrand href="#Test" float="LEFT">App Title</m:MaterialNavBrand>
</m:MaterialNavBar>

<m:MaterialSideNav width="240" m:id="mysidebar" type="FIXED" alwaysShowActivator="true" showOnAttach="false" backgroundColor="grey lighten-4" top="68" shadow="0">
	<m:MaterialNavBrand href="#Test">Analysis Type</m:MaterialNavBrand>
	<m:MaterialLink textColor="blue" text="Locations" />
	<m:MaterialLink textColor="grey" text="Overlap Analysis" />
	<m:MaterialLink textColor="grey" text="Clusters" />
</m:MaterialSideNav>

```

Upon page load the NavBar looks correct on screens wider than 960px:

<img width="672" alt="screen shot 2016-09-06 at 2 06 46 am" src="https://cloud.githubusercontent.com/assets/297748/18263295/f712a564-73d6-11e6-8720-054eec2efc36.png">

Trying to reduce the width of browser window leads to unpredictable (but always bad) results:

<img width="588" alt="screen shot 2016-09-06 at 2 07 24 am" src="https://cloud.githubusercontent.com/assets/297748/18263312/1127d0c8-73d7-11e6-81bb-582a51af6eeb.png">

<img width="442" alt="screen shot 2016-09-06 at 2 07 15 am" src="https://cloud.githubusercontent.com/assets/297748/18263311/1125ef9c-73d7-11e6-8659-b4f1bdfb3fcb.png">

Resizing the browser window to its previous width - or any other width - never fixes the problem. Only reloading the page leads to the correct positioning.

Also, reloading the page with browser width below 960px results in the same overlap of title and burger icon.

**Comment by BenDol** [comment]
Okay so what appears to be happening here is that the `MaterialSideNav` component `style` attribute at the DOM level is reset when resizing the window, meaning your `top="68"` is being removed. Our base materializecss library appears to reset the style tag when the nav bar is set to fixed. I have created a fix for this that we will push in `1.6.2` over the next few days.

As for the burger icon and the title text you simply need to add `left="60"` to your title to override the existing 0.5em left configuration. Thanks for the report(s)!
