### ISSUE TITLE
Setting showOnAttach="false" on MaterialSideNav has no effect

### ISSUE THREAD

**Issue by volgin** [GwtMaterialDesign/gwt-material#446]
MaterialSideNav with type="FIXED" is always displayed if a browser window is wider than 992px. 

(1) What's the purpose of this setting if it has no effect on MaterialSideNav behavior? I think the developer should have control over this behavior regardless of the window width - or be able to define the break point.

(2) Why 992px?

This is the code that I tested:

```
<m:MaterialSideNav width="240" m:id="mysidebar" type="FIXED" alwaysShowActivator="true" showOnAttach="false" backgroundColor="grey lighten-4" top="68" shadow="0">
	<m:MaterialNavBrand href="#Test">Analysis Type</m:MaterialNavBrand>
	<m:MaterialLink textColor="blue" text="Locations" />
	<m:MaterialLink textColor="grey" text="Overlap Analysis" />
	<m:MaterialLink textColor="grey" text="Clusters" />
</m:MaterialSideNav>
```

**Comment by kevzlou7979** [comment]
@volgin , First we have different behaviours or types of Side Nav http://gwtmaterialdesign.github.io/gwt-material-demo/#!sidenavs to follow.

The ```FIXED``` type is visible at first on Larger screen why? because on mobile its not great to display the sidenav which makes your Main Content shrink into small pieces.

Based on the Sidenav spec.
- 992px is the Based width of Larger screens. 

If you want to hide your sidenav at first I recommend to use ```PULL``` type instead.

Watch the vide tutorial here for more information https://www.youtube.com/watch?v=e-XY4EGVIuc

**Comment by volgin** [comment]
1. You source code includes 992px in two places and 960px in a different place.

2. I copied this code from your demo, where you show showOnAttach="false" with type="FIXED". This is confusing.

**Comment by BenDol** [comment]
Would be great if you could identify the inconsistency you have found in the sources so we can resolve it, thanks! Keep in mind we are under-going a large over-hall of the sources at the moment so now is a great time for these kinds of issues to be resolved. Thanks!

In regards to the issue raised, what kind of control would you be looking to have in this situation? Would you like to have the ability to configure this value to your own size configuration?

**Comment by volgin** [comment]
I am not as familiar with the code, of course, but I see that you apply different rules to smaller screens, defined as 992px:

```
protected native void pushElements(boolean toggle, int width) /*-{
....
     var mq = $wnd.window.matchMedia('all and (max-width: 992px)');


```

but showOnAttach is applied with a different rule (960px):

        if(showOnAttach) {
            Scheduler.get().scheduleDeferred(new ScheduledCommand() {
                @Override
                public void execute() {
                    if(Window.getClientWidth() > 960) {
                        show();
                    }
                }
            });
        }

I didn't look very deep, but it looks like you can get a more predictable behavior if these break points are the same.

You may consider making this  break point a default setting that users can override (e.g. 'setMinimumWidthToShow(int width)'). For many designs 993px is too narrow to show a 200-300px wide side navigation. For example, in a design that I am working on now, I would like to show SideNav by default for screens over 1180px as the main container gets too wide.
