### ISSUE TITLE
MaterialListBox throws exception or returns the wrong value

### ISSUE THREAD

**Issue by volgin** [GwtMaterialDesign/gwt-material#450]
(1) This code always results in an exception when a new value is selected:

```
Option o = new Option("Display Name");
o.setValue("name");
list.add(o);

```

(2) This code returns the wrong value:

`list.addItem("Display Name", "name");`

Both 'getSelectedItemText()' and 'getSelectedValue()' return the same - item text (e.g. " Display Name" in this example).

**Comment by BenDol** [comment]
(1) I am unable to reproduce this using version 1.6.1. Tested exactly as explained here using a `MaterialListBox`..

(2) I have resolved this and will include it in the 1.6.2 patch coming up soon (which also includes fixes to the side nav).

**Comment by volgin** [comment]
This is complete code that leads to this exception. Note the empty option:

		Option option = new Option("");
		list.add(option);

		for (Company company : Company.values()) {
			if (!company.name().equals(excludeCompany)) {
  				Option o = new Option(company.displayName());
  				o.setValue(company.name());
 				list.add(o);
			}
		}

**Comment by volgin** [comment]
What is a reason this patch is not in the master branch?

**Comment by volgin** [comment]
I switched to 1.6.2, and I now get "indexOutOfBounds" exception when switching values. I am using this code:

	<m:MaterialListBox ui:field="mapType" grid="s3" placeholder="Map type" >
		<m:html.Option text="Heat map" value="1"/>
		<m:html.Option text="Markers" value="2"/>
	</m:MaterialListBox>

It works in the master branch.

**Comment by BenDol** [comment]
Using both examples you have provided I am still unable to reproduce the exception. Please make sure you are using the correct `release_1.6.2` branch a long with its version `1.6.2-SNAPSHOT` after you have installed it with maven. This hasn't been released yet so you need to install it first.

**Comment by volgin** [comment]
I am compiling directly from the repository, using 1.6.2 branch. The exception shows the latest code correctly.

**Comment by dejia-meng** [comment]
MaterialListValueBox in version 1.6.2 is completely broken due to the incorrect values passed into ListBox.addItem and ListBox.insertItem.

An example is:
listBox.addItem(**keyFactory.generateKey(value), item**)  should have been listBox.addItem(**item, keyFactory.generateKey(value)**)

In version 1.6.2,
    public void addItem(String item, T value) {
        values.add(value);
        **listBox.addItem(keyFactory.generateKey(value), item);**
        if (initialized) {
            // reinitialize
            initializeMaterial(listBox.getElement());
        }
    }

**Comment by BenDol** [comment]
@dejia-meng you are correct, seems there was some confusion on the terms `value` and `item` when this was first implemented. We will resolve this in an up coming patch. These use cases will be tested. Thanks for reporting!
