### ISSUE TITLE
MaterialDropDown - Safari Mobile Only - SelectionHandler<Widget>().onSelection() Event Not Firing

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#451]
The .onSelection() event does not fire for the MaterialDropDown in Safari Mobile only. This is more than likely due to Safari Mobile  not implementing hover.

**Comment by kevzlou7979** [comment]
Will see if MouseDown event will fire so we need to update every click eventa

**Comment by kevzlou7979** [comment]
Hi there,

Event I changed it to mouseDown event, I can;t reproduce the issue.
Im using browserstack by the way.
![test1](https://cloud.githubusercontent.com/assets/3138071/18452504/a7fca578-796d-11e6-81c3-eb6439b493b1.gif)

Best Regards,
Kevin

**Comment by washowasho** [comment]
Hi Kevin - Thanks for replying. Just to make sure, in your video, did you change it to OnMouseDown and then record? Reason I ask is because I go to BrowserStack now, and use the same page as you, and I do not get the same results. See my screen shot. The click event is not executing all the time (I should get a Toast for all my clicks).

![animation](https://cloud.githubusercontent.com/assets/6689967/18454956/403c5d82-7915-11e6-8006-747007fb5cde.gif)

**Comment by kevzlou7979** [comment]
@washowasho I tried both but its the same one.

**Comment by kevzlou7979** [comment]
Can you specify which browser you've used? and version of ios?

**Comment by washowasho** [comment]
BrowserStack iPhone 6... I'm not exactly sure which versions are loaded on
that one.
