### ISSUE TITLE
MaterialListBox - GetSelectedValue Not Resetting After Clear() and/or Reset()

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#452]
After clearing a MaterialListBox (either using clear() or reset() ), the GetSelectedValue  of an item in the list **after repopulating the cleared** MaterialListBox is the same value as the selected item prior to the reset, not the actual selected value.

**Comment by BenDol** [comment]
This will be resolved in up coming 1.6.2, thanks for the report.

**Comment by washowasho** [comment]
Thank you. I tested the code changes in setAcceptableValues and clear... and all works well.
