### ISSUE TITLE
New app to showcase

### ISSUE THREAD

**Issue by rsallar** [GwtMaterialDesign/gwt-material#454]
Hi, I would like to share with the community my android application made with apache cordova and gwt-material. I hope you like it.

You can download it from: 

https://play.google.com/store/apps/details?id=cat.contesencatala

And find the sourcecode:

https://github.com/rsallar/contesencatala  (GWT)
https://github.com/rsallar/contesencatalapg (Cordova wrapper)

Hope you find them useful.

**Comment by kevzlou7979** [comment]
This is cool :) Will showcase it in demo site.

**Comment by kevzlou7979** [comment]
It's good also to post to https://gitter.im/GwtMaterialDesign/gwt-material or even https://plus.google.com/communities/108005250093449814286

**Comment by BenDol** [comment]
Looks cool ,unfortunately I cant test since its restricted to my country. Also the source code doesn't run as its missing `<script type="text/javascript" src="cordova.js"></script>` this library.

**Comment by remarkNS** [comment]
Not available in my country.
