### ISSUE TITLE
MaterialDatePicker features

### ISSUE THREAD

**Issue by ManOfGod** [GwtMaterialDesign/gwt-material#455]
I just wanted to ask if a new feature for MaterialDatePicker is possible to be added. I think it is good to add a year scroll or a next/previous year button like the month so that when selecting dates from previous years it will be quick.

**Comment by kevzlou7979** [comment]
Yeah this feature is already available
![image](https://cloud.githubusercontent.com/assets/3138071/18578010/073b1a38-7c20-11e6-8351-e609f8301518.png)

Here is the code
```
<m:MaterialDatePicker placeholder="Date" selectionType="YEAR"/>
or
<m:MaterialDatePicker placeholder="Date" selectionType="MONTH_DAY"/>
or
<m:MaterialDatePicker placeholder="Date" selectionType="YEAR_MONTH_DAY"/>
```
http://gwtmaterialdesign.github.io/gwt-material-demo/#!pickers

**Comment by kevzlou7979** [comment]
Feature was added 1.3.3
https://github.com/GwtMaterialDesign/gwt-material/wiki/Changelog#version-133
