### ISSUE TITLE
Crash :  with indicatorColor on MaterialTab

### ISSUE THREAD

**Issue by Axulie** [GwtMaterialDesign/gwt-material#456]
When I set "indicatorColor" on MaterialTab into ui.xml file, the application crash with this stack trace : 

> Uncaught Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: Exception caught: This UIObject's element is not set; you may be missing a call to either Composite.initWidget() or UIObject.setElement()

The issue comes from "getIndicatorElement" into "onLoad" function because the result is "undefined".
No elements have ".indicator" css class.

**Comment by kevzlou7979** [comment]
What version of gwt-material are you using?

**Comment by Axulie** [comment]
Sorry, I'm using the 1.6.2.

**Comment by BenDol** [comment]
This is normally caused when a composite UiObject doesn't set its element correctly. Can you show us the code used to produce this error? Seems more like an issue on your end than GMD.

**Comment by Axulie** [comment]
I just created a simple application with this code : 
`<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder" xmlns:g="urn:import:com.google.gwt.user.client.ui" xmlns:m="urn:import:gwt.material.design.client.ui" xmlns:ma="urn:import:gwt.material.design.addins.client">
    <ui:style>
    </ui:style>

    <g:HTMLPanel>
        <m:MaterialRow grid="s12">
            <m:MaterialColumn grid="s12" backgroundColor="blue">
                <m:MaterialTab backgroundColor="blue" indicatorColor="yellow">
                    <m:MaterialTabItem waves="DEFAULT" grid="s4">
                        <m:MaterialLink text="Info" href="#tab1" textColor="white" />
                    </m:MaterialTabItem>
                    <m:MaterialTabItem waves="DEFAULT" grid="s4">
                        <m:MaterialLink text="Transfo" href="#tab2" textColor="white" />
                    </m:MaterialTabItem>
                    <m:MaterialTabItem waves="DEFAULT" grid="s4">
                        <m:MaterialLink text="Optim" href="#tab3" textColor="white" />
                    </m:MaterialTabItem>
                    <m:MaterialTabItem waves="DEFAULT" grid="s4">
                        <m:MaterialLink text="Check" href="#tab4" textColor="white" />
                    </m:MaterialTabItem>
                </m:MaterialTab>
            </m:MaterialColumn>

            <m:MaterialColumn m:id="tab1" grid="s12">
            </m:MaterialColumn>

            <m:MaterialColumn m:id="tab2" grid="s12">
            </m:MaterialColumn>

            <m:MaterialColumn m:id="tab3" grid="s12">
            </m:MaterialColumn>

            <m:MaterialColumn m:id="tab4" grid="s12">
            </m:MaterialColumn>

        </m:MaterialRow>
    </g:HTMLPanel>
</ui:UiBinder>`
