### ISSUE TITLE
Tables and databinding

### ISSUE THREAD

**Issue by anton-johansson** [GwtMaterialDesign/gwt-material#46]
How do you best work with tables when using gwt-material?

http://www.gwt-material.appspot.com/#table

This page only shows how to use raw HTML, which isn't something I want to do. I'd like to be able to do the following:
 * Build a GUI with tables easily, for example ```<m:Table><m:TableRow><m:TableColumn></..></..></..>```
 * Bind the table to a table model. For example, if I have a domain object with a list of something, I want this list to be bound to the table.
 * Two-way bindings in the tables. For example, one column in the table might contain MaterialListBox, and if one row is changed here, I want it to be reflected to the domain object.

Any suggestions, ideas or discussions are welcome!

**Comment by kevzlou7979** [comment]
Can we use DataGrid or Cell table for this?

**Comment by anton-johansson** [comment]
I tested with GWT's CellTable, but it adds some classes that make it look like original GWT. Maybe easy to fix though. Not sure about DataGrid.

**Comment by kevzlou7979** [comment]
Ok yes, I think some CustomCellWidgets needs also to be compatible with CSS Inside Celltables

**Comment by kevzlou7979** [comment]
Hi,

We have developed the first version of DataGrid using GWT Material. You can check the simple implementation here : http://gwt-material.appspot.com/#datagrid

Regards,
GWT Material Design
