### ISSUE TITLE
GWTMaterial Browser Crash

### ISSUE THREAD

**Issue by zak905** [GwtMaterialDesign/gwt-material#461]
I have created a really simple application just to get a feel of GwtMaterial Design. The entry point looks like:
```
public class MaterialTheme implements EntryPoint {
  public void onModuleLoad() {
	  
	  MaterialIcon icon = new MaterialIcon();
	  icon.setType(ButtonType.RAISED);
	  icon.setTextColor("blue darken-1");
	  icon.setText("Test");
	  
	  RootPanel.get().add(icon);
   
  }
}
```
After packaging and deploying the application in jetty and launching the app, the browser crashes: 

![material-error](https://cloud.githubusercontent.com/assets/6265563/18794348/643c6ba2-81bf-11e6-81f4-58f7e091780a.png)

Even if I try to refresh, the browser just crashes.

**Comment by zak905** [comment]
Once I take out <inherits name="gwt.material.design.GwtMaterialBasicWithJQueryDebug"/> from the project, it works normally. 

I am not sure what really causes this, but it looks like a bug.

**Comment by kevzlou7979** [comment]
Do you have a simple project to test out as this one I can't reproduce into my machine.
Have you tested in different browsers like firefox , safari or others.

**Comment by zak905** [comment]
Here is the project: https://github.com/zak905/GwtMaterialTest 

I have tried in Firefox and Chrome, the result is the same.

**Comment by kevzlou7979** [comment]
I just checkout the project. 
I update the inherits GMD to
```
<inherits name="gwt.material.design.GwtMaterialWithJQuery"/>
```
and it works fine.

Here are the details about the GMD module imports
```
- GwtMaterialDesign # Standard use with all resources (but will not load jQuery for you).
- GwtMaterialDesignDebug # Same as above but will load non-minified js and Source URL included for Chrome debugging
- GwtMaterialWithJQuery # Standard use with all resources and will also include loading jQuery
- GwtMaterialWithJQueryDebug # Same as but will load non-minified js and Source URL included for Chrome debugging
- GwtMaterialDesignBasic # Use without materialize.css/overridecss.css file (but will not load jQuery for you).
- GwtMaterialDesignBasicDebug # Same as above but with non-minified js and Source URL included for Chrome 
- GwtMaterialBasicWithJQuery # Use without materialize.css/overridecss.css file and will also include loading jQuery
- GwtMaterialBasicWithJQueryDebug # Same as above but with non-minified js and Source URL included for Chrome debugging.
```
