### ISSUE TITLE
Crash on startup with on GWT 2.7.0 with GWT Material 1.6.2 / Classic Dev Mode

### ISSUE THREAD

**Issue by ainsley** [GwtMaterialDesign/gwt-material#462]
![gwtmat](https://cloud.githubusercontent.com/assets/201870/18810953/37171f28-829b-11e6-8d1b-105360ef196e.png)

**Comment by ainsley** [comment]
Investigated and seems a pretty simple fix. 

![mat2](https://cloud.githubusercontent.com/assets/201870/18811035/8c51955c-829d-11e6-933b-d7ca4045450d.png)

**Comment by kevzlou7979** [comment]
Hi there,

Can you show us whats the content / how you import GMD into your App.xml?
Make sure you inherit GMD with JQuery
```
<inherits name="gwt.material.design.GwtMaterialWithJQuery" />
```

Best Regards,
Kevin

**Comment by ainsley** [comment]
Thanks for your reply. I imported the module (as you guessed) as follows:

`<inherits name='gwt.material.design.GwtMaterialDesign' />`

I imported without JQuery, because I didn't think I needed it. The [page ](http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!gettingstarted) on the demo application showed me this as an available target.

**Comment by kevzlou7979** [comment]
You need jquery to use Materialize, the only way we define Basic Modules on Imports is we let the user manually import there designated JQuery Resources (Just to let them import there desired JQuery Version). So in other hand you need to import Jquery.
