### ISSUE TITLE
MaterialImage with activates 

### ISSUE THREAD

**Issue by mehtaronak** [GwtMaterialDesign/gwt-material#464]
I would like to have Image (custom) and on click of that I am showing MaterialDropDown with options. I found that m:MaterialImage doesn't have **_activates_**  and m:MaterialButton has activates  property but can'r set custom image.

What is the best way to achieve this combination ?

**Comment by kevzlou7979** [comment]
You can extend the MaterialImage and create another class then implement Has Activates. Just browsed the Acivates Mixin how we implement it.

Also why you need an Image to have a dropdown. If you want an Iconic dropdown, I prefer you use <m:MaterialButton iconType"POLYMER" /> or anything else.

**Comment by mehtaronak** [comment]
In MaterialImage  I will have used image and onclick I am showing dropdown.

**Comment by mehtaronak** [comment]
Can you give me more information on above implementation ?

**Comment by kevzlou7979** [comment]
Create a class CustomImage extends MaterialImage implements HasActivates...
once you've done that just make use of ActivateMixin which you can found on
the project path gwt/material/design/client/base/mixin

**Comment by mehtaronak** [comment]
Thank you so much for your all guidance, Attaching source code.


   public class CustomImage extends MaterialImage implements HasActivates {

	 private MaterialLink navMenu = new MaterialLink(IconType.MENU);

    	 private final ActivatesMixin<MaterialLink> activatesMixin = new ActivatesMixin<>(
			navMenu);
	 private Div div = new Div();

	 CustomImage() {
		div.setStyleName("nav-wrapper");
		div.add(navMenu);
		super.add(div);
	 }

	@Override
	public void setActivates(String activates) {
		activatesMixin.setActivates(activates);
	}

	@Override
	public String getActivates() {
		return activatesMixin.getActivates();
	  }
     }


Let me know if you find anything wrong. This option should be available in MaterialImage by default.

**Comment by kevzlou7979** [comment]
In your CustomImage() Constructor instead of writing all the logic just
call super().

**Comment by mehtaronak** [comment]
Thank you for all your suggestion. It all works. Attaching code which might be helpful to others,

public class CustomImage extends MaterialImage implements HasActivates {

	private final ActivatesMixin<CustomImage> activatesMixin = new ActivatesMixin<>(
			this);

	CustomImage() {
		super();
	}

	@Override
	public void setActivates(String activates) {
		activatesMixin.setActivates(activates);
	}

	@Override
	public String getActivates() {
		return activatesMixin.getActivates();
	}
}

**XML**

	<a:CustomImage ui:field="userAvatar" styleName="{style.avatar}"
						activates="logout" />
       
       <m:MaterialDropDown activator="logout"
				styleName="{style.dropdown}" belowOrigin="true">
				<m:MaterialLink text="Logout " />
			</m:MaterialDropDown>

**Comment by kevzlou7979** [comment]
Yeah will try to add this on 2.0 for images.

**Comment by mehtaronak** [comment]
Thank you so much for the quick response. Thanks

**Comment by kevzlou7979** [comment]
Welcome, I added it on GMD 2.0 MaterialImage via https://github.com/GwtMaterialDesign/gwt-material/commit/4752ee62be5061494f00e946baca5e202f247454
