### ISSUE TITLE
Material Date Picker Events

### ISSUE THREAD

**Issue by zak905** [GwtMaterialDesign/gwt-material#466]
I am unable to capture the MaterialDatePicker blur event : 

```
startDate.addBlurHandler(new BlurHandler(){
			@Override
			public void onBlur(BlurEvent event) {
				GWT.log("blurring");
				
			}
		});
```

**Comment by kevzlou7979** [comment]
This one is ready for 2.0

**Comment by zak905** [comment]
Ok then. I found a workaround using the close event

**Comment by zak905** [comment]
it would also be nice to also have a required property for the Material Date picker

**Comment by zak905** [comment]
It would also be great to have a required field for the MaterialDatePicker also

**Comment by kevzlou7979** [comment]
What do you mean by required property. If its validation make use of Custom
Validator see the Errors Doc on fields

**Comment by kevzlou7979** [comment]
As I browsed the AbstractValueWidget, we extended Pickers , Number Boxes and Text Fields to AbstractValueWidget meaning you can make use of property ```setAllowBlank(boolean value) ```

**Comment by zak905** [comment]
Ok. What I meant, is that since MaterialDatePicker makes use of MaterialInput to display the date value, it would be nice to have HTML5 validation for MaterialDatePicker as well, something like: <m:MaterialDatePicker required="true" TYPE="SOME_DATE_TYPE">. It's nice because it can be validated by only checking if css has :valid property or no.

**Comment by kevzlou7979** [comment]
We have a CustomValidation in GMD 1.6.x http://gwtmaterialdesign.github.io/gwt-material-demo/#!errors. Where you can setup any validation you want into AbstractValueWidget https://github.com/GwtMaterialDesign/gwt-material/tree/master/gwt-material/src/main/java/gwt/material/design/client/base/validator. There are different built in validators we implement with that link I shared.

Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/468/commits/85f7492f947b21cdebb33271769f2393fdec26fb.

I found an issue on setAllowBlank on both Time and DatePicker but it will be ready on 2.0.
![allow_blank](https://cloud.githubusercontent.com/assets/3138071/19182724/4ad37744-8ca7-11e6-9492-d9b1a857fd70.gif)
