### ISSUE TITLE
GWT 2.6.x Support

### ISSUE THREAD

**Issue by Alaa-Ellethey** [GwtMaterialDesign/gwt-material#469]
**2.6.x** versions are still in use till now for a large number of projects, just to use the **GWT designer** in eclipse, i am one of these whose depends on this version of GWT to use this feature, and i am glad to see this new integration between GWT and Google Material Design, So it is highly recommended from me to support GWT 2.6.x version and hope it easy to add this feature with the minimal changes.

**Comment by kevzlou7979** [comment]
GMD 1.x supports GWT 2.6.x and 2.7.x. Also for GWT Designer, we are not using it as we have already browser Inspector to apply any styles to element.

**Comment by Alaa-Ellethey** [comment]
Many thanks for your fast reply, but from my point of view i see that the GMD 1.x does not support for GWT 2.6.x for the next reasons

the project is depending on GWT 2.7.0 regarding to the maven dependency tree.

when i try to modify it by myself, some small compilation errors appeared, for example in MaterialListValueBox class in getSelectedItemText method, but i use alternative code from GWT 2.6 by replacing  {return listBox.getSelectedItemText();} with {return listBox.getValue(listBox.getSelectedIndex());} and this will give the same result.

after modifications with previous point, the whole project has no errors, but in runtime the browser console has a lot of js errors.

based on that i see that the current release version of GMD is not supported for GWT 2.6, and hope you try replacing the GWT 2.7.0 to GWT 2.6.1 in maven dependency to see what i mean.

before and after that, i need to say many thanks for this great effort providing us with this awesome API.

**Comment by amitanshuoranuj** [comment]
I am facing the same problem as described here. Any fix apart from upgrading to 2.7 ?
