### ISSUE TITLE
ColorsMixin does not remove old color in setTextColor method

### ISSUE THREAD

**Issue by richelivargas** [GwtMaterialDesign/gwt-material#471]
Release 2.0

Problem:

@Override
    public void setTextColor(Color textColor) {
        if (this.textColor != null && !this.textColor.getCssName().isEmpty()) {
            **uiObject.removeStyleName(this.textColor.getCssName());**
        }
        this.textColor = textColor;

        if (this.textColor != null && !this.textColor.getCssName().isEmpty()) {
            uiObject.addStyleName(ensureTextColorFormat(textColor.getCssName()));
        }
    }

Solution:

@Override
    public void setTextColor(Color textColor) {
        if (this.textColor != null && !this.textColor.getCssName().isEmpty()) {
            **uiObject.removeStyleName(ensureTextColorFormat(this.textColor.getCssName()));**
        }
        this.textColor = textColor;

        if (this.textColor != null && !this.textColor.getCssName().isEmpty()) {
            uiObject.addStyleName(ensureTextColorFormat(textColor.getCssName()));
        }
    }

**Comment by BenDol** [comment]
Nice catch, thanks!

**Comment by kevzlou7979** [comment]
Hi I added a test case example for this fixed https://github.com/GwtMaterialDesign/gwt-material/commit/8d21d3a86726f6692f962a8775807e69757954cf
![textcolor](https://cloud.githubusercontent.com/assets/3138071/19342260/a6a1117e-9163-11e6-9a5c-9cfe9392f830.gif)
