### ISSUE TITLE
Layout crash when content height is different when use grid property for RWD

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#476]
I used MaterialColumn grid property for RWD. When the height at the first column is more than the second, it will cause blame space below the first column when turns to smaller monitor. 
See the sample code below for the difference between **large** screen and **medium** screen.
I expected it should be 
```
A B
C D
```
But it is 
```
A  B
   C
D
```
The height gap between A and B should be retained at the first row but not affect the second row when change screen size. Did I misunderstand? Thanks.
`
                container = new MaterialContainer();
		container.setFontSize("20pt");

		MaterialRow row1 = new MaterialRow();

		container.add(row1);
		
		MaterialColumn col1 = new MaterialColumn();
		col1.setGrid("s12 m6 l3");
		col1.setHeight("50px");
		MaterialLabel label1 = new MaterialLabel();
		label1.setText("A");
		col1.add(label1);
		
		MaterialColumn col2 = new MaterialColumn();
		col2.setGrid("s12 m6 l3");
		MaterialLabel label2 = new MaterialLabel();
		label2.setText("B");
		col2.add(label2);
		
		MaterialColumn col3 = new MaterialColumn();
		col3.setGrid("s12 m6 l3");
		MaterialLabel label3 = new MaterialLabel();
		label3.setText("C");
		col3.add(label3);
		
		MaterialColumn col4 = new MaterialColumn();
		col4.setGrid("s12 m6 l3");
		MaterialLabel label4 = new MaterialLabel();
		label4.setText("D");
		col4.add(label4);
		
		row1.add(col1);
		row1.add(col2);
		row1.add(col3);
		row1.add(col4);`

**Comment by kevzlou7979** [comment]
This is acceptable, MaterialGrid will just occupy horizontal spaces but we have build MaterialMasonry to display your columns into Masonry Structure (Like bricks) you can take a look here to test it for your self ;).   http://gwtmaterialdesign.github.io/gwt-material-demo/#masonry
![image](https://cloud.githubusercontent.com/assets/3138071/19344162/b10c40a4-916b-11e6-86e6-31357a04bdd7.png)

**Comment by peggieHou** [comment]
Got it. Many thanks! :)
