### ISSUE TITLE
MaterialLink waves not work when change textColor in MaterialCardAction

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#477]
I followed MaterialCard sample project and used the MaterialCardAction. I found MaterialLink under MaterialCardAction will have default **orange** text color and **light** waves. But when I changed the MaterialLink textColor to another, the waves is not work, even though implement the API setWaves(WavesType.LIGHT). Could fix it?

**Comment by kevzlou7979** [comment]
Its working fine for me. Just make use of WavesType.DEFAULT not LIGHT why? because if you have a white background then you will not able to see the LIGHT wave. Thats why I think you have an issue into it.

## Code Example
```xml
            <m:MaterialCardAction>
              <m:MaterialLink waves="DEFAULT" textColor="RED" text="Link 1" iconType="POLYMER"/>
              <m:MaterialLink waves="DEFAULT" textColor="RED" text="Link 1" iconType="POLYMER"/>
            </m:MaterialCardAction>
```
## Screenshot
![link_color](https://cloud.githubusercontent.com/assets/3138071/19343976/ff8c42d4-916a-11e6-8e90-50a8cf046b67.gif)

**Comment by peggieHou** [comment]
Would you please check my code? I still have no waves effect on the Link1 on my PC. 
You can see the difference between Link1 and Link2. Thanks!

`<m:MaterialCard backgroundColor="teal lighten-1">
	<m:MaterialCardContent textColor="white">
		<m:MaterialTooltip text="More Function"
			position="RIGHT">
			<m:MaterialCardTitle text="TEST"
				iconPosition="RIGHT" />
		</m:MaterialTooltip>
	</m:MaterialCardContent>

	<m:MaterialCardAction backgroundColor="white">
		<m:MaterialLink text="(1) Link1"
			iconType="ALARM_ON" textColor="red" waves="DEFAULT"/>
		<m:MaterialLink text="(2) Link2"
			iconType="EDIT" />
	</m:MaterialCardAction>

</m:MaterialCard>`

**Comment by kevzlou7979** [comment]
I tested both 2.0 and 1.6.0 both are working fine. What Browser are you testing? We have Browserstack so it will be good if you indicate what version of your browser you are using.

**Comment by kevzlou7979** [comment]
![waves](https://cloud.githubusercontent.com/assets/3138071/19346669/357048da-9177-11e6-8690-884818c40d8b.gif)

**Comment by peggieHou** [comment]
Sorry for the late response. I tested Chrome version 53.0.2785.143 and IE 10 both are not working. Are them supported? By the way, I tested version 1.6.2 and 1.6.0 both. Thank you.

**Comment by peggieHou** [comment]
OH! You are right. I found white background cannot see the LIGHT waves, and it works fine until I changed to another background color. But I saw your test is also working fine even if background is white?
Another question, how can I have the affect like LINK2 when mouse over?

**Comment by kevzlou7979** [comment]
> But I saw your test is also working fine even if background is white?
- Yes because I Used ```WavesType.DEFAULT```
> Another question, how can I have the affect like LINK2 when mouse over?
- You can make use of css selector ``` link:hover ``` http://www.w3schools.com/cssref/sel_hover.asp

**Comment by peggieHou** [comment]
Thanks for your clearly response. It's working fine now! It's really useful.
