### ISSUE TITLE
How to change the text default uppercase style within MaterialCardAction

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#479]
The text in MaterialCardAction is always uppercase. It's not working even if I add a style name to MaterialCardAction and force to change text transform. How could I do for this? It will be very useful and flexible if any API could change text style on each GMD component.
```
           <m:MaterialCardAction>
     <m:MaterialLink text="Link 1" iconType="POLYMER"/>
     <m:MaterialLink text="Link 2" iconType="POLYMER"/>
    </m:MaterialCardAction>
```

**Comment by BenDol** [comment]
This is a CSS property for cards I assume, you jsut need to override the `text-transform` to `none`.

**Comment by peggieHou** [comment]
Yes. Traced code and found CSS for card in Materialize.min.css. But I don't know how to override is completed correct.
The CSS I override is not working.
```
.card .card-action 
{
	color: #ffab40;
	margin-right: 20px;
	transition: color .3s ease;
	text-transform: none;
}
```

**Comment by kevzlou7979** [comment]
Well make use of !important like this.
```css text-transform: none !important ```
