### ISSUE TITLE
MaterialDatePicker is not returning correct value

### ISSUE THREAD

**Issue by chinshaw** [GwtMaterialDesign/gwt-material#480]
If you print it as a string it will print the correct date but the return from the date picker is a JsDate. The value needs to be converted to java.util.Date. The format from the java date is not compliant with the DateTimePicker for conversion. 

Here is what I had to do to make it work.

    private static final DateTimeFormat GWT_DATE_FORMAT = DateTimeFormat.getFormat("dd MMMM yyyy");
...

    /**
     * Get the pickers date.
     */
    protected Date getPickerDate() {
        try {
            final JsDate selectedDate = (JsDate) $(pickatizedDateInput).pickadate("picker").get("select", getFormat());
            return GWT_DATE_FORMAT.parse(selectedDate.toString());
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

Notice that the month must be "MMMM" and not "mmmm". It looks like it work but the date is always null. I tried to convert the format = dd MMMM yyyy but that did not work for me. I am pretty sure that you cannot return a java.util.Date from the getPickerDate() without converting it from JsDate using something like DateTimeUtil.

**Comment by chinshaw** [comment]
Note I also modified the JsMaterialElement class to return a JsDate instead of a java.util.Date.

    @JsMethod
    public native JsDate get(String key, String format);

**Comment by kevzlou7979** [comment]
Ok let me check this out, and give you a response

**Comment by kevzlou7979** [comment]
I think this one is related with this https://github.com/gwtproject/gwt/issues/9286. Will figure it why it happens.

**Comment by kevzlou7979** [comment]
Fixed with https://github.com/GwtMaterialDesign/gwt-material/commit/30a04f2d186ae7f4dfc8011da0b70f5dcf7c9001
