### ISSUE TITLE
How to control activator in NavBar?

### ISSUE THREAD

**Issue by peggieHou** [GwtMaterialDesign/gwt-material#483]
I followed the NavBar sample below in JAVA:
```
<m:MaterialNavBar backgroundColor="blue" width="100%">

  <m:MaterialNavBrand href="#Test" float="LEFT">App Title</m:MaterialNavBrand>

  <m:MaterialNavSection float="RIGHT">
   <m:MaterialLink iconType="ACCOUNT_CIRCLE" iconPosition="LEFT" text="Account" textColor="white" waves="LIGHT"/>
   <m:MaterialLink iconType="AUTORENEW" iconPosition="LEFT" text="Refresh" textColor="white" waves="LIGHT"/>
   <m:MaterialTooltip text="Menu">
    <m:MaterialLink iconType="SEARCH" textColor="white" waves="LIGHT"/>
   </m:MaterialTooltip>
   <m:MaterialTooltip text="Starter">
    <m:MaterialLink iconType="MORE_VERT" textColor="white" waves="LIGHT"/>
   </m:MaterialTooltip>
  </m:MaterialNavSection>

 </m:MaterialNavBar>
```
This component is useful that MaterialNavSection will auto hidden under **medium beyond** window and will show a Menu icon at the left top. 
But when I  assigned the NavBar property as `navBar.setActivates("sidebar"); ` and created a MaterialSideNav for this Menu icon with `sideNav.setId("sidebar");`. 
1. The Menu icon will always show even under **large** window. The default effect is gone that it should be hidden on large window.
2. The MaterialSideNav will always show when page on loaded. I couldn't find API to close this SideNav.

**Comment by kevzlou7979** [comment]
Please can you enumerate what version of GMD are you using?

**Comment by peggieHou** [comment]
1.6.2

**Comment by kevzlou7979** [comment]
> 1. The Menu icon will always show even under large window. The default effect is gone that it should be hidden on large window.

<b>Answer:</b> You can control the visibility of the Nav Menu Icon by calling ```sideNav.setAlwaysShowActivator(false)``` to hide the Nav Menu.
https://github.com/GwtMaterialDesign/gwt-material/blob/release_1.6.2/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialSideNav.java#L542

>2. The MaterialSideNav will always show when page on loaded. I couldn't find API to close this SideNav.

<b>Answer:</b> You can control the visibility of the Sidenav by calling ``` setShowOnAttach(false) ``` https://github.com/GwtMaterialDesign/gwt-material/blob/release_1.6.2/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialSideNav.java#L557
