### ISSUE TITLE
MaterialSideNav (Push-type) briefly visible on page refresh even with showOnAttach==false

### ISSUE THREAD

**Issue by vidalborromeo** [GwtMaterialDesign/gwt-material#485]
For the 'push' type of MaterialSideNav, here is what I'm seeing in both Chrome and Firefox...

When showOnAttach==true (correct behavior):
- The SideNav expands by default on a large enough window size.
- The SideNav does not expand by default on window sizes smaller than that.

When showOnAttach==false (incorrect behavior):
- The SideNav _always_ pops out briefly before disappearing.

**Comment by kevzlou7979** [comment]
Duplicate https://github.com/GwtMaterialDesign/gwt-material/issues/473
