### ISSUE TITLE
Active MaterialLink in MaterialSideNav

### ISSUE THREAD

**Issue by Stanyslav** [GwtMaterialDesign/gwt-material#486]
Hello,
I tried to make MaterialSideNav
Thanks to the good documentation but everything turned out why something is not marked active MaterialLink inside MaterialSideNav
The same problem found in your demo: http://gwtmaterialdesign.github.io/gwt-material-demo/

For example: You are on the home page:!#about - but this link is not marked as active
Then if you change for example: Components-> Badges, url change #!badges
We refresh your page and see that the child and the parent menu item is active.
But if the same thing done with menu items that do not have child elements (eg about) after reloading the page does not become active.

The same problem can occur when on the move "#!about" and then in the Components-> Badges. Points about Badges and steel are both active,
about to become inactive, but still remains active.

Please advise how to get around this problem. Not as it is impossible to make navigation.

Sorry for my English.

**Comment by BenDol** [comment]
I have already added basic support for url parsing to identify the active `place` but this is something that is agnostic in our API since everyone's requirements are different. I would suggest you integrate your own url parsing method that best fits your application.

The problem with the Head button `About` not removing its active state could be resolved however, but as mentioned the support here is very basic to help get the ball rolling in your application specifically.

Thanks!

**Comment by Stanyslav** [comment]
Thanks for the response.
But I all the same not much in confusion how to realize parsing of url in the application.
You have code samples or articles which will help to understand how to solve a problem? As option to make a component for your project
<m:MaterialActiveLink targetHistoryToken="{tokens.getPageUrl}" />
which will add the Css-class "active" in case of compliance of targetHistoryToken and current url

I only began to study GWT.
In the project I use gwt platform (http://dev.arcbees.com/gwtp/index.html)
I so understand it is necessary to understand how to use
Route Token Formatter (http://dev.arcbees.com/gwtp/core/navigation/token-formats.html)
and 
Place (http://dev.arcbees.com/gwtp/core/presenters/creating-places.html) for this purpose that to mark the necessary menu items as the active. Or I look not there?

**Comment by BenDol** [comment]
This is the basic support we currently have for checking the collapsible active state based on the url: https://github.com/GwtMaterialDesign/gwt-material/blob/6079f7a7d73af5131ad5e84eb153bff06796c9fc/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialCollapsibleBody.java#L130.
So if that format isn't matched in the as seen in the `MaterialCollapsibleBody` it will simply ignore it.

So to make sure the `!about` link button is marked as active you just need to add a check in your application to mark which buttons are active based on your URL format.

**Comment by Stanyslav** [comment]
Thanks a lot, for support. It turned out to solve both problems at once. 
Here the link to the `MaterialLink` code which automatically becomes the active and vice versa.
[https://gist.github.com/Stanyslav/e217530affeed531fe5ad5e65060e00c](url)
