### ISSUE TITLE
MaterialTab loaded with Full Strip underneath of TAB

### ISSUE THREAD

**Issue by mehtaronak** [GwtMaterialDesign/gwt-material#487]
I am using this http://beta.pastee.com/w4j7h code to add MaterialTab in my application
Issue : First time when TABs are getting loaded I see BOTTOM strip underneath of all tabs Once I select any tab then TABs works fine and now I see TABs under selected tabs.

Attaching screenshot for reference.

![capture](https://cloud.githubusercontent.com/assets/13400807/19624701/8ccd8b1e-9920-11e6-954c-b43a0645c3ae.PNG)

Check YELLOW bottom strip TABs. Image is taken when TABs are loaded for first time.

**Comment by kevzlou7979** [comment]
I cant duplicate this issue on Both Errai and GWTP.
