### ISSUE TITLE
Password TextBox Missing

### ISSUE THREAD

**Issue by jeffgnpc** [GwtMaterialDesign/gwt-material#49]
Create a password TextBox that has * instead of characters.

**Comment by ye3i** [comment]
<m:MaterialTextBox type="password" />

**Comment by jeffgnpc** [comment]
Please update your login demo to have this change.

**Comment by kevzlou7979** [comment]
Hi,

You can now check the demo http://gwt-material.appspot.com/#showcase and source code here https://github.com/kevzlou7979/GWTMaterialDesign/blob/master/gwt.material.design.demo/src/gwt/material/design/demo/client/showcase/MaterialLogin.ui.xml

Regards,
GWT Material Design Team
