### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#490]
does GDM support switching page direction RTL/LTR?

**Comment by kevzlou7979** [comment]
What do you mean by switching pages

**Comment by vegegoku** [comment]
Assume i have a site that serves both english -LTR- and arabic -RTL- users, so i might have a button that change the site from english to arabic and i can click that button at any time to change the language which also supposed to change the page direction not just the labels.

**Comment by BenDol** [comment]
You will need to use GWT locales for language support http://www.gwtproject.org/doc/latest/DevGuideI18nLocale.html

I don't believe any of our widgets have hard-coded EN locales, but if we do feel free to let us know!

**Comment by kevzlou7979** [comment]
@vegegoku Note that our DatePicker contains only a hard-coded locales so we added different locales.
