### ISSUE TITLE
Horizontal FAB problem on Internet Explorer 11

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#492]
Horizontal FAB doesn't display correctly on IE11.

When FAB is open, buttons are on the right of the FAB instead of on the left.

Tested on version 1.6.2.

And possible to see on your website :
http://gwtmaterialdesign.github.io/gwt-material-demo/#fabs

Hope it helps.

**Comment by kevzlou7979** [comment]
Thanks for catching, I am able to reproduce the issue on BrowserStack and find a solution. Will commit the solution for IE11 fixed soon.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/489/commits/b1ec5a0a4448c6ff0492a7be0c29a4c803b6db1f
