### ISSUE TITLE
ShowOn SHOW_ON_MED problem

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#493]
I tried the showOn option to show a panel only on medium, but it doesn't work.

Code used :
MaterialPanel mediumFabPanel = new MaterialPanel();
mediumFabPanel.setShowOn(ShowOn.SHOW_ON_MED);

Fix for me (using initialClass) :
MaterialPanel mediumFabPanel = new MaterialPanel("hide-on-small-only", "hide-on-large-only");

Tested on version 1.6.0.

I have not try others parameters.

Not visible on your website.

Hope it helps.

**Comment by kevzlou7979** [comment]
Thanks for catching, The issue was there's no class ```show-on-med`` on Materialize it must be ```show-on-medium```, I will update the ENUM values.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/33f922b2ce13b1510d8e7330f6aeec893fe0224d
