### ISSUE TITLE
SideNav - Horizontal Spaces

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#496]
It seems that sidenav with nested collapsible sidenav items create horizontal spaces which is a cosmetic minor issue on the Ui Look of the sidenav.

![issue5](https://cloud.githubusercontent.com/assets/3138071/20173297/a5e07880-a773-11e6-9e92-3bc3cb113615.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/bb876a69d3b3db40d95da600186e859306c97162

**Comment by remarkNS** [comment]
@kevzlou7979  on the same image you can see another problem: Problem 1: Top navigation bar with blue color is "shifted" left when side navigation is open. When you click or tap on right "main" (outside side navbar) space, it will render ok, but another problem is much more serious: Problem 2: on mobile device if you close sidebar by "drag out menu" or "swipe side navigation on left" than it will render top navigator completely wrong. I do not have a time to make a screenshot now, but I can do it later if necessary. It's very easy to reproduce on real mobile device, but you cannot do it on desktop as you are not able to close it that way.

**Comment by kevzlou7979** [comment]
Yeah it seems that the issue came from Errai Demo. I am doing now the fixed which is inside the SidenavOpenEvent and SidenavCloseEvent

**Comment by BenDol** [comment]
Its a demo specific error not with the gwt material library itself

**Comment by kevzlou7979** [comment]
Yeah agreed, I updated the errai demo and now everything behaves well :)
![issues6](https://cloud.githubusercontent.com/assets/3138071/20200541/bb5fa694-a7ec-11e6-87a5-44dc94294e5c.gif)

**Comment by remarkNS** [comment]
Perfect!
