### ISSUE TITLE
MaterialLabel does not escape the given text.

### ISSUE THREAD

**Issue by yu-kopylov** [GwtMaterialDesign/gwt-material#497]
MaterialLabel does not escape the given text.
This behaviour is different from GWT Label and potentially enables XSS attacks.
GWT-Material Version: 1.6.2

Example:
`label.setText("<button>test</button>")` - will display a button, instead of text

**Comment by kevzlou7979** [comment]
We can escape the html tags or element directly but I think let's see how other users / contributors opinion about it :) Thanks for the information

**Comment by kevzlou7979** [comment]
So I got a solution for this Security Issue.

``` java

    @Override
    public void setText(String text) {
        setText(SafeHtmlUtils.fromString(text));
    }

    public void setText(SafeHtml safeHtml) {
        getElement().setInnerHTML(safeHtml.asString());
    }

```

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/07b34ce9bbb35cf4d69634a02bb1f2ad2914c549
