### ISSUE TITLE
MaterialWindow

### ISSUE THREAD

**Issue by respeso** [GwtMaterialDesign/gwt-material#498]
I have migrated my project to version 2.0rc1 and java 1.8. When I worked with version 1.5 and called MaterialWindow dynamically I had no problem, but now the window does not appear, well it appears but is hidden in the bottom of one of the panels.
I think it may be due to something related to the CssResource.legacy because when running the program the following warning appears [WARN] Line 45: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that Has not been previously defined.

**Comment by kevzlou7979** [comment]
> MaterialWindow dynamically I had no problem, but now the window does not appear, well it appears but is hidden in the bottom of one of the panels.

Can you please elaborate briefly this statement? thanks ;) Also it may be good to post this issue separately on Addins repo.
