### ISSUE TITLE
TextArea Auto Expand hiding Text

### ISSUE THREAD

**Issue by jeffgnpc** [GwtMaterialDesign/gwt-material#50]
When adding a bunch of lines in the MaterialTextArea it doesn't expand correctly and text gets hidden without a scrollbar.

This was done using the demo app on Mac Chrome

**Comment by kevzlou7979** [comment]
On Windows Chrome, everything is working fine.

**Comment by slugmandrew** [comment]
Not sure if someone wants to look into this?

**Comment by kevzlou7979** [comment]
Is this still valid?

**Comment by jeffgnpc** [comment]
It appears to be fixed in the latest verison

**Comment by kevzlou7979** [comment]
Wow great news !
