### ISSUE TITLE
Error using MaterialInput of type FILE with 2.0

### ISSUE THREAD

**Issue by andersforsell** [GwtMaterialDesign/gwt-material#502]
Hi,

I was trying 2.0-rc2 but got an error when trying to open a file with my OpenProjectDialog.
Using 1.6.2 when I click the "projectZipInput" the native open dialog is first shown and when the file has been selected the UiHandler "projectZipInputOnClick" is called.

The problem in 2.0-rc2 is that the UiHandler is called first, resulting in an error, and after that the native dialog is shown.

Any idea how to fix or workaround this?

[OpenProjectDialog.zip](https://github.com/GwtMaterialDesign/gwt-material/files/587763/OpenProjectDialog.zip)

**Comment by kevzlou7979** [comment]
I havent succeeded to replicate this issue

**Comment by andersforsell** [comment]
I added an example project on GitHub. If you push the button in the toolbar it will open the "Open Project Dialog".
In the dialog when I click the red button to browse for a file the error appears.

See https://github.com/andersforsell/gwtmaterial2-openprojectdialog

**Comment by andersforsell** [comment]
You can also run from here to see the error:
https://andersforsell.github.io/gwtmaterial2-openprojectdialog/
