### ISSUE TITLE
Wrong Color.fromStyleName() resolving, add boolean ignoreSpaces parameter

### ISSUE THREAD

**Issue by drmzperx** [GwtMaterialDesign/gwt-material#503]
Hi!

I suggest the following modification for the right css name resolving from style name:

In Color.class (enum) two new methods:

    public static Color fromStyleName(final String styleName) {
        return EnumHelper.fromStyleName(styleName, Color.class, Color.DEFAULT, false);
    }

    public static Color fromStyleName(final String styleName, final boolean ignoreSpaces) {
        return EnumHelper.fromStyleName(styleName, Color.class, Color.DEFAULT, ignoreSpaces);
    }

I get color css name from database e.g. red lighten-2 and I want to create a Color enum object with fromStyleName() method.

Thanks!

**Comment by BenDol** [comment]
In the latest rc2 you can use `ColorHelper.fromStyleName(...)`.
