### ISSUE TITLE
Date Picker translation label

### ISSUE THREAD

**Issue by 0x3333** [GwtMaterialDesign/gwt-material#505]
In the last [Date Picker example](http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers) the translation of "Close" button became:
```
function (){
    return samMethod.apply(lambda, arguments);
  }
```
Instead translated `Close`.

![screen shot 2016-11-16 at 07 16 04](https://cloud.githubusercontent.com/assets/289289/20341258/927185b6-abcc-11e6-81fb-7d8a878df1c3.png)

**Comment by kevzlou7979** [comment]
Thanks for catching this will look up into this.

**Comment by kevzlou7979** [comment]
Fixed via - https://github.com/GwtMaterialDesign/gwt-material/commit/360ff108f04c7ff9466876f47a2592baaa4ba082
