### ISSUE TITLE
Dropdown shadown in Navbar

### ISSUE THREAD

**Issue by 0x3333** [GwtMaterialDesign/gwt-material#506]
In [Dropdown examples](http://gwtmaterialdesign.github.io/gwt-material-demo/#dropdown) in the Dropdown inside Navbar example the shadow is shown in the dropdown but not in the navbar.

![screen shot 2016-11-16 at 07 21 58](https://cloud.githubusercontent.com/assets/289289/20341495/97f64f48-abcd-11e6-9e2c-2018e3bb1c05.png)

This happens on screens width larger than 1200.

Smaller ones doesn't show this behavior:

![screen shot 2016-11-16 at 07 24 13](https://cloud.githubusercontent.com/assets/289289/20341548/ca6da46c-abcd-11e6-98f9-8a1238e7a3a4.png)

**Comment by kevzlou7979** [comment]
Thanks for catching this will look up into this. It can be solve using css issue.

**Comment by 0x3333** [comment]
Actually, it happens in all navbar examples, not only in Dropdown...

**Comment by kevzlou7979** [comment]
I got the issue, its inside the demo - Where the Codeblocks / Code Snippet has background of White and is covering the shadow of the navbar. See screenshot below. I will update the demo showcase now.
![issue](https://cloud.githubusercontent.com/assets/3138071/20373165/6016f58a-acab-11e6-8a97-47bf1b06e0e4.gif)

Check now @ http://gwtmaterialdesign.github.io/gwt-material-demo/#dropdown

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-demo/commit/720cc21dc6e992a0134791b9c858ae123a94b7e3

**Comment by 0x3333** [comment]
What about other users? They will need to have transparent background?

**Comment by BenDol** [comment]
Could raise the z-index so the nav bar sits over the content panel.

**Comment by kevzlou7979** [comment]
@0x3333 Note: The issue is not on GMD itself , it's the demo because of the codeblocks having a background of white.  There are many workaround into this @BenDol suggested.

**Comment by 0x3333** [comment]
Yeah, i prefer raising z-index, because background can't be transparent all the time. Thanks.
