### ISSUE TITLE
how to git icon  ?

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#511]
how to git icon  ?  like this    iconType="FOLDER"

**Comment by BenDol** [comment]
On what component? You wanting to get the icon or set it?

**Comment by BenDol** [comment]
This is an issue tracker rather than a questions forum, can ask questions here https://gitter.im/GwtMaterialDesign/gwt-material?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by kevzlou7979** [comment]
You can request an icon here if you want https://github.com/google/material-design-icons/issues then we will have to update our core google icon fonts.
