### ISSUE TITLE
configuration property named 'CssResource.legacy' warning

### ISSUE THREAD

**Issue by sbeaufort** [GwtMaterialDesign/gwt-material#513]
A compilation's warning appears with GWT 2.8 : 
```

[INFO]          Loading inherited module 'gwt.material.design.GwtMaterialBasicWithJQuery'
[INFO]             Loading inherited module 'gwt.material.design.GwtMaterialDesignBase'
[INFO]                [WARN] Line 45: Setting configuration property named 'CssResource.legacy' in module 'gwt.material.design.GwtMaterialDesignBase' that has not been previously defined
```

Workaround for a custom GWT module's gwt.xml file :

```
    <define-configuration-property name="CssResource.legacy" is-multi-valued="false" />  
    <inherits name="gwt.material.design.GwtMaterialBasicWithJQuery"/>
```

Fix for GwtMaterialDesignBase.gwt.xml file :

```
<module>

  <source path="client"/>

  <set-configuration-property name="CssResource.enableGss" value="true"/>
  <!--
  <set-configuration-property name="CssResource.legacy" value="true"/>
  -->
</module>
```

**Comment by kevzlou7979** [comment]
Thanks for this, we will review and make a fix for this.

**Comment by kevzlou7979** [comment]
Fixed  via https://github.com/GwtMaterialDesign/gwt-material-table/commit/dc56d2058e60dc57e19c1a526a9a8f6ab5e73988
Fixed Addins via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/04b14513d3d65d36575a15983cf496227676b581
Fixed Table via  Fixed - https://github.com/GwtMaterialDesign/gwt-material-table/commit/dc56d2058e60dc57e19c1a526a9a8f6ab5e73988
