### ISSUE TITLE
how to into textarea ?

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#514]
I want use textarea in  m:MaterialPanel but build fild.

Expecting only widgets in <m:MaterialPanel backgroundColor='WHITE' padding='0' ui:field='CodePanel'>: <textarea id='code' name='code'>

how to do it  ?
my XML code is .

<m:MaterialPanel padding="0" backgroundColor="WHITE" ui:field="CodePanel">

                    <textarea id="code" name="code">
                       function findSequence(goal) {
                         function find(start, history) {
                           if (start == goal)
                             return history;
                           else if (start > goal)
                             return null;
                           else
                             return find(start + 5, "(" + history + " + 5)") ||
                                    find(start * 3, "(" + history + " * 3)");
                         }
                         return find(1, "1");
                       }</textarea>

                   </m:MaterialPanel>

**Comment by kevzlou7979** [comment]
Make use of MaterialTextARea instead

**Comment by Neo110** [comment]
I want Integrate  CodeMirror2 . can not use MaterialTextARea .

**Comment by Neo110** [comment]
👎

**Comment by BenDol** [comment]
You will need to investigate GWT UiBinder and how elements and widgets are added to the DOM to achieve what you are looking to achieve, it is not an issue with our library.

http://www.gwtproject.org/doc/latest/DevGuideUiBinder.html
