### ISSUE TITLE
addValueChangeHandler not getting called everytime

### ISSUE THREAD

**Issue by mehtaronak** [GwtMaterialDesign/gwt-material#515]
I am just trying with below peace of code , purpose is to show ICON in case M.TextBox is not empty and hide when empty,

```
          searchText.addValueChangeHandler(new ValueChangeHandler<String>() {

			@Override
			public void onValueChange(ValueChangeEvent<String> event) {
				if (event.getValue().isEmpty()) {
					MaterialToast.fireToast(searchText.getText());
					searchClose.setVisible(false);
				} else {
					MaterialToast.fireToast(searchText.getText());
					searchClose.setVisible(true);
				}
			}
		});
```
I have noticed addValueChangeHandler  is not getting called every time user add/remove something from MaterialtextBox.

**Comment by kevzlou7979** [comment]
What version of GMD are you using?

**Comment by mehtaronak** [comment]
@kevzlou7979  I am using 1.6.0

**Comment by kevzlou7979** [comment]
@mehtaronak Ok I got what you mean, The Value Change event will only get fired once you loose focus to the textbox. The solution for your requirement is to make use of KeyUpEvent Instead.

```java
      txtBox.addKeyUpHandler(new KeyUpHandler() {
            @Override
            public void onKeyUp(KeyUpEvent event) {
                if (!txtBox.getText().isEmpty()) {
                    MaterialToast.fireToast(txtBox.getText());
                }
            }
        });
```

![issue](https://cloud.githubusercontent.com/assets/3138071/20585058/121c9730-b233-11e6-8230-52084ebdc63b.gif)

**Comment by mehtaronak** [comment]
@kevzlou7979  Thank you so to provide desire method.

**Comment by BenDol** [comment]
Just to clarify the ValueChangeEvent is only fired when the text field is unfocused (blurred). So Clicking out of the text box would invoke the ValueChangeEvent.
