### ISSUE TITLE
data source implementation has error in infinity table

### ISSUE THREAD

**Issue by yogitjain** [GwtMaterialDesign/gwt-material#516]
Hello,
I am Implementing Infinity data table as u have shown in your example but DataSource<T>  has unimplemated 

    public void load(DataView<T> dataView, int startIndex, int viewSize);
    public int getDataSize();

and 
In  example you have override 

    public void load(LoadConfig<Person> loadConfig, LoadCallback<Person> callback)

also lodeConfig and loadCallback is not in package

i am using GWT 2.8.0 and gwt-material 2.0 rc2

Thanks
Yogit Kumar Jain

**Comment by kevzlou7979** [comment]
@yogitjain Take note the LoadConfig and LoadCallback was only implemented on Snapshot not on rc2 that's why you have missing classes. You might need to use the integration of rc2 OR the snapshot.

**Comment by yogitjain** [comment]
Hello  kevzlou7979,
i am unable to find snapshot version on maven . can you help me to find it out.
thanks
Yogit kumar Jain

**Comment by kevzlou7979** [comment]
Here is the snapshot https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/gwt-material-table/
