### ISSUE TITLE
[2.0] "Html is null" error when "text" in setText is null

### ISSUE THREAD

**Issue by richelivargas** [GwtMaterialDesign/gwt-material#517]
I believe that is better to set text to empty String if it is null in TextMixin::setText, because it is better than to throws an exception.
The exception is throws by the SafeHtmlUtils::htmlEscape.

**Comment by BenDol** [comment]
Resolved here https://github.com/GwtMaterialDesign/gwt-material/commit/c28ab8552b06abc966284a03476d9d49a404634c
