### ISSUE TITLE
Problem with window on reload page

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#519]
On reload, or on direct load, there is a problem with the window (an error appear in javascript browser console, and the page stop loading).

Tested on version 2.0-rc2.

And possible to see on your website :
http://gwtmaterialdesign.github.io/gwt-material-demo/#window

Hope it helps.

**Comment by BenDol** [comment]
This was resolved a few hours ago :+1: thanks anyway!

**Comment by reofake** [comment]
I got another errors like that using others component / options like length="10" on text.

**Comment by reofake** [comment]
Ok so I wait the new release :) Thanks !

**Comment by kevzlou7979** [comment]
Yeah, the release is ongoing by the way.
