### ISSUE TITLE
MaterialListBox does not react on any listener

### ISSUE THREAD

**Issue by John-Kellner** [GwtMaterialDesign/gwt-material#52]
Hey guys,

this framework is awesome. But i found a little bug.
MaterialListBox is not reacting on DOM handler.

Trying to add a listener does not end up in an result for calling method doSomething()
Instead of this, nothing happens ....

```
final MaterialListBox materialListBox = new MaterialListBox();
        materialListBox.addItem("Test");
        materialListBox.addChangeHandler(new ChangeHandler() {
            @Override
            public void onChange(ChangeEvent changeEvent) {
                doSomething(); // 
            }
        });
```
another approach ends in the same result. Nothing happens again ...

```
        materialListBox.addClickHandler(new ClickHandler() {
            @Override
            public void onClick(ClickEvent clickEvent) {
                doSomething();
            }
        });
```

Is there another way to react as a listener ?

with best regards 

John

**Comment by anton-johansson** [comment]
A workaround has been made to fix the ChangeHandler bug, see issue #24. Not sure about the ClickHandler.
