### ISSUE TITLE
Problem with detectOrientation attribute of datePicker and length attribute of MaterialIntegerBox / MaterialTextBox (others ?)

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#521]
I got en error in Javascript console when I refresh a page that contains a MaterialDatePicker with the attribute detectOrientation="true".

No problem without the param, or the param to false.

Same result using the param on java.

I got the same problem with the length attribute of MaterialIntegerBox / MaterialTextBox (using in xml and Java).

The javascript error (I'm not sure it can help) :
Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : $wnd.$ is not a function

I use the 2.0-rc3 version.

I got the same using the 2.0-SNAPSHOT version.

Hope it helps.

**Comment by reofake** [comment]
I got the same using the 2.0-SNAPSHOT version.

**Comment by kevzlou7979** [comment]
Ok thanks for catching this , I will try to reproduce it.

**Comment by kevzlou7979** [comment]
I tried to reproduce the issue on a fresh project using the gwt-material-archetype but unfortunately I can't reproduce the issue. See below what I've done.

![3](https://cloud.githubusercontent.com/assets/3138071/21073060/2a70f634-bf10-11e6-8dad-7d487c4e03ad.gif)

**Comment by BenDol** [comment]
This is most likely an issue with your GMD lib version. Make sure you are using the latest versions correctly.

**Comment by reofake** [comment]
My minimalist project in zip file to reproduce.
[reofake-demo.zip](https://github.com/GwtMaterialDesign/gwt-material/files/645388/reofake-demo.zip)

**Comment by reofake** [comment]
If it can help, I work around this problem by adding the options I need (length / detectOrientation) on onAttach and it works. So don't works in constructor of the view and in XML, but work in onAttach...

**Comment by reofake** [comment]
I finally found the solution : just replace @ProxyStandard annotation by @ProxyCodeSplit in Presenter classes (same solution for others problems I post).
