### ISSUE TITLE
MaterialSideNav of "fixed" type disappears on window resize

### ISSUE THREAD

**Issue by ingosch** [GwtMaterialDesign/gwt-material#523]
Resize the window and the fixed type SideNav gets hidden instantly independent from the window size. The "left" property of the element style is set to a negative value like with "small screen".
Tested with 2.0-rc3.
But it didn't work correctly since 1.6.1 or 1.6.2. There it didn't reappear when it was hidden and the window size was increased to "large screen".

**Comment by sbeaufort** [comment]
The side navigation was displayed well in the version 2.0-rc2

**Comment by ingosch** [comment]
Did you use "FIXED" as type?
I took some Screenshots from gwt-material-demo 2.0-rc3 to show what it does.
I just changed the type of the SideNav from "PUSH" to "FIXED" in MenuView.ui.xml. Nothing else.

#1 was taken directly after opening the demo: SideNav is visible
![sidenav-fixed-1](https://cloud.githubusercontent.com/assets/9692514/21043083/8b2d4ca0-bdf5-11e6-9c58-52aa8a319a11.jpg)

#2 is after resizing the browser window: SideNav is gone cause element.style-property "left" is set to -260px. Activator button is not showing up cause width of the window is still bigger than 992px;
![sidenav-fixed-2](https://cloud.githubusercontent.com/assets/9692514/21043091/937f90c0-bdf5-11e6-9669-aa5c84710dc6.jpg)

#3 the window size is smaller than 992px, now also the activator shows up.
![sidenav-fixed-3](https://cloud.githubusercontent.com/assets/9692514/21043097/991b2f9e-bdf5-11e6-97c8-67493724eebf.jpg)

Increasing the window size above 992px doesn't bring back the SideNav. It only shows up when pressing the button.

**Comment by kevzlou7979** [comment]
Ok I have reproduced the issue successfully on the demo showcase. Everything works fine now.
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/3b6d6ffd7f9eff88b16298c9f2037d2a6176bbe9
Also take note: You must add a css property below:
```css
header, main, footer {
     margin-left: 280px; // your side nav width.
}
```
![side-nav-fixed](https://cloud.githubusercontent.com/assets/3138071/21096155/b0288e10-c099-11e6-879a-9af3eb319558.gif)

**Comment by ingosch** [comment]
I'm confused. Can't get this to work with the latest release_2.0 branch snapshots.
First your code ist faulty. hide() function is always called and therefore also show() is always called.
Code inside the ResizeHandler should look like this:
`                if (isSmall()) {
                    if (!isOpen()) {
                        show();
                    }
                } else {
                	if (isOpen())
                		hide();
                }`
Here your code leads the DOM to get flodded with sidenav-overlay elements.

But even with this changes I get strange behaviour.
SideNav get's pushed in on every resize.
Sometimes it get's hidden on big window.
Sometimes if window get's small it stays visible where it shouldn't.
Sometimes the sidenav-overlay is visible on small window but without the SideNav.
When maximizing the window SideNav is not always showing up. In most cases it's state gets just switched (visible before -> invisible after maximizing and vice versa).
I'm not into JS, JQuery and much in CSS but it seems somethings going wrong with the transition.
I also figured out the event defined in line 427 get's triggered on every resize.
`        element.on("side-nav-closing", e1 -> {
            onClosing();
            return true;
        });`
Maybe I'm just doing something wrong, but I really don't know what.

**Comment by BenDol** [comment]
This has now been resolved in the latest snapshot.
