### ISSUE TITLE
Window appear when open the page then disapear

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#524]
I have a window on my page (in xml) , and when I open the page, the window appear briefly then disapear.

I use the 2.0-rc3 version.

Hope it helps.

**Comment by BenDol** [comment]
Can I see how you are defining the `MaterialSideNav`? I fixed this on the last release.

**Comment by reofake** [comment]
I use this :

<m:MaterialSideNav ui:field="sideNav" m:id="sideBar" type="PUSH" width="250" closeOnClick="false" allowBodyScroll="true" showOnAttach="true">

**Comment by BenDol** [comment]
Remove `showOnAttach="true"`, see if that fixes it for you.

**Comment by reofake** [comment]
Same problem without showOnAttach="true".
But are you shure you answer for the good issue ?

**Comment by BenDol** [comment]
Oh you said Window, gotcha haha when i read it in my email thought you were meaning MaterialSideNav. Right, this issue should have been resolved in rc3 also. Can you share your `MaterialWindow` setup?

**Comment by reofake** [comment]
I use this :<ma:window.MaterialWindow ui:field="windowEdition" toolbarColor="{tokens.getColor}" backgroundColor="WHITE" width="75%">
	<m:MaterialRow>
		<m:MaterialColumn grid="s12 m4 l4">
			<m:MaterialTextBox ui:field="abrege"/>
		</m:MaterialColumn>
		<m:MaterialColumn grid="s12 m12 l12">
			<m:MaterialTextBox ui:field="libelle"/>
		</m:MaterialColumn>
	</m:MaterialRow>
	
	<m:MaterialRow>
		<m:MaterialColumn  grid="s12 m12 l3" offset="l3">
			<m:MaterialButton ui:field="save" width="100%" waves="LIGHT" backgroundColor="{tokens.getColor}" textColor="WHITE" iconType="SAVE" iconPosition="LEFT"/>
		</m:MaterialColumn>
		<m:MaterialColumn grid="s12 m6 l3">
			<m:MaterialButton ui:field="cancel" width="100%" waves="LIGHT" textColor="{tokens.getColor}" type="FLAT" iconType="CLOSE"/>
		</m:MaterialColumn>
		<m:MaterialColumn grid="s12 m6 l3">
			<m:MaterialButton ui:field="delete" width="100%" waves="LIGHT" backgroundColor="RED" textColor="WHITE" iconType="DELETE" iconPosition="LEFT"/>
		</m:MaterialColumn>
	</m:MaterialRow>
</ma:window.MaterialWindow>

**Comment by BenDol** [comment]
If you switch to `2.0-SNAPSHOT` can you still reproduce the issue?

**Comment by reofake** [comment]
Sorry, but how to use 2.0-SNAPSHOT ? XD

**Comment by BenDol** [comment]
Make sure you have this in your `pom.xml`:
```xml
<pluginRepositories>
    <pluginRepository>
      <id>public-snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/public/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </pluginRepository>
</pluginRepositories>
```

**Comment by reofake** [comment]
I'm going to try.

**Comment by reofake** [comment]
I got the same result with the 2.0-SNAPSHOT version.
I used :
        <gwt-material.ext>-rc3</gwt-material.ext>
        <gwt-material.version>2.0${gwt-material.ext}</gwt-material.version>
        <gwt-material-table.version>1.0${gwt-material.ext}</gwt-material-table.version>

        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material</artifactId>
            <version>2.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-themes</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-addins</artifactId>
            <version>${gwt-material.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.gwtmaterialdesign</groupId>
            <artifactId>gwt-material-table</artifactId>
            <version>${gwt-material-table.version}</version>
        </dependency>

Should I try with all SNAPSHOT versions ?

**Comment by reofake** [comment]
I try to reproduce the problem in a minimalist project, and I have not reproduced the problem. Finally I have added a dataTable as in my real project, and I reproduce !

So the REAL PROBLEM is when there is a dataTable and a window in the same page !

**Comment by reofake** [comment]
See #521 I upload my project.
To reproduce, change order of window and row containing the table (WindowView.ui.xml), launch the project, click "Window" => the window appear and disapear briefly.

**Comment by kevzlou7979** [comment]
Ok will check your project now.

**Comment by reofake** [comment]
I finally found the solution : just replace @ProxyStandard annotation by @ProxyCodeSplit in Presenter classes (same solution for others problems I post).
