### ISSUE TITLE
Firefox complains of wrong GWT permutation for 2.0-rc3

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material#525]
When 2.0-rc3 Release Demo is opened in Firefox 49, following is (silently) logged in Console:

```
Wed Nov 30 22:51:34 GMT+100 2016 com.google.gwt.logging.client.LogConfiguration
SEVERE: Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8).
Expect more errors.
com.google.gwt.useragent.client.UserAgentAsserter$UserAgentAssertionError: Possible problem with your *.gwt.xml module file.
The compile time user.agent value (safari) does not match the runtime user.agent value (gecko1_8).
Expect more errors.
	at Unknown.Throwable(gwtmaterialdemo-0.js)
	at Unknown.Error_0(gwtmaterialdemo-0.js)
	at Unknown.UserAgentAsserter$UserAgentAssertionError(gwtmaterialdemo-0.js)
	at Unknown.assertCompileTimeUserAgent(gwtmaterialdemo-0.js)
	at Unknown.apply_0(gwtmaterialdemo-0.js)
	at Unknown.entry0(gwtmaterialdemo-0.js)
	at Unknown.entry_0/<(gwtmaterialdemo-0.js)
	at Unknown.anonymous(Unknown)
```

Same happens in my app which prevents me from catching "real" exceptions.

When inspecting GMD modules, I've found following in /gwt/material/design/jquery/JQuery.gwt.xml and JSCore.gwt.xml:

`<set-property name="user.agent" value="safari" />`

However, according to GitHub, those files were not changed since Jul 18, so I'm not sure are they source of this problem (someone would probably notice by now).

I didn't notice any other issue in Firefox (didn't test much, either).

As one would expect, in Chrome it works ok. Did not test in IE (I'm on Linux).

**Comment by kevzlou7979** [comment]
I browsed some projects the user.agent property is not visible to other projects. Might be conflicting with new GWT 2.8.0.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-jquery/commit/296c3f957bda887d45671e6545aabe5f327a3e2b

Upon investigating deeper, I found out that we can set all the available ```user.agent``` to jquery.xml

```<set-property name="user.agent" value="safari,gecko1_8,ie10,ie9,ie8"/>```

Also upon searching if we set multiple values we might need to set the incremental to false on gwt-maven-plugin.

```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>${gwt.plugin.version}</version>
        <configuration>
          <gen>${basedir}/gen</gen>
          <!--jsInteropMode>JS</jsInteropMode-->
          <generateJsInteropExports>true</generateJsInteropExports>
          <incremental>false</incremental>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
