### ISSUE TITLE
MaterialDatePicker 

### ISSUE THREAD

**Issue by mstitane** [GwtMaterialDesign/gwt-material#526]
I set up a MaterialDatePicker  : 
 _`<m:MaterialDatePicker ui:field="dateDebut" autoClose="true" detectOrientation="true"  format="yyyy-mm-dd" language="FR"/>`_
But when I call it from my Editor, this error below happened : 

> Exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'stop' of undefined

_`Error: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'stop' of undefined.`_

```
public void setLanguage(DatePickerLanguage language) {
        this.language = language;
        if(language.getJs() != null) {
            ScriptInjector.fromString(language.getJs().getText()).setWindow(ScriptInjector.TOP_WINDOW).inject();
        }

        this.stop();
        this.reinitialize();
    }
```

**Comment by kevzlou7979** [comment]
I am able to reproduce the issue. What version of GMD are you using?
Note: With version 2.0 - We solved the issue by providing check:
```java
    public void stop() {
        if(this.pickatizedDateInput != null) {
            JsMaterialElement.$(this.pickatizedDateInput).pickadate("picker").stop();
        }

    }
```

**Comment by mstitane** [comment]
We use the 2.0-rc2 version.

**Comment by kevzlou7979** [comment]
Use 2.0-rc3 and the issue will be solved

**Comment by mstitane** [comment]
ok , thanks.
