### ISSUE TITLE
MaterialSideNav of "Card" type isn't static anymore in RC3

### ISSUE THREAD

**Issue by tempofeng** [GwtMaterialDesign/gwt-material#527]
I was playing around the gwt-material-patterns project and found out that if I upgraded gwt-material to RC3, the sideNav of Google Contacts demo (Card type)  will disappear after attached.

* In RC2
<img width="1368" alt="gwtmaterialpatterns" src="https://cloud.githubusercontent.com/assets/1229817/21074542/7b745974-bf36-11e6-9a2f-0b77bc573262.png">

* In RC3
<img width="1373" alt="gwtmaterialpatterns" src="https://cloud.githubusercontent.com/assets/1229817/21074521/0533086e-bf36-11e6-8596-f83cddbeed27.png">

If I add ```showOnAttach="false"``` to ```<MaterialSideNav>```, it becomes static again.

**Comment by BenDol** [comment]
Resolved in https://github.com/GwtMaterialDesign/gwt-material/commit/ea91fd8715ce7cad9aceab4b324281cb9b7e8931
