### ISSUE TITLE
Showing label and placeholder on MaterialTextBox at the same time

### ISSUE THREAD

**Issue by tempofeng** [GwtMaterialDesign/gwt-material#528]
The new label property in MaterialTextBox is pretty nice. But when you set both the label and placeholder on the same MaterialTextBox, they overlap:

![scv](https://cloud.githubusercontent.com/assets/1229817/21094269/282295cc-c091-11e6-8fe3-29df0d34fc6b.png)

Maybe it's better if the label and placeholder are set at the same time, the label becomes ACTIVE. (Like the pic below)

![scv 2](https://cloud.githubusercontent.com/assets/1229817/21094275/2c3d3900-c091-11e6-91ae-22e79fe2cc52.png)

**Comment by kevzlou7979** [comment]
Nice catch will investigate this.

**Comment by BenDol** [comment]
This is its intended functionality, seems odd that this is happening. When I tested it I didn't have this issue.
