### ISSUE TITLE
DatePicker leaks <div> when adding / removing it.

### ISSUE THREAD

**Issue by jrmalzieu** [GwtMaterialDesign/gwt-material#530]
Hi,

When adding / removing DatePicker to a panel, it attach a div (containing the label, the error and the input) to the destination container, and also another div to the RootPanel that contains the real Picker.

The issue is that the div attached to the RootPanel is never removed. My application uses a lot of DatePicker, and after some time working with it, we get a huge amount of unecessary blocks within the root panel.

So far, I have found a workaround that is to override the MaterialDatePicker and to add this onUnload() function :
`    @Override
    public void onUnload() {
        super.onUnload();
        $("#" + getPickerId() + "_root").remove();
    }
`

This is working, but this should be at least added to the MaterialDatePicker (or another better solution).

Keep up the good job, the lib is wonderful!

**Comment by kevzlou7979** [comment]
Thanks for this we will review this soon.

**Comment by kevzlou7979** [comment]
I tried your workaround but it has an issue when you try to navigate back again to the date picker. Try the demo http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#pickers

**Comment by kevzlou7979** [comment]
With the recent update on DatePicker (2.0-SNAPSHOT) @jrmalzieu Is this still an issue to your side?
