### ISSUE TITLE
MaterialListBox: setSelectedValue, setValueSelected methods do not work with emptyPlaceHolder

### ISSUE THREAD

**Issue by chinshaw** [GwtMaterialDesign/gwt-material#531]
The index is not being calculated wrong when there is an emptyPlaceHolder specified in the properties.  Not sure why I have a placeholder and emptyPlaceHolder. I probably found the emptyPlaceHolder after the fact. None the less, this is what I did to replicate the issue. I was using setSelectedValue and the index was being calculated correctly as the first element. However the place holder text was showing. I then tested by incrementing the index of the value provided from getIndex(String) and this showed the correct value. I then tried removing the emptyPlaceHolder property and the MaterialListBox set the correct value. This may be a combination of having placeHolder and emptyPlaceHolder but I am reporting anyway.

```
<m:MaterialListBox ui:field="heightWidth"
			validateOnBlur="true" emptyPlaceHolder="Select Width Height ... "
			placeholder="Width Heigth">
```

Thanks,
Chris

**Comment by kevzlou7979** [comment]
Why you need to define emptyPlaceholder if you added placeholder on the other hand? Please choose only one option.

**Comment by BenDol** [comment]
I think the issue here is the ambiguity between the two options. They might need to be defined if they haven't already for clarity, or redesigned to make more sense.
