### ISSUE TITLE
MaterialTab wrong line on resize

### ISSUE THREAD

**Issue by andrescirulo** [GwtMaterialDesign/gwt-material#532]
When you resize the page by showing or hiding the sidenav the line under the selected tab changes incrorrectly its size.
It can be seen happening on the demo page.

**Comment by kevzlou7979** [comment]
It seems that it;s a materialize issue. The calculation of the indicator width is not well calculated on browser resize.

**Comment by kevzlou7979** [comment]
Filed an issue to materialize https://github.com/Dogfalo/materialize/issues/4323

**Comment by kevzlou7979** [comment]
Hi there @andrescirulo ,

Upon investigating the issue, we provided a method for tabs for ```resize()``` , which recalculates and reinitialize the tabs .

Added test demo 
https://gwtmaterialdesign.github.io/gwt-material-patterns/snapshot/#navbar_tab_push

Workaroud
```java
        sidenav.addOpenedHandler(event -> tab.resize());
        sidenav.addClosedHandler(event -> tab.resize());
```
