### ISSUE TITLE
DatePicker problem when setLanguage then setDetectOrientation

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#533]
I use a datePicker, and when I try to setLanguage then setDetectOrientation in onAttach, the onAttach statement stop.

A quick fix for me is to setDetectOrientation first, then setLanguage.

I use the 2.0-rc3 version.

Hope it helps.

**Comment by reofake** [comment]
I finally found the solution : just replace @ProxyStandard annotation by @ProxyCodeSplit in Presenter classes (same solution for others problems I post).

**Comment by reofake** [comment]
The problem is still present by setting language then setting detectOrientation, but now I can set detectOrientation in XML, so the problem is still present, but just not for me, so I reopen the issue.

**Comment by kevzlou7979** [comment]
I can't totally reproduce the issue. I tried many use cases depends on your statements. Can you create a code snippet.

**Comment by reofake** [comment]
I reproduce in my huge project, I will try to reproduce in a minimalist project.

**Comment by reofake** [comment]
See my project :
[reofake-demo.zip](https://github.com/GwtMaterialDesign/gwt-material/files/670485/reofake-demo.zip)

The interesting code is :
```java
@Override
    protected void onAttach() {
        if(!initialized) {
            initialized = true;
            
            // This don't work
            date.setLanguage(DatePickerLanguage.EN);
            date.setDetectOrientation(true);
            
            // This work
//            date.setDetectOrientation(true);
//            date.setLanguage(DatePickerLanguage.EN);
            
            MaterialToast.fireToast("Test");
        }
    }
```

**Comment by kevzlou7979** [comment]
What kind of framework are you using? GWTP? Errai? plain GWT. Why you need to call on Attach?

**Comment by kevzlou7979** [comment]
I tried to check your code, your using GWTP and now why you need to set DetectOrientation / Language on the OnAttach. Just in UiBinder and it will work.
```
 <m:MaterialDatePicker language="AR" detectOrientation="true" autoClose="true" ui:field="date" selectionType="YEAR"/>
```

**Comment by reofake** [comment]
I don't need to set the two since I use @ProxyCodeSplit. I just need the setLanguage dynamically. But this result is strange no ?
