### ISSUE TITLE
Outdated instructions for Theming

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#534]
On [Theming](http://gwtmaterialdesign.github.io/gwt-material-demo/#themes) the code snippet still advices to use module **gwt.material.design.themes.GwtMaterialThemeBlue**. Seems like the theming modules have been renamed meanwhile. (The blue one is now **gwt.material.design.themes.ThemeBlue**.)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-demo/commit/a32109154828945a1fbd73eceb22debb15639c13
