### ISSUE TITLE
Version JAVA 7 vs JAVA 8

### ISSUE THREAD

**Issue by gaston2303** [GwtMaterialDesign/gwt-material#535]
Hello, good morning/afternoon,

I am developing a project with GWT. I have included the last version of your libraries (2.0-rc3), since I needed to work with Data Table. 

My problem is that I am working with Google Cloud Platform in runtime standard which does not let me work with Java 8. I cannot do deploy unless I come back to Java 7. The only way is using runtime flexible which would increase time and cost to my project. 

Is there any possibility to have the last libraries with Java 7?

The code line that doesn’t allow it to compile is when I call to this method: .addRowSelectHandler((e, model, elem, selected) -> { 

Thank you very much,
Gastón.

**Comment by kevzlou7979** [comment]
Hi @gaston2303,

Java 8 is fully integrated to GMD 2.0 with the existence of Lambda support.

> Is there any possibility to have the last libraries with Java 7?

You can pull the Github Code, then try to revert all lambdas to Java 7 supported. Also I dont think GWT 2.8.0 used Java 8 also.

**Comment by muirfer** [comment]
Hi @gaston2303,

I am having exactly the same problem. Works perfectly in devmode but cannot deploy.

I am working with java 8 and gwt 2.8.0 but setting level compilation to 1.7 in Maven.

Where you able to find a solution besides the one mentioned above? I would really appreciate if you did and can share it with me.

Thanks

**Comment by muirfer** [comment]
@gaston2303 :

If you are still intereseted i found the solution with less impact for this problem. What @kevzlou7979 wrote is what is needed to succeed. Doing it by hand can be too much effort. So i managed to do it through Retrolambdas plugin for maven (https://github.com/orfjackal/retrolambda)

So, check-out **gwt-material 2.0rc3** code and add the following to the **pom.xml** of the projects (in my case, base project, addins and theme) that need it:

![image](https://cloud.githubusercontent.com/assets/21373665/21592718/5fd41e42-d0ee-11e6-8301-92318a5fdd1f.png)

Execute **mvn clean install** and the plugin handles the lambdas expressions and generated **java 7** bytecode. You can check it by running javap -v <AnyClassNameInJar.class> (version 51)

Then compile and deploy your project. This way i deployed my project using latest gwt-material version in Google App Engine and it runs correctly. In fact, retrolambdas can also be util for using lambdas in your project and be more prepared when Google decides to support java 8.

**Comment by lukelast** [comment]
@gaston2303 It is possible to use Java8 GWT 2.8 with Java 7 on the server side. I'm doing that because I also have a project in Google App Engine standard environment. I use this [Maven Plugin](https://github.com/tbroyer/gwt-maven-plugin) but the key is just to build your GWT and server projects separately.
