### ISSUE TITLE
Custom widget should be dismissible on outside click

### ISSUE THREAD

**Issue by mehtaronak** [GwtMaterialDesign/gwt-material#536]
I have been trying to dismiss my widget on outside click. Its similar to MaterialDropDown and MaterialListBox , both dismisses on outside click. I havbe implemented custom listing dynamically where I can't use MaterialDropDown or MaterialListBox  , it all worked but except list is not getting dismiss on outside click. 

How can I achieve this behaviors with custom component ? It should be dismiss when outside lick of widget.

**Comment by kevzlou7979** [comment]
You can make use of OnBlur Event, I think on Subclass MaterialWidget , you can ```addBlurEvent```. https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/base/MaterialWidget.java#L481

**Comment by mehtaronak** [comment]
Thank you for the response. I have also tried with OnBlur  but it didn't work.

    public class CustomMaterialPanel extends MaterialPanel implements HasBlurHandlers{
	  @Override
	  public HandlerRegistration addBlurHandler(BlurHandler handler) {
	        	return addDomHandler(handler, BlurEvent.getType());
	     }
    }

  In  java file I've written 

  	@UiField
	 CustomMaterialPanel panel;
    
        panel.addBlurHandler(new BlurHandler() {
			
			@Override
			public void onBlur(BlurEvent event) {
				MaterialToast.fireToast("outside");
			}
		});

   I don't see any Toast message. am I doing anything wrong ?

**Comment by mehtaronak** [comment]
@kevzlou7979 Hey  Can you look for possible solution ?

**Comment by BenDol** [comment]
Make sure your widget has tabindex=-1 or any index value for the widget (`widget.setTabIndex(-1)`)

**Comment by mehtaronak** [comment]
@BenDol  Yes I just have set `customPanel.setTabIndex(-1);` but still not working.

**Comment by mehtaronak** [comment]
I see Toast message when I click on Item resides in `MaterialPanel` but this is not expected,

**Comment by mehtaronak** [comment]
My **xml** code looks like,

    <a:CustomMaterialPanel ui:field="customPanel">
			<m:MaterialColumn ui:field="searchCollection"
				styleName="{style.material-column}">
			</m:MaterialColumn>
      </a:CustomMaterialPanel>

 I am adding items dynamically in `MaterialColumn` and later I apply

            customPanel.setTabIndex(-1);
		customPanel.addBlurHandler(new BlurHandler() {

			@Override
			public void onBlur(BlurEvent event) {
				MaterialToast.fireToast("outside");
			}
		});

This should actually work.

**Comment by kevzlou7979** [comment]
@mehtaronak I can see that you implement HasBlurHandler into your custom panel. 
Take not that by default All MaterialWidget (e.g. MaterialPanel) has implemented already the BlurEvent.
