### ISSUE TITLE
Impossible to select first value of MaterialListValueBox using setValue()

### ISSUE THREAD

**Issue by hajo70** [GwtMaterialDesign/gwt-material#538]
The problem is the that values.indexOf(value) returns 0 for the first value, thus the `(index > 0)` is false. To work around this bug I created the following subclass:

public class MaterialListValueBoxPatch<T> extends MaterialListValueBox<T> {
    @Override
    public void setValue(T value, boolean fireEvents) {
        int index = values.indexOf(value);
        if (index >= 0) {
            T before = getValue();
            setSelectedIndex(index);

            if (fireEvents) {
                ValueChangeEvent.fireIfNotEqual(this, before, value);
            }
        }
    }
}

**Comment by kevzlou7979** [comment]
Please submit a pull request for this patch. Hoping to verify and test soon :)

**Comment by kevzlou7979** [comment]
Please check this https://github.com/GwtMaterialDesign/gwt-material/compare and create PR.
Choose ```release_2.0 branch``` to patch the solution.

**Comment by kevzlou7979** [comment]
Fixed issue https://github.com/GwtMaterialDesign/gwt-material/commit/cac255b8bce8fd6d0e724a43f051ffce7bc91d0f
