### ISSUE TITLE
Input fields together with Materialize rows and columns

### ISSUE THREAD

**Issue by anton-johansson** [GwtMaterialDesign/gwt-material#54]
Hi! I have an issue regarding the indententation of some input fields (MaterialTextBox for example). If you compare [your examples](http://gwt-material.appspot.com/#forms) with [materializecss' examples](http://materializecss.com/forms.html), you can see that there is a small difference in the indentation of the placeholder.

In materializecss' examples, they have this:
```xml
<div class="row">
	<div class="input-field col s12">
		<input id="email" type="email" class="validate">
		<label for="email" data-error="wrong" data-success="right">Email</label>
	</div>
</div>
```

To simulate this, I'd do this in my *.ui.xml file:
```xml
<m:MaterialRow>
	<m:MaterialColumn grid="s12">
		<m:MaterialTextBox ui:field="txtTest" placeholder="Test" />
	</m:MaterialColumn>
</m:MaterialRow>
```

However, this turns into:
```xml
<div class="row">
	<div class="col s12">
		<div class="input-field">
			<i></i>
			<input type="text" class="gwt-TextBox validate" id="101">
			<label for="101">
				<div class="gwt-Label">Test</div>
			</label>
		</div>
	</div>
</div>
```

This extra div makes it look no different than before (i. e. it looks exactly as your example). But it makes sense, because that's how I structured my UiBinder.

One idea how to solve this is to have a grid-property on ALL material input fields. Something like this:
```java
public void setGrid(String grid) {
	this.grid = grid;
	addStyleName("col");
	addStyleName(grid);
}
```

This way I can design my UiBinder like this:
```xml
<m:MaterialRow>
	<m:MaterialTextBox ui:field="txtTest" placeholder="Test" grid="s12" />
</m:MaterialRow>
```

I've tested this in my own code and it works perfectly, atleast for MaterialTextBox and MaterialTextArea. I tested on MaterialListBox, but I got some trouble with a slightly misplaced caret. I had  a hard time finding a solution, since the HTML you get from MaterialListBox does not match the HTML in the materializecss examples.

Ideas, thoughts?

**Comment by kevzlou7979** [comment]
Ok I agree with this we can set up a grid attribute for every input fields.
You can pull a request on this :)

**Comment by anton-johansson** [comment]
Allright. I will investigate some more about the other components though, for example about the issue mentioned above with MaterialListBox.

**Comment by slugmandrew** [comment]
@anton-johansson We are currently discussing rewriting elements to render the exact same css as materializecss.com, so this will probably be done in a future release. Hopefully in the next couple of weeks.

**Comment by anton-johansson** [comment]
Sounds great! Nice work with the milestones, it helps people getting a visual on how things are progressing. :)

**Comment by kevzlou7979** [comment]
Ok now specific gwt material elements supports grid : (Just add grid="s2 m2 l2" to the uiBinder element then it will work pretty well)

Grid Column Support:
- Autocomplete
- Card
- CheckBox
- Collapsible
- Collection
- Date Picker
- Time Picker
- Image 
- Label
- Link
- ListBox
- Radio Button
- Switch
- Text Area
- Text Box
- Video

**Comment by kevzlou7979** [comment]
OK we will add the remaining widget icons and buttons then we can close this

**Comment by fredrickRoyal** [comment]
Hi i have  this error in version 4
[ERROR] Unexpected text in element: "?": <m:MaterialRow>

**Comment by kevzlou7979** [comment]
@fredrickRoyal Please provide your code snippet.

**Comment by fredrickRoyal** [comment]
Hi i found out from your code at git.

On Sat, Feb 13, 2016 at 3:15 AM, kevzlou7979 <notifications@github.com>
wrote:

> @fredrickRoyal <https://github.com/fredrickRoyal> Please provide your
> code snippet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GwtMaterialDesign/gwt-material/issues/54#issuecomment-183539214>
> .
>



-- 






*Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
<0704901261>-408387Email:fkasoma@planetsystems.co
<http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
*Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*

"No Burden Bearer Carries Burden of the other"

**Comment by fredrickRoyal** [comment]
Can u Please update for us the showcase.. Its so confusing when we see
version 1.4.0 yet on maven repo. its 1.4, then the code snippet are not
correlating.. they are all the same for all versions. please update us with
new links to new versions.
thank you for the innovation. we were struggling with smartgwt, senchaGWT,
the worst is gwt plain.. thank you very much. Can we  also borrow some
things from polymer boys?

On Mon, Feb 15, 2016 at 9:41 AM, Kasoma Fredrick <kfredrick35@gmail.com>
wrote:

> Hi i found out from your code at git.
>
> On Sat, Feb 13, 2016 at 3:15 AM, kevzlou7979 <notifications@github.com>
> wrote:
>
>> @fredrickRoyal <https://github.com/fredrickRoyal> Please provide your
>> code snippet.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GwtMaterialDesign/gwt-material/issues/54#issuecomment-183539214>
>> .
>>
>
>
>
> --
>
>
>
>
>
>
> *Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
> Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
> <0704901261>-408387Email:fkasoma@planetsystems.co
> <http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
> *Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*
>
> "No Burden Bearer Carries Burden of the other"
>
>


-- 






*Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
<0704901261>-408387Email:fkasoma@planetsystems.co
<http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
*Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*

"No Burden Bearer Carries Burden of the other"

**Comment by kevzlou7979** [comment]
Please follow this http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!gettingstarted
![version_table](https://cloud.githubusercontent.com/assets/3138071/13041589/a4b5cc66-d3f3-11e5-9293-f4b5d5004e39.PNG)

**Comment by fredrickRoyal** [comment]
thank man..
i am developing my application based on gwt-material and its so good.
I will send you a link after uploading.

On Mon, Feb 15, 2016 at 9:51 AM, kevzlou7979 <notifications@github.com>
wrote:

> Please follow this
> http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!gettingstarted
> [image: version_table]
> <https://cloud.githubusercontent.com/assets/3138071/13041589/a4b5cc66-d3f3-11e5-9293-f4b5d5004e39.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GwtMaterialDesign/gwt-material/issues/54#issuecomment-184084464>
> .
>



-- 






*Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
<0704901261>-408387Email:fkasoma@planetsystems.co
<http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
*Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*

"No Burden Bearer Carries Burden of the other"

**Comment by fredrickRoyal** [comment]
Send me a like of both show case and demo for version 1.4.1.
Im using maven so am likely not to use 1.5.0 until it stabilizes.
Thank you.

On Thu, Feb 25, 2016 at 9:32 AM, Kasoma Fredrick <kfredrick35@gmail.com>
wrote:

> thank man..
> i am developing my application based on gwt-material and its so good.
> I will send you a link after uploading.
>
> On Mon, Feb 15, 2016 at 9:51 AM, kevzlou7979 <notifications@github.com>
> wrote:
>
>> Please follow this
>> http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!gettingstarted
>> [image: version_table]
>> <https://cloud.githubusercontent.com/assets/3138071/13041589/a4b5cc66-d3f3-11e5-9293-f4b5d5004e39.PNG>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GwtMaterialDesign/gwt-material/issues/54#issuecomment-184084464>
>> .
>>
>
>
>
> --
>
>
>
>
>
>
> *Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
> Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
> <0704901261>-408387Email:fkasoma@planetsystems.co
> <http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
> *Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*
>
> "No Burden Bearer Carries Burden of the other"
>
>


-- 






*Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
<0704901261>-408387Email:fkasoma@planetsystems.co
<http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
*Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*

"No Burden Bearer Carries Burden of the other"

**Comment by fredrickRoyal** [comment]
Hi how do u do file upload with gwtmaterialdesign..?
i mean the wigdets to use
thank you.

On Thu, Feb 25, 2016 at 9:35 AM, Kasoma Fredrick <kfredrick35@gmail.com>
wrote:

> Send me a like of both show case and demo for version 1.4.1.
> Im using maven so am likely not to use 1.5.0 until it stabilizes.
> Thank you.
>
> On Thu, Feb 25, 2016 at 9:32 AM, Kasoma Fredrick <kfredrick35@gmail.com>
> wrote:
>
>> thank man..
>> i am developing my application based on gwt-material and its so good.
>> I will send you a link after uploading.
>>
>> On Mon, Feb 15, 2016 at 9:51 AM, kevzlou7979 <notifications@github.com>
>> wrote:
>>
>>> Please follow this
>>> http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!gettingstarted
>>> [image: version_table]
>>> <https://cloud.githubusercontent.com/assets/3138071/13041589/a4b5cc66-d3f3-11e5-9293-f4b5d5004e39.PNG>
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/GwtMaterialDesign/gwt-material/issues/54#issuecomment-184084464>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>>
>>
>>
>>
>> *Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
>> Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
>> <0704901261>-408387Email:fkasoma@planetsystems.co
>> <http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
>> *Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*
>>
>> "No Burden Bearer Carries Burden of the other"
>>
>>
>
>
> --
>
>
>
>
>
>
> *Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
> Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
> <0704901261>-408387Email:fkasoma@planetsystems.co
> <http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
> *Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*
>
> "No Burden Bearer Carries Burden of the other"
>
>


-- 






*Fredrick KasomaSoftware DeveloperPlanet Systems (U) LtdPlot 170 Semawata
Road-NtindaP.O.Box 3761 Kampala UgandaTel: 0700
<0704901261>-408387Email:fkasoma@planetsystems.co
<http://www.planetsystems.co:2095/cpsess938237924/3rdparty/roundcube/?_task=mail&_action=show&_uid=193&_mbox=INBOX&_caps=pdf%3D1%2Cflash%3D1%2Ctif%3D0#NOP>*
*Email:kfredrick35@gmail.com <Email:kfredrick35@gmail.com>*

"No Burden Bearer Carries Burden of the other"

**Comment by gilberto-torrezan** [comment]
Hi @fredrickRoyal 
With you have any questions about the project, please talk to us at the [gitter chat room](https://gitter.im/GwtMaterialDesign/gwt-material), or if you find any other issues not related to this one, please open a new ticket ;-)

**Comment by fredrickRoyal** [comment]
@gilberto-torrezan  let me try it out.
thank you in advance.

**Comment by shadabgaurft** [comment]
Hi All, I am working on a project and trying to use GWT Material Design 1.4.1.
Could anyone please share any working full example. It will be a great help!
My login sample was working fine with MaterialDesign 1.3.3 version but not with 1.4.1.

Also, please share any link to refer proper sample examples. Thank you very much.
