### ISSUE TITLE
Window move end problem

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#541]
At the end of the movement of a window, the window move again, and if we have scroll, the window will go too high, and then impossible to close.

To reproduce, go to your [website](http://gwtmaterialdesign.github.io/gwt-material-demo/#window), scroll to "Window with Overlay", click the button "Open with overlay", move the window.

**Comment by kevzlou7979** [comment]
Next time, please submit the issue related to Addins on this link https://github.com/GwtMaterialDesign/gwt-material-addins/issues. So that everything we do a release, it will be important for us to specify the release notes between ADdins and Core components :)

**Comment by reofake** [comment]
Close for reopen here : https://github.com/GwtMaterialDesign/gwt-material-addins/issues/179
