### ISSUE TITLE
Window size in function of screen size ?

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#542]
Actually, the window only have a "width" attribute for all screen size. I think this would be interesting to have the possibility to change the width of the window depending on the screen size.

**Comment by reofake** [comment]
Close for reopen here : https://github.com/GwtMaterialDesign/gwt-material-addins/issues/180

**Comment by kevzlou7979** [comment]
Appreciate the update :) It will help us to identify the release notes easily
