### ISSUE TITLE
MaterialAutoComplete does not work in TEXT mode

### ISSUE THREAD

**Issue by lukelast** [GwtMaterialDesign/gwt-material#543]
You can see the issues in the demo:
http://gwtmaterialdesign.github.io/gwt-material-demo/#autocomplete

Type in some text and hit enter, the text disappears.
Select and clear a few items in a row and you'll see the input box slowly move to the right.
There is no way to read back the text value entered by the user from the MaterialAutoComplete object.

**Comment by kevzlou7979** [comment]
This issue is related to Addins, I will migrate now this issue to correct repo.

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/184

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/aa041565ff0ac9af18045d662d5517a378137016
