### ISSUE TITLE
add TreeItem not selected

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#544]
I want  add item to tree .but  add TreeItem not selected;  
like this http://gwtmaterialdesign.github.io/gwt-material-demo/#tree   not selected too

**Comment by kevzlou7979** [comment]
Im not sure if I understand your issue :)

**Comment by Neo110** [comment]
I want add   "items" to  docTree , added is ok ,but this item can't selected .
how to fix this  ?

  MaterialTreeItem items = docTree.getSelectedItem(); ;
            MaterialTreeItem item = new MaterialTreeItem();
             item.setText(  sumlFile.getName());
             item.setIconType(IconType.FOLDER);

             if(sumlFile.getName().equals("dir")){
                 item.setIconType(IconType.INSERT_DRIVE_FILE);
             }
             item.setIconColor(Color.BLUE);

             docTree.getSelectedItem().addItem(item);

**Comment by axls** [comment]
I think this one is related to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/173.
Are you using gwt-material-addins 2.0-rc3? If so, try to switch to snapshot for awhile.

**Comment by Neo110** [comment]
Still can not

**Comment by Neo110** [comment]
how can help me  ?

**Comment by kevzlou7979** [comment]
This issue belongs to Addins, I will migrate now this issue to correct repo.

**Comment by kevzlou7979** [comment]
Migrated to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/183

**Comment by kevzlou7979** [comment]
Confirmed on 2.0-Snapshot with the demo http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#tree. Its working well.

![issue1](https://cloud.githubusercontent.com/assets/3138071/21597712/10d06a84-d18a-11e6-877f-4612972586cc.gif)

**Comment by Neo110** [comment]
nice wook.

**Comment by Neo110** [comment]
how to change version?  change to snapshot ?

**Comment by kevzlou7979** [comment]
This is how you pull the source code to snapshot

```xml
    <!-- Connect to Snapshot Repository -->
    <repositories>
        <repository>
            <id>central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>sonatype-nexus-snapshot</id>
            <name>Sonatype Nexus snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
```


```xml
       <dependencies>
            <dependency>
                <groupId>com.github.gwtmaterialdesign</groupId>
                <artifactId>gwt-material</artifactId>
                <version>2.0-SNAPSHOT</version>
             </dependency>
        </dependencies>
```
