### ISSUE TITLE
Slack channel for discussion, help,...

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#545]
Hi guys,
What do you think about a slack channel for this repo?
Especially when it comes to questions about usage, I'm not sure if to post in the issues section of this repo. Hence a slack channel would come in handy, to have a possibility to throw in questions, input,... and share directly with the community?

**Comment by kevzlou7979** [comment]
Slack is good, At the moment we have 3 channels for discussing GMD.
1. Github Issue
2. Gitter
3. Google Plus
I think these 3 channels are fine with us.
