### ISSUE TITLE
DatePicker visual problem on horizontal orientation with 6 weeks

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#546]
See this ![image](https://cloud.githubusercontent.com/assets/23258418/21639481/93a250f8-d270-11e6-893a-8adbf3710433.png)

Reproduce on your [website](http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers) ("Mobile" section).

**Comment by kevzlou7979** [comment]
Ok Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/ce119ed98cb0d2f18a6588bf38abdb193ee56e80.
Tested with any zoom sizes + screen size

![datepicker](https://cloud.githubusercontent.com/assets/3138071/22507404/6693c036-e8c0-11e6-93e9-968338913217.gif)

**Comment by reofake** [comment]
Nice 👍
