### ISSUE TITLE
How to achieve an initial closed Side Nav (old behaviour) on large screens

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#547]
In the previous version, the side nav bar was initially collapsed, but now it stays automatically open when on bigger screens.
Is there an option to set the initial state, please?

Cheers,
stefan

**Comment by kevzlou7979** [comment]
Use type PUSH instead of FIXED.

**Comment by wassx** [comment]
thx!

**Comment by kevzlou7979** [comment]
Try setShowOnAttach(false) into your sidenav.

**Comment by wassx** [comment]
Thanks! This works for me.
BTW: I want to thank you guys for this great project
