### ISSUE TITLE
MaterialListBox does not change selection via code 

### ISSUE THREAD

**Issue by John-Kellner** [GwtMaterialDesign/gwt-material#55]
I tried to change the current selection of MaterialListBox via code in four different ways, but it does not react at all.

```
@UiField 
protected MaterialListBox tabItemImageSelection;

public Menu(){
   tabItemImageSelection.setSelectedIndex(2); // first test

   tabItemImageSelection.setTitle("Test"); // secound test
   tabItemImageSelection.setValue(1,"Test"); // third test
}

```

**Comment by ye3i** [comment]
you can use this, after change:
```java
tabItemImageSelection.onInitMaterialDesign();
```

**Comment by John-Kellner** [comment]
the method onInitMaterialDesign doesn't exist in MaterialListBox I use the current Version 1.3.2

**Comment by ye3i** [comment]
oh, They changed it in workaround 

now does not work :/

**Comment by slugmandrew** [comment]
@kevzlou7979 Any ideas for a quick fix on this?

**Comment by lukelast** [comment]
The hacky workaround I've been using is always call `insertItem` after changing any state. Another option would be to extend `MaterialListBox` so you can call `initializeMaterial(id);` after changing state like the selected index.

**Comment by lukelast** [comment]
One fix would be overriding mutators like `setSelectedIndex` and `removeItem` and make then also call `initializeMaterial(id);`.

**Comment by kevzlou7979** [comment]
@lukelast  I have override all the listbox methods by adding ```initializeMaterial()```
