### ISSUE TITLE
MaterialTable with Pager

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#550]
Hello,

a colleague of mine found something interesting yesterday. Apparently you get an IndexOutOfBounds if you have a table with a pager and less than 5 items in it. We're currently using RC3.

Can you confirm this issue or is it something we are missing on our end?

Thanks and keep up the good work!

kr

Chris

**Comment by reofake** [comment]
Hi ! You didn't post in the right project :). If you use the ListDataSource, I already posted that issue [here](https://github.com/GwtMaterialDesign/gwt-material-table/issues/34). But it can also be something else.
If you use data table like me [that other issue](https://github.com/GwtMaterialDesign/gwt-material-table/issues/33) may interest you.
Personally I rewrote classes to get arround these errors.

**Comment by kevzlou7979** [comment]
Please reopen an issue here https://github.com/GwtMaterialDesign/gwt-material-table/issues/ for DataTable Issues.
