### ISSUE TITLE
Side Navigation Bar disappears when zooming or resizing window

### ISSUE THREAD

**Issue by adibacco** [GwtMaterialDesign/gwt-material#552]
I just migrated to 2.0-rc3 from 1.5.1 and I'm experiencing a nasty problem. I'm using the NavigationBar  (type="FIXED") but if I try to resize the browser window or zooming the browser window the navigation bar disappears. I'm using Chrome version 55.0.2883.95 (64-bit). I'm attaching a video to explain the issue  https://youtu.be/63ukkOH1siA

[ApplicationView.ui.xml.gz](https://github.com/GwtMaterialDesign/gwt-material/files/711184/ApplicationView.ui.xml.gz)

**Comment by leforthomas** [comment]
Same problem here...

**Comment by ingosch** [comment]
Please try compiling with 2.0-SNAPSHOT. It's the latest version for 2.0. 2.0-rc3 is two  months old.
I reported this issue before (https://github.com/GwtMaterialDesign/gwt-material/issues/523) and it has been marked as fixed.
But when I use 2.0-SNAPSHOT (including the fix) the FIXED-type SideNav is completely broke.
See: https://youtu.be/2shmFfCv0cc
Just changed the type from PUSH to FIXED.
So it would be interesting to know what it looks like when you use 2.0-SNAPSHOT!? @adibacco @leforthomas

**Comment by BenDol** [comment]
Recent changes to `applyFixedType` in `MaterialSideNav` has broken FIXED type. @kevzlou7979 what was the `applyFixedType` suppose to resolve?

**Comment by BenDol** [comment]
Nevermind I have found the issue and applied a fix, will commit the fix soon.

**Comment by ingosch** [comment]
Thx for your immidiate response @BenDol .
Works much better now but there's still an issue. With lage view/windowsize > 992px the SideNav get's pushed out and in at the first window resize. Happens in two steps, Resizing the window one pixel pushes the SideNav out, resizing again brings it back. Happens also when SideNav is visible in medium view and increasing windowsize over 992px. Tested with Edge and Chrome 55.
