### ISSUE TITLE
tree BUG

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#553]
how do you fix this  ?  http://gwtmaterialdesign.github.io/gwt-material-demo/#tree  
What time can be repaired?      http://gwtmaterialdesign.github.io/gwt-material-demo/#tree   ？
My question is the same.  Has been raised several times have not received your effective answer.  
this  https://github.com/GwtMaterialDesign/gwt-material/issues/544 ;

If you can solve the above problems can solve my problem.Thank you

**Comment by kevzlou7979** [comment]
Hi @Neo110,

This https://github.com/GwtMaterialDesign/gwt-material/issues/544 bug has been solved, you just need to make use of the snapshot in order to make it work.
