### ISSUE TITLE
ma:splitpanel.MaterialSplitPanel  BUG

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#554]
I use  ma:splitpanel.MaterialSplitPanel  tag .but like this image so bad。how can fix this problem? thank for your.

![2017-01-20 1 41 50](https://cloud.githubusercontent.com/assets/12504669/22137575/daab60ae-df16-11e6-942a-52d0f4a6fdfa.png)

**Comment by kevzlou7979** [comment]
Please make sure all addin bugs must belong to correct repo https://github.com/GwtMaterialDesign/gwt-material-addins
