### ISSUE TITLE
MaterialDropDown bugs

### ISSUE THREAD

**Issue by leforthomas** [GwtMaterialDesign/gwt-material#555]
I noticed the following:
- setConstrainWidth(false) has no effect
- setBelowOrigin(true) has no effect
I use them in my uibinder file.

I had a quick look and it seems the name of the options is not correct. I think it should be constrainwidth and not constrain_width (although it IS constrain_width in the class but in the options it looks for constrainwidth - don't ask).

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/e6260574b28ddea7cf1ddb2d8268593827ca98a0

**Comment by kevzlou7979** [comment]
Try the snapshot , see if it solves the issue
