### ISSUE TITLE
Date Picker problem on Mozilla Firefox

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#556]
It seems that in some cases (I have not found exactly the conditions to reproduce, but it's easy to reproduce on a long page with scroll : open a picker, scroll, open another ... and it will occurs) the picker is not at the place that you think it is (it is visually well placed , but it's not possible to click on the buttons).

This issue is visible on your [website](http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers), and only on Mozilla Firefox (no problem on IE11, Chrome, Edge).

**Comment by kevzlou7979** [comment]
What version of firefox are you running?

**Comment by reofake** [comment]
I will check on Monday at work, I don't reproduce with the 50.1.0 version at home... :)

**Comment by reofake** [comment]
I don't reproduce with the 51.0.1 at home no more...

**Comment by kevzlou7979** [comment]
SO we can close now this issue as we cant reproduce the same page.
