### ISSUE TITLE
Overridden setValue( ) fires events

### ISSUE THREAD

**Issue by mitchmartin** [GwtMaterialDesign/gwt-material#557]
The documentation of `com.google.gwt.user.client.ui.HasValue#setValue(T)` states that it should set the value without firing events. However, many of the overridden `setValue `functions in Material classes that implement this interface do the opposite.

This is true for [AbstractValueWidget, MaterialSwitch, (Addins)MaterialComboBox, and MaterialListValueBox](https://github.com/search?q=org%3AGwtMaterialDesign+%22setValue%28value%2C+true%29%22&type=Code)

Either these implementations should be fixed to not fire events (as stated by the `HasValue `interface), or these implementations should be documented such that this is explained.

**Comment by tflinz** [comment]
Came across this when using MaterialDatePicker (which extends AbstractValueWidget<Date>), very confusing and needs to be fixed.

**Comment by tflinz** [comment]
Another observation, is that even if you do call .setValue(value,false) it still fires an event somewhere under the hood.  Or, I am crazy. So if someone else was able to confirm this behaviour, it would be much appreciated.

**Comment by kevzlou7979** [comment]
@mitchmartin Ok thanks for catching this up. I will do a revision to not fire the event automatically. Will be ready on release 2.0-rc4

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/a570922b59bccdfaf2f49516149d936f6dbe0463

**Comment by kevzlou7979** [comment]
Reverted this, As we found some major fallbacks on some widgets. 
Also I found out the culprit on DatePicker event firing even we call ```setValue(Value, false) ``` on line https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialDatePicker.java#L270

**Comment by kevzlou7979** [comment]
Status
- Fixed issue on Switch component added Manual (Demo) and Automated (JUnit) Test

**Comment by kevzlou7979** [comment]
Final Phase is done, Everything is setup and tested on both Manual(Demo created) and Automated test(JUnit Test)
