### ISSUE TITLE
GWT 2.0-rc3 problem on <= IE10

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#559]
Hi guys, the 2.0-rc3 release of library doesn't
work properly on IE 10 (and minor versions)

I think at least the IE 10 is needed for a production mode.

Can you fix it?

Thank you.

Marco

**Comment by kevzlou7979** [comment]
Will take a close investigation with it.

**Comment by kevzlou7979** [comment]
I just checked BrowserStack (Used IE10), I don't see any issue on my side. What specific issue you've got?
![image](https://cloud.githubusercontent.com/assets/3138071/22580579/9e5e9360-ea14-11e6-9b87-9c9a3461fbb1.png)

**Comment by MarcoCucchi** [comment]
Yes, sorry Mark, I use IE11 with IE10 emulation. (see the image attached)
In this mode when I click on a function for example "Components" the page
page is not rendered.

![error](https://cloud.githubusercontent.com/assets/13817916/22583657/4bc98734-e9ee-11e6-8af4-4507a6406c74.png)

**Comment by MarcoCucchi** [comment]
1)
I think that I have found the problem, I widely use Display.FLEX in my UI
but it's not fully supported by IE10.... 

IE10 has uses the old syntax. So:

display: -ms-flexbox; /* will work on IE10 */
display: flex; /* is new syntax, will not work on IE10 */

but Material does not use this specific IE10 syntax... 

2)
The screeshot that I have attached is another problem,  is related to compilation permutations
since I added the right userAgent I worked properly.  (see below)
<set-property name="user.agent" value="ie10, gecko1_8, safari" />

**Comment by kevzlou7979** [comment]
I cant see your userAgent below.

**Comment by MarcoCucchi** [comment]
<set-property name="user.agent" value="ie10, gecko1_8, safari" />

**Comment by MarcoCucchi** [comment]
set-property name="user.agent" value="gecko1_8, safari"

**Comment by MarcoCucchi** [comment]
or better
set-property name="user.agent" value="ie10, gecko1_8, safari"

**Comment by kevzlou7979** [comment]
Figure out the solution http://vinaytechs.blogspot.com/2009/09/gwt-compiler-compiling-for-one-browser.html this link provides a better explanation on User Agents. We just need to have support IE8 at least.

Fixed via https://github.com/GwtMaterialDesign/gwt-material-jquery/commit/32a23120b22efdb771dc9e56afb7d1e8ce507f6b
