### ISSUE TITLE
Striped and hoverable table styles in 1.3.3 does not work any more

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#56]
In the latest 1.3.3 demo striped an hoverable table styles does not have any affect on table like it was before. In the previous demo striped and hoverable styles were working fine. Tested on desktop Chrome, IE, FireFox and mobile Android Chrome.

**Comment by kevzlou7979** [comment]
Hi,

We used DataGrid for the better Data Bindings on GWT Material. You can check it here http://gwt-material.appspot.com/#datagrid.

Best Regards,
GWT Material Team
