### ISSUE TITLE
Do we have equivalents of HTML lists?

### ISSUE THREAD

**Issue by chadluo** [GwtMaterialDesign/gwt-material#560]
Like `ul`, `ol` and their corresponding `li`. It would be nice and handy to construct some layouts with them.

**Comment by kevzlou7979** [comment]
You can make use of https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/html/ListItem.java

**Comment by chadluo** [comment]
Cool. Do we have ordered lists?
