### ISSUE TITLE
Frozen Column in gwt material table

### ISSUE THREAD

**Issue by sameepsinghania** [GwtMaterialDesign/gwt-material#562]
Hi,
This is not a bug but a requirement I would say.
It will be good if we have a feature to frezee columns.
What I mean is, if there are say 100 columns in the table and we get a horizontal scroll bar to navigate through those columns, than I don't my first column or let's say first 2 columns to also move. Rather they should be fixed and visible at all times.
This is a pressing need I believe and in today's scenario it is largely required for enterprise applications.

**Comment by kevzlou7979** [comment]
Thanks for this but please re add this issue to specific repository https://github.com/GwtMaterialDesign/gwt-material-table. Thanks a lot

**Comment by kevzlou7979** [comment]
Please go to this ticket now https://github.com/GwtMaterialDesign/gwt-material-table/issues/83
