### ISSUE TITLE
Add setLineHeight method in MaterialWidget

### ISSUE THREAD

**Issue by richelivargas** [GwtMaterialDesign/gwt-material#563]
Add setLineHeight method in MaterialWidget to change more easily  the line height.

**Comment by kevzlou7979** [comment]
Thanks for the request, we will provide it now.

**Comment by kevzlou7979** [comment]
Fixed via - https://github.com/GwtMaterialDesign/gwt-material/commit/e1ed35adc1e7d4c473e23513d19432b17d3373c1
