### ISSUE TITLE
MaterialListValueBox - unable to programatically select the first option

### ISSUE THREAD

**Issue by mitchmartin** [GwtMaterialDesign/gwt-material#564]
`MaterialListValueBox#setValue` is ignoring the first option when validating index values. It should be verifying that the index is non-negative, as `0` is a valid index.

I know that `setSelectedIndex` is available, but that is not available behind the `HasValue` or `AbstractValueWidget` abstractions.

[MaterialListValueBox#setValue:241](https://github.com/GwtMaterialDesign/gwt-material/blob/4f7767a80b5797ff9f180b4e362578cb9ae8b044/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialListValueBox.java#L241)
```
    public void setValue(T value, boolean fireEvents) {
        int index = values.indexOf(value);
        if (index > 0) {
            T before = getValue();
            setSelectedIndex(index);

            if (fireEvents) {
                ValueChangeEvent.fireIfNotEqual(this, before, value);
            }
        }
    }
```

**Comment by BenDol** [comment]
This is resolved in 2.0-SNAPSHOT
