### ISSUE TITLE
stickyTableHeaders is not a function

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#565]
Hello I try use MaterialDataTable copy code from GWT-MaterialDesign DEMO and Have error
What I do wring?

> ApplicationPresenter#onLogin
> AdminConsole-0.js:84332 Problem setting up the DataView.
> H3f_g$ @ AdminConsole-0.js:84332
> AdminConsole-0.js:84328 Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : this.$table_0_g$.stickyTableHeaders is not a function
> AdminConsole-0.js:84332 TypeError: this.$table_0_g$.stickyTableHeaders is not a function
>     at kli_g$.hgi_g$ [as setupStickyHeader_0_g$] (AdminConsole-0.js:61548:22)
>     at kli_g$.egi_g$ [as setup_2_g$] (AdminConsole-0.js:61505:12)
>     at Jui_g$.Rti_g$ [as setup_2_g$] (AdminConsole-0.js:69061:22)
>     at Jui_g$.$ui_g$ [as setup_2_g$] (AdminConsole-0.js:69435:27)
>     at Jui_g$.Rsi_g$ [as onLoad_0_g$] (AdminConsole-0.js:68832:12)
>     at Jui_g$.HA_g$ [as onAttach_0_g$] (AdminConsole-0.js:15970:8)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AdminConsole-0.js:41474:10)
>     at mBd_g$ (AdminConsole-0.js:41430:14)
>     at yMd_g$.eAd_g$ [as doAttachChildren_0_g$] (AdminConsole-0.js:41090:3)
>     at yMd_g$.HA_g$ [as onAttach_0_g$] (AdminConsole-0.js:15969:8)
>     at GAi_g$._A_g$ [as onAttach_0_g$] (AdminConsole-0.js:16175:20)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AdminConsole-0.js:41474:10)
>     at mBd_g$ (AdminConsole-0.js:41430:14)
>     at $Ih_g$.eAd_g$ [as doAttachChildren_0_g$] (AdminConsole-0.js:41090:3)
>     at $Ih_g$.HA_g$ [as onAttach_0_g$] (AdminConsole-0.js:15969:8)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AdminConsole-0.js:41474:10)
>     at mBd_g$ (AdminConsole-0.js:41430:14)
>     at $Ih_g$.eAd_g$ [as doAttachChildren_0_g$] (AdminConsole-0.js:41090:3)
>     at $Ih_g$.HA_g$ [as onAttach_0_g$] (AdminConsole-0.js:15969:8)
>     at $Ih_g$.PA_g$ [as setParent_0_g$] (AdminConsole-0.js:16065:12)
>     at uGh_g$.cAd_g$ [as adopt_0_g$] (AdminConsole-0.js:41077:14)
>     at uGh_g$.oAd_g$ [as add_8_g$] (AdminConsole-0.js:41135:8)
>     at uGh_g$.Xeh_g$ [as add_8_g$] (AdminConsole-0.js:54082:27)
>     at uGh_g$.nAd_g$ [as add_7_g$] (AdminConsole-0.js:41128:8)
>     at uGh_g$.Weh_g$ [as add_6_g$] (AdminConsole-0.js:54071:25)
>     at uGh_g$.aAd_g$ [as add_5_g$] (AdminConsole-0.js:41065:8)
>     at sd_g$.ud_g$ [as setInSlot_2_g$] (AdminConsole-0.js:4253:27)
>     at w4g_g$.qb_g$ [as setInSlot_1_g$] (AdminConsole-0.js:3492:25)
>     at w4g_g$.pb_g$ [as setInSlot_0_g$] (AdminConsole-0.js:3481:8)
>     at Bte_g$ (AdminConsole-0.js:52149:22)
>     at Gte_g$.Hte_g$ [as execute_1_g$] (AdminConsole-0.js:52183:3)
>     at Mbb_g$ (AdminConsole-0.js:20992:28)
>     at qbb_g$ (AdminConsole-0.js:20714:9)
>     at fbb_g$.lbb_g$ [as flushPostEventPumpCommands_0_g$] (AdminConsole-0.js:20806:5)
>     at Dbb_g$.Ebb_g$ [as execute_2_g$] (AdminConsole-0.js:20945:22)
>     at ibb_g$ (AdminConsole-0.js:20682:19)
>     at X9_g$ (AdminConsole-0.js:20426:28)
>     at $9_g$ (AdminConsole-0.js:20482:16)
>     at AdminConsole-0.js:20462:14
>     at callback_0_g$ (AdminConsole-0.js:20733:39)
> H3f_g$ @ AdminConsole-0.js:84332
> AdminConsole-0.js:84332 Could not setup AbstractDataTable due to previous errors.
> H3f_g$ @ AdminConsole-0.js:84332
> ConsoleLogger.java:55Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : this.$table_0_g$.stickyTableHeaders is not a function
> ConsoleLogger.java:32TypeError: this.$table_0_g$.stickyTableHeaders is not a function
>     at kli_g$.hgi_g$ [as setupStickyHeader_0_g$] (AbstractDataView.java:648)
>     at kli_g$.egi_g$ [as setup_2_g$] (AbstractDataView.java:472)
>     at Jui_g$.Rti_g$ [as setup_2_g$] (AbstractDataTable.java:171)
>     at Jui_g$.$ui_g$ [as setup_2_g$] (MaterialDataTable.java:77)
>     at Jui_g$.Rsi_g$ [as onLoad_0_g$] (AbstractDataTable.java:161)
>     at Jui_g$.HA_g$ [as onAttach_0_g$] (Widget.java:359)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AttachDetachException.java:34)
>     at mBd_g$ (AttachDetachException.java:74)
>     at yMd_g$.eAd_g$ [as doAttachChildren_0_g$] (Panel.java:129)
>     at yMd_g$.HA_g$ [as onAttach_0_g$] (Widget.java:354)
>     at GAi_g$._A_g$ [as onAttach_0_g$] (Composite.java:179)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AttachDetachException.java:34)
>     at mBd_g$ (AttachDetachException.java:74)
>     at $Ih_g$.eAd_g$ [as doAttachChildren_0_g$] (Panel.java:129)
>     at $Ih_g$.HA_g$ [as onAttach_0_g$] (Widget.java:354)
>     at pBd_g$.qBd_g$ [as execute_4_g$] (AttachDetachException.java:34)
>     at mBd_g$ (AttachDetachException.java:74)
>     at $Ih_g$.eAd_g$ [as doAttachChildren_0_g$] (Panel.java:129)
>     at $Ih_g$.HA_g$ [as onAttach_0_g$] (Widget.java:354)
>     at $Ih_g$.PA_g$ [as setParent_0_g$] (Widget.java:484)
>     at uGh_g$.cAd_g$ [as adopt_0_g$] (Panel.java:124)
>     at uGh_g$.oAd_g$ [as add_8_g$] (ComplexPanel.java:105)
>     at uGh_g$.Xeh_g$ [as add_8_g$] (MaterialWidget.java:192)
>     at uGh_g$.nAd_g$ [as add_7_g$] (ComplexPanel.java:87)
>     at uGh_g$.Weh_g$ [as add_6_g$] (MaterialWidget.java:181)
>     at uGh_g$.aAd_g$ [as add_5_g$] (Panel.java:68)
>     at sd_g$.ud_g$ [as setInSlot_2_g$] (ApplicationView.java:65)
>     at w4g_g$.qb_g$ [as setInSlot_1_g$] (PresenterWidget.java:374)
>     at w4g_g$.pb_g$ [as setInSlot_0_g$] (PresenterWidget.java:347)
>     at Bte_g$ (RevealContentHandler.java:60)
>     at Gte_g$.Hte_g$ [as execute_1_g$] (RevealContentHandler.java:58)
>     at Mbb_g$ (SchedulerImpl.java:50)
>     at qbb_g$ (SchedulerImpl.java:183)
>     at fbb_g$.lbb_g$ [as flushPostEventPumpCommands_0_g$] (SchedulerImpl.java:347)
>     at Dbb_g$.Ebb_g$ [as execute_2_g$] (SchedulerImpl.java:78)
>     at ibb_g$ (SchedulerImpl.java:141)
>     at X9_g$ (Impl.java:239)
>     at $9_g$ (Impl.java:291)
>     at Impl.java:77
>     at callback_0_g$ (SchedulerImpl.java:196)
> H3f_g$ @ ConsoleLogger.java:32
> ConsoleLogger.java:32Exception caught: Exception caught: (TypeError) : $wnd.$(...).longpress is not a function
> H3f_g$ @ ConsoleLogger.java:32
> ConsoleLogger.java:55Exception: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: (TypeError) : $wnd.$(...).longpress is not a function
> ConsoleLogger.java:32Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: Exception caught: (TypeError) : $wnd.$(...).longpress is not a function
>     at kBd_g$.g1_g$ [as createError_0_g$] (Throwable.java:121)
>     at kBd_g$.q1_g$ [as initializeBackingError_0_g$] (Throwable.java:113)
>     at kBd_g$.a1_g$ (Throwable.java:74)
>     at kBd_g$.G1_g$ (Exception.java:33)
>     at kBd_g$.O1_g$ (RuntimeException.java:33)
>     at kBd_g$.hLc_g$ (UmbrellaException.java:65)
>     at kBd_g$.oLc_g$ (UmbrellaException.java:26)
>     at kBd_g$ (AttachDetachException.java:136)
>     at mBd_g$ (AttachDetachException.java:87)
>     at $Ih_g$.eAd_g$ [as doAttachChildren_0_g$] (Panel.java:129)
>     at $Ih_g$.HA_g$ [as onAttach_0_g$] (Widget.java:354)
>     at $Ih_g$.PA_g$ [as setParent_0_g$] (Widget.java:484)
>     at uGh_g$.cAd_g$ [as adopt_0_g$] (Panel.java:124)
>     at uGh_g$.oAd_g$ [as add_8_g$] (ComplexPanel.java:105)
>     at uGh_g$.Xeh_g$ [as add_8_g$] (MaterialWidget.java:192)
>     at uGh_g$.nAd_g$ [as add_7_g$] (ComplexPanel.java:87)
>     at uGh_g$.Weh_g$ [as add_6_g$] (MaterialWidget.java:181)
>     at uGh_g$.aAd_g$ [as add_5_g$] (Panel.java:68)
>     at sd_g$.ud_g$ [as setInSlot_2_g$] (ApplicationView.java:65)
>     at w4g_g$.qb_g$ [as setInSlot_1_g$] (PresenterWidget.java:374)
>     at w4g_g$.pb_g$ [as setInSlot_0_g$] (PresenterWidget.java:347)
>     at Bte_g$ (RevealContentHandler.java:60)
>     at Gte_g$.Hte_g$ [as execute_1_g$] (RevealContentHandler.java:58)
>     at Mbb_g$ (SchedulerImpl.java:50)
>     at qbb_g$ (SchedulerImpl.java:183)
>     at fbb_g$.lbb_g$ [as flushPostEventPumpCommands_0_g$] (SchedulerImpl.java:347)
>     at Dbb_g$.Ebb_g$ [as execute_2_g$] (SchedulerImpl.java:78)
>     at ibb_g$ (SchedulerImpl.java:141)
>     at X9_g$ (Impl.java:239)
>     at $9_g$ (Impl.java:291)
>     at Impl.java:77
>     at callback_0_g$ (SchedulerImpl.java:196)
> H3f_g$ @ ConsoleLogger.java:32
> ConsoleLogger.java:55Caused by: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: (TypeError) : $wnd.$(...).longpress is not a function

**Comment by kevzlou7979** [comment]
Can you show us your app.gwt.xml wherein you import the GMD Modules.

**Comment by LeshaRB** [comment]
Yes
<?xml version="1.0" encoding="UTF-8"?>
<module rename-to='AdminConsole'>

    <inherits name='com.google.gwt.user.User'/>
    <inherits name="com.google.gwt.resources.Resources"/>
    <inherits name="com.google.gwt.logging.Logging"/>

    <inherits name="com.google.web.bindery.autobean.AutoBean"/>

    <inherits name='com.gwtplatform.mvp.MvpWithEntryPoint'/>

    <inherits name="gwt.material.design.GwtMaterialWithJQuery"/>
    <inherits name="gwt.material.design.GwtMaterialDesignBasic"/>
    <inherits name="gwt.material.design.themes.ThemeBlue"/>
    <inherits name="gwt.material.design.GwtMaterialTable" />
    <inherits name="gwt.material.design.jquery.JQuery" />

    <inherits name="com.github.nmorel.gwtjackson.GwtJackson"/>
    <inherits name="org.fusesource.restygwt.RestyGWT"/>
    <inherits name="com.googlecode.gwt.crypto.Crypto"/>

    <source path='client'/>
    <source path='shared'/>

    <extend-configuration-property name='gin.ginjector.modules' value='by.softclub.admin.client.gin.ClientModule'/>

    <set-configuration-property name='CssResource.enableGss' value='true'/>
    <set-configuration-property name="CssResource.gssDefaultInUiBinder" value="true"/>

    <extend-property name="locale" values="ru"/>
    <extend-property name="locale" values="en"/>
    <set-property name="locale" value="ru"/>

    <set-property name="gwt.logging.logLevel" value="INFO"/>
    <set-property name="gwt.logging.enabled" value="TRUE"/>
    <set-property name="gwt.logging.consoleHandler" value="ENABLED"/>
</module>

**Comment by LeshaRB** [comment]
I have this error when try use this example
https://github.com/GwtMaterialDesign/gwt-material-demo/blob/master/src/main/java/gwt/material/design/demo/client/application/addins/datatable/table/PageTable.java

but when I use this demo
https://github.com/GwtMaterialDesign/gwt-material-table-sample/blob/master/src/main/java/gwt/material/design/sample/client/ui/PageTable.java
All work fine

I think demo in first example old. For exmaple 
pager.setRowCountOptions(5, 10, 15, 20); - doesn't have this method

**Comment by kevzlou7979** [comment]
FYI the Snapshot git repo is here https://github.com/GwtMaterialDesign/gwt-material-demo/blob/release_2.0/src/main/java/gwt/material/design/demo/client/application/addins/datatable/table/PageTable.java

**Comment by davidmoers** [comment]
I think I got the reason of that problem. It's because of RestyGWT. When I am not using it, I don't get this JavaScript Error.

**Comment by LeshaRB** [comment]
I also used this library

**Comment by futuretec** [comment]
same here - RestyGWT + gwt-material-table won't play along for now

initial error (with `useStickyHeader="true"`):
`this.$table_0_g$.stickyTableHeaders is not a function`

after I turn off the sticky headers .. the next JS error occurs:
`$wnd.TableSubHeaders is undefined`

has anyone found a fix yet to maintain RestyGWT + GMD Data Tables in a single GWT project?

**Comment by davidmoers** [comment]
My Project is without errors now...

gwt.xml:

```
<!-- <inherits name="com.google.gwt.user.theme.standard.Standard"/> -->
<inherits name="com.google.gwt.user.theme.clean.Clean" />
<!-- <inherits name="com.google.gwt.user.theme.chrome.Chrome"/> -->
<!-- <inherits name="com.google.gwt.user.theme.dark.Dark"/> -->

<!-- Other module inherits -->
<inherits name="com.github.nmorel.gwtjackson.GwtJackson" />
<inherits name="org.fusesource.restygwt.RestyGWT" />

<!-- GWT Material with add-ins -->
<inherits name="gwt.material.design.GwtMaterialBasicWithJQuery" />
<inherits name="gwt.material.design.addins.GwtMaterialAddins" />
<inherits name="gwt.material.design.GwtMaterialTable" />

<!-- GWT Material themes, requires MaterialBasic instead of Material (see above) -->
<inherits name="gwt.material.design.themes.ThemeBlue"/>`

<!-- GWT Material themes, requires MaterialBasic instead of Material (see above) -->
<inherits name="gwt.material.design.themes.ThemeBlue"/>
```

pom.xml:
```
<!-- Convenience property to set the GWT version -->
<gwt.version>2.8.2</gwt.version>
<gwtmaterialdesign.version>2.0</gwtmaterialdesign.version>

<!-- GWT needs Java 1.8 -->
<java.build.version>1.8</java.build.version>
```

and pom.xml depencencies:

```
		<!-- GWT Material Design -->
		<dependency>
			<groupId>com.github.gwtmaterialdesign</groupId>
			<artifactId>gwt-material</artifactId>
			<version>${gwtmaterialdesign.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.gwtmaterialdesign</groupId>
			<artifactId>gwt-material-themes</artifactId>
			<version>${gwtmaterialdesign.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.gwtmaterialdesign</groupId>
			<artifactId>gwt-material-addins</artifactId>
			<version>${gwtmaterialdesign.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.gwtmaterialdesign</groupId>
			<artifactId>gwt-material-jquery</artifactId>
			<version>${gwtmaterialdesign.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.gwtmaterialdesign</groupId>
			<artifactId>gwt-material-table</artifactId>
			<version>${gwtmaterialdesign.version}</version>
		</dependency>

		<!-- RestyGWT: Advanced REST service integration -->
		<!-- https://mvnrepository.com/artifact/javax.ws.rs/javax.ws.rs-api -->
		<dependency>
			<groupId>javax.ws.rs</groupId>
			<artifactId>javax.ws.rs-api</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>org.fusesource.restygwt</groupId>
			<artifactId>restygwt</artifactId>
			<version>2.2.2</version>
		</dependency>
		<dependency>
			<groupId>com.github.nmorel.gwtjackson</groupId>
			<artifactId>gwt-jackson</artifactId>
			<version>0.14.2</version>
		</dependency>
```
