### ISSUE TITLE
MaterialFileUploader - setEnable(false) not working

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material#566]
When MaterialFileUploader.setEnable(false) user can upload file, and user see information about success but event success isn't calling.
![image](https://cloud.githubusercontent.com/assets/608413/23065319/4d6fa96a-f515-11e6-8edb-30eae1c11009.png)

**Comment by kevzlou7979** [comment]
I will move this issue to addins repository as it is the best place.

**Comment by kevzlou7979** [comment]
Issue moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/201
