### ISSUE TITLE
Number Value Box is not working in IE 11

### ISSUE THREAD

**Issue by dramesh123** [GwtMaterialDesign/gwt-material#567]
Hi,
In IE 11, Number Value Box
<m:MaterialDoubleBox ui:field="txtDoubleBox" label="Double value"/>
is appearing as normal text box.  But It works fine in firefox. Any fix for this?

**Comment by kevzlou7979** [comment]
I have tested this on the demo showcase and other projects but can't reproduce your issue. I think some css styles overrides your Double Box input element. Just check your element on ```Inspect Element``` and share with me what's the generated element for the double box/ 
![image](https://cloud.githubusercontent.com/assets/3138071/23328724/0b94e10e-fb64-11e6-945c-ea194c699d12.png)

**Comment by dramesh123** [comment]
Sorry for the delay in my response. We are not overriding the default CSS of this widget. We can see couple of issues here.

1. In Firefox, for **MaterialDoubleBox**   is working fine and also allows arrow icon to increment/decrement the number (Similar to spinner widget).
But in IE, this is not the case. It is not showing the arrow icons to avail this feature.
2. API for this widget is not working
            In Firefox : boxObject.getValue() and boxObject.getValueAsNumber() function returns proper result .
            In IE : boxObject.getValue()and boxObject.getValueAsNumber()  function returns NULL and NaN.

Please help us in this regard.

Thanks
Ramesh


          For temporarily solution we are using  boxObject.getText() to get value from box.
