### ISSUE TITLE
MaterialListBox setError

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#568]
The setError method for MaterialListBox  flags the field properly, but the Error Text does not display. It appears that the red line is drawn slightly below the line of the MaterialListBox , so the text may be hidden because of that.

**Comment by kevzlou7979** [comment]
Fixed via 
![image](https://cloud.githubusercontent.com/assets/3138071/23285177/a2128956-fa6a-11e6-8274-41cc5504f4f8.png)
