### ISSUE TITLE
MaterialDropDown there is no way to get one of its child elements (MaterialLink)

### ISSUE THREAD

**Issue by John-Kellner** [GwtMaterialDesign/gwt-material#57]
I've tried to add Elements that works fine but then ...

```
    @UiField
    protected MaterialDropDown combo;

   @Override
    protected void onAttach() {
        super.onAttach();

        combo.addWidget(new MaterialLink("Pos 1", "black"));
        combo.addWidget(new MaterialLink("Pos 2", "black"));
        combo.addWidget(new MaterialLink("Pos 3", "black"));

        combo.addDomHandler(new ClickHandler() {
            @Override
            public void onClick(ClickEvent clickEvent) {

                if (combo.getWidget() instanceof MaterialLink) {
                    Console.log("Widget found !!");
                }
            }
        }, ClickEvent.getType());
    }

```

The above code does not indicate the message "Widget found".

 - There is no change handler or something like this. 
- getSelectedIndex() / setSelectedIndex method is missing 
- with getWidget() comes back a Button Widget but for all of the items the same one.

How do you guys get the selected Elements ?
Does anybody know how to deal with them ?

**Comment by kevzlou7979** [comment]
Hi,

The Handlers of MaterialDropDown depends on each Item(MaterialLInk), meaning you can add ClickHandlers on each MaterialLink to trigger some event on selected MaterialDropItem.

e.g.

MaterialLink link = new MaterialLink("Pos 1", "black");
link.addClickHandler(new ClickHandler() {
            @Override
            public void onClick(ClickEvent clickEvent) {
                       MaterialToast.alert("Toast Me");
            }
        });
combo.addWidget();

Regards,
GWT Material Design
