### ISSUE TITLE
Helper text not displaying anymore in 2.0-SNAPSHOT

### ISSUE THREAD

**Issue by youncta-dev** [GwtMaterialDesign/gwt-material#570]
I'm using 2.0-SNAPSHOT and noticed that yesterday something has changed that doesn't make the helper text work in **MaterialFloatBox** and **MaterialIntegerBox**

It doesn't work neither if you use the API setHelperText not if you set the helper text in the **ui.xml**

**Comment by kevzlou7979** [comment]
I checked on my test and everything works fine. Also the recent changes didnt affect any regressions as the changes only applied to ```ActiveMixin``` not ```ErrorMixin```
https://github.com/GwtMaterialDesign/gwt-material/commit/fcb598eb3f920c23a72b26719911c4b343a48f33

![image](https://cloud.githubusercontent.com/assets/3138071/23285404/0ca39bce-fa6c-11e6-851d-81b8f134e4a3.png)

Please can you submit a fresh project or post your code snippet. Might be an issue with Style into your app css.

**Comment by youncta-dev** [comment]
You are right, it was a mistake in my app css. So sorry. Forgive me.

**Comment by kevzlou7979** [comment]
No worries :) I will close now this issue.
