### ISSUE TITLE
MaterialFooter 

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#571]
I add in my project

>         <m:MaterialFooter ui:field="footer" type="DEFAULT" styleName="{res.style.footer}">
>             <m:MaterialFooterCopyright>
>                 <m:MaterialLabel ui:field="author"/>
>             </m:MaterialFooterCopyright>
>         </m:MaterialFooter>

So I have some questions:

1. Why GWT-Materialdesign redefines my style???

> ...
> < footer class="by-client-resources-AppResources-Style-footer **page-footer**"><div class="container" 
> ...

2.  Why do we need these styles, if I only want to display the "footer-copyright" without "container". So I need to override the styles put the "!Important" or add my own style see point 1).

> footer.page-footer {
>     **margin-top: 20px;**
>     **padding-top: 20px;**
>     background-color: #64b5f6;
> }

![footer](https://cloud.githubusercontent.com/assets/439337/23294462/a52e8b8c-fa7c-11e6-8526-d9af74a458d4.png)

**Comment by kevzlou7979** [comment]
MaterialFooter is a fixed component meaning we have default containers inside of it. if you want you can extend it and change the way you like. Or build another footer.
