### ISSUE TITLE
MaterialDatePicker - page jumps to bottom

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#573]
Hello,

for some reason, when you open the MaterialDatePicker modal, the page scrolls to the bottom. Can be reproduced using the Demo Site (http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers) and choosing the date using the first picker.

IIRC this was not always an issue.

kr

Chris

**Comment by reofake** [comment]
Duplicate of https://github.com/GwtMaterialDesign/gwt-material/issues/558

**Comment by simerlec** [comment]
ah, thanks reo - I've overlooked that.

**Comment by kevzlou7979** [comment]
@reofake Thanks to follow up this issue.

**Comment by reofake** [comment]
No problem !
