### ISSUE TITLE
Wrong Hamburger-Icon order with MaterialNavSection

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#576]
Hi
In GWT-Material Snapshot 2.0 is new a Hamburger-Icon order issue.
If you have a MaterialNavBar with a MaterialNavSection and a MaterialSideNav an the Hamburger-Icon is on, the Hamburger-Icon has a wrong display order.

![hicon](https://cloud.githubusercontent.com/assets/24357072/23528217/52d19c9a-ff99-11e6-950c-8bd53cae8d10.jpg)

Code:

```
    <!--Header Navigation-->
    <m:MaterialNavBar ui:field="navBar" type="FIXED" backgroundColor="BLUE_DARKEN_2" activates="sideBar"
                      textColor="WHITE" width="100%">
      <m:MaterialNavSection float="LEFT">
        <m:MaterialLabel ui:field="headerTitle" addStyleNames="{style.headTitle}"/>
      </m:MaterialNavSection>
    </m:MaterialNavBar>

    <m:MaterialSideNav ui:field="sideNav" m:id="sideBar" type="PUSH" width="240" closeOnClick="false"
                       allowBodyScroll="true" showOnAttach="true" alwaysShowActivator="true" float="LEFT">
       .....
       .....
    </m:MaterialSideNav>    
```

In GWT-Material 2.0-rc3 the order is ok.
Thanks

**Comment by kevzlou7979** [comment]
Thanks for catching this issue I will work now on this.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/c622726d3f4ad6bfa4465c67a07e6022aa1fa5fe
