### ISSUE TITLE
Menu bar issue

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#578]
Hi guys, seems we have a problem to catch a sub-menu voice inside a short space area.
(see the attached file)

![bug_menu](https://cloud.githubusercontent.com/assets/13817916/23716505/cab9cdd6-0430-11e7-951f-fced5744db06.gif)

**Comment by kevzlou7979** [comment]
Thanks for catching this up will add it to rc4

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/4876184c63652624731661e574e11893320e1619

Screenshot:
![578](https://cloud.githubusercontent.com/assets/3138071/23733990/12fd558c-04b7-11e7-8933-6b655cdade65.gif)

**Comment by MarcoCucchi** [comment]
Great! than you

**Comment by MarcoCucchi** [comment]
Mark could you remove the attribute  **max-height: 32px !important;**
from .menu-bar .dropdown-content li  css? (like the old menu)
I would like to like to be able to put rows bigger than 32 pixel.

Thanks

**Comment by MarcoCucchi** [comment]
Mark we have another issue, is you put an Icon to a submenu it starts to behave in a weird way..
see the example attached.

[error.txt](https://github.com/GwtMaterialDesign/gwt-material/files/830408/error.txt)

**Comment by kevzlou7979** [comment]
Hi there, will update it now

**Comment by MarcoCucchi** [comment]
Hi Mark, have you updated the css? ty

**Comment by kevzlou7979** [comment]
I have added a method ```setItemHeight``` to easily configure each menu bar item's height.
Also take note that on Material Design Spec (We are following the standards for each widget size dimensions for not having any cosmetic issue). I will update now the release.

Sample code:
```<ma:menubar.MaterialMenuBar itemHeight="40px" />```

**Comment by kevzlou7979** [comment]
Follow up fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/1c19476c8da53eef6277ae92d6f058269f7694eb

**Comment by MarcoCucchi** [comment]
Thank you very much Mark.
