### ISSUE TITLE
SideNav with Type Fixed initial resize disappears

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material#579]
With 2.0-rc4 I still experience what is described in #552 latest comment.

With large view/windowsize > 992px the SideNav get's pushed out and in at the first window resize. Happens in two steps, Resizing the window one pixel pushes the SideNav out, resizing again brings it back. Happens also when SideNav is visible in medium view and increasing windowsize over 992px. Tested with Edge and Chrome 55.

**Comment by ingosch** [comment]
Fixed SideNav has also an issue when windowsize "jumps" from < 993px to > 992px in a single resize like changing page orientation from portrait to landscape on mobile devices.
If the SideNav is opened it doesn't get shown after the flipping the device.
Look at the video to see both bugs. Demo 2.0-rc4 with just SideNav set to FIXED and added padding to the other content.
https://www.youtube.com/watch?v=eaCQnKG0U8o

**Comment by kevzlou7979** [comment]
Hi @ingosch thanks for the video now i visualize better the issue. Will ping you once i found the solution for this issue.

**Comment by BenDol** [comment]
I thought this was resolved in the latest version.

**Comment by BenDol** [comment]
This appears to be a slight issue with the materialize library, I will look into a fix later today.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/00ac3e6b0bb2be59b616abf366353c1a41dfa532.

**Comment by kevzlou7979** [comment]
Just tested this on other projects, it seems that the workaround / solution does not fully solved the issue. Will see other solution soon.

**Comment by kevzlou7979** [comment]
I've created a test project here : 
https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/%23579

Fixed via https://github.com/GwtMaterialDesign/gwt-material/tree/release_2.0

Screenshot : 
![sidenav-fixed-type](https://cloud.githubusercontent.com/assets/3138071/24277761/308f8bd2-107a-11e7-9e05-948741843e28.gif)
