### ISSUE TITLE
GWT-Material Documentation - MaterialSideProfile Namespace

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#581]
Minor issue... but may be very confusing for some beginning users. The sample code implies that MaterialSideProfile  part of the same namespace as normal UI elements such as MaterialSideNav. Should note somewhere (and/or change to ma:MaterialSideProfile) that it's part of add ins.

<m:MaterialSideNav type="FIXED" m:id="sideNav" closeOnClick="false" width="280">
 <m:MaterialSideProfile url="http://static1.squarespace.com/static/51609147e4b0715db61d32b6/521b97cee4b05f031fd12dde/5519e33de4b06a1002802805/1431718693701/?format=1500w">

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-demo/commit/d12a6bca77078c26e87e9e0ac970f63612f19bb3
