### ISSUE TITLE
Any MaterialNumberField throws "RuntimeException: Field must be a number." when empty

### ISSUE THREAD

**Issue by hajo70** [GwtMaterialDesign/gwt-material#583]
To reproduce this one can simply clear the input-value of any number field and call getValue() afterwards. I'd expect the method to return null instead.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/7be98abe6e1f80f6b52f8e4b05113eac4fc02771.
