### ISSUE TITLE
MaterialDatePicker setPickerDate call by setValue problem on async callback

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#588]
I got an error when I try to update the value of a MaterialDatePicker on an async callback.
I got this error : $wnd.$(...).pickadate(...) is undefined

I fixed it, but I don't know if this is a good fix (just catch Exception like in getPickerDate) :
```
public void setPickerDate(JsDate date, Element picker) {
    try {
        $(picker).pickadate("picker").set("select", date, () -> {
            DOM.createFieldSet().setPropertyObject("muted", true);
        });
    }
    catch (Exception e) {
        e.printStackTrace();
    }
}
```

**Comment by kevzlou7979** [comment]
Might be a race issue, will investigate further.

**Comment by kevzlou7979** [comment]
Have you tried to use ```setDate()``` or ```setValue()``` methods instead? There might be an issue with your second parameter in ```setPickerDate(date, picker)``` method.

**Comment by kevzlou7979** [comment]
I've tried to create a new GMD 2.0-SNAPSHOT test project to create a service async callback and tested setVaue() on datepicker. 


Code sample:
![image](https://cloud.githubusercontent.com/assets/3138071/24176004/8394675a-0ed4-11e7-81dd-2061df1a1eb9.png)

Tests:
![async](https://cloud.githubusercontent.com/assets/3138071/24176074/d2717d86-0ed4-11e7-9523-f24a3ec326cd.gif)

Please can you provide your code deeper. It seems that maybe you have some race issue deep into your code.

**Comment by reofake** [comment]
The only difference is that my async call is on the onAttach, and I call :
`datePicker.setValue(null);` to reset (no problem)
then
`datePicker.setValue(value);` to set the value (if necessary)

**Comment by reofake** [comment]
Another subject, it seems that setting the value to null does not work, is there any way reset the datepicker value ?

**Comment by reofake** [comment]
There is the same problem with the clearValues() method.

**Comment by kevzlou7979** [comment]
Ok i will update my test project to load the async callback on ```onAttach``` to see if the problem persist. Also test the clearValues() and setValue(null).

**Comment by kevzlou7979** [comment]
I have updated my test project and migrate the code snippet to ```onAttach()``` it works well. Please can you provide a sample project so that we can have a fast progress on getting the exact issue.

![image](https://cloud.githubusercontent.com/assets/3138071/24245252/0bf16b60-0ffd-11e7-9023-3ef59b6206b2.png)

**Comment by kevzlou7979** [comment]
Hi @reofake,

I have provided the Test Project repository, please check if the issue still persists.
Here's the link for the app.
https://github.com/GwtMaterialDesign/gwt-material-issue-test

Note: You can submit PR into that repository I created for you to show your code.

The Test Demo App will look like this:
![setvalue - datepicker](https://cloud.githubusercontent.com/assets/3138071/24246700/9b8e800e-1003-11e7-908f-dc742cb96acf.gif)
 

Follow up Fixed: https://github.com/GwtMaterialDesign/gwt-material/commit/6f676d1372c9ee1c9d95b889423e3b5b6baf140b

**Comment by reofake** [comment]
I try to reproduce with your project, I will be back when success :)

**Comment by kevzlou7979** [comment]
Why do you need to replace SNAPSHOT version with RC4?? .For sure the upate will not be there because RC4 was released and its FINAL. SNAPSHOTS are the ones that being updated everytime I do fixes. ALSO i created the repository Test Project because you didnt provide the whole code. Please use the repository i shared to have a use for it.

**Comment by reofake** [comment]
I finally found how to reproduce easily (no need to callback finaly) :

```
protected void onAttach() {
        super.onAttach();

        picker.setValue(new Date());
        
        if(!initialized) {
            initialized = true;
            
            picker.setLanguage(DatePickerLanguage.FR);
        }
        
        picker.setValue(new Date());
    }
```

And now I can confirm that your fix (https://github.com/GwtMaterialDesign/gwt-material/commit/6f676d1372c9ee1c9d95b889423e3b5b6baf140b) is OK.
