### ISSUE TITLE
MaterialSideNav: setAlwaysShowActivator(false) not working for type PUSH

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#589]
On latest snapshot: if I create a MaterialSideNav with type PUSH and `setAlwaysShowActivator(false)` the activation button is nonetheless always visible. With type FIXED the activator is hidden correctly if not needed.

**Comment by kevzlou7979** [comment]
Fixed https://github.com/GwtMaterialDesign/gwt-material/commit/2fc992283432571dab659656eb5083c815b3c53d.

You can test the demo here:
https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/%23589

Screenshot
```
alwaysShowActivator='false'
```
![image](https://cloud.githubusercontent.com/assets/3138071/24250182/ed22b0b8-1010-11e7-8c09-c6d8655187a9.png)

```
alwaysShowActivator='true'
```
![image](https://cloud.githubusercontent.com/assets/3138071/24250203/033018e6-1011-11e7-9867-7853c7256655.png)

**Comment by LeshaRB** [comment]
Please dont' close ticke so quickly

Yes you fix it 
https://github.com/GwtMaterialDesign/gwt-material/issues/586

But when I remove MaterialSideNav, button menu don't remove =(
Also see
https://github.com/GwtMaterialDesign/gwt-material/issues/569

![navbar](https://cloud.githubusercontent.com/assets/439337/24288038/ec599882-108c-11e7-8f78-4ac59f6bd3fe.png)

**Comment by kevzlou7979** [comment]
Please can you try the one I made https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/%23589 , I tried to remove my sidenav and it works fine. 

![image](https://cloud.githubusercontent.com/assets/3138071/24290450/fae25cf8-10bf-11e7-9fbc-1f50c1ec6c69.png)

**Comment by kevzlou7979** [comment]
Also make sure to use the Snapshot version. Thanks in advance :)

**Comment by kevzlou7979** [comment]
Can we do Team Viewer then so that I can help you deeply :)

**Comment by LeshaRB** [comment]
I have two presenter
Application with MaterialHeader
and 
Menu with MaterialSideNav 

When user logout I remove menu presenter with MaterialSideNav  widget
But menu button  in MaterialHeader stay show =(

**Comment by LeshaRB** [comment]
> ```
>         <m:MaterialHeader>
>             <m:MaterialNavBar ui:field="header" styleName="{res.style.header}" activates="menuConsole">
>                 <m:MaterialNavBrand marginLeft="60" float="LEFT" text="{resLocale.headerTitle}"/>
>                 <m:MaterialNavSection marginRight="60" float="RIGHT">
>                     <m:MaterialLink iconType="ACCOUNT_CIRCLE" iconPosition="LEFT" text="{resLocale.headerAccount}" textColor="WHITE" waves="LIGHT" ui:field="account"/>
>                 </m:MaterialNavSection>
>             </m:MaterialNavBar>
> 
>             <g:SimplePanel ui:field="menu"/>
>         </m:MaterialHeader>
> 

```
In <g:SimplePanel ui:field="menu"/> I add MenuNavBar

>     @Override
>     public void setInSlot(Object slot, IsWidget content) {
>         centerPanel.removeStyleName(AppResources.INSTANCE.style().verticalCenter());
>         if (slot == ApplicationPresenter.SLOT_MENU_CONTENT) {
>             menu.clear();
>             menu.add(content);
>         } else if (slot == ApplicationPresenter.SLOT_MAIN_CONTENT) {
>             centerPanel.clear();
>             centerPanel.add(content);
>         } else
>             super.setInSlot(slot, content);
>     }
> 

MenuViewImpl.ui.xml
```
<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder" xmlns:m="urn:import:gwt.material.design.client.ui">
    <m:MaterialSideNav ui:field="menu" m:id="menuConsole" width="300" type="PUSH" allowBodyScroll="false" alwaysShowActivator="true" showOnAttach="false" closeOnClick="true"/>
</ui:UiBinder>
```

**Comment by esocode** [comment]
This seems not to be fixed (in the snapshot). Now if I call `setAlwaysShowActivator(false)` the menu icon is never shown, even if I resize to a small browser window. If I inspect the DOM the menu button is there with the correct styles but also with a `display: none !important` attribute in the element style which causes it to be always hidden. If I remove this attribute the button behaves as expected (visible on small screens and hidden on large). I could not identify the code which adds the display: none to the button element.

**Comment by kevzlou7979** [comment]
@esocode I submitted a follow up fixed https://github.com/GwtMaterialDesign/gwt-material/commit/c4ba258aad442511677a5613c23673a4ee5af6d9, I changed the hard coded style injection to Correct one using ```HideOn``` and ```ShowOn```. Also @LeshaRB There was an issue on the navmenu condition, just checked that commit if your MVP sample will work and will be corrected.

Thanks guys. :)

**Comment by kevzlou7979** [comment]
Added some test case for validation https://github.com/GwtMaterialDesign/gwt-material/commit/8c34f28c39ae03e23ed3de06100a2a61b7eb082b

**Comment by esocode** [comment]
Yes, now the activator is shown and hidden correctly if setAlwaysShowActivator is false. But if it is set to true the activator is hidden if the browser width becomes small (i.e. the case where it should be displayed on false). Furthermore if it is false and the browser window is resized the side nav suddenly appears, perhaps at sizes where media queries become active. This is the same problem that occurs with the FIXED type SideNavs.

**Comment by esocode** [comment]
I just noticed that a FIXED type SideNav won't popup unexpectedly if it doesn't have the `fixed` CSS style set (this is also true for the CARD and MINI styles). Furthermore that is exactly the style that I need and wich I would expect: an auto-hiding side menu without push effect. But such a style cannot be selected because SideNavType doesn't have a constant for a non-fixed side nav. Should I create a feature request issue for this?

**Comment by kevzlou7979** [comment]
I will recommend for not having ```setFixed()``` in the component, because it seems to have redundant into the setType(FIXED) - I think I need to remove that API from the component.

**Comment by kevzlou7979** [comment]
Also Take note that SideNav FIXED - Overrides the Activator to be not shown on Desktop - that's what the documentation says.

**Comment by kevzlou7979** [comment]
See this line https://github.com/GwtMaterialDesign/gwt-material/blob/gwt-material-2.0-rc3/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialSideNav.java#L377 (Specific to 2.0-rc3) that we only allow alwaysShowActivator on PUSH / Card type not on FIXED type. I think what we can do is we will throw IllegalArgumentException because you can't configure a FIXED type.

**Comment by kevzlou7979** [comment]
Hi @esocode ,

Thanks for the follow up. I tried to be able to support setAlwaysShowActivator(boolean) on FIXED type.
It concluded that the adding of ```.open``` class on sidenav causes the sidenav to not close.
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/5147ef1a3d3c7ab54b4616b92a36f22cc00941a8

For your second comment , the ```setFixed(boolean)``` is an old API that's why it seems to be redundant on ```setType(FIXED)``` which causes the issue.

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/7055b42a686848675777e68c4a07f978476a7bd0

**Comment by kevzlou7979** [comment]
Also for type FIXED and alwaysShowActivator(true). We let the user customize the opening / closing event (Best for customization). See code below:

```
        sideNav.setType(SideNavType.FIXED);
        sideNav.setAlwaysShowActivator(true);
        sideNav.setCloseOnClick(true);

        sideNav.addClosingHandler(event -> {
            header.setPaddingLeft(0);
        });

        sideNav.addOpeningHandler(event -> {
            header.setPaddingLeft(sideNav.getWidth());
        });
```

**Comment by esocode** [comment]
The latest change made the behavior worse. Before, at least when I removed the `fixed` style the side nav behaved as I expected: initially hidden, didn't appear on resize, correctly closing on click, activator (set to always show = false) only visible on small screens and working correctly. Now, with or without style (and type) `fixed` the side nav appears on resize and if the width becomes small the whole page becomes completely black (at least in our app), which is only reverted if the size is increased above medium (as I would guess).

**Comment by kevzlou7979** [comment]
Can we do team viewer? It seems that you might have some config issues into your side. I can discuss you the FIXED on my side. Also whats your goal to be achieved into your app? Simple FIXED type can worked out or even any Logic

**Comment by kevzlou7979** [comment]
Well I found out that the issue on resize creating many overlay was cause by external library (Another valid issue) https://github.com/Dogfalo/materialize/pull/1865. Will try to solve this issue.

**Comment by esocode** [comment]
I just found out that the "blackening" is caused by your latest change to `applyFixedType()` (the scheduled call to `show()`). After removing that my modified subclass (without the `fixed` style= works again.

What do you think of my suggestion of an additional side nav type that doesn't have fixed style? Besides being the only full-size type that works without problems at the moment I think this is a often needed style because it is only visible if needed and doesn't modify the underlying page. The PUSH type may be similar but it shifts the underlying page and may have side effects. For example, our pages have a fixed width and the push type drags them too far left on larger windows when it is hidden.

**Comment by kevzlou7979** [comment]
Im creating a type OVERLAY which by default the sidenav is hidden and when open it will overlay on top. 
![sidenav-float](https://cloud.githubusercontent.com/assets/3138071/24450093/20164f30-14ac-11e7-9f6d-eeb711f4efca.gif)

**Comment by esocode** [comment]
Thanks, that is exactly what I meant (and need) 👍

**Comment by LeshaRB** [comment]
I found hwy menu button don't delete

For example I have
> <m:MaterialSideNav ui:field="menu" m:id="menuConsole" width="300" type="PUSH".. >

and

>         <m:MaterialHeader>
>             <m:MaterialNavBar ui:field="header" styleName="{res.style.header}" activates="menuConsole">
>                 <m:MaterialNavBrand marginLeft="60" float="LEFT" text="{resLocale.headerTitle}"/>
>                 <m:MaterialNavSection marginRight="60" float="RIGHT">
>                     <m:MaterialLink iconType="ACCOUNT_CIRCLE" iconPosition="LEFT" text="{resLocale.headerAccount}" textColor="WHITE" waves="LIGHT" ui:field="account"/>
>                 </m:MaterialNavSection>
>             </m:MaterialNavBar>
> 
>             <g:SimplePanel ui:field="menu"/>
>         </m:MaterialHeader>

When  I don't attach MaterialSideNav MaterialHeader has such structure

> <a class="button-collapse circle waves-effect waves-light center-align" data-activates="menuConsole" aria-hidden="true" style="cursor: pointer; font-size: 2.7em; width: 64px; display: none;">
> <i class="material-icons" style="cursor: pointer;">menu</i>
> </a>

After attach add class style **show-on-large** and sturcture now **MaterialSideNav#initialize**

<a class="button-collapse circle waves-effect waves-light center-align show-on-large" data-activates="menuConsole" aria-hidden="true" style="cursor: pointer; font-size: 2.7em; width: 64px; display: none;">
<i class="material-icons" style="cursor: pointer;">menu</i>
</a>

But when I detach MaterialSideNav  style **show-on-large** don't remove from MaterialHeader

**Comment by kevzlou7979** [comment]
@esocode Here's another one We can add FLOAT type:
![sidenav-float1](https://cloud.githubusercontent.com/assets/3138071/24450812/dbcfacec-14ae-11e7-809f-56ae6aa8d43b.gif)

**Comment by kevzlou7979** [comment]
@LeshaRB FYI - You can easily hide your navmenu by:

```java

@UiField MaterialNavBar navBar;

navBar.getNavMenu().setVisible(false);

```

**Comment by esocode** [comment]
What is the difference between OVERLAY and FLOAT?

**Comment by kevzlou7979** [comment]
OVERLAY - contains a grey overlay panel and it overlays on the entire page.
FLOAT - does not contain overlay panel and it only overlays on the content not on NavBar.

**Comment by esocode** [comment]
OK, then FLOAT is what I need 😄  But it's nice to have both options.

**Comment by kevzlou7979** [comment]
Yeah I am just testing it, and clean up some code then I can submit this types. I need your confirmation later then we can close this in.

**Comment by LeshaRB** [comment]
@kevzlou7979 Can it be done, automatic in MaterialSideNav. 
If you make any changes. =)

**Comment by kevzlou7979** [comment]
@esocode  Here it is the initial integration of OVERLAY & FLOAT Type
https://github.com/GwtMaterialDesign/gwt-material/commit/bee225743e64bca90b3f92adffd0078e06aca5fb

**Comment by kevzlou7979** [comment]
Also you can override the styles of the each types if you want.

**Comment by kevzlou7979** [comment]
@LeshaRB  Have you updated your GMD Dependency to 2.0-SNAPSHOT?

**Comment by esocode** [comment]
OVERLAY works as expected (almost: there is no overlay) without appearing on resize but doesn't respect `setAlwaysShowActivator(false)` - the activator is always visible. With FLOAT the activator mode is handled correctly but there is a gray overlay (shouldn't that be the case for OVERLAY?) and the menu is transparent so that only the text appears on the overlay. 

I have only tried the new files of MaterialSideNav and SideNavType because I assume the changes aren't yet in the snapshot? BTW, today I had a problem with the latest snapshot as Eclipse didn't resolve the new dependency. I'm using Gradle and on the command line it was resolved correctly. But it seemed that gradle only downloaded a new binary for the latest snapshot, not the sources and I assume that confused Eclipse. Could it be that the latest snapshot upload was incomplete?

**Comment by esocode** [comment]
If I remove `getNavMenu().setShowOn(ShowOn.SHOW_ON_LARGE)` from `applyOverlayType()` the activator is handled correctly with `setAlwaysShowActivator(false)`.

**Comment by kevzlou7979** [comment]
For the maven build - you need to wait until the travis build is finished (We have a auto deploy enabled to it). You can the snapshot here https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/ (Check for the time)

Ah yes thanks for catching that one.
Committed https://github.com/GwtMaterialDesign/gwt-material/commit/5036b4a4d6dc1d694e7672dd0d733dfdf304b7e8

**Comment by LeshaRB** [comment]
@kevzlou7979 yes I change 2.1 snap to 2.0 snap.

But It's seems float is not work propely

**Comment by kevzlou7979** [comment]
What's your issue about float?

**Comment by kevzlou7979** [comment]
@esocode It's expected on FLOAT type that on Mobile we will display a overlay panel but not in Desktop that's what the doc says.

**Comment by LeshaRB** [comment]
When type = FLOAT main widget don't change his position

![float1](https://cloud.githubusercontent.com/assets/439337/24458242/026a511c-14a1-11e7-9258-2882b082776a.png)
![float2](https://cloud.githubusercontent.com/assets/439337/24458241/02686410-14a1-11e7-8c21-1b5da20e2af5.png)

**Comment by esocode** [comment]
With mobile you mean at smaller width? Because I tested it in a desktop browser. Nonetheless the FLOAT menu was transparent, i.e. page was completely transparent gray with black text on it.

**Comment by kevzlou7979** [comment]
@esocode 

FLOAT - has attributes Transparent background (Which you can configure easily via CSS) - as I said that's the Material Design Spec (Spend some time to read MD if you want).

**Comment by kevzlou7979** [comment]
This is how you change background in css 
![image](https://cloud.githubusercontent.com/assets/3138071/24458359/4849ed30-14cb-11e7-8f73-70b6cf5c883c.png)

**Comment by LeshaRB** [comment]
In float main widhet has

```
element.style {
    padding-left: 240px;
}
```

Which don't remove

ui:field="menu" m:id="menuConsole" width="300" type="FLOAT" alwaysShowActivator="true" allowBodyScroll="true" showOnAttach="false" closeOnClick="true"/>

**Comment by kevzlou7979** [comment]
@LeshaRB 
Ok I got what you need, you want it to be automatic which is acceptable demand, added a feature here https://github.com/GwtMaterialDesign/gwt-material/commit/64165b36bc262605ebe9086841658d9582a60040.

**Comment by kevzlou7979** [comment]
![sidenav-float-issue](https://cloud.githubusercontent.com/assets/3138071/24458867/bf01c514-14cc-11e7-91fa-39c7fda7c360.gif)

**Comment by LeshaRB** [comment]
@kevzlou7979 Thank but also one small bug when FLOAT

showOnAttach="true"
MaterialSideNav - show and main widget has 

> element.style {
>     padding-left: 300px;
>     transition: all 0.2s;
> }

BUT when
showOnAttach="true"
MaterialSideNav - don't show and main widget has 

> element.style {
>     padding-left: 300px;
>     transition: all 0.2s;
> }

As a result of which left the empty field ...

**Comment by kevzlou7979** [comment]
> showOnAttach="true"
> MaterialSideNav - show and main widget has

and 

> showOnAttach="true"
> MaterialSideNav - don't show and main widget has

These statements are confusing , can elaborate it clearly, thanks

**Comment by LeshaRB** [comment]
Excuse me

In the first showOnAttach="true"
In the second showOnAttach="false"

**Comment by kevzlou7979** [comment]
Here you go I got updated the FLOAT type, thanks for catching this. https://github.com/GwtMaterialDesign/gwt-material/commit/0c4a15c3d247318008dfa0cc87bdea69b87b423c

**Comment by kevzlou7979** [comment]
Just ping if everything is ok , then we can close this issue and we can prepare a release for 2.0-rc5 end of this week. Thanks again for your tests, I'd appreciated it

**Comment by esocode** [comment]
I did some testing with 0c4a15c. Noticed the following:
* FLOAT (setAlwaysShowActivator = false): OK
* FLOAT (true): on large width behaves like PUSH, i.e. pushes the page to the right
* OVERLAY (false): OK, does not add a glass pane
* OVERLAY (true): OK, adds a glasspane (I think the use of a glass pane should be configurable)
* FIXED: pushes navbar content to the right but that may be fixable with CSS
* PUSH (false): menu appears on window resize
* PUSH (true): OK (but both PUSH variants drag indented content too far left on closing)
* CARD (false): not a card, looks like OVERLAY
* CARD (true): a card on large sizes but slightly to small (displays a scrollbar) for a menu that contains an search field; like OVERLAY on small sizes
* MINI: behaves OK (appearances not testable with my setup)

**Comment by kevzlou7979** [comment]
> FLOAT (true): on large width behaves like PUSH, i.e. pushes the page to the right

That's a request from @LeshaRB We declared all methods on protected , you can easily override it just extend the MaterialSidenav

**Comment by esocode** [comment]
But where's the difference then between FLOAT and PUSH?

**Comment by kevzlou7979** [comment]
PUSH - Pushes the whole thing 
FLOAT - Floats below the navbar and pushes the content. (As I said you can control the way you like on how it behaves).

**Comment by kevzlou7979** [comment]
I just adjusted the way it behaves on FLOAT type. See if it's ok, Thanks in advance
![float-redesign](https://cloud.githubusercontent.com/assets/3138071/24506640/c1beca08-1590-11e7-93b7-682a834ac151.gif)

**Comment by kevzlou7979** [comment]
Also @LeshaRB Please update your sidenav type to PUSH_WITH_HEADER. 
![push-with-header](https://cloud.githubusercontent.com/assets/3138071/24507437/07b8b3b4-1593-11e7-8756-76a4d9d9e72b.gif)

**Comment by kevzlou7979** [comment]
@esocode  and @LeshaRB  - We will update the name FLOAT - OVERLAY_WITH_HEADER so that it will be consistent.

FIXED
OVERLAY
OVERLAY_WITH_HEADER
PUSH
PUSH_WITH_HEADER
MINI
CARD

**Comment by kevzlou7979** [comment]
Updated https://github.com/GwtMaterialDesign/gwt-material/commit/6c89492f8eae09fd656c16f8e207fa2fa0ee52e7

**Comment by LeshaRB** [comment]
type="OVERLAY_WITH_HEADER" allowBodyScroll="true"
Then when scroll body 

We see menu border 

![over](https://cloud.githubusercontent.com/assets/439337/24547134/01af983c-1617-11e7-81a6-49717b0f24fd.png)

**Comment by LeshaRB** [comment]
6.
type="PUSH_WITH_HEADER"

For example such structure
https://github.com/GwtMaterialDesign/gwt-material-starter/blob/master/src/main/java/gwt/material/starter/client/application/ApplicationView.ui.xml

When I open SideNav
Main widget applay
padding-left: 300px;

But footer widget don't applay, so we have


![footer123](https://cloud.githubusercontent.com/assets/439337/24550776/48cb511e-1628-11e7-9cfc-e02eff3c24e9.png)

**Comment by LeshaRB** [comment]
In SideNav if text very big. It's wrap next line. Looks very awful.
I suggest change some style

```
/* Menu */
.side-nav a {
    display: flex;
    line-height: normal;
    align-items: center;
}
![menu2](https://cloud.githubusercontent.com/assets/439337/24552388/e6a66abc-162e-11e7-96c5-e65098b6b344.png)
![menu1](https://cloud.githubusercontent.com/assets/439337/24552389/e6a689ac-162e-11e7-8a73-0aa829b1dcbb.png)


```

**Comment by kevzlou7979** [comment]
> type="PUSH" & 'PUSH_WITH_HEADER'
> I open SideNav
> Then I remove widget SideNav, and main widget does not return to the old position

Solved via https://github.com/GwtMaterialDesign/gwt-material/commit/63c43f637e3c6dfe7acd2bb93dff28bfd8af3d6a

**Comment by LeshaRB** [comment]
Hello when you delete menu button from panel
You don't remove such styles

> show-on-medium-and-down show-on-large

Before
`<a class="button-collapse circle waves-effect waves-light center-align" data-activates="menuConsole" style="cursor: pointer; font-size: 2.7em; width: 64px; visibility: hidden;"><i class="material-icons" style="cursor: pointer;">menu</i></a>`
After
`<a class="button-collapse circle waves-effect waves-light center-align show-on-medium-and-down show-on-large" data-activates="menuConsole" style="cursor: pointer; font-size: 2.7em; width: 64px; visibility: hidden;"><i class="material-icons" style="cursor: pointer;">menu</i></a>`

In different type of menu you change styles for example
PUSH_WITH_HEADER

You add to header
```
 width: 100%; 
 position: fixed; 
 z-index: 999; 

```

For main widget 

`    padding-left: 0px;`

But in FIXED you don't CHANGE style header and main widget


Also FIXE don't work in 2.0 SNASHOT 04042017

**Comment by kevzlou7979** [comment]
Fixed issues on both https://github.com/GwtMaterialDesign/gwt-material/commit/9a59ce265d58024dceb706b04d83b999dc8ea87c & https://github.com/GwtMaterialDesign/gwt-material/commit/9a59ce265d58024dceb706b04d83b999dc8ea87c

**Comment by LeshaRB** [comment]
Thank you =)

**Comment by LeshaRB** [comment]
gwt-material-2.1-20170405.013945-44.jar

Don't work =((( 
Type = PUSH_WITH_HEADER
```
element.style {
    width: 100%;
    position: fixed;
    z-index: 999;
}

element.style {
    transition: 200ms;
    padding-left: 0px;
}
```

**Comment by kevzlou7979** [comment]
@LeshaRB I will just need to close this first before merging to 2.1. Now I will close now as it works on 2.0. We are ready now to release 2.0 - Major update on SideNav

**Comment by esocode** [comment]
In the latest snapshot the MaterialSideNav is completely broken. All worked well with the previous iteration but now it is even worse than before. I use DRAWER_WITH_HEADER (but tried other styles too - BTW, I think the term OVERLAY was more approriate than DRAWER) and upon starting my application the menu shortly appears (although ShowOnAttach is FALSE) and then leaves the page content pushed to the right although no push style is used. When resizing the windows the menu "wobbles" in and out until the width becomes too small in which case the whole page becomes black so that no content is visible. Furthermore the menu in and out animations are very jerky.

**Comment by kevzlou7979** [comment]
Our Team agreed to use ```DRAWER``` instead of ```OVERLAY```.
