### ISSUE TITLE
Error loading gwt-material.appspot.com

### ISSUE THREAD

**Issue by slugmandrew** [GwtMaterialDesign/gwt-material#59]
The site isn't loading at all. Happens in Chrome and Firefox. Not very useful error message:

    Uncaught TypeError: Cannot read property 'G' of undefined
    qI	@	gwt_material_design_demo-0.js:2348
    HI	@	gwt_material_design_demo-0.js:887
    MI	@	gwt_material_design_demo-0.js:549
    ET	@	gwt_material_design_demo-0.js:2666
    hH	@	gwt_material_design_demo-0.js:2666
    (anonymous function)	@	gwt_material_design_demo-0.js:817
    Vm	@	gwt_material_design_demo-0.js:745
    Ym	@	gwt_material_design_demo-0.js:931
    (anonymous function)	@	gwt_material_design_demo-0.js:2301

*Anyone else getting this?*

**Comment by anton-johansson** [comment]
Yeah, I'm getting the same.

**Comment by John-Kellner** [comment]
Yes, me too!

**Comment by stikdragon** [comment]
Likewise

**Comment by kevzlou7979** [comment]
Hi, 

Everything Looks better now, we discovered some heapSize problem on loading the Datagrid. So we removed it from the next release in order for the showcase run. We will inspect deeply why is datagrid causes heasize out of memory to be able to release it.

Regards,
GWT Material Team
