### ISSUE TITLE
MaterialNavBrand no longer implements HasText although set/getText methods exist

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#590]
The HasText interface has been removed from MaterialNavBrand although it still has the methods setText(String) and getText(). In my case this causes an incompatibility with code that uses gwt-material 1.x that checks for the HasText interface.

**Comment by BenDol** [comment]
Yes HasText tells GWT that it can only contain text, this causes a lot of issues when you want to provide more than just text inside a MaterialNavBrand widget.
