### ISSUE TITLE
MaterialWindow is not taking color overrides

### ISSUE THREAD

**Issue by payammeyer** [GwtMaterialDesign/gwt-material#591]
setToolbarColor(Color color) and setBackgroundColor(Color color) do nothing, the default color is always shown. Even in the [demo](http://gwtmaterialdesign.github.io/gwt-material-demo/#window), styled one has no green overlay on it.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/fe60e3fc08fb708a30c3b157c7a823ba578b80db.

Added Test Demo here
https://github.com/GwtMaterialDesign/gwt-material-issue-test/tree/%23591
