### ISSUE TITLE
MaterialValueBox readonly state not working

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#595]
This is caused by MaterialValueBox.setReadOnly() not invoking ValueBoxBase.setReadOnly() but only setting the style name of the widget. That is not sufficient to prevent editing in the value box.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/fe25e4976597c380e216531ee1e667b484ffb819
