### ISSUE TITLE
MaterialDatePicker with setLanguage cropping text

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material#598]
Using DatePicker with `**setLanguage(DatePickerLanguage.PL)**` system cropping button text image](https://cloud.githubusercontent.com/assets/608413/24707683/e7a23f74-1a14-11e7-8572-456670fd286c.png)

**Comment by kevzlou7979** [comment]
This is intended style behaviour for longer text on DatePicker action links. We used ellipsis to crop long texts.
