### ISSUE TITLE
MaterialDatePicker - problem with many widget

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material#599]
Using MaterialDatePicker in Errai with @Inject and @Datafiled and **`.setLanguage(DatePickerLanguage.PL);`,** system show only first configured DatePicker. When user click next field with DatePicker system didn't open. 
When remove  `.setLanguage(DatePickerLanguage.PL);` system show every DatePicker.

Now in code for every DatePicer I must addClickHandler to open.

**Comment by kevzlou7979** [comment]
Might be duplicate issue with this https://github.com/GwtMaterialDesign/gwt-material/issues/597

**Comment by kevzlou7979** [comment]
Fixed on recent loading rework of all widgets
