### ISSUE TITLE
Material Grid

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#60]
On desktop when you shrink browser window in one moment header (on the left) and rows are not aligned correctly (note arrow that points direction)

![desk](https://cloud.githubusercontent.com/assets/9980558/8781154/bef47568-2f0d-11e5-9d93-12d393e3365f.png)

On mobile it does not render correctly, it depends on direction of mobile device, two real screen shots taken from Google Nexus mobile will demonstrate the problem:

No price and actions:

![screenshot_2015-07-20-18-23-15](https://cloud.githubusercontent.com/assets/9980558/8781248/2bc0e1fe-2f0e-11e5-8b76-16bc384f5bf6.png)

Nothing at all:

![screenshot_2015-07-20-18-24-30](https://cloud.githubusercontent.com/assets/9980558/8781256/325d9af2-2f0e-11e5-8e5e-b865dd0bb790.png)

BTW, this is going to be great feature when you resolve this layout issues !

**Comment by kevzlou7979** [comment]
Ok , I spent time to fixed the css styles of the datagrid and it was success. It will be available this comming showcase site update.
