### ISSUE TITLE
MaterialDatePicker popUP

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#602]
It is only displayed above the main widget, not over the entire application
How for example Standart Popup panel
![datepicker](https://cloud.githubusercontent.com/assets/439337/24797644/d54ad7b4-1b9a-11e7-95f4-8859b5caed22.png)

**Comment by LeshaRB** [comment]
![datepicker1](https://cloud.githubusercontent.com/assets/439337/24797665/ec74a71c-1b9a-11e7-85f7-45ed2d59e5a0.png)

**Comment by kevzlou7979** [comment]
Why you use PopupPanel? GMD DatePicker is already a popup overlay which has it''s own overlay styles.

**Comment by LeshaRB** [comment]
I don't use PopupPanel, it's only example!!!!

Main widget has height 200 px
Datepicker will not fit there

**Comment by kevzlou7979** [comment]
Can you please try to create a Pull Request here https://github.com/GwtMaterialDesign/gwt-material-issue-test and put your code on it. So that it can be easily monitored and tested.

**Comment by LeshaRB** [comment]
Hello


You can quickly repeat my actions. Open the
Https://github.com/GwtMaterialDesign/gwt-material-issue-test/blob/master/src/main/resources/gwt/material/design/test/client/application/ApplicationView.ui.xml
Line 42 * <M: MaterialContainer padding = "40">* Change to *<M:
MaterialContainer padding = "40" backgroundColor = "WHITE" waves = "LIGHT"
shadow = "3">*







*С Уважением, АлексейE-Mail lesharb@gmail.com <lesharb@gmail.com>Skype
lesharbICQ 5222880*

2017-04-09 3:52 GMT+03:00 kevzlou7979 <notifications@github.com>:
