### ISSUE TITLE
MaterialTabItem indicator

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#604]
I think indicator height must be near 5px;

![ind1](https://cloud.githubusercontent.com/assets/439337/24828308/c1a59294-1c62-11e7-913e-911848b6961a.png)
![ind2](https://cloud.githubusercontent.com/assets/439337/24828309/c1a7dcca-1c62-11e7-8d7c-6fa96bdafdbc.png)

**Comment by kevzlou7979** [comment]
Hi @LeshaRB  The Material Design spec says that the height of the tab indicator must be 2px
![image](https://cloud.githubusercontent.com/assets/3138071/24829004/a7bfe56c-1c1e-11e7-9649-5be87a8fb4b4.png)

Here's the GMD implementation
![image](https://cloud.githubusercontent.com/assets/3138071/24829007/b20cb644-1c1e-11e7-9051-de96125f7dd4.png)

If you want to increase the height of your TAB just do it via CSS
Here's how you do it.

```css
.tabs .indicator {
   height: 5px !important; 
}
```
