### ISSUE TITLE
MaterialTab : getTabIndex() always returns 0

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#605]
When I want to get the index of the selected tab, getTabIndex() returns 0

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/c12bd95a5ad031eaf8148d45468d76f2cbc83d9d

Added JUnit Test https://github.com/GwtMaterialDesign/gwt-material/commit/504a212ae12e31f9deb0fd6005a00dec5318aba5
