### ISSUE TITLE
Sidenav can't hide items

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material#607]
setVisible(false) on a MaterialLink in sideNav no longer works.

See change
https://github.com/GwtMaterialDesign/gwt-material/commit/b1ebba1f3de0b193b2749d8f274870639329dc1e

display: flex !important;   overrides display: none;

**Comment by BenDol** [comment]
Yeah we should not be using ` !important` in most (if not all) of our CSS definitions http://stackoverflow.com/a/3706876 @kevzlou7979

**Comment by kevzlou7979** [comment]
@mvanrobaeys  and @BenDol Thanks for this information, Updated the fixed for the ongoing rework on sidenav https://github.com/GwtMaterialDesign/gwt-material/commit/55f1a82219db9c3ce6e63d0a5f21ef97e0ca80e0. I will monitor and update some values that needs to be updated like this.
