### ISSUE TITLE
Label color of input field

### ISSUE THREAD

**Issue by mpallesen** [GwtMaterialDesign/gwt-material#608]
Hi

Maybe i'm missing something, but i'm having trouble setting the text color on the label of a MaterialTextBox. The label field is private, so i have no way of reaching it from the code. 
Could you make it protected or make a helper method to make this possible?

/Michael

**Comment by kevzlou7979** [comment]
Hi there,

Ok I will add this api update on the current rework to have a getter for all widgets embedded into it's parent to access it and redefine some styles and behavior. You can watch the update here https://github.com/GwtMaterialDesign/gwt-material/pull/601.

Best Regards,
Kevin

**Comment by kevzlou7979** [comment]
Updated via https://github.com/GwtMaterialDesign/gwt-material/pull/601/commits/4a293d31e9a30a6db18ba309f89d10b9ce6d5f6f
