### ISSUE TITLE
Menu-subMenu with icons

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#609]
Hi, the menu has a strange behaviour (with 2.0-rc4 - Chrome 57/Firefox 52 ) when I put an icon to a sub-menu that has a father with an icon. (see the xml example attached, the bug comes out on menu "New")

[TestMenu.ui.xml.txt](https://github.com/GwtMaterialDesign/gwt-material/files/912922/TestMenu.ui.xml.txt)

**Comment by kevzlou7979** [comment]
This issue is specific to MaterialMenuBar - which the right place to post is here https://github.com/GwtMaterialDesign/gwt-material-addins/issues. I will close this and reopen into the addins for correct repository.

**Comment by kevzlou7979** [comment]
Opened ticket on addins https://github.com/GwtMaterialDesign/gwt-material-addins/issues/220
