### ISSUE TITLE
After selecting "Material Charts" no page will open correctly

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#61]
There is a problem with menu selection. To reproduce the problem do the following:

1. Select Material Charts : OK
2. Select Component - Badges : NOT OK (Header is still Material Carts but with no content)
3. Select Buttons : OK
4. Select Component - Badges again : Now is OK
5. Select Material Charts : OK
6. Select Component - Buttons or any other page : NOT OK (The same as 2.)
...

Conclusion: After selecting "Material Charts" no page will open correctly.

**Comment by slugmandrew** [comment]
I noticed this exact same behaviour. The first page load after the charts page doesn't work, it just removes the charts from the page and leaves the "Material Charts" heading there.

**Comment by slugmandrew** [comment]
This has been partly fixed but I'm leaving it open as we need to change the history management of the demo. I'll do it when I mavenize everything and each page should be  GWTP Presenter-View couplet.

**Comment by BenDol** [comment]
It is to do with the MaterialColorChart widget. Still investigating the reason.
