### ISSUE TITLE
ListBox scrollbar is not working in IE 11

### ISSUE THREAD

**Issue by dramesh123** [GwtMaterialDesign/gwt-material#610]
Dear Team,

My application ListBox component scroll bar is getting vanished when i try to drag in IE 11. But the same is working fine in firefox. Attached the behavior for your reference. Even i have observed the same issue for GWTMaterialDesign demo site in IE also.

[2017-04-11_18-28-17.zip](https://github.com/GwtMaterialDesign/gwt-material/files/914963/2017-04-11_18-28-17.zip)

Thanks
Ramesh

**Comment by kevzlou7979** [comment]
Found the duplicate issue on Materialize https://github.com/Dogfalo/materialize/issues/901. I will analyze it clearly and provide a proper fix.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/c8123bed28c1dd7e403f98f1091bd1c9b04db3cb

Manual Test
![issue-610](https://cloud.githubusercontent.com/assets/3138071/25225731/0a6f26e8-25f5-11e7-87d6-b3ee12038d26.gif)

Tested on
IE 10 / 11 / Edge, Chrome, Safari, FireFox, Opera, Mobile
