### ISSUE TITLE
MaterialComboBox getSingleValue()

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#611]
Hey guys,

I believe there is a bug in the new method getSingleValue(). Following scenario - you are trying to get a value:
```java
    public T getSingleValue() {
        List<T> values = getSelectedValue();
        if(!values.isEmpty()) {
            return values.get(0);
        }
        return null;
    }
```

you get over to:

```java
 public List<T> getSelectedValue() {
        return getValue();
    }
```
 and finally to 

```java
@Override
    public List<T> getValue() {
        if(!multiple) {
            int index = getSelectedIndex();
            if (index != -1) {
                return Collections.singletonList(values.get(index));
            }
        } else {
            return getSelectedValues();
        }
        return null;
    }
```

now I have a single selection box **without** a selected index which results in a -1 return from getSelectedIndex(). Therefore getValue() returns null, getSelectedValue() returns null and in getSingleValue() you have...

```
List<T> values = getSelectedValue(); //which is null
if(!values.isEmpty()) 
...
```

and you get an exception.

**Comment by BenDol** [comment]
Good catch, we should return an empty list. Thanks!

**Comment by kevzlou7979** [comment]
This issue has been moved to GMD Addins Repository - https://github.com/GwtMaterialDesign/gwt-material-addins/issues/223
