### ISSUE TITLE
MaterialSideNav type

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#614]
In last 2.0-SnapShot
I cann't set type

`[ERROR] Class MaterialSideNav has no appropriate setType() method: <m:MaterialSideNav allowBodyScroll='true' alwaysShowActivator='true' closeOnClick='true' m:id='menuConsole' showOnAttach='false' type='PUSH_WITH_HEADER' ui:field='menu' width='300'> (:5)`

**Comment by kevzlou7979** [comment]
Please read this https://github.com/GwtMaterialDesign/gwt-material/pull/587
