### ISSUE TITLE
Complete hang on upgrading to 2rc4

### ISSUE THREAD

**Issue by jcosmo** [GwtMaterialDesign/gwt-material#615]
I've a part time project which has been using v 1.5.0 for a while and I decided to update to 2.0 rc 4.

Whenever I start up the app I get a complete crash of the browser as it loads.  In chrome I'm unable to open the console, and if the console was open beforehand then it errors after a minute or so informing me it's lost connection to the browser.  

I'm using GWTP 1.4, Java 8, GWT 2.8.

Any hints on what I might have missed in the upgrade that is causing this would be useful, as trying to debug it is proving difficult in the absence of any means of getting logging during startup.

**Comment by kevzlou7979** [comment]
Can you please share with us your Browser Logs and also your Runtime Logs in your IDE? THanks in advance

**Comment by kevzlou7979** [comment]
Please consider to read the changelogs from 2.0-rc1 to 2.0-rc4 https://github.com/GwtMaterialDesign/gwt-material/wiki/Changelog.

**Comment by BenDol** [comment]
@jcosmo make sure you are using one of the GwtMaterialWithJQuery modules, a warning was added to help solve this issue.

**Comment by jcosmo** [comment]
Sorry - for some reason I completely missed the early responses from @kevzlou7979 to my post - apologies. There were no logs worth posting, given the browser just hung and wouldn't debug at all in IDEA.

I think I was trying to avoid the JQuery variants, so I'll give that a try - thanks @BenDol

**Comment by BenDol** [comment]
Cool, you can manually add JQuery if you have it, you just need to make sure its loaded first.
