### ISSUE TITLE
Collection type="CHECKBOX"

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material#616]
After adds `addClickHandler()` to MaterialCollectionItem, system twice call ClickEvent when user click on MaterialCheckBox.
Method `event.getSource()`  show the same source.
![collectionitem_onclick](https://cloud.githubusercontent.com/assets/608413/25129403/30789f30-243e-11e7-8505-ac251febe40d.gif)

**Comment by kevzlou7979** [comment]
I just checked the culprit is the MaterialCheckBox , I tried to reproduce using Simple - MaterialPanel then adds a checkbox, whenever I ```addClickHandler``` on MaterialPanel it seems that checkbox fires also which it calls two events. I tried Switch and Radio and luckily they behave well. We will try to figure out the root cause of this.

**Comment by kevzlou7979** [comment]
Same issue with this https://www.sencha.com/forum/showthread.php?93365-Radio-CheckBox-event-listener-onClick-fires-twice-on-label

**Comment by kevzlou7979** [comment]
@matam Can you try ```event.getNativeEvent().getEventTarget().toSource()``` if it returns different target as we expected.

**Comment by matam** [comment]
@kevzlou7979 Thx. Now I can distinguish source event. Checkbox return HTMLInputElement.

**Comment by kevzlou7979** [comment]
@matam Good to hear that :)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/604749f9236145907b425a2ef2135acc4ddf612c

Manual Test
![issue-616](https://cloud.githubusercontent.com/assets/3138071/25209597/c3a05fde-25ae-11e7-8563-4b2848034dcc.gif)

JUnit Test
https://github.com/GwtMaterialDesign/gwt-material/commit/25befa870ab49a01a8b710dfeeccb6bf083632df
