### ISSUE TITLE
Fixed SideNav still/again broken

### ISSUE THREAD

**Issue by ingosch** [GwtMaterialDesign/gwt-material#617]
Just try the Snapshot-Demo.
With large window SideNav "jumps" on every resize and DOM get's flooded with Overlay-DIVs.
https://gwtmaterialdesign.github.io/gwt-material-patterns/snapshot/#sidenav_fixed

**Comment by kevzlou7979** [comment]
Thanks for testing it, will try to solve the said issue.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/6d619b8db679aa93893441200f0045ab3241db62
