### ISSUE TITLE
tweensContainer of undefined

### ISSUE THREAD

**Issue by mvanrobaeys** [GwtMaterialDesign/gwt-material#618]
I can't reliably reproduce this, but seems to track down to velocity / jquery:

![test](https://cloud.githubusercontent.com/assets/18280223/25329532/5f9faf2c-28dc-11e7-80c7-063052edf0cb.png)

**Comment by kevzlou7979** [comment]
Can you provide the code, as we can't reproduce the issue without having a brief information. Thanks in advance.

**Comment by kevzlou7979** [comment]
What version of GWT Material are you using?

**Comment by kevzlou7979** [comment]
Related to https://github.com/Dogfalo/materialize/issues/1031

**Comment by mvanrobaeys** [comment]
Working on 2.0-SNAPSHOT from 10 days ago.  The codebase is quite extensive and I can't reproduce this issue myself.  Just some end users are reporting this problem.  If I find how to reproduce it, I will post something here.

**Comment by kevzlou7979** [comment]
Thanks @mvanrobaeys

**Comment by nauris-m** [comment]
![tweens](https://user-images.githubusercontent.com/4180797/28815591-8d72f94c-76aa-11e7-857d-414cc1fce63f.PNG)
i have noticed this also in "2.0-rc5"

**Comment by kevzlou7979** [comment]
This is I think related to https://github.com/Dogfalo/materialize/issues/1031
