### ISSUE TITLE
MaterialWidget 

### ISSUE THREAD

**Issue by matam** [GwtMaterialDesign/gwt-material#621]
After this commit https://github.com/GwtMaterialDesign/gwt-material/commit/d1e9a8f9fb1d3082d5d3bfe9ac393d0fcba9b8e7
During project compilation system shows this error

```
         [ERROR] Errors in 'jar:file: ......m2/repository/com/github/gwtmaterialdesign/gwt-material-table/1.0-SNAPSHOT/gwt-material-table-1.0-20170308.071613-135.jar!/gwt/material/design/client/ui/table/TableSubHeader.java'
            [ERROR] Line 61: Cannot reduce the visibility of the inherited method from MaterialWidget

```

**Comment by HoochSDS** [comment]
Hi 
I have the same compiler error, described by @matam on every gwt-material-table release candidate (rc3, rc4, and SNAPSHOT)
```
[INFO]       [ERROR] Errors in 'jar:file:/C:/Users/rapid/.m2/repository/com/github/gwtmaterialdesign/gwt-material-table/1.0-rc3/gwt-material-table-1.0-rc3.jar!/gwt/material/design/client/ui/table/TableSubHeader.java'
[INFO]          [ERROR] Line 61: Cannot reduce the visibility of the inherited method from MaterialWidget

```
Thank you

**Comment by kevzlou7979** [comment]
Hi there I got the issue fixed. There was just an issue with ambiguous method, it should be ```build()``` instead of ```intialize()``` on ```TableSubHeader``` 

Please update GMD , GMD Addins, GMD Table because I updated the initialize() and build() method to be in separate instances.

Best Regards,
Kevin

**Comment by kevzlou7979** [comment]
Also as for the information, https://github.com/GwtMaterialDesign/gwt-material/pull/587. We updated the versions for DataTable and JQUERy to be uniform on all GMD Projects.

Current SNAPSHOT - 2.0-SNAPSHOT
Next Release - 2.0-rc5
