### ISSUE TITLE
MaterialMasonry: initMasonry disappeared, what's the replacement?

### ISSUE THREAD

**Issue by youncta-dev** [GwtMaterialDesign/gwt-material#623]
Method initMasonry has been removed from MaterialMasonry, how can understand what's the replacement?

**Comment by kevzlou7979** [comment]
Here's the link for updated changes https://docs.google.com/spreadsheets/d/1A5tbYgDsFaUe6fq0o9JccSRYWyRgVC1hWw5A-p-amSQ/edit#gid=1508671137. Also you can call ```reinitialize()``` method if you were trying to reinitialize the masonry if you have any other initialization you can just override the ```initialize()``` method. Also please submit ADDINS issues to https://github.com/GwtMaterialDesign/gwt-material-addins/issues. Thanks for following the guidelines :)
