### ISSUE TITLE
Callback in JsMaterialElement.closeModal is never called

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material#624]
GWT 2.8.1
GwtMaterial: 2.0-rc4
Chrome: 58

Looks like callback param get lost after combining parameters with their defaults (materialize-0.97.5.js:781):

`options = $.extend(defaults, options);`

Looks like function parameters have to be wrapped in distinct object, like it is done for `openModal` - this works ok:

```
@JsMethod
public native JQueryElement closeModal(JsModalOptions options);
```

and then update call in MaterialModal like this:

```
protected void close(Element e, boolean autoClosed) {
    JsModalOptions options = new JsModalOptions();
    options.complete = () -> onNativeClose(autoClosed);
    $(e).closeModal(options);
}
```

**Comment by kevzlou7979** [comment]
I tried your solution above, But there was an issue, the event keep firing twice because of registering new JsModalOptions.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/53bc5b5c5f0a19fcf8c5ecbeeafe5db516d22e5d
