### ISSUE TITLE
Migrate from mojo to tbroyer gwt plugin.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#626]
GMD must upgrade it's gwt-maven-plugin to tbroyer https://tbroyer.github.io/gwt-maven-plugin/ Modern GWT Plugin. This could be part of GMD 2.1 and it includes also the latest GWT release 2..8.1.

**Comment by vegegoku** [comment]
i have been using tbroyer plugin for sometime so far, no issues, and it is actually very good plugin.
i even managed to make it work with vertx instead of tomcat and the codeServer with superDev mode are still working.

**Comment by kevzlou7979** [comment]
@vegegoku That's nice to hear buddy, We are also excited to migrate to this plugin.

**Comment by masterdany88** [comment]
Good Idea, but what about errai support? They are still with Mojo plugin :(

**Comment by kevzlou7979** [comment]
Maybe we can create a new demand issue to update their gwt maven plugin https://github.com/errai/errai

**Comment by masterdany88** [comment]
It will be greate, cause I've lost a lot of time to bind those two together without success. And I don't like to have shared packages with f.e. services, entities etc in client module :( bleh.
I've asked already on those forum, and stackoverflow, but no answer till now :(

- https://stackoverflow.com/questions/41875120/can-i-split-errai-maven-project-into-multimodule

- https://developer.jboss.org/thread/273754

- https://developer.jboss.org/thread/273739

**Comment by kevzlou7979** [comment]
Submitted issue to https://github.com/errai/errai/issues/252 and https://issues.jboss.org/browse/ERRAI-1040?filter=-4.

**Comment by kevzlou7979** [comment]
Got an update with Errai Team
