### ISSUE TITLE
ListBox/ MaterialComboBox there is no default null value. Always first from the list is selected.

### ISSUE THREAD

**Issue by masterdany88** [GwtMaterialDesign/gwt-material#628]
Always after adding items to empty `MaterialCompoBox` the first on from the list (with index 0) is selected, which is of course  missleading. 
I should programatically set selected value, or by ui. And before that methods like: `getSelectedValue()`,`getValue()` should return null.

**Comment by kevzlou7979** [comment]
This was already added on our TODO on 2.1 to deal with null values on any select components / other value widgets that does not support it.

**Comment by kevzlou7979** [comment]
Might be duplicate with https://github.com/GwtMaterialDesign/gwt-material-addins/issues/194
