### ISSUE TITLE
MaterialComboBox does not work with Errai Data binding

### ISSUE THREAD

**Issue by saso5** [GwtMaterialDesign/gwt-material#633]
When the setValue is called the setSelectedIndex is set

![image](https://cloud.githubusercontent.com/assets/26303578/25939094/eeb36a34-3631-11e7-800e-6be056067bb8.png)

,but getSelectedIndex does not return the set variable but reads the html instead.

![image](https://cloud.githubusercontent.com/assets/26303578/25939125/0cad6d46-3632-11e7-82df-59fe956f182c.png)

getValue return null becasue getSelectedValue() return -1.

This happens only on the initialization (postConstruct) when I set the default value. The default value must me set because there in no null/empty option.

**Comment by kevzlou7979** [comment]
I will close this one, please post issues related to addins here https://github.com/GwtMaterialDesign/gwt-material-addins

**Comment by kevzlou7979** [comment]
Placed it here https://github.com/GwtMaterialDesign/gwt-material-addins/issues/233
