### ISSUE TITLE
Canvas added to MaterialPanel inside MaterialStep drawn in a wrong coordinates 

### ISSUE THREAD

**Issue by tsatatwer** [GwtMaterialDesign/gwt-material#634]
Hi ,
I have created a canvas and added to a MaterialPanel inside MaterialStep but the canvas drawn in a wrong coordinates if I get MaterialPanel top and left and then use it with RootPanel .add(Widget w, int left, int top) then the canvas drawn in the intended coordinates  , so I am not sure if that a BUG or I miss some thing .the canvas itself work correctly .

**Comment by kevzlou7979** [comment]
Can you submit any simple project that we can test / reproduce - Thanks in advance.

**Comment by tsatatwer** [comment]
Many thanks for the fast replay and support , actually I use the MaterialStepper from the demo and just try to add a canvas created to a MaterialPanel inside MaterialStep .
I will try to post a code example soon.

**Comment by tsatatwer** [comment]
Hi ,
the code :
UiBinder  ui.xml

`<!DOCTYPE ui:UiBinder SYSTEM "http://dl.google.com/gwt/DTD/xhtml.ent">
<ui:UiBinder xmlns:ui="urn:ui:com.google.gwt.uibinder"
   xmlns:g="urn:import:com.google.gwt.user.client.ui"
	xmlns:c="urn:import:com.google.gwt.canvas.client"
	xmlns:m="urn:import:gwt.material.design.client.ui"
	xmlns:ma="urn:import:gwt.material.design.addins.client">
	
	
	<ui:style>
	.important {
		font-weight: bold;
	}
	
	 .block{
            padding: 15%;

	}
	</ui:style>
	
	
	<m:MaterialPanel width="100%" >
	<g:HTMLPanel>
	
	<m:MaterialRow>
 <m:MaterialColumn grid="s12 m6"  height="600px" padding="0" textAlign="CENTER">
  <m:MaterialPanel height="500px" width="100%" >
 <ma:stepper.MaterialStepper ui:field="stepper"  axis="HORIZONTAL" shadow="1" >
 <ma:stepper.MaterialStep step="1" title="Name of Step 1" description="Description of Step 1">
 <m:MaterialPanel  ui:field="canvasPanel"  width="100%" height="400px" addStyleNames="{style.block}" backgroundColor="GREY_LIGHTEN_2"/>
 <m:MaterialButton ui:field="btnContinue1" text="Continue to Step 2" grid="l4" marginTop="12" textColor="WHITE" waves="DEFAULT"/>
 <m:MaterialButton ui:field="btnPrev1" text="Cancel" grid="l4" marginTop="12" type="FLAT" waves="DEFAULT"/>
 </ma:stepper.MaterialStep>
 <ma:stepper.MaterialStep step="2" title="Name of Step 2" description="Description of Step 1">
 <m:MaterialPanel width="100%" addStyleNames="{style.block}" backgroundColor="GREY_LIGHTEN_2"/>
 <m:MaterialButton ui:field="btnContinue2" text="Continue to Step 3" grid="l4" marginTop="12" textColor="WHITE" waves="DEFAULT"/>
 <m:MaterialButton ui:field="btnPrev2" text="Cancel" grid="l4" marginTop="12" type="FLAT" waves="DEFAULT"/>
 </ma:stepper.MaterialStep>
 <ma:stepper.MaterialStep step="3" title="Name of Step 3" description="Description of Step 1">
 <m:MaterialPanel width="100%" addStyleNames="{style.block}" backgroundColor="GREY_LIGHTEN_2"/>
 <m:MaterialButton ui:field="btnContinue3" text="Finish" grid="l4" marginTop="12" textColor="WHITE" waves="DEFAULT"/>
 <m:MaterialButton ui:field="btnPrev3" text="Cancel" grid="l4" marginTop="12" type="FLAT" waves="DEFAULT"/>
 </ma:stepper.MaterialStep>
 </ma:stepper.MaterialStepper>
 </m:MaterialPanel>
 </m:MaterialColumn>
 
  <m:MaterialColumn>
  </m:MaterialColumn>
  </m:MaterialRow>
  
		
	</g:HTMLPanel>
	
	</m:MaterialPanel>
	
	
</ui:UiBinder> `




UiBinder CanvasStepperTest.java

`

package com.test.client;

import com.google.gwt.canvas.client.Canvas;
import google.gwt.canvas.dom.client.Context2d;
import com.google.gwt.core.client.GWT;
import com.google.gwt.event.dom.client.ClickEvent;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.uibinder.client.UiHandler;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.client.ui.Button;
import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.HasText;
import com.google.gwt.user.client.ui.Widget;

import gwt.material.design.addins.client.stepper.MaterialStepper;
import gwt.material.design.client.ui.MaterialPanel;

public class CanvasStepperTest extends Composite {

	private static CanvasStepperTestUiBinder uiBinder = GWT.create(CanvasStepperTestUiBinder.class);
	
	@UiField MaterialPanel canvasPanel;
	@UiField  MaterialStepper stepper;
	private Canvas testCanvas;
	private Context2d gc;
	

	interface CanvasStepperTestUiBinder extends UiBinder<Widget, CanvasStepperTest> {
	}

	public CanvasStepperTest() {
		 testCanvas = Canvas.createIfSupported();
		initWidget(uiBinder.createAndBindUi(this));
	}

	
	

	public CanvasStepperTest(String firstName) {
		initWidget(uiBinder.createAndBindUi(this));
		
	}
	
	
	public void initCanvas()  {
		
		 int w = canvasPanel.getOffsetWidth() ;
		 int h = canvasPanel.getOffsetHeight();
	   
	    testCanvas.setCoordinateSpaceHeight(canvasPanel.getOffsetHeight());
		testCanvas.setCoordinateSpaceWidth(canvasPanel.getOffsetWidth());
		testCanvas.setWidth(w +"px");
		testCanvas.setHeight(h +"px");
		
		gc = testCanvas.getContext2d();
		gc.setStrokeStyle("#00c853"); //(CssColor.make("#00c853"));
		gc.strokeText("Hello", 50, 50);
		
	}

	

}
`

Entry point class Test_GWT.java
`
public class Test_GWT implements EntryPoint {
	
	
	
	private final GreetingServiceAsync greetingService = GWT.create(GreetingService.class);
	
	private CanvasStepperTest canvasStepperTest;

	/**
	 * This is the entry point method.
	 */
	public void onModuleLoad() {
		
		
		canvasStepperTest = new CanvasStepperTest();
		canvasStepperTest.initCanvas();
		RootPanel.get().add(canvasStepperTest);
		
	
	}
}
`

**Comment by tsatatwer** [comment]
Hi,
here the screenshot show where the canvas(with color black background) added.
![canvas test](https://cloud.githubusercontent.com/assets/19878047/26117230/bd91abca-3a5d-11e7-9735-2e560641f1ce.jpg)

**Comment by kevzlou7979** [comment]
I think this is not a core GMD Specific, it should probably a styling issue on Canvas.

**Comment by tsatatwer** [comment]
Can you please explain more ??
When I use RootPanel  add method with MaterialPanel TOP and LEFT position the canvas is drawing correctly .

**Comment by tsatatwer** [comment]
I have added the same canvas to  GWT panels include HTMLPanel and FlowPanel the canvas is added correctly , please see screenshot below:

![canvas_gwt_panel](https://cloud.githubusercontent.com/assets/19878047/26145577/d722b80e-3ae4-11e7-9f56-9aa8505d9cb6.jpg)

**Comment by tsatatwer** [comment]
Any word on that please

**Comment by tsatatwer** [comment]
Again any comment on this issue thanks.
