### ISSUE TITLE
MaterialToast resets all existing toast ID attributes when using custom styles

### ISSUE THREAD

**Issue by mitchmartin** [GwtMaterialDesign/gwt-material#635]
If I pass a custom className to MaterialToast, the new toast ID gets applied to all existing toast elements. This in turn causes any widgets to be added to the first toast instead of to the appropriate one.

After creating the toast element, it is retrieved by Class in order to apply the ID attribute. If a custom class is provided, the generated ID is not applied to the class, therefore ALL toasts with the custom class are returned and updated: [See here](https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialToast.java#L159)

This behavior can be [viewed in the Demo](http://gwtmaterialdesign.github.io/gwt-material-demo/#dialogs) as well, by checking ID attributes of multiple created toasts in "Styling Toasts"

**Comment by kevzlou7979** [comment]
Thanks for catching this, I will review this and reproduce

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/638
