### ISSUE TITLE
Endless loop in MaterialDesignBase.onModuleLoaded() 2.0-rc5

### ISSUE THREAD

**Issue by agelun** [GwtMaterialDesign/gwt-material#636]
Everything went fine until some day I've restarted eclipse and.... Everything was broken.

I dont know exactly why – maybe some caches was cleaned or smth like that.

Loop in `onModuleLoad` cannot terminate because it calls `void injectJs(TextResource resource, boolean removeTag, boolean sourceUrl)` and every call adds one more resource in line ` futureResources.add(new FutureResource(resource, removeTag, sourceUrl));`

From Java point of view it'll cause exception (ArrayList was modified during iteration) but in GWT it silently creates endless loop.

```
    protected void onModuleLoaded() {
        if (futureResources != null) {
            for (FutureResource res : futureResources) {
                injectJs(res.resource, res.removeTag, res.sourceUrl);
            }
        }
    }
...
    public static void injectJs(TextResource resource, boolean removeTag, boolean sourceUrl) {
        if (!resource.getName().contains("jQuery") && !checkJQuery(sourceUrl)) {
            // We need to wait for jQuery to load
            if (futureResources == null) {
                futureResources = new ArrayList<>();
            }
            futureResources.add(new FutureResource(resource, removeTag, sourceUrl));
        } else {
            String text = resource.getText() + (sourceUrl ?
                "//# sourceURL=" + resource.getName() + ".js" : "");

            // Inject the script resource
            ScriptInjector.fromString(text)
                .setWindow(ScriptInjector.TOP_WINDOW)
                .setRemoveTag(removeTag)
                .inject();
        }
    }
```

**Comment by agelun** [comment]
Adding <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> to HTML's head can solve the problem because `checkJQuery(sourceUrl)` will return true

**Comment by kevzlou7979** [comment]
What specific module you import?

**Comment by ccvo** [comment]
I have exactly the same issue. It was working before. And one day, I run it again, it hang and the browser's inspector points to an endless loop at the following for-loop in the MaterialDesignBase.java:
protected void onModuleLoaded() {
        if (futureResources != null) {
            for (FutureResource res : futureResources) {
                injectJs(res.resource, res.removeTag, res.sourceUrl);
            }
        }
}

In the app.gwt.xml file, the following GMD modules are imported:
  <inherits name="gwt.material.design.GwtMaterialDesignBasic" />
  <inherits name="gwt.material.design.themes.ThemePurple"/>

Adding <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> to HTML's head does solve the issue.

**Comment by BenDol** [comment]
Can you please provide your GWT module configuration?

**Comment by BenDol** [comment]
This is actually the intended functionality. You aren't loading with GwtMaterialBasicWithJQuery meaning none of the dependencies can be loaded without jQuery. This puts the future resources into an endless loop waiting for jQuery to be loaded.

You can solve this by using GwtMaterialBasicWithJQuery or as you are doing, including jquery manually yourself.

**Comment by ccvo** [comment]
The guide here http://gwtmaterialdesign.github.io/gwt-material-demo/#themes says:
"
<inherits name="gwt.material.design.GwtMaterialDesignBasic" />
<inherits name="gwt.material.design.themes.ThemeBlue"/>
"

**Comment by BenDol** [comment]
Make sure you have cleaned your SuperDevMode cache and rebuilt. If it is still happening after that, I will need you to set up a small project to reproduce the issue as we are not able to reproduce the problem on our end. If you link me the repository I can investigate the issue.

**Comment by ccvo** [comment]
I have setup a simple project that has the issue at:
https://github.com/ccvo/gmd-sample

Running this project, we can see the following endless looping issue:
![endless_looping](https://user-images.githubusercontent.com/2313891/27207268-e22dacb4-5280-11e7-9cb4-93091e7dcd33.png)

**Comment by BenDol** [comment]
Running that project you linked I have no issues
http://i.imgur.com/2Qx5upd.png

**Comment by BenDol** [comment]
Make sure you clean your SuperDevMode cache & that all files are up
![cs-email2](https://user-images.githubusercontent.com/1935706/27208208-780d4cb4-5298-11e7-9208-f7125823da97.gif)

**Comment by ccvo** [comment]
Clean the SuperDevMode cache DOES fix the endless looping issue.
Many thanks.
------------
Not sure what is the best practices when to clear the cache.

**Comment by BenDol** [comment]
Not 100% sure what requires cache cleans also, but I find that core module changes generally require a clean to refresh it. Glad you have it working!
