### ISSUE TITLE
MaterialDatePicker ignore readOnly status

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#637]
Hi 
If you have a DatePicker in a form with a readOnly="true" or enabled="false" satus
and you move through the form with the Tab-Key, the DatePicker accept still inputs.
Using GMD 2.0-rc5
Thanks
![datepicker](https://user-images.githubusercontent.com/24357072/26871272-f155eeb4-4b72-11e7-8cd9-f05f715aefba.gif)

**Comment by kevzlou7979** [comment]
Thanks will check this out

**Comment by kevzlou7979** [comment]
We must wire up the existing Readonly API for the datepicker in ours http://amsul.ca/pickadate.js/date/#editable

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/5655d5fee8afc78756d53aa67eb8714d4056812c

**Comment by kevzlou7979** [comment]
This is a series of solution I've got https://stackoverflow.com/questions/3682812/disabling-tab-focus-on-form-elements

**Comment by kevzlou7979** [comment]
Follow up fixed https://github.com/GwtMaterialDesign/gwt-material/commit/c5f4a5bd1507f9c5573236f24c03b4897a2d59ca and Junit Test case
