### ISSUE TITLE
Customised MaterialNavBar Icon alignment

### ISSUE THREAD

**Issue by asmaalej** [GwtMaterialDesign/gwt-material#64]
Hi everybody!

As I have mentionned in the gitter gwt-material forum, I'm asking about the possibility to customize my MaterialNavBar icons alignment, so that I could place them as I want such as the burger-menu-icon that I would place it in the extreme left side.
And also the sideNav that can be hide or shown on the click of the menu-botton.
Please help me to solve these problems. thanks to all !

**Comment by asmaalej** [comment]
Hi again,
I'd like to follow up my last question to the team members to know if is it possible to fix my problem.

Thanks !

**Comment by kevzlou7979** [comment]
Please attached an image about the expected result, for better clarity

**Comment by asmaalej** [comment]
Thank you, first, for your reply, here is the reqiested image :
https://drive.google.com/file/d/0BxCFkpzqz9_rbFlPQWpRS1RYQjA/view?usp=sharing
So what I'm looking for is to have a menu button on the extreme left side that appear even if in a wide screen (not only for tablet and smartphone) just to let sideBar hide and show on its click. 

Thank you in advance

**Comment by slugmandrew** [comment]
I think this relates to #67 - by having the icons inside a container we can set the alignment. Scheduling for 1.4 release.

**Comment by kevzlou7979** [comment]
Hi I just implement what you asked on MaterialNavBar, Just add the attribute sideBar="hidden" in to your NavBar and everything will work fine.
