### ISSUE TITLE
Programmatically created Scrollspy doesn't work

### ISSUE THREAD

**Issue by dannmartens** [GwtMaterialDesign/gwt-material#642]
The demo only shows a working UI Binder example. But when I tried to use it in a dynamic application, none of it worked anymore.
Clicking a link anywhere on the Scrollspy didn't move the page to the right id. It doesn't move at all. Nothing happens.
The active classes are not changed while scrolling the page.
I'd by happy to get some hints what could be wrong, but right now I am stumped.
Has anyone got a working example? 
I tried to fix the problem with GWT APIs and I could get half of it working again, so what's missing here?

**Comment by kevzlou7979** [comment]
Please take a look at this code  it's pure java. https://github.com/GwtMaterialDesign/gwt-material-demo-errai/blob/master/src/main/java/gwt/material/demo/errai/client/page/components/ScrollspyPage.java. Can you please show us your source code, might be missing something inscluding the wiring up of the scrollspy in to your page.

**Comment by dannmartens** [comment]
So far, from the example you've provided the source code this is based on appears completely identical. Almost verbatim.
However, there is a difference in the use of the lifecycle method:
>    @Override
>    protected void onPostConstruct() {
>        super.onPostConstruct();
>        buildScrollspy();
>   }
I based my code on the buildScrollspy example in the demo application, which doesn't use the onPostConstruct callback.
I'll try to fiddle with those as well. I'll post my source code next.

**Comment by dannmartens** [comment]
I refactored the Demo application so it would populate the Scrollspy programmatically and that worked. Nothing I tried could make it work in my own application; as it was based on a very early version of GMD, I rewrote the skeleton from scratch using Demo for 2.0-rc5 and it works now. Also worth mentioning is that I wasn't using GWTP, so I wouldn't be surprised this was some lifecycle issue.
