### ISSUE TITLE
MaterialOverlay threw an exeption on close() when opened with open()

### ISSUE THREAD

**Issue by spirann** [GwtMaterialDesign/gwt-material#643]
When the MaterialOverlay is opened with "open()", no source and then no animator is applied.
But "close()" call the reverseAnimate() on the animator who has no targetElement and throw a null/undefined Exception.

**Comment by kevzlou7979** [comment]
Wrong repository, moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/241
