### ISSUE TITLE
Checkbox and Radio inputs aren't focusable

### ISSUE THREAD

**Issue by RLHawk1** [GwtMaterialDesign/gwt-material#644]
On http://materializecss.com/forms.html checkboxes and radio buttons can be focused and controlled using the keyboard by tabbing through them. However, with GWT Material, these inputs can't be focused or controlled with the keyboard, as seen at https://gwtmaterialdesign.github.io/gwt-material-demo/#forms

I'd love the ability to see the highlight around focused checkboxes and tab through and change values with the keyboard.

**Comment by kevzlou7979** [comment]
This can be enhanced on 2.1. Thanks I like the idea.

**Comment by kevzlou7979** [comment]
Supported Focusable Widgets:
- Button & Links
- Checkbox, Switch, Radio Buttons
- Chips
- Collections and Collapsibles
- Fields, ListBox & Pickers
- Tabs & Breadcrumbs
- Range

**Comment by kevzlou7979** [comment]
![advance-search-2](https://user-images.githubusercontent.com/3138071/90089745-c1678600-dd54-11ea-96af-cbceb8286042.gif)

**Comment by kevzlou7979** [comment]
![radio](https://user-images.githubusercontent.com/3138071/90089963-59656f80-dd55-11ea-9943-ced2b23c3d83.gif)

**Comment by kevzlou7979** [comment]
![switch](https://user-images.githubusercontent.com/3138071/90090011-79952e80-dd55-11ea-9d2c-2ecc0923c705.gif)

**Comment by kevzlou7979** [comment]
![buttons](https://user-images.githubusercontent.com/3138071/90090041-916cb280-dd55-11ea-948c-a252213240a8.gif)

**Comment by kevzlou7979** [comment]
![tabs](https://user-images.githubusercontent.com/3138071/90200638-19f95a80-de0b-11ea-8886-78b65d7d3978.gif)

**Comment by kevzlou7979** [comment]
![focus-tab](https://user-images.githubusercontent.com/3138071/91015057-193ba200-e61d-11ea-85ad-3844e66af152.gif)
![focus-button](https://user-images.githubusercontent.com/3138071/91015062-1b056580-e61d-11ea-8f9c-1e079e7312bb.gif)

**Comment by kevzlou7979** [comment]
![side-1](https://user-images.githubusercontent.com/3138071/91110312-03c38800-e6b0-11ea-8946-c40ae7c79da6.gif)

**Comment by kevzlou7979** [comment]
![collapsible](https://user-images.githubusercontent.com/3138071/91113354-fca07800-e6b7-11ea-9ccc-6680c869aa8d.gif)

**Comment by kevzlou7979** [comment]
![collection](https://user-images.githubusercontent.com/3138071/91113399-1346cf00-e6b8-11ea-8a11-1a5b6fb10502.gif)

**Comment by kevzlou7979** [comment]
We can now close this and check https://github.com/GwtMaterialDesign/gwt-material/pull/972 for status updates.
