### ISSUE TITLE
Upgrade all module to GWT 2.8.1 instead of GWT 2.8.0

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#648]
@kevzlou7979 Elemental 2 work correctly only with GWT 2.8.1 while GMD is using GWT 2.8.0, GMD should upgrade the GWT version to allow the use of elemental2, upgrading to GWT 2.8.1 should have impact to the existing code.

**Comment by kevzlou7979** [comment]
Hi @vegegoku Once Errai will upgrade there GWT version to 2.8.1 - then we will start migrating all GMD Projects to 2.8.1

https://github.com/errai/errai/blob/master/pom.xml#L279

**Comment by vegegoku** [comment]
Hi @kevzlou7979 does this mean the next GMD will use errai instead of widgets?

**Comment by kevzlou7979** [comment]
No we still love Widgets, This could be updated on 2.0-rc6

**Comment by kevzlou7979** [comment]
Update GMD Modules GWT Version to 2.8.1
- GMD - https://github.com/GwtMaterialDesign/gwt-material/commit/5dbacb1a79222dbb400f5e0c7305f71bf0d23e7e

- JQuery - https://github.com/GwtMaterialDesign/gwt-material-jquery/commit/955a78a12452672d5691d14396a326210bdc435f

- Addins  -https://github.com/GwtMaterialDesign/gwt-material-addins/commit/91874245f6d399aee50f38ba9678f907a9dcb2ca

- Themes - https://github.com/GwtMaterialDesign/gwt-material-themes/commit/a371dbc8f5e2fb82959c09dc7497b7a45d8f1985

- Table - https://github.com/GwtMaterialDesign/gwt-material-table/commit/9cd00583492a27ff94fbdf65fcd131946be6709e
