### ISSUE TITLE
MaterialCollapsible expandable type broken

### ISSUE THREAD

**Issue by Dramur** [GwtMaterialDesign/gwt-material#662]
It is impossible to open more then one item when accordion is set to false.
It doesn´t matter if I set accordion in the xml or in java.

The html has the right attribute `data-collapsible="expandable"` but it doesn´t behave like it should.

The problem is also in the show case 2.0 and 2.1

**Comment by kevzlou7979** [comment]
I can confirm this at the demo showcase, thanks for the catch

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/fd2522f989cb04b977e7caffd0424753b4aed095
