### ISSUE TITLE
MaterialTab: missing initialization on later addition of tabs

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#664]
The initialization of MaterialTab is only performed once. If tab widgets are added later they will not be initialized correctly. Furthermore the `reinitialize()` method cannot be used for this purpose as it omits the event handler setup that is done in `initialize()`. It would be better to invoke the initialization code in an  overloaded `add(Widget)` method so that each time a tab widget is added it is initialized correctly.

**Comment by kevzlou7979** [comment]
- [ ] Add Documentation on GMD Demo
- [ ] Add JUnit Test - try to implement the Selenium Test (Will be nice)
- [ ] Perform Manual Test

**Comment by kevzlou7979** [comment]
![test](https://user-images.githubusercontent.com/3138071/29316256-df77dae6-81f9-11e7-92a0-3c21ffc12da5.gif)
