### ISSUE TITLE
showcase phonegap apk - menu scrolling act's weird

### ISSUE THREAD

**Issue by kaefert** [GwtMaterialDesign/gwt-material#667]
Hey there, 

I installed your Phonegap Android app on my Android 7.1.2 device.
The menu button seems to work only on every second click.
When trying to scroll the menu sometimes the content scrolls instead. And when the scrolling of the menu does work as soon as you hit one end the content starts scrolling again

**Comment by kevzlou7979** [comment]
Hi @kaefert - we are planning to use PWA instead of Phonegap in the future. As it will be more reliable, fast and engaging https://github.com/GwtMaterialDesign/gwt-material/issues/656.

**Comment by kevzlou7979** [comment]
Also what version of GMD have you installed on Phonegap?

**Comment by kaefert** [comment]
your showcase references an apk download:
http://gwt-material.appspot.com/bin/gwtmaterial.apk

I downloaded and installed this apk.

**Comment by kevzlou7979** [comment]
ah well I think that is old GMD Version, well we might change that though, either upgrade the GMD Version from 1.x to 2.x but on 2.1 we will support Progressive web app over it.

**Comment by kaefert** [comment]
yes the progressive web app support is one of the features that brought me to take a closer look at your library ;)

You should adapt the showcase either to remove the apk reference or to at least state that the PWA approach is the preferred one and phone-gap kind of deprecated.

though the one big advantage of the phone-gap approach is that you as the developer / designer can decide when you want to ask the user to install. with PWA you have to hope chrome thinks it's a good idea to show the install banner (subject to change..?)

**Comment by kevzlou7979** [comment]
Yeah logged the issue of replacing Phonegap with PWA https://github.com/GwtMaterialDesign/gwt-material-demo/issues/68. But still it will be under discussion if we support both. Also maybe we could just update the Phonegap APK file for 2.0. 

We are still hammering the GMD 2.0 for stability phase and will ping the community soon about its official release.
