### ISSUE TITLE
Help regarding use of custom css classes in attributes such as indicatorColor, textColor, backgroundColor

### ISSUE THREAD

**Issue by ichigo92** [GwtMaterialDesign/gwt-material#672]
Hi, 
I have just migrated my application from 1.5 to 2.0 rc-6. In 1.5 i was able to add my custom css classes in attributes such as indicatorColor, textColor etc. but now it can not parse custom css classes.

`[ERROR] Cannot parse value: "BoothbyBlue" as type gwt.material.design.client.constants.Color:<m:MaterialTab addStyleNames='self-end {style.fixed-size}' backgroundColor='WHITE' indicatorColor='BoothbyBlue' ui:field='tabs'> (:38)`

`<m:MaterialTab ui:field="tabs" backgroundColor="WHITE" indicatorColor="BoothbyBlue" addStyleNames="self-end {style.fixed-size}"  >`

How can i add my custom css class or color hex value in these attributes which require Color type?

**Comment by kevzlou7979** [comment]
On GMD the Color.class has its default pallete selection of colors for MD Spec, which indicatorColor takes Color class as parameter, the only way to define it is thru Css. But I think you can extend Color class then try to add your predefined color scheme there.
