### ISSUE TITLE
Visual bug when using MaterialPopupMenu, MaterialLink, MaterialDropDown.

### ISSUE THREAD

**Issue by mtmmtm9** [GwtMaterialDesign/gwt-material#674]
I have used these classes in materialize-GWT: MaterialPopupMenu, MaterialLink, MaterialDropDown.
I looks a bit weird when scrolling the items to the right. Is this supposed to work (I mean combining these classes) ?
I use version 2.0-rc6.
<img width="591" alt="skarmavbild 2017-08-20 kl 13 23 54" src="https://user-images.githubusercontent.com/19796957/29494613-5d0688e2-85ae-11e7-940f-237d5fddf8d3.png">

**Comment by kevzlou7979** [comment]
I suggest you might use [Menu Bar](https://gwtmaterialdesign.github.io/gwt-material-demo/#menubar) a wrapper for dropdown combinations.

**Comment by mtmmtm9** [comment]
Thank you. I will try that solution ;)
