### ISSUE TITLE
Problems showing cards on M$ Edge

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#675]
Hi, with 2.8 and 2.8.1 i have this issue con with cards using Microsoft Edge 25/ Edge HTML 13.
See the animated gif.

![issue_cards](https://user-images.githubusercontent.com/13817916/29509627-314385a6-8659-11e7-8bc8-9d0432d34abb.gif)

**Comment by kevzlou7979** [comment]
Related http://community.powerbi.com/t5/Service/Images-not-showing-on-Microsoft-Edge-but-showing-in-Chrome/td-p/139571

**Comment by kevzlou7979** [comment]
Been drilling this couple of weeks ago, and found out that the images are in ` webp ` format, on the 2.1 - we created a support for webp types using the new addin ``` MaterialWebpImage ``` and have a fallback when browser doesnt support it.
