### ISSUE TITLE
Filling/Showing MaterialListBox with many items is really slow

### ISSUE THREAD

**Issue by moschkom** [GwtMaterialDesign/gwt-material#678]
I have a MaterialListBox with around 100 items. When I open the view where my MaterialListBox is placed it takes up to three seconds until it is loaded (on a tablet it takes up to 10 seconds to load this view). When I activate the old-style mode on the MaterialListBox it works like a charme.

As far I can see the problem is that every call to addItem() triggers a reinitialize of the dropdown component. Further the reinitialization seems to happen when the MaterialListBox widget is already populated and the view is about to be shown (onLoad).

Find attached an extract of the performance profiling I did with Chrome. You can see that t.fn.material_select is called over and over again.
![developer tools - http --127 0 0 1 8888-index html_001](https://user-images.githubusercontent.com/10659482/29557731-4df0818c-872a-11e7-9204-290737c08016.png)

**Comment by kevzlou7979** [comment]
Please feel free to submit free Pull Request for the enhancement. Also these are the guidelines to do so 

- [Contributing](https://github.com/GwtMaterialDesign/gwt-material/wiki/Contributing)
- [Submit Test](https://github.com/GwtMaterialDesign/gwt-material/wiki/How-do-I-submit-a-test-case-on-GMD%3F)

**Comment by kevzlou7979** [comment]
On the current rework, we added an api 
```
 /**
     * Adds an item to the list box. This method has the same effect as
     * <pre>addItem(item, item)</pre>
     *
     * @param value  the item's value, to be submitted if it is part of a
     *              {@link FormPanel}; cannot be <code>null</code>
     * @param reload perform a 'material select' reload to update the DOM.
     */
     public void taddItem(T value, boolean reload)
```
Then you can just lazy load it by this call
```

for (Item item : items) {
    listbox.addItem(item, false); // turn off auto reload
}
listbox.reload();

```

**Comment by moschkom** [comment]
Thanks a lot.
