### ISSUE TITLE
ComboBox in popup window

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#679]
Hi, with Microsoft Edge I have this issue when I'm opening a popup window that contains a ComboBox.
See the attached animation.
![cb_edge_issue](https://user-images.githubusercontent.com/13817916/29611016-4dd60618-87fc-11e7-81d0-2d8a4c2d0436.gif)

**Comment by rmraya** [comment]
Works fine on latest version of Edge. Tested in snapshot demo and it is OK.

**Comment by kevzlou7979** [comment]
OK we can now close this issue. @rmraya Thanks for testing this out. I will double check this also.
