### ISSUE TITLE
RotateIn animation issue with Microsoft Edge

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#680]
The animantion "rotatein" doesn't work properly on Mircrosoft Edge.

See the below the behaviour:

![edge_rotatein_issue](https://user-images.githubusercontent.com/13817916/29612489-d8b10486-8801-11e7-8c46-3c5b92bcb02d.gif)

**Comment by kevzlou7979** [comment]
This should be probably an [animate.css](https://daneden.github.io/animate.css/)  bug.

**Comment by rmraya** [comment]
Works fine on latest version of Edge. Tested with snapshot demo and it is OK.

**Comment by kevzlou7979** [comment]
Tested it and it works fine in Edge 11
