### ISSUE TITLE
MaterialChip - Tooltip will not disappear when chip is removed thru icon

### ISSUE THREAD

**Issue by meiao** [GwtMaterialDesign/gwt-material#682]
Clicking on a chip's icon will make that chip disappear. However if that chip had a tooltip, the tooltip will not be dismissed.

```
MaterialChip chip = new MaterialChip();
chip.setText("My Name");
chip.setTooltip("my@email.com");
chip.setTooltipPosition(Position.BOTTOM);
chip.setIconType(IconType.CLOSE);
```

This maybe because the Materialize code that removes the chip does not allow GWT to properly clean it up before removing.

One workaround is to add your own click handler:
```
chip.getIcon().addClickHandler(event -> chip.removeFromParent());
```

**Comment by kevzlou7979** [comment]
The close icon needs to be standardized even the CloseHandler should be put inside the Chip Component.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/e3c0c73ef52837f4c7d9d2926b733349b9c8e0c1
