### ISSUE TITLE
MaterialDatePicker - after setValue is called, it is impossible to go to a blank state

### ISSUE THREAD

**Issue by meiao** [GwtMaterialDesign/gwt-material#683]
In my single page application I have a form that is used for both creating and editing an entity.
It has a date picker that should default for blank when creating an entity, or to the value already saved on the entity when editing.

The edit code calls:
```
  datePicker.setValue(aDate);
```
when preparing the page for creating, I tried calling all of
```
  datePicker.clear();
  datePicker.clearValues();
  datePicker.setValue(null);
```
and any call will revert the value to the value set on edit.
Even if I use the picker to set a different date then call any of those methods, the value is still the one that was set while editing.

**Comment by meiao** [comment]
It looks like that `this.date` is set on MaterialDatePicker#setValue(Date, boolean) when the Date received it is not null.
But it is never set to null neither when setValue is called passing null nor when clearValues is called.

Adding
```
  this.date = null;
```
to either
- MaterialDatePicker#setValue(Date, boolean) when Date is null or;
- MaterialDatePicker#clearValues()
seems to do the trick.

**Comment by kevzlou7979** [comment]
MaterialDatePicker#clearValues() should be the correct place to set the datepicker value to null.
Will submit a patch on the current rework.
