### ISSUE TITLE
belowOrigin and constrainWidth don't work in MaterialDropDown

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material#694]
MaterialDropDown does not honor these properties: belowOrigin="true" constrainWidth="false"

You can test this issue at https://dev.maxprograms.com/TestCase/ clicking on "Settings"

Java source and UiBinder XML are available on the page.

**Comment by kevzlou7979** [comment]
Tested  mine but it seems its working fine on latest snapshot.
![image](https://user-images.githubusercontent.com/3138071/31648177-e2db40a8-b33e-11e7-86b7-4c369599da65.png)
