### ISSUE TITLE
Inverted order of parameters in MaterialListValueBox#addItem

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#695]
The docs suggests that text goes first, value second. Yet when you do that your user gets a list of keys instead of a list of user friendly text values.

What you want:
![ok](https://user-images.githubusercontent.com/6112450/30775673-1b2459ee-a099-11e7-961a-f776c24962f4.png)

What you get instead:
![fail](https://user-images.githubusercontent.com/6112450/30775668-0ffa9e8e-a099-11e7-954e-b97ce41b7199.png)

Look at the body of gwt.material.design.client.ui.**MaterialListValueBox#addItem**(T, java.lang.String)
```
    /**
     * Adds an item to the list box, specifying an initial value for the item.
     *
     * @param item  the text of the item to be added
     * @param value the item's value, to be submitted if it is part of a
     *              {@link FormPanel}; cannot be <code>null</code>
     */
    public void addItem(T item, String value) {
        values.add(item);
        listBox.addItem(value, keyFactory.generateKey(item)); 
        reinitialize();
    }

```
The first line of MaterialListValueBox#addItem already seems wrong. An item goes into values?
And when you look into the addItem method of the underlying ListBox you will find out it expects <text, key>, we are sending <key, text>

The other (2+ arguments) versions of the MaterialListValueBox#addItem seem to suffer from the same.

**Comment by kevzlou7979** [comment]
Yeah we need to edit the Java Doc for this it must be
