### ISSUE TITLE
MaterialCard - reveal content not working (css?) (tested on firefox)

### ISSUE THREAD

**Issue by akubasa** [GwtMaterialDesign/gwt-material#7]
revealed:
![unbenannt1](https://cloud.githubusercontent.com/assets/6769786/7217237/f9345160-e61c-11e4-9f40-5da290aa5f44.PNG)

unrevealed:
![unbenannt](https://cloud.githubusercontent.com/assets/6769786/7217236/f9322444-e61c-11e4-8323-8f4812bca8c3.PNG)

SOLUTION: adding  
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;

to the .card .card-reveal css class does the trick.

in materialize.css version 15.5 this card-reveal class looks :

 .card .card-reveal {
    padding: 20px;
    position: absolute;
    background-color: #FFF;
    width: 100%;
    overflow-y: auto;
    top: 100%;
    height: 100%;
    z-index: 1;
    display: none; }

**Comment by kevzlou7979** [comment]
This one is solved on the current release 1.3.1
