### ISSUE TITLE
Material Chips

### ISSUE THREAD

**Issue by slugmandrew** [GwtMaterialDesign/gwt-material#70]

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/9002035/ebc9a898-3713-11e5-8b4a-1cf97739aab8.png)

This is what I have developed about Material chips.

**Comment by kevzlou7979** [comment]
They are all, Closed Chip. Open Chips is an advanced feature with the combination of Material Autocomplete and Material Chips itself. Take a look at this https://www.google.com/design/spec/components/chips.html#

**Comment by remarkNS** [comment]
Looking great, I am looking forward to see this in the demo. 
BTW its over quota again. 
I think we should open one ticket to discuss other options for the demo deployment.

https://pages.github.com ?
https://www.openshift.com ?

**Comment by kevzlou7979** [comment]
Yes we have discussion with @fmax32  about the redeployment of the showcase to other Cloud Hosts like https://www.heroku.com/ but @ first we need first to make the Showcase app mavenized.

But we will update as soon as possible about the quota issue.

Regards

**Comment by slugmandrew** [comment]
Those Chips looks awesome
