### ISSUE TITLE
MaterialListValueBox addItem functions twist parameters

### ISSUE THREAD

**Issue by ingosch** [GwtMaterialDesign/gwt-material#701]
Signature of addItem functions of MaterialListValueBox and GWT ListBox are equal, but in MaterialListValueBox the item and value parameters get twisted, so in the underlying GWT ListBox item is used as value and value is used as item.

```
    public void addItem(T item, String value) {
        values.add(item);
        listBox.addItem(value, keyFactory.generateKey(item));
        reinitialize();
    }
```
```
    public void addItem(T item, Direction dir, String value) {
        values.add(item);
        listBox.addItem(value, dir, keyFactory.generateKey(item));
        reinitialize();
    }
```

**Comment by kevzlou7979** [comment]
This was already done on the current rework

**Comment by kevzlou7979** [comment]
Related commit https://github.com/GwtMaterialDesign/gwt-material/pull/697/commits/a7423b6f8abde375754db22c150fc0239f4a9e53

**Comment by ingosch** [comment]
Thx!
Sry, I should have checked the closed issues first and I also didn't recognize there's a rework branch with the latest commits at all.

**Comment by kevzlou7979** [comment]
No problem, be sure to watch this repository and also the pull requests as we are updating it each day for the new features. https://github.com/GwtMaterialDesign/gwt-material/pulls
