### ISSUE TITLE
Default MaterialChipProvider use suggetion text instead of selection text

### ISSUE THREAD

**Issue by rlagoue** [GwtMaterialDesign/gwt-material#702]
Hi all, 

By the default implementation of MaterialChipProvider (DefaultMaterialChipProvider) use the method com.google.gwt.user.client.ui.SuggestOracle.Suggestion.getDisplayString() to get the text to put into the Chip. 

According to the javadoc coming from com.google.gwt.user.client.ui.SuggestOracle.Suggestion.getDisplayString(), the selection text should be the value returned by com.google.gwt.user.client.ui.SuggestOracle.Suggestion.getReplacementString()

Our company could provide the fix if possible

BR
Rodrigue

**Comment by kevzlou7979** [comment]
@rlagoue We welcome any Pull Request and we will review it.

**Comment by kevzlou7979** [comment]
This should be ported to GMD Addins as this is related addins issue.
https://github.com/GwtMaterialDesign/gwt-material-addins/issues/271
