### ISSUE TITLE
NO DEVELOPMENT , IS THE PROJECT STALLED???

### ISSUE THREAD

**Issue by two10** [GwtMaterialDesign/gwt-material#703]

**Comment by kevzlou7979** [comment]
What do you mean by no development, fyi we are having a rework done in the snapshot. so you must check it. Please be advice also to be friendly you have CAPS on your title.

**Comment by two10** [comment]
Thanks , will keep in mind  regarding the caps :)

Really like your project.

**Comment by kevzlou7979** [comment]
Subscribe to this pull request, note that in github you can subscribe the pr (2.0-release) to see every day development. We are near on closing the pr probably this weekend to open the community testing with the release of 2.0-rc7. https://github.com/GwtMaterialDesign/gwt-material/pull/655
