### ISSUE TITLE
MaterialDropDown IllegalStateException on GWTP

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#706]
Hi, on a GWTP-Application l load the DropDown-List from the DB into the MaterialDropDown like this.

Presenter:
```
  @Override
  protected void onBind() {
      super.onBind();
  
      dispatcher.execute(ptableService.getList(), new AsyncCallback<List<PbaseDTO>>() {
          @Override
          public void onFailure(Throwable caught) {
          }

          @Override
          public void onSuccess(List<PbaseDTO> result) {
              getView().setupList(result);
          }
       });
  }
```

View:
```
  @Override
  public void setupList(List<PbaseDTO> result) {
      for (PbaseDTO s : result) {
          MaterialLink ml = new MaterialLink(s.getText());
          dropDownList.add(ml);
      }
  }
```

UI:
```
  <m:MaterialIcon ui:field="btnDropDown" iconType="ARROW_DROP_DOWN" iconSize="SMALL" activates="dp-4" 
                              marginTop="30" iconPosition="LEFT" hideOn="HIDE_ON_MED_DOWN"/>
  <m:MaterialDropDown ui:field="dropDownList" activator="dp-4" constrainWidth="false" marginTop="62"/>
```
Now I'm facing this 
Exception:
```
There is no activator element with id: 'dp-4' in the DOM, cannot instantiate MaterialDropDown without a data-activates.
>Exception: java.lang.IllegalStateException
  Error: java.lang.IllegalStateException
    at TEg_g$.Hj_g$ [as createError_0_g$] (App-0.js:5516:10)
    at TEg_g$.Rj_g$ [as initializeBackingError_0_g$] (App-0.js:5571:43)
    at TEg_g$.yj_g$ (App-0.js:5404:8)
    at TEg_g$.ck_g$ (App-0.js:5652:9)
    ...
    ...
    ...
```
On the previous versions it was no problem.
Using Snapshot gwt-material-2.0-20171015.002523-448.jar

Thanks

**Comment by kevzlou7979** [comment]
Ok thanks we will test this out and patch on the 2.0-SNAPSHOT

**Comment by kevzlou7979** [comment]
I tested it the perfect place to populate your dropdown is on ``` onReveal() ``` lifecycle on GWTP.

**Comment by HoochSDS** [comment]
Hi, thank you for checking out this issue.

But l want to load the DropDown-List only once. That's why l have to place it in onBind().
[GWTP:Lifecyle](https://dev.arcbees.com/gwtp/core/presenters/lifecycle.html)
If a place it onReveal() every time l navigate back to the "place" the DropDown-List is loaded again. 
Ok, l can prevent this with a flag but l think this is not the best way.
Thanks

**Comment by kevzlou7979** [comment]
On the latest update, we handle already the onload / unload structure, I just reviewed and tested the GWTP lifecycle, it seems that when ``` onBind ``` had been called the widget is not yet attached which causes your issue.  The good implementation is that add items on onReveal() then clear them onHide()

**Comment by HoochSDS** [comment]
Feedback:

First: 
The Exception: java.lang.IllegalStateException has nothing to do with the GWTP-lifecycle onBind() or onReveal()
The Exception thrown in the View-Module at initWidget(binder.createAndBindUi(this))
```
  @Inject
  TestTab1View(Binder binder) {
    initWidget(binder.createAndBindUi(this));
  }
```
Second: 
I did some simple test with only one dropdown Widget. But I couldn't reproduce this Exception.

Third:
I went back to my main-application and I add Attribute after Attribute to the MaterialDropDown-Widget.
```
 <m:MaterialDropDown activator="dp-4" ui:field="dropDownList" marginTop="62" hideOn="HIDE_ON_MED_DOWN"
                     constrainWidth="false" enabled="true"/>
```
Fourth:
Every time I add the `enabled` Attribute the Exception is thrown. If I remove the `enabled `Attribute everything is good.

It confuses me that I could not prove the mistake in the simple test configuration.

Thanks

**Comment by BenDol** [comment]
@kevzlou7979 there is an issue with setEnabled in MaterialDropDown, its not checking if we are are attached or if we have a parent before calling `reload` and `parent.setEnabled(...)`:

```java
@Override
public void setEnabled(boolean enabled) {
    super.setEnabled(enabled);

    if(isAttached()) {
        Widget parent = getParent();
        if (parent != null && parent instanceof HasEnabled) {
            ((HasEnabled) parent).setEnabled(isEnabled());
        }
        reload();
    }
}
```
Should be like so.

**Comment by kevzlou7979** [comment]
This has been patched at recent snapshot Thanks @BenDol
