### ISSUE TITLE
AutoClose blocks month change in MaterialDatePicker

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material#708]
It is not possible to change month when autoClose is set to true in a MaterialDatePicker.

When you click on the arrows that switch to previous next month, the picker closes and no date is selected.

You can verify this in current demo, https://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#pickers

**Comment by kevzlou7979** [comment]
Thanks for catching this, we need a selenium test in order to test this with internal picker navigation. 
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/712/commits/40c1239cbe7461cbf3b7009838e53e8400ab6f81
