### ISSUE TITLE
MaterialDatePicker setDateMax()

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#713]
Hey,

seems like there is another issue like #707 and #705 but this time with setDateMax and setDateMin.

I made sure that I'm using the current version by cleaning out the repo.

Calling the methods results in...

```
Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'set' of undefined
ConsoleLogger.java:32 TypeError: Cannot read property 'set' of undefined
    at vsh_g$.Bth_g$ [as setDateMax_0_g$] (MaterialDatePicker.java:253)
    ...
```

thx and kr

**Comment by kevzlou7979** [comment]
We cannot reproduce this issue to our side. Here is a Unit Test we've created to stabilize the loading mechanism done in 2.0-rc7. https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/test/java/gwt/material/design/client/ui/MaterialDatePickerTest.java#L252.

**Comment by simerlec** [comment]
Thanks for the fast reply - I'll look for faults on my side.

Just to be sure - I'm on the 2.0-SNAPSHOT.

**Comment by simerlec** [comment]
Seems I have found the issue - I had the setter inside a scheduler block which caused the issue.

```
Scheduler.get().scheduleDeferred(new Command() {
            @Override
            public void execute() {
                //date setup stuff was called in here...
            }
        });
```

**Comment by kevzlou7979** [comment]
Why do you need to wrap an scheduler to set the datepicker , this seems causing the issue.

**Comment by simerlec** [comment]
I don't - seems this was a remnant from an earlier stage of development. But up until now the setup inside the scheduler has not caused issues so no one recognized the "problem".

**Comment by kevzlou7979** [comment]
Removing the scheduler works onto your side? This ticket also will help the user if they have the same issue.

**Comment by simerlec** [comment]
Yes, if I do the setup outside of the scheduler everything seems to work fine.
