### ISSUE TITLE
MaterialTab.selectTab(String) is not updating tabIndex

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#716]
After I use MaterialTab.selectTab(String), MaterialTab.getTabIndex() returns the index of the previously selected tab.

**Comment by kevzlou7979** [comment]
Nice catch, im working this now thanks.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/718db10eef9ba689704e4d853dbdb133bad65ea0
