### ISSUE TITLE
MaterialTabItem.setActive(boolean) not working

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#717]
MaterialTabItem.setActive(boolean) is settings the css classes on MaterialBodyItems but is not setting the display styles. It seems like the call to MaterialTab.initCollapsible(), used in MaterialTab.setActive(int), is missing.

**Comment by kevzlou7979** [comment]
Ok will take a look on this

**Comment by kevzlou7979** [comment]
@pfacmf There is no ```MaterialTabItem#setActive(boolean)``` in MaterialTab components. Please verify this. Also what versions of GMD Are you using?

**Comment by kevzlou7979** [comment]
I checked MaterialTabItem 1.x there was no method setActive(boolean) https://github.com/GwtMaterialDesign/gwt-material/blob/release_1.6.2/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialTabItem.java

**Comment by kevzlou7979** [comment]
I just checked MaterialTabItem on 1.x but there was no method for setActive(boolean) 
Reference: https://github.com/GwtMaterialDesign/gwt-material/blob/release_1.6.2/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialTabItem.java

**Comment by pfacmf** [comment]
I'm very sorry about this. The issue is with MaterialCollapsible. I will file a new issue. I'm very sorry again.
