### ISSUE TITLE
Expanding collapsible from code break the inputs

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#718]
If I use MaterialCollapsible.setActive(int) or MaterialCollapsibleItem.expand() the inputs from them are broken, the label is overlapping the value.

![brokeninput](https://user-images.githubusercontent.com/4210304/31947135-48bd7bc8-b8dc-11e7-8cf9-c763907d273c.png)

**Comment by kevzlou7979** [comment]
Thanks this might be a css style issue inside the collapsible item.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/b807feb766dbaf32c46d1bbd70c19e249de0144c
