### ISSUE TITLE
MaterialCollapsibleItem.setActive(boolean) not working

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#719]
MaterialCollapsibleItem.setActive(boolean) is settings the css classes on MaterialCollapsibleBody but is not setting the display style. The collapsible item is not expanding because of this. I am using GMD 2.0-rc6

**Comment by kevzlou7979** [comment]
Thanks for clearing the information for https://github.com/GwtMaterialDesign/gwt-material/issues/717.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/3dc64db7e85c79cd0e7c615395215429728a6210 and updated unit test.
