### ISSUE TITLE
Integrate Material Chips with Material Autocomplete

### ISSUE THREAD

**Issue by slugmandrew** [GwtMaterialDesign/gwt-material#72]
Dependent on #69 and #70 being implemented first

**Comment by kevzlou7979** [comment]
Hi ,  I just finished the implemetation of material autocomplete integration with chips see attached screenshot.

Simple Autocomplete integration
![autocomplete](https://cloud.githubusercontent.com/assets/3138071/9077224/76173838-3ae0-11e5-85fb-5b9484bc6b23.gif)

With Image Integration
![autocomplete_2](https://cloud.githubusercontent.com/assets/3138071/9077231/888fa7a2-3ae0-11e5-9aa8-fc664721eac1.gif)
