### ISSUE TITLE
MaterialSideNav classes inconsistent

### ISSUE THREAD

**Issue by esocode** [GwtMaterialDesign/gwt-material#725]
2.0-rc7: `MaterialSideNav` is both a base class for several `SideNavType`-specific subclasses like `MaterialSideNavCard` but also a concrete class that is used to implement the FIXED type. This is quite confusing, especially because it's not even documented in the class comment. Either should `MaterialSideNav` be an abstract base class that only has concrete sub-types or there should be only the side nav class which handles the different types internally. I would prefer the latter variant because it makes it easier to algorithmically create differently typed side navs. To achieve the abstraction of the rendering as it is currently done in the subclasses something like a SideNavRenderer class (or similar) could be used or maybe it could even be added to the type mixin.

**Comment by kevzlou7979** [comment]
I agree with abstracting the MaterialSideNav and will extend those existing types into it. This could be an enhancement on 2.1.

**Comment by kevzlou7979** [comment]
Implemented via https://github.com/GwtMaterialDesign/gwt-material/commit/448226445de873cc59e689eecafa80ed795ffec9
