### ISSUE TITLE
Opening a ListValueBox does not close the another ListValueBox that is open

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#726]
When I have more listValueBoxes on a page, opening a listValueBox does not close another one that is open. I open the list boxes by clicking on them.

![listboxes](https://user-images.githubusercontent.com/4210304/32071469-0a522826-ba98-11e7-9678-b56497ab490f.png)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/62dcfa3d1375c30c5befe0ed1047932ed7d57954
