### ISSUE TITLE
MaterialTooltip default delay shouldn't be 0

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material#728]
Delay of 0 (AKA "no delay at all") makes tooltips popup _immediately_ after mouse enters a widget (even if mouse was just, very quickly, passing above widget). That makes very bad visual experience and may collide with other operations, for example, if link that opens a `MaterialDropDown` has tooltip, tooltip will cover `MaterialDropDown` every time, because it is impossible to click a link without triggering tooltip.

Even changing initial value in `MaterialTooltip.java` from 0 to, say, 1000 would be beneficial, but best solution  would be if that default delay could be configurable.

**Comment by kevzlou7979** [comment]
Setting delay in MaterialTooltip is availble, you can set it by 
``
<m:MaterialButton tooltipDelayMs="1000" tooltipHTML="&lt;i&gt;Italic text&lt;/i&gt;" text="Tooltip with HTML" />
```

**Comment by gkresic** [comment]
I forgot to mention: I know that manually setting delay is possible, but, at least as I see it, default delay of 0ms is... well... suboptimal default :)

**Comment by kevzlou7979** [comment]
Ok yeah this could be an enhancement we can set to default of 350ms as MD specification has for the UX

**Comment by kevzlou7979** [comment]
http://materializecss.com/dialogs.html

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/1c6c0602ce4be1e03da0324ea21cadca3e0ebae1
