### ISSUE TITLE
MaterialLink iconType 3D_ROTATION Fails

### ISSUE THREAD

**Issue by weatherdrew** [GwtMaterialDesign/gwt-material#731]
I cannot seem to set the "iconType" property to "3D_ROTATION" without a GWT compiler error:

```
Invoking generator com.google.gwt.uibinder.rebind.UiBinderGenerator
            [ERROR] Cannot parse value: "3D_ROTATION" as type gwt.material.design.client.constants.IconType: <material:MaterialLink float='LEFT' iconColor='WHITE' iconPosition='NONE' iconType='3D_ROTATION' padding='10' paddingBottom='5' ui:field='toolbarFly' waves='LIGHT'> (:20)
```
Using GWT 2.8 and gwt-material 2.0 rc6

**Comment by weatherdrew** [comment]
After looking more into the documentation site, it appears you simply need to swap the first portion of the items string name when a number is involved. So, for "3d rotation" use:

`iconType="ROTATION_3D"`

Found an example at []https://gwtmaterialdesign.github.io/gwt-material-demo/#icons)

**Comment by kevzlou7979** [comment]
Oh thanks for the cactch

**Comment by kevzlou7979** [comment]
![screenshot from 2017-11-03 07-05-27](https://user-images.githubusercontent.com/3138071/32354613-70b8a3ce-c065-11e7-800f-5946a1112566.png)

I just  checked the Generator and it seems fine, yeah instead of `3D_ROTATION` make use of `ROTATION_3D`

**Comment by kevzlou7979** [comment]
Oh I know why we swap ROTATION_3D because Java variables can't start with 3D_ROTATION it's invalid. so we do ROTATION_3D instead.
