### ISSUE TITLE
Implement a Popup like dialog that appears relative to another widget

### ISSUE THREAD

**Issue by vegegoku** [GwtMaterialDesign/gwt-material#735]
One of the cool widgets we see in google application is the google apps popup, same thing can be seen with google notification icon :

![selection_048](https://user-images.githubusercontent.com/5379625/32543734-2315711a-c47f-11e7-8be1-6c9edfcbe256.png)

it might be a nice widget to add to the GMD.

Thanks

**Comment by vegegoku** [comment]
![popup-bubble](https://user-images.githubusercontent.com/5379625/32564509-28b31a80-c4bd-11e7-949a-666f385b9d81.gif)

@kevzlou7979 here is the best i could do, i am not HTML nor CSS expert, and i dont think i can make a perfect pull request for this, maybe if i take this one as a practice and learned more about the GMD development while you guide me through this, i might end-up doing some pull requests.
Anyway i will upload the project in which i implemented this to github so you can look at all the things i did.
Thanks

**Comment by kevzlou7979** [comment]
Ok this issue is addin specific, so I migrated this to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/280
