### ISSUE TITLE
DropDown doesn't work on 2.0 version

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#739]
Hi, I migrated from 2.0 rc06 to 2.0 and I noticed that
the drop down widget doesn't work properly, even in the demo page.
(https://gwtmaterialdesign.github.io/gwt-material-demo/#dropdown)
I used the latest version of Chrome, Firefox and Safari.

Can you please check?

Thanks .

**Comment by kevzlou7979** [comment]
Hi @MarcoCucchi ,

I just checked the Dropdown component and it behaves well. Can you elaborate more steps to reproduce it. Also which environment (Specific with version) you are using? Browser? Device?

![peek 2017-11-19 04-05](https://user-images.githubusercontent.com/3138071/32984310-fa031b70-ccde-11e7-8ced-f5be70b8c751.gif)
