### ISSUE TITLE
Disabled button with waves keeps the wave element

### ISSUE THREAD

**Issue by simerlec** [GwtMaterialDesign/gwt-material#749]
Hello,

just stumbled upon something interesting - apparently the wave elements are kept in the DOM if a Button is disabled. To show you what I mean, here's a gif:

![waveception](https://user-images.githubusercontent.com/5793380/33543968-485f4176-d8d9-11e7-86c8-db268208eb4e.gif)

![screenshot 2017-12-04 09 58 02](https://user-images.githubusercontent.com/5793380/33544088-ae56a424-d8d9-11e7-9f2d-633178bbda3d.png)

Reproducible using the demo page https://gwtmaterialdesign.github.io/gwt-material-demo/#buttons

thanks and kr

**Comment by kevzlou7979** [comment]
Thanks for catching this, will patch it to 2.0.1.

**Comment by kevzlou7979** [comment]
Upon drilling the issue, it was only on Button : Flat type.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/8cee3c5c15feb8a2e0609d1e99b818a27ddb14c3 and Updated Unit test. Will be available on 2.0.1.
