### ISSUE TITLE
MaterialDatePicker - setFormat & getFormat for Months

### ISSUE THREAD

**Issue by washowasho** [GwtMaterialDesign/gwt-material#750]
MaterialDatePicker setFormat & getFormat for Months should follow the Java standard for months "MM" instead of "mm". Lower case "m" should be reserved for minutes. Allowing only "mm" for months in the current MaterialDatePicker  makes it challenging to convert the format into a true date.

![image](https://user-images.githubusercontent.com/6689967/33784976-031905ec-dc31-11e7-8cf7-64462e519309.png)

**Comment by kevzlou7979** [comment]
Hi there, 

Regarding the core js api, we strictly follow there formatting rules. Maybe I'll put a documentation guidelines about it http://amsul.ca/pickadate.js/date/#formats. If you have any suggestions feel free to discuss it.

Regards,
Mark

**Comment by washowasho** [comment]
Hi Mark - Thanks for the response. I understand the need for formatting in JS standards to make everything work... however I believe the value of both GWT and GWT Material Design is being able to code in Java  and have the GWT compiler transpile the code into JS. To follow that spirit in this case, it would accept Java formatting and translate that to what JS requires.

**Comment by kevzlou7979** [comment]
Yeah make sense, I can setup constants for this date formats and convert the javascript format to java one. If you have any suggestions feel free to discuss.

**Comment by kevzlou7979** [comment]
I will suggest, that we will basically support Java Formats by lowercasing the suggested formats ``` (MM -> mm). If you want more complex Java Date Formatting you will be welcome to submit Pull Request.

**Comment by kevzlou7979** [comment]
Refer to https://github.com/gwtbootstrap/gwt-bootstrap/blob/master/src/main/java/com/github/gwtbootstrap/datepicker/client/ui/base/DateBoxBase.java#L116

**Comment by kevzlou7979** [comment]
Added basic DateFormatHelper https://github.com/GwtMaterialDesign/gwt-material/commit/2a3d8f6616f7997af6754d51eb4719d89414fac5. Feel free to submit PR for advance parsing of formats.
