### ISSUE TITLE
EmptyPlaceHolder causes IndexOutOfBoundsException on MaterialListValueBox#getValue

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#751]
Selecting the very last item in the list and then calling **MaterialListValueBox#getValue** causes **IndexOutOfBoundsException**. This is because **MaterialListValueBox#setEmptyPlaceHolder** adds a new item into the list but does not add a new value into the array of the underlying model.

MaterialListValueBox#setEmptyPlaceHolder:
```
    public void setEmptyPlaceHolder(String value) {
        listBox.insertItem(value, 0);

        getOptionElement(0).setDisabled(true);
    }
```
I did not think this through at all, but maybe adding a null value at the 0-index of the underlying array could work? (Unless someone will beat me to it I shall look into it during this upcoming week.)

**Comment by jzaruba** [comment]
Are you working on this one? Otherwise I would fork `release_2.0.1` and do it...

Also it seems that calling `MaterialListValueBox#clear` probably annihilates the placeholder.

**Comment by jzaruba** [comment]
A pull request has been created with a fix.

Anyways, maybe a more clear solution/approach to the `#emptyPlaceHolder` thing would be not adding the placeholder into the `#listBox` at all... It serves no purpose there, it can not be selected, it looks weird when the list is opened/expanded (especially with multiple=true when it has now a disabled checkbox)
...we could avoid the `#values.length != #listBox.length` thing.
Maybe the placeholder could be displayed only when the `MaterialListValueBox` widget is not opened/expanded...?

**Comment by kevzlou7979** [comment]
@jzaruba Can you please add a test case for any new features to avoid regressions in the future.

**Comment by kevzlou7979** [comment]
> Maybe the placeholder could be displayed only when the MaterialListValueBox widget is not opened/expanded...?

I don't think its necessary to hide it.

**Comment by jzaruba** [comment]
@kevzlou7979 I did not consider this one a new feature, rather a bug-fix.
