### ISSUE TITLE
date picker closes itself

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#752]
```
@Override
public void onModuleLoad() {
	RootPanel main = RootPanel.get("main");
	main.add(new MaterialDatePicker());
	main.add(new MaterialTextBox());
	MaterialTextBox password = new MaterialTextBox();
	password.setType(InputType.PASSWORD);
	main.add(password);
}
```

...this, together with **`Chrome pre-populating the inputs with previously stored credentials`** creates circumstances under which clicking the "Next month" or the "Previous month" arrow hides the date picker.
When I open the page in the incognito mode (i.e. no credentials get auto-entered) the date picker behaves correctly.

Inspecting the page revealed that for some reason `focus` gets called on the username input, which then leads to the damned `close` event getting triggered on the date picker.

I have been experiencing this also with another form that contained no password inputs. The login inputs were present in the DOM though, just hidden (after successful sign-in)... I am still trying to narrow that one down.

Not sure it can play any role in anything, but I also noticed that "close" gets called on an already closed date picker when you move focus from the date input to another widget.

**Comment by jzaruba** [comment]
OK, tested the previously mentioned other form, this time making sure the login inputs are not present in the DOM. And indeed the issue does not occur.
Chrome credentials auto-filling seems to be the culprit.

**Comment by kevzlou7979** [comment]
Ok I'll check this out tomorrow including some bugs need to be fixed on 2.0.1-SNAPSHOT.

**Comment by gkresic** [comment]
Is there any workaround for this bug? I didn't noticed it earlier, but now I can witness it in Chrome 73 on both Linux and Windows.

Picker works (mostly) when date is initially unset, but closes immediately upon click when there is any input in it (popup just flashes briefly).

[Screencast from demo site](https://youtu.be/sLzkRhhnpxg)

**Comment by kevin-i3** [comment]
The fixed was already patched on 2.2-SNAPSHOT
https://github.com/GwtMaterialDesign/gwt-material/issues/901

And demo was migrated to https://gwtmaterialdesign.github.io/gmd-core-demo/#datePicker

**Comment by washowasho** [comment]
This also looks good in 2.3-SNAPSHOT.

**Comment by kevzlou7979** [comment]
Cool
