### ISSUE TITLE
returnBlankAsNull for AbstractValueWidget

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#753]
Hello

I need MaterialTextBox to return null instead of blank value. So I extended it like this:

```
public class MaterialTextBox extends gwt.material.design.client.ui.MaterialTextBox {
        /**
         * If true #getValue will return null when the value is blank
         */
	private boolean returnBlankAsNull = false;

	public boolean isReturnBlankAsNull() {
		return this.returnBlankAsNull;
	}

	public void setReturnBlankAsNull(boolean returnBlankAsNull) {
		this.returnBlankAsNull = returnBlankAsNull;
	}

	@Override
	public String getValue() {
		if(isReturnBlankAsNull() && isBlank()) {
			return null;
		}
		return super.getValue();
	}

	protected boolean isBlank() {
		return !createBlankValidator().isValid(super.getValue());
	}
}
```

I have added the new attribute to MaterialTextBox but I believe it should eventually go to gwt.material.design.client.base.AbstractValueWidget.

Would you consider accepting this modification i.e. a pull request?

**Comment by jzaruba** [comment]
Typical use-case would be non-mandatory inputs/fields with `@Pattern` constraint, like e-mail or phone number. In such cases the POJO you get from the editor will have "" in its String fields, and validation will test `@Pattern.regexp` against "", which usually fails.
While there are other solutions to the situation (a pipe in your regexp, preprocessing your POJO, ...), personally I like the null-approach the best.

**Comment by BenDol** [comment]
This would be acceptable, however note that there are edge cases in classes like `MaterialValueBox` where the `getValue` is accessing its value from the `valueBoxBase`. So you will have to perform the check there also (at least until that class is rewritten).

**Comment by BenDol** [comment]
In fact you will have to make sure all the classes extending `MaterialValueBox` call super.getValue() before accessing the value for real and handle it appropriately. I would be okay reviewing a PR if you want to submit one. Thanks!

**Comment by jzaruba** [comment]
Which branch should the changes go to please?

**Comment by BenDol** [comment]
release_2.1

**Comment by jzaruba** [comment]
In the end it seems `MaterialValueBox` is actually the best place to implement the change.

**Comment by kevzlou7979** [comment]
Agreed this can be used also not only in materialisbox but also addins such as combobox.

**Comment by kevzlou7979** [comment]
I'm writing now the Documentation on the Latest 2.1 demo snapshot and also A JUnit test for this.

**Comment by kevzlou7979** [comment]
Demo Added
![test1](https://user-images.githubusercontent.com/3138071/34556098-fa9ba25e-f16f-11e7-9a57-8c8a921b5d98.gif)

JUnit Added
