### ISSUE TITLE
MaterialListValueBox<T> method getIndex(String) should be getIndex(T)

### ISSUE THREAD

**Issue by jzaruba** [GwtMaterialDesign/gwt-material#754]
Am I wrong assuming this method of MaterialListValueBox&lt;T&gt; should accept T, rather than String?
```
    public int getIndex(String value) {
        int count = getItemCount();
        for (int i = 0; i < count; i++) {
            if (getValue(i).equals(value)) {
                return i;
            }
        }
        return -1;
    }
```
Look at the getValue(int) call in the above code, getValue actually returns &lt;T&gt;, as it should:
```
    public T getValue(int index) {
        return values.get(index);
    }
```
Shouldn't all methods related to the `values` field have String replaced with T in their signatures?

Currently MaterialListBox is the only subclass of MaterialListValueBox:
```
public class MaterialListBox extends MaterialListValueBox<String> {
    ...
}
```
...so this is not an issue, also it means **replacing similar String parameters with T should have zero impact.**
What do you think?
(I noticed this while working on #751, so I would take this one when I'm done with 751.)

**Comment by kevzlou7979** [comment]
@jzaruba Yeah cool, if you can open a Pull Request and create a simple unit test that could be cool.

**Comment by BenDol** [comment]
Well you can make your own implementation of `MaterialListValueBox` since `MaterialListBox` is only mean't to handle Strings.

**Comment by jzaruba** [comment]
@BenDol That's the point, you can't. If you try to do that, let's say you go with MaterialListIntegerBox, you will find out that because of this issue you are stuck with String at exactly 5 spots where you should have Integer.
