### ISSUE TITLE
MaterialListBox does not get focus when clicked on

### ISSUE THREAD

**Issue by mtmmtm9** [GwtMaterialDesign/gwt-material#756]
I would like to have a key-handler for some widgets. MaterialListBox and MaterialTextBox
when calling addDomHandler() for these widgets I have problem receiving any events for the MaterialListBox . It only works if I click on a MaterialTextBox and the uses <TAB> to move the focus to the MaterialListBox . After that it is possible to receive the key-event. The problem might be that clicking on a MaterialListBox  does not give it focus. Tested on 2.0.1-SNAPSHOT.

**Comment by kevzlou7979** [comment]
This was fixed via , it's because of the hacked fixed done on IE 11 https://github.com/Dogfalo/materialize/issues/901 which on the upcoming Materialize 1.0 we will receive a patch for the IE issue.

**Comment by kevzlou7979** [comment]
![focus-blur](https://user-images.githubusercontent.com/3138071/35026511-7086e5bc-fb86-11e7-93f0-6f0824878f3d.gif)
