### ISSUE TITLE
Resources injection issue on DebugModules.

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#761]
When inheriting GwtMaterialDesignDebug it seems that materialize.min.css still injecting to the DOM, it must be only materialize.css.

**Comment by BenDol** [comment]
Have you identified where `materialize.min.css` is injecting? Browsing the module and entry point there is no point that materialize.min.css is injected.

**Comment by kevzlou7979** [comment]
Yeah Im currently checking the modules, might be some other Project (i.e addins (which I suspected)) inherits the ``` materialize.min.css```. Checking now.

**Comment by BenDol** [comment]
I suspect one of the addins or another module is also importing another material module.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/fea4b36b5477143fb8af39a595fcb28f22670c3d
