### ISSUE TITLE
MaterialDatePicker YearsToDisplay not mentioned in changelog

### ISSUE THREAD

**Issue by Surykat** [GwtMaterialDesign/gwt-material#763]
Hello.

For some reasons I have to use version 1.5.3 - YearsToDisplay property seems to be absent. In which version it was filled? Change log say nothing about it.

Best regards,
Mateusz

**Comment by kevzlou7979** [comment]
Hi @Surykat thanks for validating this, the Feature was added to Official 2.0 of GMD.

Updated the changelog.
https://github.com/GwtMaterialDesign/gwt-material/wiki/Changelog
