### ISSUE TITLE
Material Time Picker Feature

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#77]
Implement the ability to have time picker inside the application. 
Refer to this guideline : https://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

**Comment by remarkNS** [comment]
I am looking forward to see this. It would be great if we can have ability of component to adopt to the device’s orientation (from the same guideline you have sent) that counts not only for time picker but date picker as well. 

BTW chips and autocomplite are looking really great on the latest demo.

**Comment by xavier20marj** [comment]
![timer_picker](https://cloud.githubusercontent.com/assets/13691374/9131297/326f495c-3c9f-11e5-8bea-15e6cd84af26.gif)

Thank you @kevzlou7979  for this , this was awesome

**Comment by remarkNS** [comment]
Awesome !

**Comment by remarkNS** [comment]
For some reason on mobile device keyboard is poping out when you activate Time picker and is hard to use it this way ? I think it's because TimeField on the page is focused when picker is started as opposed to Date picker where everything is fine.

**Comment by kevzlou7979** [comment]
Hi ,

We are excited to announce the landscape mode of Material Pickers (Time and Date) on GWT Material.
It will be available on next release, we will update the components menu to separate the Pickers from Forms Menu.

![landscape_date](https://cloud.githubusercontent.com/assets/3138071/9198040/fed22b4e-3fed-11e5-9f76-35864a87b67b.PNG)

![landscape_time](https://cloud.githubusercontent.com/assets/3138071/9198042/03943334-3fee-11e5-8973-574ebf3c70d1.PNG)



Regards,
GWT Material

**Comment by remarkNS** [comment]
Perfect !!!

**Comment by ibart** [comment]
cool.
