### ISSUE TITLE
MaterialTooltip setHtml() throws an Exception

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#771]
Hi, if you create a MaterialTooltip Object like this
```
  MaterialTooltip tp = new MaterialTooltip();
  tp.setHtml("<i>Italic text</i>");
```
an  Exception in the MaterialTooltip class at the line
```
public void setHtml(String html) {
....
  Element element = this.widget.getElement();
....
```
is thrown.
``>Exception: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'getElement_0_g$' of undefined
Vbi_g$	Xbi_g$	Wbi_g$	cIh_g$	rHh_g$	qHh_g$	NHh_g$	__c_g$	cY_g$	bY_g$	OX_g$	(anonymous function)	  Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'getElement_0_g$' of undefined
``

My **Question** is also, how can I change the Background Color of the Tooltip Widget.
Now it's always black with white writing. Using GMD 2.0.1
Thanks

**Comment by kevzlou7979** [comment]
You need to provide the widget by calling ``` setWidget(widget) ``` first before calling ``` setHtml() ``` or other related options.

Additional thing I added is a check whether the widget is null or not.
