### ISSUE TITLE
Indefinite MaterialToast

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material#774]
Looking at Materialize's [source](https://github.com/Dogfalo/materialize/blob/v1-dev/js/toasts.js#L238), it seems that toasts can be shown without timeout.

Unfortunately, since GMD's wrapper [uses `int` for duration parameter](https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/js/JsMaterialElement.java#L242), it's not possible to pass `Infinity` as value. On the other hand, GWT supports `Double.POSITIVE_INFINITY`, but using `Double` for duration in milliseconds looks like bad interface.

I can think of two solutions, both with drawbacks:

1. keep `int` in `JsMaterialElement.toast` but make it an overlay for private version that accepts `Double` as duration and convert `Integer.MAX_VALUE` to `Double.POSITIVE_INFINITY`
1. same as first solution, but replace `Integer.MAX_VALUE` to `Double.POSITIVE_INFINITY` conversion with additional `fireIndefiniteToast` methods and appropriate constructors

Current workaround is to always use `Integer.MAX_VALUE` as timeout which gives us ~596 hours which is *close* to infinity, but not exactly there :)

Clearing such toasts should be done with wrapper around native [`dismiss()`](https://github.com/Dogfalo/materialize/blob/v1-dev/js/toasts.js#L257) method.

**Comment by kevzlou7979** [comment]
This was already done. https://github.com/GwtMaterialDesign/gwt-material/blob/release_2.1/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialToast.java#L161. Just need a documentation to have it. If you set your duration less than 0 then it will trigger that Indefinite Toast.
