### ISSUE TITLE
MaterialWidget visible="false" + style is not working

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#776]
If I set on an element in uibinder style and visible="false" the element will be visible.

**Comment by kevzlou7979** [comment]
What version of GMD did you reproduce this issue?

**Comment by pfacmf** [comment]
I use 2.1-SNAPSHOT

`<m:MaterialColumn grid="s12" m:id="pool"  style="margin-top:20px;" visible="false">`

**Comment by kevzlou7979** [comment]
you might use a regular uibinder usage 
``` <m:MaterialColumn grid="s12" m:id="pool" marginTop="20" visible="false"> ```

With your current implementation it's a hook for style attribute into your widget so you can do it too.
```<m:MaterialColumn grid="s12" m:id="pool" style="margin-top:20px;" display="none">```

Note: You might use the standard GMD Styling instead of hooking the style attribute.
