### ISSUE TITLE
MaterialDnd ignoreFrom() with multiple elements

### ISSUE THREAD

**Issue by ak80** [GwtMaterialDesign/gwt-material#777]
I tried to use the ignoreFrom(Element... elements) method with MaterialDnd only the last element is used. When we give more than one element, the other elements are not used to ignore the dnd, only the last one. 

We are using version 2.0.1

Is there a workaround or possible fix, please?

**Comment by kevzlou7979** [comment]
Moved this to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/304
