### ISSUE TITLE
mvn gwt:run doesn't work on macos

### ISSUE THREAD

**Issue by ykphuah** [GwtMaterialDesign/gwt-material#781]
After using the archetype to generate the project, if I run mvn gwt:run right away on macos, I get a error 404. I have tried the exact same steps on Windows and it did work.

Troubleshooted further and it seems like the issue is with the mojo plugin, as if I just use that archetype, I get the same problem as well.

The new plugin (https://github.com/tbroyer/gwt-maven-plugin) doesn't have this issue though. And this is also the plugin used by the GWT Plugin in Eclipse when generating mvn project.

Are you planning to move the archyetype to the tbroyer plugin or you want to stick around with the mojo one? I think I can help to make either of the above happen.

**Comment by ykphuah** [comment]
Added    <copyWebapp>true</copyWebapp> in the pom.xml and now it works.

Seems the same is needed here:
http://technovergence-en.blogspot.my/2011/03/starting-with-atmosphere-framework-gwt.html#gwt-maven-plugin

**Comment by kevzlou7979** [comment]
The TBroyer plugin was introduced on 2.1 release of GMD. https://github.com/GwtMaterialDesign/gwt-material/pull/732. So yes we have it on 2.1-SNAPSHOT. Stay tune for the release.
