### ISSUE TITLE
MaterialListValueBox

### ISSUE THREAD

**Issue by pfacmf** [GwtMaterialDesign/gwt-material#782]
Is it possible to insert the list of values of MaterialListValueBox into body? If I put it in a short div with overflow hidden or auto the list is either truncated or triggers a scroll bar.

**Comment by kevzlou7979** [comment]
Do you mean, you want to add your MaterialListValueBox widget into the RootPanel or body? If it is, then the answer is you can.

**Comment by pfacmf** [comment]
You should insert select-dropdown in document body. The dropdown is adding scroll bars or is hidden when you use the listvaluebox in containers with css overflow set to hidden or auto.
