### ISSUE TITLE
Transition.SHOW_GRID - causing its element to be overflow: hidden

### ISSUE THREAD

**Issue by jaletechs** [GwtMaterialDesign/gwt-material#783]
Hello, I tried to use a MaterialDropDown in the MaterialCardAction of a material card. IN the grid that displays the cards, the drop down is hidden behind other cards. I tried to use CSS property to set it to VISIBLE, but that didn't work. Any ideas? Below is a picture.
![selection_047](https://user-images.githubusercontent.com/22795062/37929162-170cf26a-3137-11e8-868a-b1819662cfae.png)

**Comment by jaletechs** [comment]
The material dropdown has 3 items, but the last item is hidden by the next card on the grid.

**Comment by kevzlou7979** [comment]
I can't reproduce this on my demo: Can you please elaborate more elements that is wrapping your dropdown component. 
``` xml
      <m:MaterialColumn grid="s12">
          <m:MaterialCard>
            <m:MaterialCardAction>
              <m:MaterialButton  text="Dropdown" iconType="ARROW_DROP_DOWN" iconPosition="RIGHT" textColor="WHITE" activates="dp-2"/>
              <m:MaterialDropDown activator="dp-2" constrainWidth="true">
                <m:MaterialLink text="First"/>
                <m:MaterialLink text="Second"/>
                <m:MaterialLink text="Third"/>
              </m:MaterialDropDown>
            </m:MaterialCardAction>
          </m:MaterialCard>
        </m:MaterialColumn>
```

**Comment by kevzlou7979** [comment]
Can you whether your card action / card / column do contain ``` overflow: hidden ```. ?

**Comment by jaletechs** [comment]
I played around with those values for all the widgets concerned, and it
didn't make any difference. The card is always on top of the drop down

**Comment by jaletechs** [comment]
As a temporary solution, I did reduce the font size of the drop down
content, but the last item is still hidden.

On Apr 19, 2018 7:55 AM, "Jeremiah Adamson" <jaletechs@gmail.com> wrote:

I played around with those values for all the widgets concerned, and it
didn't make any difference. The card is always on top of the drop down

**Comment by kevzlou7979** [comment]
Can you please show a snippet, tried to reproduce outside UiBinder but still the issue didnt show up.

**Comment by kevzlou7979** [comment]
Code:
```
for (int i = 1; i <= 10; i++){
           MaterialColumn column = new MaterialColumn();
           column.setGrid("s5");
           MaterialCard card = new MaterialCard();

           MaterialCardAction action = new MaterialCardAction();

           String activator = DOM.createUniqueId();
           MaterialButton button = new MaterialButton();
           button.setActivates(activator);
           button.setText("Button");

           MaterialDropDown dropDown = new MaterialDropDown();
           dropDown.setActivator(activator);
           dropDown.add(new MaterialLabel("Test"));
           dropDown.add(new MaterialLabel("Test 2"));
           dropDown.add(new MaterialLabel("Test 3"));

           column.add(card);
           action.add(button);
           action.add(dropDown);
           card.add(action);
           row.add(column);
       }
```

Demo:
![dropdown](https://user-images.githubusercontent.com/3138071/38976239-4a48bd30-43e3-11e8-81f0-b04e2a9d0e1a.gif)

**Comment by jaletechs** [comment]
`public class BookSearchItem extends MaterialCard{

    private final MaterialCardTitle bookTitle;
    private final BookDto book;
    private final MaterialImage bookImage;
    private final MaterialLabel authorLabel;
    private final MaterialButton status, addButton;
    private MaterialDropDown statusDropdown;
    private String currentStatus;

    public BookSearchItem(BookDto book){
        this.book = book;

        setHoverable(true);

        setBackgroundColor(Color.WHITE);
        setTextColor(Color.BLACK);
        setOrientation(Orientation.LANDSCAPE);
        setOverflow(Style.Overflow.VISIBLE);
        setSize("100%", "100%");

        MaterialCardImage image = new MaterialCardImage();
        image.setWaves(WavesType.LIGHT);

        bookImage = new MaterialImage(book.getImageUrl());
        bookImage.setPixelSize(190, 190);
        bookImage.setPadding(10);
        image.add(bookImage);

        bookTitle = new MaterialCardTitle();
        bookTitle.setText(book.getTitle());
        bookTitle.setIconPosition(IconPosition.RIGHT);
        bookTitle.setTruncate(true);
        bookTitle.setFontSize(16, Style.Unit.PX);
        bookTitle.setFontWeight(Style.FontWeight.BOLD);
        bookTitle.setTooltip(book.getTitle());
        bookTitle.setWidth("100%");
        bookTitle.setSeparator(true);

        authorLabel = new MaterialLabel(book.getAuthor().getName());

        MaterialCardContent content = new MaterialCardContent();
        content.add(bookTitle);
        content.add(authorLabel);

        MaterialCardAction action = new MaterialCardAction();
        action.setWidth("100%");

        statusDropdown = new MaterialDropDown();
        statusDropdown.setActivator(book.getId() + "");
        statusDropdown.setConstrainWidth(true);
        statusDropdown.setOverflow(Style.Overflow.VISIBLE);

        addDropDownItems();

        status = new MaterialButton("Book Status", IconType.ARROW_DROP_DOWN, ButtonType.RAISED);
        status.setWaves(WavesType.LIGHT);
        status.setMarginRight(20);
        status.setIconPosition(IconPosition.RIGHT);
        status.setBackgroundColor(Color.GREEN);
        status.setActivates(book.getId() + "");
        status.setFontSize(12, Style.Unit.PX);
        status.setTruncate(true);

        statusDropdown.addSelectionHandler(new SelectionHandler<Widget>() {
            @Override
            public void onSelection(SelectionEvent<Widget> event) {
                currentStatus = ((MaterialLink) event.getSelectedItem()).getText();
                status.setText(currentStatus);
            }
        });

        addButton = new MaterialButton("SAVE", IconType.SAVE, ButtonType.RAISED);
        addButton.setWaves(WavesType.LIGHT);
        addButton.setBackgroundColor(Color.AMBER);
        addButton.setIconPosition(IconPosition.RIGHT);
        addButton.setFontWeight(Style.FontWeight.BOLD);
        addButton.addClickHandler(new SaveHandler());

        MaterialRow actionRow = new MaterialRow();
        actionRow.setPaddingLeft(10);
        actionRow.setWidth("100%");
        actionRow.add(status);
        actionRow.add(statusDropdown);
        actionRow.add(addButton);

        action.add(actionRow);

        add(image);
        add(content);
        add(action);
    }`

And some other place, I am doing this :
`for(BookSearchItem book : books){
            MaterialColumn column = new MaterialColumn();
            column.setGrid("l6 m6 s12");

            column.add(book);
            add(column);
  }`

**Comment by jaletechs** [comment]
No special need really. I tried to align right, and the entire thing went haywire. So i figured I could align in the action row before I add to the action. But I have added to the action, and it still doesn't change much
Here's a screen shot.

![selection_054](https://user-images.githubusercontent.com/22795062/38977496-757461ee-43ac-11e8-951d-6b3a883c8a09.png)

**Comment by kevzlou7979** [comment]
Oh upon deep findings, I just found out that the `waves-effect` contains ` overflow: hidden ` so that causing the dropdown to be hidden by default.

**Comment by kevzlou7979** [comment]
So the better way to structure is add a waves effect only to MaterialCardContent instead of the whole card.

```xml
  <MaterialCard>
            <MaterialCardContent waves="DEFAULT">
                         ... contents i.e images, texts
            </MaterialCardContent>
            <MaterialCardAction>
                           .. actions for your card i.e buttons
             </MaterialCardAction>
 </MaterialCard >

**Comment by jaletechs** [comment]
I removed all of the waves-effects and it still is hidden. Maybe I'll just keep at it till it works

**Comment by kevzlou7979** [comment]
Oh i forgot to ask you, what's the version of GMD are you using?

**Comment by jaletechs** [comment]
Actually, I found the reason why. It was a line that was intended to
animate the cards as they are displayed. Is there a reason why animation
would cause this issue?

**Comment by kevzlou7979** [comment]
Ok thanks for this information, I will look at the SHOW_GRID.

**Comment by kevzlou7979** [comment]
I checked with SHOW_GRID it works as expected.
![working-dropdown](https://user-images.githubusercontent.com/3138071/39161282-8ebc9370-47a2-11e8-861f-030efe547947.gif)

**Comment by kevzlou7979** [comment]
Did you used MaterialCardReveal?
