### ISSUE TITLE
MaterialTabItem.selectTab(): NPE if parent not yet initialized

### ISSUE THREAD

**Issue by javafh** [GwtMaterialDesign/gwt-material#786]
`MaterialTabItem` holds a copy of it's parent reference in a `parent` variable of type `MaterialTab`, but that is only initialized in the `onLoad()` method. This may cause a race condition if the method `selectTab()` is invoked earlier than `onLoad()`. This can be fixed easily by not using the separate parent reference at all and change `selectTab()` to invoke `((MaterialTab) getParent()).selectTab(sHref)` instead. `onLoad()` can then be removed.

**Comment by kevzlou7979** [comment]
Fixed and updated unit test via https://github.com/GwtMaterialDesign/gwt-material/commit/9552d1f813c3adfe6b85bbd80509a8bbcd2a8475
