### ISSUE TITLE
MaterialLink setEnabled not work properly 

### ISSUE THREAD

**Issue by MrD0llaro** [GwtMaterialDesign/gwt-material#787]
library version: gwt-material-2.0-rc6
I have found this problem, I prepare a page with GWT with the MateriaLink button disabled.

my Java view:

 @UiField
 MaterialLink exportLink;
my view.xml:

 <m:MaterialLink ui:field="exportLink" text="Esporta Report" addStyleNames="btn" target="_blank"  float="RIGHT" enabled="false"/>
The button is disabled and the click not work (GOOD).

if the user complete the Form, I will enable it.

   exportLink.setHref(updatedUrl());
    exportLink.setEnabled(true);
and work perfert.

When I try to disable it becouse the user put a wrong value.

exportLink.setHref(null);
            exportLink.setEnabled(false);
the button looks ok but is possible to click it

**Comment by kevzlou7979** [comment]
Been reading and researching the difference of MaterialLink with the use of href's , seems to me that its not enough to add ``` disabled ``` attributes.

Here is the reference:
https://techniblogic.com/how-to-disable-anchor-tag-href-links-by-html-css-javascript/

Note: I might see the best solution to prevent us to directly go to the provided href whenever it is disabled.
