### ISSUE TITLE
Date and Time pickers

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#79]
All screen shoots are from the real mobile device (Android 5.1.1).

1.) zIndex of Time Picker:

![zindex](https://cloud.githubusercontent.com/assets/9980558/9254458/d9d82cec-41e3-11e5-97e3-e9f3989e135e.png)

2.) Focus on Time Picker: When time picker is active it does not have focus. The focus stays on Field behind which results with mobile keyboard constantly poping out. 

![focus](https://cloud.githubusercontent.com/assets/9980558/9254540/58000cb6-41e4-11e5-8c6c-4c4b15a38516.png)

3.) Landscape and Portrait versions of DatePicker and TimePicker is really great to have, the only thing is that components should update their orientation automatically, it should not be left to the developer to achieve this. This should be done internally, at least this is what I think. Some discussions how this (detection of orientation change) can be done: http://stackoverflow.com/questions/1649086/detect-rotation-of-android-phone-in-the-browser-with-javascript

and finally two screenshots that demonstrate something that should never happen:

Landscape date picker on Portrait mobile orientation:

![dplandscapeonportrait](https://cloud.githubusercontent.com/assets/9980558/9254668/1247c046-41e5-11e5-8ca2-ca989a9f6c00.png)

Landscape time picker on Portrait mobile orientation:

![tplandscapeonportrait](https://cloud.githubusercontent.com/assets/9980558/9254680/1fa5a578-41e5-11e5-91c9-5c7e2f227944.png)

BTW awesome work done on this pickers.

**Comment by kevzlou7979** [comment]
Hi,

Thanks for your thorough test.
You're a great tester :) +1

Regards,
Kevin

**Comment by remarkNS** [comment]
I am trying to help you guys. Testing is all I can do in this moment as I do not have a time for development of bug fixing, but hopefully this will change in the future. Anyway keep up the good work.

Regards,
ReMark

**Comment by kevzlou7979** [comment]
The only thing left here is the Orientation update, it will be nice if we have the auto detect feature whether we are in mobile landscape mode. This also can be applied to Steppers and other components.

**Comment by kevzlou7979** [comment]
This can be done using @media (orientation: landscape) ..

**Comment by remarkNS** [comment]
Yes, everything has been solved except the orientation. Great job done!

**Comment by BenDol** [comment]
Currently working on the orientation detection for the `MaterialTimePicker`:
![orientation-timepicker](https://cloud.githubusercontent.com/assets/1935706/20049330/44908582-a527-11e6-8fc9-cb09009fbfaa.gif)
Can expect the changes in the next few hours.

**Comment by remarkNS** [comment]
So cool! This is exactly what I thought when I have created this issue.

**Comment by kevzlou7979** [comment]
Nice one

**Comment by remarkNS** [comment]
Maybe one small addition to this issue. It can be reproduced only on real Android device (LG G4 in my case). The problem is that when DatePicker opens, I do not see buttons (TODAY, CLEAR, CLOSE). I can scroll (swipe up) to see them, but it would be much better if I do not have to do anything in order to use those buttons. Maybe you can try on some other device, I am not sure how it behaves on others as I have tried only mine. Here is the sceen shot:
 
![ss1](https://cloud.githubusercontent.com/assets/9980558/20050772/636e10fc-a4cb-11e6-8ced-3f1b3e570fde.png)

**Comment by remarkNS** [comment]
It would be really nice if it can open like this:

![ss2](https://cloud.githubusercontent.com/assets/9980558/20050905/50735c18-a4cc-11e6-9eb9-ce20575d4632.png)

**Comment by kevzlou7979** [comment]
Maybe we can reduce some margin top on this, to solve the issue.

**Comment by BenDol** [comment]
Finished the orientation for both the time picker and date picker:
![orientation-datepicker](https://cloud.githubusercontent.com/assets/1935706/20058852/1d410b06-a558-11e6-891f-3060aefc5214.gif)
See latest commits.

**Comment by kevzlou7979** [comment]
Nice one, I'm going to test it out.

**Comment by kevzlou7979** [comment]
I just run``` mvn clean install ``` and Our Test case failed https://travis-ci.org/GwtMaterialDesign/gwt-material. We have an error in the recent commit https://github.com/GwtMaterialDesign/gwt-material/commit/d529deedbae0f19c1c459efe50d15ca951c5e861.

**Comment by kevzlou7979** [comment]
Test cases pays a lot whenever we have regression :)

**Comment by BenDol** [comment]
Most likely a false positive here, but double check it to make sure.

**Comment by kevzlou7979** [comment]
Just committed the new check / test for datepicker on orientation

**Comment by kevzlou7979** [comment]
Ok everything is ok now.

DatePicker : http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#pickers
TimePicker: http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#timepickers

**Comment by remarkNS** [comment]
Everything is great now !
