### ISSUE TITLE
Selecting CheckBox in GWT material datatable is not selecting row

### ISSUE THREAD

**Issue by sawantrajd** [GwtMaterialDesign/gwt-material#790]
@kevzlou7979  In GWT material data table if you click on checkbox to select row its not working. If you click on row it select checkbox. In demo also its not working. https://gwtmaterialdesign.github.io/gwt-material-demo/ But its working in infinite data table.

**Comment by kevzlou7979** [comment]
Please migrate this on datatable for further tracking.
