### ISSUE TITLE
MaterialTextBox with number is not validating maxLenght

### ISSUE THREAD

**Issue by rodrigobastosv** [GwtMaterialDesign/gwt-material#791]
I've created a MaterialTextBox with lenght="20", maxLenght="20" and InputType="NUMBER"

With this specific setup i can write more than 20 numbers like if the maxLenght is not working

Above is the code i used
`<m:MaterialTextBox length="20" maxLength="20" type="NUMBER"/>`

**Comment by kevzlou7979** [comment]
Ok will take a loon on this

**Comment by kevzlou7979** [comment]
Ok will take a look on it.

**Comment by kevzlou7979** [comment]
Checked this https://stackoverflow.com/questions/18510845/maxlength-ignored-for-input-type-number-in-chrome?answertab=active#tab-top. 

In the MDN Specification `maxLength` is not designed to ` type=NUMBER `

**Comment by kevzlou7979** [comment]
> maxlength
If the value of the type attribute is text, email, search, password, tel, or url, this attribute specifies the maximum number of characters (in UTF-16 code units) that the user can enter. For other control types, it is ignored. It can exceed the value of the size attribute. If it is not specified, the user can enter an unlimited number of characters. Specifying a negative number results in the default behavior (i.e. the user can enter an unlimited number of characters). The constraint is evaluated only when the value of the attribute has been changed.
