### ISSUE TITLE
MaterialListBox auto-hides with multipleSelect on

### ISSUE THREAD

**Issue by RLHawk1** [GwtMaterialDesign/gwt-material#792]
Unlike the multiple select on http://materializecss.com/forms.html#select, the GWT Material version auto-closes each time you check/uncheck an item.  Ideally it would stay open until you focus something else like the materialize one does.

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material/issues/842
