### ISSUE TITLE
Extra Large screens support

### ISSUE THREAD

**Issue by ruzkant** [GwtMaterialDesign/gwt-material#794]
So materializecss has an additional media query for extra large screens. I just copied the css and I am currently using it as follows:
        column.setGrid("xl4 l6 m6 s12");

The boundary is 1200px and up.

So while incorporating this into the gwt material is helpful, it is still not the whole story. I have a 2560px width screen and then you get 4096px for 4k. The differences in sizes are quite significant.

Further GWT Material has a Resolution enum, but the screen sizes don't align with the grid media queries, which is somewhat confusing as to what the intention is. 

Another strange one is that the 4k enum is half the size of a 4k screen:
    LAPTOP_4K(new WidthBoundary(1441, 2560));

So at the very least it would be great to incorporate xl, but xxl would also be useful to investigate. In some brief searching I could not find clear guidelines as to where others are putting in the resolution breaks above 1200.

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material/issues/842
