### ISSUE TITLE
MaterialDatePicker ClassCastException with Gwt 2.8.2 and 2.1-SNAPSHOT

### ISSUE THREAD

**Issue by Hadesskywalker** [GwtMaterialDesign/gwt-material#797]
Hi,
I have observed a problem in the gwt-material 2.1-SNAPSHOT branch using GWT 2.8.2 HEAD-SNAPSHOT using Chrome.
In the MaterialDatePicker switching the month or selecting a day, a ClassCastException is thrown.
With GWT 2.8.1 the MaterialDatePicker works.

We would like to use gwt-material for multiple upcoming products, using GWT 2.8.2.
If there is anything I could help with an investigation please ask.

Thank you for an awesome library and I hope the following Console Log helps.

![screenshot from 2018-05-09 16-55-29](https://user-images.githubusercontent.com/14997253/39822040-e9b1e448-53a9-11e8-8bd7-af18d7633d10.png)

**Comment by kevzlou7979** [comment]
Could post a snippet regarding your issue.

**Comment by kevzlou7979** [comment]
Tried in our current demo - with GWT 2.8.2 and GMD 2.1-SNAPSHOT the issue is not reproducible.

**Comment by kevzlou7979** [comment]
![test](https://user-images.githubusercontent.com/3138071/40232042-dcc4363c-5acf-11e8-930a-a53c0d843103.gif)

**Comment by Hadesskywalker** [comment]
If I am not mistaken the gwt-material-demo branch release_2.1 is running with gwt 2.8.1 and not 2.8.2

From the gwt-material-demo branch release_2.1 pom.xml
```
<!-- GWT -->
<gwt.version>2.8.1</gwt.version>
```

**Comment by kevzlou7979** [comment]
We will update to be 2.8.2

**Comment by Hadesskywalker** [comment]
Thank you, I am looking forward to that!
