### ISSUE TITLE
Cards - Horizontal Type - White Space

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#798]
There was an issue on Cards with Horizontal Type causing white space.

![image](https://user-images.githubusercontent.com/39285900/40090748-5c78ffa2-58e6-11e8-9b86-bc3fdaa585b3.png)

Browser: Firefox39+
OS: Windows10
Demo: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#cards  - HorizontalType section

**Comment by kevzlou7979** [comment]
Fixed in all browsers
![image](https://user-images.githubusercontent.com/3138071/40518361-d0176d1a-5fec-11e8-91ac-dbd7ad147bff.png)

**Comment by kevzlou7979** [comment]
Ready for retest @marecrismatias1

**Comment by marecrismatias1** [comment]
Confirmed in IE11,Safari9,Firefox39 and Android:Chrome
