### ISSUE TITLE
Autocomplete - Placeholder color is not updated when setting an error

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#803]
![image](https://user-images.githubusercontent.com/39285900/40104223-568ecff4-5922-11e8-8cf2-5150dd4c53cd.png)

Demo: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#errors Autocomplete Section

**Comment by kevzlou7979** [comment]
Error style
![image](https://user-images.githubusercontent.com/3138071/40462453-a8063cb6-5f42-11e8-97f0-e69cdd9549c9.png)

Success style
![image](https://user-images.githubusercontent.com/3138071/40462473-b9b78ce4-5f42-11e8-9181-59df1248d0e0.png)

**Comment by kevzlou7979** [comment]
Ready for retest @marecrismatias1

**Comment by marecrismatias1** [comment]
Confirmed in Android:Chrome, Firefox39, IE11 and Safari9
