### ISSUE TITLE
NumberBox : ReadOnly should not display the spinner arrows

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#805]
![image](https://user-images.githubusercontent.com/39285900/40150732-166c296c-59ae-11e8-841e-d45ea3f0c435.png)

Demo: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#textfields - Read Only Section

**Comment by marecrismatias1** [comment]
Also Disabled styles
![image](https://user-images.githubusercontent.com/39285900/40150771-4a48ca1a-59ae-11e8-9bcd-47f28d1903d3.png)

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/40462426-89fc9396-5f42-11e8-9863-1703e3ff3451.png)

**Comment by kevzlou7979** [comment]
Fixed in Safari
![image](https://user-images.githubusercontent.com/3138071/40462726-da43182e-5f43-11e8-84ab-5d2092debecb.png)

**Comment by kevzlou7979** [comment]
Ready for retest @marecrismatias1

**Comment by marecrismatias1** [comment]
Confirmed in Firefox39 and Safari9
