### ISSUE TITLE
Touch-Scrolling in MaterialDropDown closes the DropDown

### ISSUE THREAD

**Issue by AlbrechtStriffler** [GwtMaterialDesign/gwt-material#806]
When adding many options to the DropDown, it eventually becomes scrollable. This works fine, as long as you are using a scroll wheel or other means to cause scroll events. If you however are on a touch device and only are able to scroll by touch, you can no longer use the DropDown, because it closes as soon as you touch it, even if you want to only scroll. This is reproducible in Chrome debugger by emulating touch devices.

I found this can easily be fixed by not registering the function to close the DropDown on touchstart, see  [line 650 in materialize.js](https://github.com/GwtMaterialDesign/gwt-material/blob/5973481815d13d02d24571f9efb518509a9fe947/gwt-material/src/main/resources/gwt/material/design/client/resources/js/materialize-0.97.5.js#L650). As long as the handler for the click event remains, the DropDown closes just fine when selecting an option (click or touch) and still can be scrolled by touch scroll.

I fixed the issue in my project by unbinding the touchstart handler at the right time externally, but  changing line 650 to the following should fix it in general:

Currently:
`$(document).bind('click.'+ activates.attr('id') + ' touchstart.' + activates.attr('id'), function...`

Fixed:
`$(document).bind('click.'+ activates.attr('id'), function (e) {`

**Comment by kevzlou7979** [comment]
This might be an internal bug with Materialize.

**Comment by AlbrechtStriffler** [comment]
I'm sorry, I never checked whether this file is a separate library or not, just assumed it's all from this repository. I agree, this is most likely an internal bug in Materialize and I will report it over there.

**Comment by AlbrechtStriffler** [comment]
Just check over there, and it seems like it was already fixed in March in [commit dd7f0d6fd4e6d7fb0cf820afbb1aedb0b57a8afd](https://github.com/Dogfalo/materialize/commit/dd7f0d6fd4e6d7fb0cf820afbb1aedb0b57a8afd#diff-482573c55de5f85b5364c3b776635db9)
Not tested their version just yet, but you might want to update the library then...
