### ISSUE TITLE
PWA - App Install banner log errors on IE11+

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#807]
![image](https://user-images.githubusercontent.com/39285900/40235438-d9d7a960-5adc-11e8-9977-0076438d6dd6.png)

**Comment by marecrismatias1** [comment]
With validation with @kevzlou7979 this might be an issue with the new PWA Install banner (WebAppManifest)

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/40462500-d35c04fe-5f42-11e8-9a6c-db87b35b1621.png)

Added check using 
```java
PwaManager.isPwaSupported();
```

**Comment by marecrismatias1** [comment]
Confirmed in IE11
