### ISSUE TITLE
ListBox arrow is different on ComboBox

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#812]
![image](https://user-images.githubusercontent.com/39285900/40711606-32f4e8e6-642e-11e8-8f72-a6381c3598a8.png)

https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#textfields under TYPE: DEFAULT

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/issues/823

**Comment by kevzlou7979** [comment]
Ready for tests @marecrismatias1
