### ISSUE TITLE
Range - Current slider line color in IE is different from other Browsers

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#814]
Minor difference
![image](https://user-images.githubusercontent.com/39285900/40712771-149a7c28-6431-11e8-8d82-2872f5901da5.png)

Expected
![image](https://user-images.githubusercontent.com/39285900/40712803-23c5bac8-6431-11e8-86a9-96c1b28eb7ca.png)

**Comment by kevzlou7979** [comment]
Ready for test @marecrismatias1  The line color now is the same.
![image](https://user-images.githubusercontent.com/3138071/41884189-dd67ffce-7924-11e8-94fa-8da9e955f49d.png)
