### ISSUE TITLE
Range - The range indicator is still visible on the slider.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#815]
Actual
![image](https://user-images.githubusercontent.com/39285900/40713283-2e7d0d12-6432-11e8-838f-523ae5eee80e.png)

Expected
![image](https://user-images.githubusercontent.com/39285900/40713333-46f247c2-6432-11e8-857d-be565a55d79e.png)

https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#range

**Comment by kevin-i3** [comment]
Ready for testing @marecrismatias1 
Fixed and using the code below hides the duplicate Indicator for the range slider value:
```css
::-ms-tooltip {
    display: none;
}
```
![image](https://user-images.githubusercontent.com/38387414/41883669-4bace1dc-7922-11e8-99d8-dc7e55db6c75.png)
