### ISSUE TITLE
MaterialLink doubts

### ISSUE THREAD

**Issue by 1151136** [GwtMaterialDesign/gwt-material#817]
Hi, when I declare a MaterialLink type, how can I add some action when clicked on a Link button?

**Comment by kevzlou7979** [comment]
Hi there you can easily add click handler to the `  MaterialLink ` component.
![link-click](https://user-images.githubusercontent.com/3138071/40894272-0b742d3a-67db-11e8-895c-a979a01c07b2.gif)

**Comment by 1151136** [comment]
Thanks you very much for the help, I hadn’t seen this part.

De: Mark Kevin Baldemor <notifications@github.com>
Responder A: GwtMaterialDesign/gwt-material <reply@reply.github.com>
Data: segunda-feira, 4 de junho de 2018, 02:38
Para: GwtMaterialDesign/gwt-material <gwt-material@noreply.github.com>
Cc: "Carlos Rodrigues (1151136)" <1151136@isep.ipp.pt>, Author <author@noreply.github.com>
Assunto: Re: [GwtMaterialDesign/gwt-material] MaterialLink doubts (#817)


Hi there you can easily add click handler to the MaterialLink component.
[link-click]<https://user-images.githubusercontent.com/3138071/40894272-0b742d3a-67db-11e8-895c-a979a01c07b2.gif>
