### ISSUE TITLE
Badge Inside SideNav link misaligned

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#819]
![image](https://user-images.githubusercontent.com/39285900/41222027-7ae59e5c-6d98-11e8-9498-b3a3b9aa5d3c.png)

Go to demo page https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/ then see the sidenav badge on the left side and you will see that the badge is not aligned with the sidenav label.

**Comment by kevzlou7979** [comment]
Duplicate of https://github.com/GwtMaterialDesign/gwt-material/issues/810
