### ISSUE TITLE
DatePicker - Year Selection doesnt show the whole text.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#820]
![image](https://user-images.githubusercontent.com/39285900/41222253-fa9bdc74-6d98-11e8-91ae-17336b5a4747.png)

Navigate to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/?locale=fr#pickers 
Under Year Selection Type click on the DatePicker
And you will the exact screenshot I've shared.

**Comment by kevzlou7979** [comment]
Fixed and Ready for Test @marecrismatias1 

![image](https://user-images.githubusercontent.com/3138071/41761938-a05168e2-762b-11e8-905f-6852ec83adf2.png)
