### ISSUE TITLE
TextFields - Error Style misalignment contained with column and rows

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#821]
![image](https://user-images.githubusercontent.com/39285900/41223159-9a709fb2-6d9b-11e8-8ada-ff4d82e9a9e3.png)

Setting the first item with error pushes the other text fields below that are contained inside the row.

https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/?locale=fr#textfields under type DEFAULT

**Comment by kevzlou7979** [comment]
Fixed the overall layout structure of new FormFIelds (OUTLINED, FILLED, LEFT_ALIGNED and DEFAULT) types to be able to adapt row column nested styles.

**Comment by kevzlou7979** [comment]
DEFAULT
![image](https://user-images.githubusercontent.com/3138071/41808910-a1b455c2-7717-11e8-936e-09bfad0d5de6.png)

FILLED
![image](https://user-images.githubusercontent.com/3138071/41808969-549ff16e-7718-11e8-95f3-d9111edf1eae.png)

OUTLINED
![image](https://user-images.githubusercontent.com/3138071/41808976-67c1e1ee-7718-11e8-8dec-1ffb9aec311c.png)

LEFT ALIGNED
![image](https://user-images.githubusercontent.com/3138071/41808984-7ac014f0-7718-11e8-8b5c-e3ec065c33bc.png)

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for retest
