### ISSUE TITLE
ListBox - OUTLINED Type -  We must need a padding for the dropdown arrow

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#823]
![image](https://user-images.githubusercontent.com/39285900/41223446-687175da-6d9c-11e8-996b-2796e5c11170.png)

**Comment by kevzlou7979** [comment]
Fixed Layout (ListBox - OUTLINED & FILLED)
![image](https://user-images.githubusercontent.com/3138071/41700511-232bcd92-755b-11e8-80ee-d4ceb637dc70.png)

![image](https://user-images.githubusercontent.com/3138071/41700530-31e87344-755b-11e8-8f55-1ad8596e2d22.png)

**Comment by kevzlou7979** [comment]
Also for ComboBox

![image](https://user-images.githubusercontent.com/3138071/41700557-46fa5bee-755b-11e8-9460-5fb15f6b9718.png)


![image](https://user-images.githubusercontent.com/3138071/41700549-3f8eb6a2-755b-11e8-8da4-1eba5a43edcf.png)

**Comment by kevzlou7979** [comment]
Updated also the look for the arrow to standardized it to MD Spec

![image](https://user-images.githubusercontent.com/3138071/41751962-f240f058-75f6-11e8-9d8f-248b3d21ae1b.png)


![image](https://user-images.githubusercontent.com/3138071/41751959-eafba6bc-75f6-11e8-9e02-b6280e638e40.png)

![image](https://user-images.githubusercontent.com/3138071/41751971-ffc59c4c-75f6-11e8-8607-c0db7ce27f5a.png)

![image](https://user-images.githubusercontent.com/3138071/41751975-057f2860-75f7-11e8-889d-a3801b4f9b25.png)

![image](https://user-images.githubusercontent.com/3138071/41752029-66682f50-75f7-11e8-8320-25a82c6c3692.png)

![image](https://user-images.githubusercontent.com/3138071/41752032-6c3ba2cc-75f7-11e8-85f9-f3a1ec3d432b.png)

**Comment by kevzlou7979** [comment]
Ready for tests @marecrismatias1
