### ISSUE TITLE
Branch 2.1 , API for Notification Browser gone

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#824]
Hi, 
API for Notification Browser is gone in 2.1 branch ,  I use snapshot jar ,

**Comment by kevin-i3** [comment]
We removed the old Notification API , instead we are transitioning to new PWA Notification API. Please wait for that in 2.1 release

**Comment by kevzlou7979** [comment]
Hi @nseb ,

There's a new implementation of PushNotification Service in GMD will be updating the demo once we've got the browser testing final.

Best Regards,
Mark

**Comment by nseb** [comment]
Hi @kevzlou7979 , I had seen that the API had changed, only in passing we had lost, the ability to create a simple notification from the client, without the notification necessarily come from the server

**Comment by kevzlou7979** [comment]
Yup the api (External push service) is not supported anymore in 2.1. However you can add your own custom implementation as a addin / incubator widget https://pushjs.org/#

**Comment by kevzlou7979** [comment]
Available now in 2.1 - https://gwtmaterialdesign.github.io/gwt-material-demo/#notification
