### ISSUE TITLE
TextArea - OUTLINED the width is different from others because of padding

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#826]
![image](https://user-images.githubusercontent.com/39285900/41400730-7a37b6ac-6ff0-11e8-9484-7916cabc6735.png)

Can be reproduced in https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#textfields under FieldType - OUTLINED

**Comment by kevzlou7979** [comment]
Fixed the layout issue
![image](https://user-images.githubusercontent.com/3138071/41700435-da87d73e-755a-11e8-95e1-aaf2659442eb.png)

**Comment by kevzlou7979** [comment]
For Outlined Type
![image](https://user-images.githubusercontent.com/3138071/41700479-050b5cec-755b-11e8-93e0-ceba46ebdd3b.png)

**Comment by kevzlou7979** [comment]
Ready for tests @marecrismatias1
