### ISSUE TITLE
Breadcrumbs in Mobile (IOS) third item is hidden

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#829]
We must support a horizontal scrolling when we have multiple breadcrumb items.
![image](https://user-images.githubusercontent.com/39285900/41752962-32befb4c-75fd-11e8-9901-11306485b5a5.png)

**Comment by marecrismatias1** [comment]
Also happening in IOS:Chrome

**Comment by kevzlou7979** [comment]
This was added to GMD 2.2 backlog https://github.com/GwtMaterialDesign/gwt-material/issues/842
