### ISSUE TITLE
MaterialDatePicker

### ISSUE THREAD

**Issue by MarcoCucchi** [GwtMaterialDesign/gwt-material#83]
1) is it possible to invalidate MaterialDatePicker to indicate that it is mandatory? (for ex. implement a method like setInvalid() of MaterialButton obj)

2) bug:  when i 1) open the MaterialDatePicker 2) click outside the MaterialDatePicker but inside the browser and 3) click outside the browser and finally 4) click inside the brorser the MaterialDatePicker show on without clicking on it.

2) how to change the label for multi-language purpose?

ty

**Comment by kevzlou7979** [comment]
Yes that's what we are working on the Error indication of each material forms , textbox, listbox, pickers etc. https://www.google.com/design/spec/patterns/errors.html#errors-incompatible-state-errors

**Comment by remarkNS** [comment]
"User input errors" looks really great: https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

It would be nice to have this.

**Comment by kevzlou7979** [comment]
@MarcoCucchi  Please follow this issue #84 which includes the error patterns on each material widgets

**Comment by MarcoCucchi** [comment]
ok @kevzlou7979 
ty

**Comment by kevzlou7979** [comment]
About the language internalization I think it can supported we will try to make the magic on it

**Comment by kevzlou7979** [comment]
Material date picker now is fixed inside a modal
