### ISSUE TITLE
Cards : Horizontal Type in Mobile (IOS) has different layout

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#830]
Expected
![image](https://user-images.githubusercontent.com/39285900/41753016-9239cfac-75fd-11e8-908e-3e07374df510.png)

Actual
![image](https://user-images.githubusercontent.com/39285900/41753005-7f7cb4a6-75fd-11e8-9d52-c26bda6c5883.png)

**Comment by marecrismatias1** [comment]
Also happening in IOS:Chrome

**Comment by kevzlou7979** [comment]
@marecrismatias1  Ready for tests
