### ISSUE TITLE
ListBox - In Mobile (IOS) the select field was treated as textfield.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#832]
![2018-06-22 09 28 40](https://user-images.githubusercontent.com/39285900/41753238-af666f4e-75fe-11e8-9dc6-2b1115a3d265.gif)

**Comment by kevzlou7979** [comment]
Related bug https://stackoverflow.com/questions/38848742/material-select-blinking-on-ios

**Comment by kevzlou7979** [comment]
Fixed now and ready for retest @marecrismatias1
