### ISSUE TITLE
Dropdown in NavBar is not visible

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#834]
We should probably update the demo to view the dropdown.

![image](https://user-images.githubusercontent.com/39285900/41753484-3a166c06-7600-11e8-974b-5473051e9128.png)

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for retest

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/42304161-6ebfe430-8057-11e8-901e-52c141a4e8df.png)

![image](https://user-images.githubusercontent.com/3138071/42304166-748e33da-8057-11e8-9bea-fe538a974f0f.png)

**Comment by marecrismatias1** [comment]
Regression Bug on IE11+
![image](https://user-images.githubusercontent.com/39285900/42309475-3d157d0a-806b-11e8-891d-759666f262e6.png)

**Comment by kevzlou7979** [comment]
There was a great explanation for the fixes on IE about the staircase issue https://code.tutsplus.com/tutorials/9-most-common-ie-bugs-and-how-to-fix-them--net-7764 Section 2

@marecrismatias1 You can now retest this issue
