### ISSUE TITLE
Footer in Mobile (IOS) esp. the Copyright label is half visible.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#835]
![image](https://user-images.githubusercontent.com/39285900/41753608-ffebdc04-7600-11e8-9797-a7fdbe5875bf.png)

Go to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#footer

**Comment by marecrismatias1** [comment]
Happening also in IOS:Chrome

**Comment by kevzlou7979** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/3138071/42304261-f2a18b0a-8057-11e8-94b8-6778323361b9.png)

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for retest
