### ISSUE TITLE
Range Slider - In Mobile (IOS) the popup indicator is not fixed with the circle slider.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#836]
![2018-06-22 09 48 36](https://user-images.githubusercontent.com/39285900/41753728-c1d92254-7601-11e8-9189-7099f2affccf.gif)

**Comment by marecrismatias1** [comment]
Happening also in IOS:Chrome

**Comment by kevzlou7979** [comment]
This bug should be related to https://github.com/GwtMaterialDesign/gwt-material/issues/809
