### ISSUE TITLE
NavBar - in mobile still the hamburger button is visible even we don't have sidenav

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#837]
![image](https://user-images.githubusercontent.com/39285900/41753841-5ffde186-7602-11e8-99bb-111c69135d0a.png)

**Comment by marecrismatias1** [comment]
Happening on Small Devices

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for tests
