### ISSUE TITLE
Material Error Patterns 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#84]
Implements error messages on each predefined widgets :
- Autocomplete
- Date Picker
- Range
- Switch
- Text Area
- Text Box
- Time Picker

**Comment by kevzlou7979** [comment]
![image](https://cloud.githubusercontent.com/assets/3138071/9375330/28385680-46b4-11e5-8502-507f51a4b361.png)

![image](https://cloud.githubusercontent.com/assets/3138071/9375334/326f130a-46b4-11e5-90cb-b872073a1244.png)

![image](https://cloud.githubusercontent.com/assets/3138071/9375339/3b46e55c-46b4-11e5-9430-7bbb18593ec0.png)

**Comment by kevzlou7979** [comment]
all these elements implements HasError interface that has two methods:
.setError(String message) and setSuccess(String success)

**Comment by MarcoCucchi** [comment]
Hi, excellent work, what about MaterialDropDown component?

**Comment by kevzlou7979** [comment]
OK we will add this on the lists
