### ISSUE TITLE
Tabs should support horizontal scrolling for multiple tab items.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#840]
In Mobile (IOS) when adding more tabs it is not usable because it was hidden.
![image](https://user-images.githubusercontent.com/39285900/41753955-06b767c2-7603-11e8-855c-b36bdcaa65ba.png)

Go to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#tabs under dynamic tabs then keep adding items.

**Comment by marecrismatias1** [comment]
Happening on small devices

**Comment by kevzlou7979** [comment]
This was added to GMD 2.2 backlog This was added to GMD 2.2 backlog https://github.com/GwtMaterialDesign/gwt-material/issues/842
