### ISSUE TITLE
Tabs : Controlled widths doesnt display the tab text.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#841]
![image](https://user-images.githubusercontent.com/39285900/41754069-56da431e-7603-11e8-9d66-f328a840211f.png)

Go to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#tabs then navigate to controlling the width of tabs.

**Comment by marecrismatias1** [comment]
Happening on small devices.

**Comment by kevzlou7979** [comment]
@marecrismatias1 Ready for tests 
![image](https://user-images.githubusercontent.com/3138071/42266259-7c5a9950-7fa8-11e8-93ef-59cca55096ba.png)
