### ISSUE TITLE
MaterialEmptyState with calc height  throw error negative value 

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#846]
Hi,
If I use MaterialEmptyState with height ="calcl(100vh-120px)" throw error (negative value for height)

**Comment by kevzlou7979** [comment]
Ok will check this out, this is an addin widget so next time you must register all addin widget issues directly to https://github.com/GwtMaterialDesign/gwt-material-addins so that we can sort and organized all bugs.

**Comment by kevzlou7979** [comment]
Migrated https://github.com/GwtMaterialDesign/gwt-material-addins/issues/346.
