### ISSUE TITLE
Core Animations : Layout 

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#848]
![image](https://user-images.githubusercontent.com/39285900/41968663-acb4b016-7a37-11e8-8384-406659233ec7.png)

Navigate to https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#coreAnimations then on mobile scroll horizontal to see the excess space.

**Comment by kevzlou7979** [comment]
@marecris You can now retest this
