### ISSUE TITLE
Multiple backend calls after autocomplete input click event

### ISSUE THREAD

**Issue by pohorelec** [GwtMaterialDesign/gwt-material#849]
For 2.1-rc2 version there are multiple backend calls for autocomplete click event. The MaterialAutoComplete.build method defines 2 click handlers (one for list and one for itemBox):

`list.addDomHandler(event -> suggestBox.showSuggestionList(), ClickEvent.getType());`

`itemBox.addClickHandler(event -> suggestBox.showSuggestionList());`

I am not sure if this will effect something else but I would recommend to remove either list or itemBox handler. Or introduce protected method for every click handler definition and programmer can override behaviour if he does not like it that way.

**Comment by kevzlou7979** [comment]
Migrated to Addin lists of issues https://github.com/GwtMaterialDesign/gwt-material-addins/issues/350
