### ISSUE TITLE
Extended MaterialSearch with remote search

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#850]
Hi,

it's possible to extend MaterialSearch to search on remote server ?

**Comment by kevzlou7979** [comment]
Hi there, we currently did a basic search feature on ` MaterialSearch ` we are looking forward for advance feature in the  future, This might be a platform implementation specific.

**Comment by nseb** [comment]
Ok , then is it possible to change the visibility of the properties to make the onLoad overlay easier for me so that I can make a remote call to fill the internal list.
