### ISSUE TITLE
incubator - Language selector bug displayng images.

### ISSUE THREAD

**Issue by andreaht** [GwtMaterialDesign/gwt-material#851]
Sometimes the language selector display the available languagese 2xtimes
![schermata del 2018-06-28 11-07-28](https://user-images.githubusercontent.com/8243955/42276180-31e544a2-7f93-11e8-93b1-262cc1f820fd.png)

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/352
