### ISSUE TITLE
Sidenav - Provide auto closing when navigating any item for Mobile

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#852]
This might improve navigation flow on Mobile Devices.

![image](https://user-images.githubusercontent.com/39285900/42320172-ff57b6a6-8086-11e8-9410-890ac53a8292.png)

**Comment by kevzlou7979** [comment]
Ok that will minimize navigation time.

**Comment by kevzlou7979** [comment]
This could be added to GMD 2.2

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material/issues/842
