### ISSUE TITLE
Chips - Zooming the chip causes a slight space between the letter and the border

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#853]
![image](https://user-images.githubusercontent.com/39285900/42320261-52b1e0d8-8087-11e8-9476-7d3069be51bb.png)

**Comment by kevzlou7979** [comment]
Oh nice catch - will check this out

**Comment by kevzlou7979** [comment]
This is now fixed, we need to recalculate the border provided by the ` outlined ` class.
![image](https://user-images.githubusercontent.com/3138071/42328692-8983ffc8-80a1-11e8-8d49-65e0c092ad8f.png)
