### ISSUE TITLE
MaterializeDataTable and SelectionType.NONE is not working with a input component in the first column

### ISSUE THREAD

**Issue by MalteSchwenker** [GwtMaterialDesign/gwt-material#854]
If the SelectionType is NONE and in the first column is an component which use the classname `selected` like a switch or a checkbox the method `AbstractDataView.toggleRowSelect` toggle the state of all components in this column. 

This is ok if the SelectionType is not NONE and in the first column is the CheckBox for the selecting a row. The Method `AbstractDataView.toggleRowSelect` should not be called if the SelectionType is NONE

![image](https://user-images.githubusercontent.com/9953522/42434178-5c34a6d6-8352-11e8-8779-8e7c2577478d.png)

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material-table/issues/167
