### ISSUE TITLE
Dialog component scrolls page to the top on open

### ISSUE THREAD

**Issue by remal** [GwtMaterialDesign/gwt-material#860]
1. Open Dialogs demo page: https://gwtmaterialdesign.github.io/gwt-material-demo/#dialogs
1. Scroll down to any Dialog component
1. Open the Dialog

Result:
Page has been scrolled to the top

Expected result:
Page scrolling remains the same as it was before the Dialog opening.

Used browser: Desktop Chrome

**Comment by kevzlou7979** [comment]
This is an intended default behaviour of Dialog in ` Materialize.css ` version 0.97 .
