### ISSUE TITLE
MaterialButton with href

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#864]
Hi  ,

I use a MateriaButton with href top open a new url in new window , but it's not working. I have to use a cliclHander and call Window.open from gwt

**Comment by kevzlou7979** [comment]
I think we had ` MaterialAnchorButton ` that you can try, because it's not ideal to make ` MaterialButton ` to have an href. It should be only for links but as I said there is ` MaterialAnchorButton `
