### ISSUE TITLE
Tab.selectTab 

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#865]
Hi,

it's possible to extend this method to fireEvents SelectionEvent , it's demanded , like ,MaterialValueBox
 setValue(T value, boolean fireEvents)

**Comment by kevzlou7979** [comment]
This could be added as enhancement on 2.2

**Comment by kevzlou7979** [comment]
Updated https://github.com/GwtMaterialDesign/gwt-material/issues/842 for the standardization.
