### ISSUE TITLE
MaterialSideNavPush closeOnClick depending on screen size

### ISSUE THREAD

**Issue by rwursthorn** [GwtMaterialDesign/gwt-material#866]
I am using a MaterilSideNavPush (but I think the feature would be nice for all SideNavs) and would like to contol the "closeOnClick"-behaviour depending on the size of the sreen.
When it's a small screen, where the overlay is shown, closeOnCLick should be activated, but on large screens the SideNav should be shown until the user closes it manually by clicking the three stripes.

Is there a way to achive this behaviour? Or could you include this feature in a future release?

**Comment by kevzlou7979** [comment]
We could include this feature on future releases

**Comment by vishalgromor** [comment]
In side nav I have a drop-down menu and I applied closeOnClick attribute on drawer. Whenever I click on drop-down the drawer is getting closed , so is there any way to  control closeOnClick  ?

**Comment by kevzlou7979** [comment]
Updated the 2.2 backlog to support customization on closeOnclick (It might be an interface wherein you can define your own custom behaviour) . See https://github.com/GwtMaterialDesign/gwt-material/issues/842
