### ISSUE TITLE
Problem CustomTheme 

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#867]
I want use my custom Theme , for ce moment I just copy files BlueTheme (in project theme) , in my new Theme. My Theme inherits <inherits name="gwt.material.design.themes.ThemeBase"/> , and I copied all files from blue theme.

In my application I use GwtMaterialBasicWithJQuery , I have a blank space left instead side nav  : 

![image](https://user-images.githubusercontent.com/6363226/44332836-59377f80-a46d-11e8-8366-111062ab4a0a.png)

the rest seem to work

**Comment by kevzlou7979** [comment]
This is one of the major fixes to be released on 2.1.1

**Comment by kevzlou7979** [comment]
Fixed via Fixed via https://github.com/GwtMaterialDesign/gwt-material-themes/commit/1a77ba5f40737b0f9f434e7f668ee9f561092604

**Comment by nseb** [comment]
Thans @kevzlou7979   , I must copy override and materialize to make my own theme ?

**Comment by kevzlou7979** [comment]
For Custom theming in GMD requires SASS as Materialize specification indicated. For us we just created gwt-material-themes to in house all the basic themes (blue, amber etc.).  I must post some tutorial later on to show you how to build your custom theme.

**Comment by nseb** [comment]
@kevzlou7979 I started my custom theme but I would like to change the primaies colors, how can I do with sasss, instead of doing everything by hand?

**Comment by kevzlou7979** [comment]
You can download Koala and import the variable.scss into it then generate
the css file

**Comment by kevzlou7979** [comment]
You can download it from materialize releases just get the 0.97 version

**Comment by nseb** [comment]
Thanks , I can create a materialize.css, but the file ovveride.css, you have a source scss file?

**Comment by nseb** [comment]
I managed to compile a version (starting from 0.97), but the style is all broken, because I think that the version generated does not correspond to version present in the override file.
In addition, when I look at the source files of materialize, there are many variables that are not found in the file scss GWT Material

**Comment by nseb** [comment]
You are sure versio 0.97 , because , there is no 
/*** Chips ***/
/*** Date Picker ***/
/*** Spinners | Loaders ***/

**Comment by nseb** [comment]
I found 0.97.5 , not a bad match, can you confirm that this is the correct version?

**Comment by kevzlou7979** [comment]
Yeah that's the current of Materialize we're using
