### ISSUE TITLE
MaterialCollapsible Issue programtically setting more than one active

### ISSUE THREAD

**Issue by lukelast** [GwtMaterialDesign/gwt-material#869]
I found an issue with `MaterialCollapsible` in accordion=false mode, where it allows multiple items to be active at once.

Say you are adding 2 items and you want both to be active. When you call `MaterialCollapsibleItem#expand()` on the second one, it eventually calls `parent.clearActive();` which clears the active state of the first item.

You can reproduce in the demo: https://gwtmaterialdesign.github.io/gwt-material-demo/#collapsible

My workaround was to call this directly instead of `expand()`.

```
header.addStyleName( CssName.ACTIVE );
body.setDisplay( gwt.material.design.client.constants.Display.BLOCK );
```

**Comment by kevzlou7979** [comment]
Thanks for catching this up - will be including a patch on 2.1.1 release

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/80ae695d95dc0d64ccb6ab76513883a6226a9051 and added test case.
