### ISSUE TITLE
MaterialNavBar : Dropdown Menu

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#87]
Add dropdown components into nav bar.

**Comment by kevzlou7979** [comment]
![dropdowncomponent](https://cloud.githubusercontent.com/assets/3138071/9841957/4a1269a6-5a5c-11e5-958a-13b1877b7bc4.gif)

**Comment by kevzlou7979** [comment]
This v1 will be updated with right material design specs

**Comment by kevzlou7979** [comment]
<h3>Follow this spec </h3>
![image](https://cloud.githubusercontent.com/assets/3138071/10062483/8e00e37c-6295-11e5-879f-9f44086969a9.png)

**Comment by kevzlou7979** [comment]
<h3>Result</h3>
<h4>For MaterialNavBar : Link Menu </h4>
![drop-navbar](https://cloud.githubusercontent.com/assets/3138071/10072478/dfb4b226-6276-11e5-844c-d3cbe6ac982a.gif)

<h4>Code</h4>
```xml
      
       <m:MaterialNavBar backgroundColor="blue">
		    <m:MaterialNavBrand href="#Test">Title</m:MaterialNavBrand>
			<m:MaterialNavSection align="right">
                <!--Activator-->
			    <m:MaterialLink  icon="mdi-navigation-arrow-drop-down" iconPosition="right"  text="DropDown" textColor="white" activates="dropdown1"/>
			</m:MaterialNavSection>
		</m:MaterialNavBar>
        <!--Activator-->
        <m:MaterialDropDown name="dropdown1" belowOrigin="false" constraintWidth="true">
			<m:item><m:MaterialLink text="First" /></m:item>
			<m:item><m:MaterialLink text="Second" /></m:item>
			<m:item><m:MaterialLink text="Third" /></m:item>
		</m:MaterialDropDown>
```

<h4>For MaterialNavBar : Icon Menu </h4>
![drop-icon](https://cloud.githubusercontent.com/assets/3138071/10072474/ce42fb24-6276-11e5-87db-1ff0a27b302e.gif)
<h4>Code</h4>
```xml
       <m:MaterialNavBar backgroundColor="blue">
            <m:MaterialNavBrand href="#Test">Title</m:MaterialNavBrand>
            <m:MaterialNavSection align="right">
                <!--Activator-->
                <m:MaterialIcon  icon="mdi-navigation-more-vert" tooltip="Starter" activates="dropdown1"/>
            </m:MaterialNavSection>
        </m:MaterialNavBar>
        <!--Activator-->
        <m:MaterialDropDown name="dropdown1" belowOrigin="false" constraintWidth="true">
            <m:item><m:MaterialLink text="First" /></m:item>
            <m:item><m:MaterialLink text="Second" /></m:item>
            <m:item><m:MaterialLink text="Third" /></m:item>
        </m:MaterialDropDown>

```

**Comment by MarcoCucchi** [comment]
Hi, I added a MaterialDropDown in a MaterialNavBar but when i click on it the menu is overlapped by the the underlying object. (which in this case is a MaterialSlide)
I added a gif for better explanation.
![materialdropdown](https://cloud.githubusercontent.com/assets/13817916/10268521/d860c0bc-6abb-11e5-9085-c491d50e3379.gif)


Can you help me?
