### ISSUE TITLE
Update version jquery

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#873]
It's possible to upgrade jquery version . becaue 2.1.1 has vulnerabilities : 
https://snyk.io/vuln/npm:jquery?lh@2.1.1

**Comment by BenDol** [comment]
Yeah we should update it soon, keep in mind you can load JQuery yourself using `GwtMaterialDesign` module instead of `GwtMaterialWithJQuery` module. Then just make sure the JQuery dependency is loaded before GMD loads and it will work fine.

**Comment by nseb** [comment]
until version is supported by GWT Material?

**Comment by nseb** [comment]
I do not understand why you stay on this version of 2014, you would at least upgrade to 2.2.4 which does not break all the API (as the 3.X does)

**Comment by BenDol** [comment]
If you re-read my first comment you will see that I said we should update it. What is the issue?

**Comment by nseb** [comment]
no problems , I wanted to know if there were any technical reasons to stay on this version

**Comment by BenDol** [comment]
I haven't investigated updating the JQuery version yet, the dependency on JQuery goes through a large portion of the library including the base `materializecss` library which is an external project that GMD is based on. So its possible there are issues updating, but I assume they won't be too big.

Feel free to use `GwtMaterialDesign` module and load later versions of JQuery to test it out and report back.
