### ISSUE TITLE
Scroll stay after change presenter on iOS

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#874]
I have a problem quite complicated to describe, my application on a mobile iOS, if I change the main presenter after clicking on a page that is long enough (I use GWTP), the new presenter is positioned well, but the scroll remains at the initial position, without reset for the new presenter

**Comment by nseb** [comment]
I found the problem:
in 'main' tag  , transition not wok in Safari : transition: all 200ms cubic-bezier(0, 0, 0.2, 1) 0ms ,
Where style is added , and why cubic ?

I prefer remove this style and add in setInSlot method in ApplicationView :main.getElement().setScrollTop(0);

works on Andoid and Safari

Thanks

**Comment by nseb** [comment]
In main tag , why : transition: all 200ms cubic-bezier(0, 0, 0.2, 1) 0ms , If i remove , all works

**Comment by kevzlou7979** [comment]
We need the main tag to have a transition whenever we open the sidenavigation, you can override it using 
``` 
transition: none;
```

**Comment by nseb** [comment]
If I remove transition attrbute, I have sidenavigation transition work's corectly

**Comment by nseb** [comment]
@kevzlou7979  , scrollTop not working.
My code ApplicatonView : 

`
@Override
    public void setInSlot(Object slot, IsWidget content) {
        super.setInSlot(slot, content);
        //On s'assure que la nav bar est caché
        //TODO , cel ne focntionne pas si c'est le meme presenter
        sideNavField.hide();

        //MaterialPathAnimator.animate(navBar.asWidget().getElement(), main.getElement());
        MaterialAnimation animation = new MaterialAnimation();
        animation.setTransition(Transition.FADEINRIGHT);
        animation.setDelay(0);
        animation.setDuration(400);
        animation.setInfinite(false);
        animation.animate(content.asWidget());
    }

`
MaterilaAnimation is correct for you ?
