### ISSUE TITLE
line stays red when calling clearErrorText() of MaterialTextBox

### ISSUE THREAD

**Issue by ingosch** [GwtMaterialDesign/gwt-material#876]
The "invalid" class doesn't get removed from the input element when calling clearErrorText() so the line stays red if an error was set before. It is needed to override clearErrorText() in MaterialValueBox like it's done with clearStatusText().

**Comment by kevzlou7979** [comment]
This was already fixed on coming 2.2 https://github.com/GwtMaterialDesign/gwt-material/commit/6860dd2f5e00be339276814bd4e37fc87dd3370a
