### ISSUE TITLE
Configuration property named ''serviceWorker'' warning

### ISSUE THREAD

**Issue by tsatatwer** [GwtMaterialDesign/gwt-material#879]
compilation's warning using version gwt-material 2.1.1 Service Worker as described in the demo : 

`[WARN] Line 94: Setting configuration property named 'serviceWorker' in module 'com.mytest.Mytest' that has not been previously defined.`

In the Module 

`<set-configuration-property name="serviceWorker" value="service-worker.js" />`

The service-worker.js is under webapp directory.
Starting the application I get this error:
TypeError: Cannot read property 'getServiceWorker_0_g$' of undefined

The simple code:

		    				if(PwaManager.isPwaSupported() )  {	 
		    					 MaterialToast.fireToast("PWA is supported");
		    				 
		    				 MaterialToast.fireToast("Script URL : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().scriptURL);
		    				 MaterialToast.fireToast("State : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().state);
		    				 
		    				 }

Or I did some thing wrong.

**Comment by kevzlou7979** [comment]
@tsatatwer  You dont need to set the configuration via the Module.xml, you might need to apply it thru java:
``` 
    PwaManager.getInstance()
                    .setThemeColor("#1565c0")
                    .setWebManifest("manifest.json")
                    .setServiceWorker(new ServiceWorkerManager("service-worker.js"))
                    .load();

```

**Comment by tsatatwer** [comment]
OK I did and then see the code

` MaterialToast.fireToast("Script URL : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().scriptURL);
		    				 MaterialToast.fireToast("State : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().state)`

I get what ever I try to access ServiceWorker    :

`Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'active' of undefined
ConsoleLogger.java:33 TypeError: Cannot read property 'active' of undefined
    at VEm_g$._Em_g$ [as getServiceWorker_0_g$] (ServiceWorkerManager.java:259)`

**Comment by tsatatwer** [comment]
I get this exception :

`Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read property 'active' of undefined
ConsoleLogger.java:33 TypeError: Cannot read property 'active' of undefined
    at VEm_g$._Em_g$ [as getServiceWorker_0_g$] (ServiceWorkerManager.java:259)`

The code :

` if(PwaManager.isPwaSupported() )  {
		    					 
		    					 MaterialToast.fireToast("PWA is supported");
		    					 
		    					 PwaManager.getInstance()
		    	                    .setThemeColor("#1565c0")
		    	                    .setWebManifest("manifest.json")
		    	                    .setServiceWorker(serviceWorkerManager = new ServiceWorkerManager("service-worker.js"))
		    	                    .load();
		    					 
		    					 
		    					 
		    				 
		    				 MaterialToast.fireToast("Script URL : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().scriptURL);
		    				 MaterialToast.fireToast("State : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().state);`

Exception thrown when ever I try to access the ServiceWorker from browser log:

Service Worker is registered
service-worker.js:27 [ServiceWorker] Caching app shell
service-worker.js:35 [ServiceWorker] Activate
ConsoleLogger.java:33 Service worker is installed
ConsoleLogger.java:33 Service worker is activating
service-worker.js:39 [ServiceWorker] Removing old cache cache_1532397298988
ConsoleLogger.java:33 Service worker is activated

**Comment by kevzlou7979** [comment]
Remove these llines
```
MaterialToast.fireToast("Script URL : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().scriptURL);
	    				 MaterialToast.fireToast("State : " + PwaManager.getInstance().getServiceWorkerManager().getServiceWorker().state);`
```

as the service worker is not yet activated.
