### ISSUE TITLE
MaterialOverlay Opacity

### ISSUE THREAD

**Issue by RLHawk1** [GwtMaterialDesign/gwt-material#880]
MaterialOverlay has a constructor that allows you to set the opacity, However, the open([...]) functions all end up setting the opacity to 1. I would like to be able to open an overlay that isn't fully opaque.

**Comment by RLHawk1** [comment]
A workaround for this is to not call overlay.setBackgroundColor but instead call getElement().getStyle().setBackgroundColor("rgba(0,0,0,0.2)"), for example, to set a black, 0.2 opacity.

**Comment by kevzlou7979** [comment]
Nice catch will update the overlay .

**Comment by kevzlou7979** [comment]
FYI this will be moved to addins

**Comment by kevzlou7979** [comment]
Moved to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/369
