### ISSUE TITLE
Release 2.2 branch fails to build

### ISSUE THREAD

**Issue by rmraya** [GwtMaterialDesign/gwt-material#881]
[gwt.material.design.client.ui.MaterialListBoxTest.txt](https://github.com/GwtMaterialDesign/gwt-material/files/2439664/gwt.material.design.client.ui.MaterialListBoxTest.txt)

Failing test report attached.

**Comment by kevzlou7979** [comment]
Nice catch , will investigating now the issue.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/24b02a48ff8ab0087df6c13aa7a0d3f996c3a9a5
