### ISSUE TITLE
Problem with two MateialFileUploader in same view

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#884]
Hi,
this code make problems, second row style is broken : 

` 
            <m:MaterialRow padding="1">
                <m:MaterialTitle title="Poster"
                                 description="Filled text fields carry more visual emphasis, making them stand out when surrounded by other content and components."/>
                <m:MaterialColumn grid="s12" padding="1">
                    <ma:fileuploader.MaterialFileUploader ui:field="posterMediaUploader" url="/fake"
                                                          acceptedFiles="image/*"
                                                          grid="l4"
                                                          preview="false" maxFileSize="1" shadow="0" padding="1"
                                                          clickable="posterUploadButton">
                        <m:MaterialCard padding="2">
                            <m:MaterialCardImage>
                                <m:MaterialImage ui:field="posterMediaPreview" url=""/>
                            </m:MaterialCardImage>
                            <m:MaterialCardContent layoutPosition="RELATIVE">
                                <m:MaterialLabel ui:field="lblName" text="Sample.png" fontSize="1.5em"/>
                                <m:MaterialLabel ui:field="lblSize" text="13 mb" fontSize="0.8em"/>
                                <m:MaterialProgress ui:field="progress" layoutPosition="ABSOLUTE" bottom="0" left="0"
                                                    type="DETERMINATE" percent="0"/>
                                <m:MaterialButton m:id="posterUploadButton" layoutPosition="ABSOLUTE" top="-25"
                                                  right="25"
                                                  type="FLOATING" backgroundColor="PINK" size="LARGE"
                                                  iconType="CLOUD_UPLOAD" iconColor="WHITE"/>
                            </m:MaterialCardContent>
                        </m:MaterialCard>
                    </ma:fileuploader.MaterialFileUploader>
                </m:MaterialColumn>
            </m:MaterialRow>

            <m:MaterialRow padding="1" paddingTop="25">
                <m:MaterialTitle title="Add Document"
                                 description="Add un document PDF"/>
                <m:MaterialColumn grid="s12" padding="1">
                    <ma:fileuploader.MaterialFileUploader ui:field="documentUploader" url="/fake"
                                                          acceptedFiles="application/pdf" grid="l4"
                                                          preview="false" maxFileSize="1" shadow="0" padding="1"
                                                          clickable="cardUpload">
                        <m:MaterialCard padding="2">
                            <m:MaterialCardImage>
                                <m:MaterialLabel text="Document.png" fontSize="1.5em"/>
                            </m:MaterialCardImage>
                            <m:MaterialCardContent layoutPosition="RELATIVE">
                                <m:MaterialLabel text="Document.png" fontSize="1.5em"/>
                                
                                <m:MaterialButton m:id="cardUpload" backgroundColor="PINK" size="LARGE"
                                                  iconType="CLOUD_UPLOAD" iconColor="WHITE"/>
                            </m:MaterialCardContent>
                        </m:MaterialCard>
                    </ma:fileuploader.MaterialFileUploader>
                </m:MaterialColumn>
            </m:MaterialRow>`

**Comment by kevzlou7979** [comment]
Can you post an image screenshot what this looks like? This might be an internal styling issue which you can easily solve

**Comment by kevzlou7979** [comment]
Moving this to addins

**Comment by kevzlou7979** [comment]
https://github.com/GwtMaterialDesign/gwt-material-addins/issues/371
