### ISSUE TITLE
Icon LIVE_TV

### ISSUE THREAD

**Issue by nseb** [GwtMaterialDesign/gwt-material#886]
Hi,
small problem with icon LIVE_TV , not aligned with other icons. The problem is the image of the icon.

![image](https://user-images.githubusercontent.com/6363226/47412297-a2f15e80-d76b-11e8-98fb-9aaa15bbb8cf.png)

code 
` <m:MaterialIcon iconType="WEB" iconColor="BLACK" waves="DEFAULT" circle="true" ui:field="timingButton"/>
            <m:MaterialIcon iconType="LIVE_TV" iconColor="BLACK" waves="DEFAULT" circle="true" ui:field="streamingButton"/>
            <m:MaterialIcon iconType="VIEW_LIST" iconColor="BLACK" waves="DEFAULT" circle="true" ui:field="resultButton"/>`

**Comment by kevzlou7979** [comment]
This is a expected behavior because the antenna on the tv makes the icon pushed a bit to the bottom. What you could do is to adjust the ` margin-top ` of the icon element for the TV
