### ISSUE TITLE
Add click() function for MaterialButton

### ISSUE THREAD

**Issue by AlexOreshkevich** [GwtMaterialDesign/gwt-material#89]
GWT internal class Button has a useful function click() that simulate a mouse-click:

```
  /**
   * Programmatic equivalent of the user clicking the button.
   */
  public void click() {
    getButtonElement().click();
  }
```

Could we have something like that in MaterialButton?

PS Is it possible to extend existing class hierarchy to avoid migration problems, in this case, could MaterialButton extend ButtonBase first rather than directly MaterialWidget?

**Comment by kevzlou7979** [comment]
Hi thanks Alex for this request, we will do our best to meet your expectation. :) Welcome to Material World

**Comment by kevzlou7979** [comment]
I tried extending it to ButtonBase but it seems its not possible, some elements are not compatible on it

**Comment by kevzlou7979** [comment]
What is you reuse the @UiHandler method of the button , e.g
@UiHandler("btn")
void onClick(ClickEvent e){
     // do something here
}


then you call it by

onClick(null);

**Comment by remarkNS** [comment]
@AlexOreshkevich you can simulate click() on any DOM element, not only ButtonBase by calling:

public static native void clickElement(Element elem) /*-{
    elem.click();
}-*/;

Example with Label :

clickElement(myLabel.getElement());

Try getting element from MatrialButton and do the same.

Hope it helps.
