### ISSUE TITLE
MaterialCardTitle icon not well positioned

### ISSUE THREAD

**Issue by Fuzzo** [GwtMaterialDesign/gwt-material#890]
The MaterialCardTitle icon has not the same vertical align as title text. 
I suppose there's a missing marginTop of 13px on the image.
You can see the bug also in demo app: https://gwtmaterialdesign.github.io/gwt-material-demo/#cards

**Comment by kevzlou7979** [comment]
Nice catch will updating this on 2.2 release

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/b63389a30835f732098518be8defcaec7d429393

**Comment by kevzlou7979** [comment]
Also updated all themes https://github.com/GwtMaterialDesign/gwt-material-themes/commit/50ba96612256ca50e9b977485af7fac17e12c3f4
