### ISSUE TITLE
Window with table bug

### ISSUE THREAD

**Issue by Sorreldd** [GwtMaterialDesign/gwt-material#894]
Hi !

Problem:
When the window is moving, the table header is no longer sticky.

Description:
I have simple MaterialWindow with MaterialDataTable

Table init looks like:
```
table = new MaterialDataTable<>();
TableScaffolding scaffolding = table.getScaffolding();
scaffolding.getTopPanel().clear();
scaffolding.getTopPanel().add(scaffolding.getInfoPanel());
table.getTableTitle().setText("Domains");
table.setSelectionType(SelectionType.MULTIPLE);
table.setUseStickyHeader(true);
table.addColumn(new TextColumn<String>() {
       @Override
       public String getValue(String domain) {
           return domain;
       }
}, "Domain");
```

**Comment by kevzlou7979** [comment]
WE have this issue before , If I'm not mistaken this will be patched in GMD Table 2.2-SNAPSHOT

**Comment by Sorreldd** [comment]
I used 2.1. Ok, i will try 2.2 version.

Thank you.

**Comment by kevzlou7979** [comment]
Yeah just confirm if it fixes the issue, if not then we will add it on our
bug fixing backlog.
