### ISSUE TITLE
MaterialDatePicker.setValue(null, true) does not fire events

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#897]
If you pass value null and fireEvents true to MaterialDatePicker.setValue, events are not fired because         super.setValue(value, fireEvents) is not called.

**Comment by kevzlou7979** [comment]
Nice catch will be patching this on GMD 2.2

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/302e9d9d8569913fa6a52c187c78a33b9ba55ae6
