### ISSUE TITLE
MaterialListBox#getIndex(String value) throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rodrigoborgesdeoliveira** [GwtMaterialDesign/gwt-material#899]
If the MaterialListBox has an empty placeholder, the following code
```java
public int getIndex(T value) {
        int count = getItemCount();
        for (int i = 0; i < count; i++) {
            if (Objects.equals(getValue(i), value)) {
                return i;
            }
        }
        return -1;
    }
```
throws an `IndexOutOfBoundsException` at `getValue(i)`.  
The reason is that the `getItemCount()` will also count the empty placeholder as an item, so when calling `getValue(i)` in the for loop, it will then call `getValueInternal(index + getIndexOffset())`, which will, in the last element, try to get a position = count.  
Example:  
If the list has no items, count will be 1 and `getValue(0)` will translate to `getValueInternal(1)`. Since there is only one element (index 0), it will throw the exception.

**Comment by kevzlou7979** [comment]
Merged via https://github.com/GwtMaterialDesign/gwt-material/commit/6804e9f153eb78ce47d208163338beccdf2c85d4. Again thanks for your contribution.
