### ISSUE TITLE
 sideNav button click

### ISSUE THREAD

**Issue by asmaalej** [GwtMaterialDesign/gwt-material#90]
Hi everyone,

I have implemented a sideBar menu where I have some links, my issue is that when I click on one of these links, I want get the sideBar hidden, but that doesn't happen, have you any idea how to get that works.

thanks in advance

**Comment by asmaalej** [comment]
I tried to open the materialize.js, then I detected that the 'closeOnClick' option was disabled, so I  changed it to true, but I've seen any improvement.

any help please ?

**Comment by kevzlou7979** [comment]
Ok on the next release of MaterialNavBar and MaterialSideNav changes we implemented :

just add closeOnClick="true" to hide the sidenav when click

```
<m:MaterialSideNav width="300" name="mysidebar"  type="clip" closeOnClick="true">
			<m:MaterialLink icon="mdi-content-inbox" iconPosition="left" textColor="blue"  text="Inbox" />
			<m:MaterialLink icon="mdi-action-stars" iconPosition="left" textColor="grey"  text="Starred" />
			<m:MaterialLink icon="mdi-content-send" iconPosition="left" textColor="grey"  text="Sent Mail" />
			<m:MaterialLink icon="mdi-content-drafts" iconPosition="left" textColor="grey"  text="Drafts" />
			<m:MaterialLink icon="mdi-content-markunread" iconPosition="left" textColor="grey"  text="All Mail" />
</m:MaterialSideNav>
```

**Comment by asmaalej** [comment]
Ok that's great idea to separate MaterialNavBar and materialSideBar, but this feature is very important in my case and urgent to get work right now. So if you have an idea how could I fix it instantly or if my attempt to set the closeOnClick  property to true in the materialize.js file could be successful or not, please let me know

**Comment by kevzlou7979** [comment]
Hi,

Yes closeOnClick is the way to go. Thats what I did on the new sidenav
property.

Regards,
Kevin

**Comment by asmaalej** [comment]
so why it doesn't works for me, this is the code I found in the materialize.je:

 var methods = {
    init : function(options) {
      var defaults = {
        menuWidth: 240,
        edge: 'left',
        closeOnClick: true
      }

but I didn't see a result when I clicked on the sub menu link.

**Comment by asmaalej** [comment]
furthermore when I checked if this option is enabled or not on the 
http://gwt-material-demo.herokuapp.com/#about  site, I discovered that it works fine, so what I have missed to let it works also ?? 

THanks in advance

**Comment by kevzlou7979** [comment]
call the method sideNav.hide() everytime you click a link for the moment

**Comment by asmaalej** [comment]
did you mean navBar.hide() ?? because the sideNav is just an attribute of the MaterialNavBar element, 
and when we want to get it with :navBar.getSideNav() we'll get a String

**Comment by kevzlou7979** [comment]
ah sorry my bad, call navBar.hide();

**Comment by asmaalej** [comment]
oh thanks so much, that's worked finally, but I have just an other problem, and I hope you could help me.
Actually my submenu height of my collapsible-body are too large (64px) and I wanna get them smaller (45px) than the collapsible-header, but when I set their height with css attribute within my UiBinder, I get always the height set to 64px but it's just cut from the bottom to show only the 45px I want. 
then when I track the css style in the chrome developer tool, I find that the header and the sub menu items call the same style and can't set their style separately.

Normally, I think that the sub menu Item of the collapsible-Item have to call the following style of the materialize.blue.css:

 .side-nav .collapsible-body li a {
    margin: 0 1rem 0 2rem; 
 ;}

exaclty like in your http://gwt-material-demo.herokuapp.com/#about site but that's not happening.
may be you are enough annoyed, but It's very important and urgent for me. 
thank you for your comprehension

**Comment by asmaalej** [comment]
any idea Kevin ,please ??

**Comment by kevzlou7979** [comment]
Can you provide me the screenshot so that it will be precise when it comes
to visualization. It will help me to figure out faster :)

**Comment by asmaalej** [comment]
here is a link to to the appropriate image
http://wikisend.com/download/987360/sideNav.png
I hope it's clear enough

thanks

**Comment by kevzlou7979** [comment]
thanks I will check this part

**Comment by kevzlou7979** [comment]
on the submenu we have a fixed height thats why its not getting youre
desired height,
On possible fix is for Collapsible Menu to have MaterialLink as header

**Comment by asmaalej** [comment]
So what can I do in this case ??
here you are a screenshot of my html generated source code,
http://wikisend.com/download/335856/subMenuLink-style.png

**Comment by kevzlou7979** [comment]
Hi ,

I think you can do this trick un your uibinder


first define this in your ui:style

@external side-nav;
.collapseSideBar .side-nav a{
height: 45px !important;
}

then add stylename into your collapse sidebar
like this:


<m:MaterialNavBar addStyleNames="{style.collapseNavBar}">
    <m:sidebaritem>
        <m:MaterialCollapsible>
          .....
        </m:MaterialCollapsible>
    </m:sidebaritem>
</m:MaterialNavBar>

**Comment by asmaalej** [comment]
ok that's works fine for the sub menu item, but it have unfortunately affected the collapsible-header, ????

**Comment by asmaalej** [comment]
especially when I want to add the 'line-height:45px' property in order to make them in the middle, so that the collapsible header will be on the top of their container ???

**Comment by asmaalej** [comment]
have you an idea how to avoid that collapsible header be affected with the external style I added ?
thank you a lot

**Comment by kevzlou7979** [comment]
Use {style.collapse} so that gwt will generate a unique class

**Comment by asmaalej** [comment]
excuse but could you be more clear, is this a predefined style and where should I put it.
Thanks a lot

**Comment by kevzlou7979** [comment]
yes its a predefined style , just add it into your collapsible component,
