### ISSUE TITLE
DatePicker disappears on Chrome version 73

### ISSUE THREAD

**Issue by mbudnick** [GwtMaterialDesign/gwt-material#901]
If you click down with Chrome Version 73 in an inputfield with datePicker the overlay appear.
If you release the klick the overlay disappear.
If you then change into an other tab and came back the overlay is visible once again and you can use the datePicker.

**Comment by fzamagni** [comment]
Goodmorning.
I confirm the bug: I have just updated Chrome to version 73 and the bug appears.
For me doesn't work changing tab and come back: MaterialDatePicker doesn't work ever.
Same Issue on MaterialTimePicker.

We use Java 7 and GMD 1.6.2, but I have the same issue on demo sites of GMD 2.1.1 and 2.2.

**Comment by kevin-i3** [comment]
Thanks for the catch, will be having a bug fixing session as soon as possible.

**Comment by burl21** [comment]
I noticed that when the click is over the placeholder(label) the modal do not close, works correctly.

**Comment by washowasho** [comment]
This also applies to the TimePicker as well.

**Comment by Shogikishi** [comment]
Any updates on this issue?

**Comment by Shogikishi** [comment]
> Thanks for the catch, will be having a bug fixing session as soon as possible.

Any updates on this issue?

**Comment by h3r3t1c** [comment]
Here is my quick fix to get the date picker dialog to open:
```java
MaterialDatePicker mDatePicker = new MaterialDatePicker(){

	@Override
	protected void onLoad() {
		super.onLoad();
		final MaterialDatePicker dp = this;
		this.getElement().getStyle().setPosition(Position.RELATIVE);
		MaterialPanel p = new MaterialPanel();
		p.getElement().getStyle().setPosition(Position.ABSOLUTE);
		p.getElement().getStyle().setZIndex(100);
		p.setHeight("50px");
		p.setWidth("100%");
		p.getElement().getStyle().setTop(0, Unit.PX);
		p.getElement().getStyle().setCursor(Cursor.POINTER);
		p.addClickHandler(new ClickHandler() {

			@Override
			public void onClick(ClickEvent event) {
				dp.open();
			}});
		this.add(p);
	}
	
};
```
This also works with MaterialTimePicker.

**Comment by kevin-i3** [comment]
Tested the old showcase and new one, I think there was an issue with the new Chrome 73. Will be applying a patch today and release a snapshot 2.2 tomorrow early

**Comment by kevin-i3** [comment]
Related issue https://github.com/amsul/pickadate.js/issues/1138

**Comment by kevin-i3** [comment]
https://github.com/amsul/pickadate.js/commit/82900d689ca416fe9a3b90cd86c91a4d5f567981 This was there commit. We might need to apply this patch directly from materialize.js.

**Comment by kevzlou7979** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=941910

**Comment by kevin-i3** [comment]
https://stackoverflow.com/questions/55147819/chrome-update-73-materialize-css-js-trigger-error

**Comment by kevin-i3** [comment]
Tested also on time picker.

**Comment by washowasho** [comment]
Is the 2.2-SNAPSHOT on the Maven Central repo? Or is it somewhere else?

**Comment by kevin-i3** [comment]
Just pushing the changes, 2.2-SNAPSHOT was on Maven Central.

**Comment by kevin-i3** [comment]
DatePicker has been updated and resolved the issue on 2.2-SNAPSHOT

**Comment by kevin-i3** [comment]
![dp-tp-updates](https://user-images.githubusercontent.com/38387414/55549287-15497000-5708-11e9-945b-1622271b9746.gif)

Ok Timepicker and DatePicker has been fully patched on 2.2-SNAPSHOT. Check them out.

**Comment by washowasho** [comment]
I'm looking here, and I don't see it. Am I looking in the wrong spot?

http://central.maven.org/maven2/com/github/gwtmaterialdesign/gwt-material/

**Comment by kevzlou7979** [comment]
It's here https://oss.sonatype.org/content/repositories/snapshots/com/github/gwtmaterialdesign/

**Comment by kevzlou7979** [comment]
If you are using maven then it will auto-download the update, if jar then you need to download it directly from the link I've shared

**Comment by washowasho** [comment]
Got it. That was exactly it,... my Maven wasn't tied to the repository. Thanks man.

	  <repository>
	        <id>oss-sonatype</id>
	        <name>oss-sonatype</name>
	        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
	        <snapshots>
	            <enabled>true</enabled>
	        </snapshots>
	  </repository>

**Comment by chamgda** [comment]
This issue is only partially fixed in the version deployed on https://gwtmaterialdesign.github.io/gmd-core-demo/#datePicker. If you do not release the mouse button immediately when clicking anywhere else but the label of the datepicker, the behaviour is just like before.
Interestingly when clicking on the label, the datepicker is only opened on mouse-up and stays open, when you click on the input, the datepicker is opened on mouse-down and closes on mouse-up if you don't release the mouse button immediately.
