### ISSUE TITLE
MediaQueries that change NavBar height/expandable SidNavMini height don't match

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#903]
materialize.css defines 

```
@media only screen and (min-width: 601px)
nav, nav .nav-wrapper i, nav a.button-collapse, nav a.button-collapse i {
    height: 64px;
    line-height: 64px;
}
```

while override.css defines

```
@media screen and (max-width: 992px)
ul.side-nav.mini-with-expand {
    top: 56px;
    height: calc(100vh - 56px);
}
```

resulting in the expandable SideNavMini overlapping the NavBar by 8px if the screen width is between 601px and 992px.

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/71e3a8cf026fe34b24a74f8386859002caf4e6ca
