### ISSUE TITLE
Removing the CollapsibleItem that contains the active ListItem in the CollapsibleBody causes a JS Exception

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#905]
Given a MaterialCollapsible of the following structure (used in a SideNav)

```
<MaterialCollapsible>
    <MaterialCollapsibleItem>
        <MaterialCollapsibleHeader />
        <MaterialCollapsibleBody>
            <UnorderedList>
                <ListItem>
                    <MaterialLink />
                </ListItem>
                <ListItem>
                    <MaterialLink />
                </ListItem>
                <ListItem>
                    <MaterialLink />
                </ListItem>
            </UnorderedList>
        </MaterialCollapsibleBody>
    </MaterialCollapsibleItem>
    .
    .
    .
</MaterialCollapsible>
```

if you remove a CollapsibleItem while one of the contained ListItems is active, a JavaScriptException occurs:

`Cannot read property 'clearActive__V' of null`

This is caused by the remove implementation of MaterialCollapsible recursivly setting the parent of all HasCollapsibleParent children to null and MaterialCollapsibleBody.makeActive() calling parent.clearActive() without a null check on the parent.

**Comment by kevzlou7979** [comment]
Thanks for the catch will be fixing asap
