### ISSUE TITLE
MaterialCheckbox (BaseCheckBox) directionTextHelper is null

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#908]
When I create checkboxes programmatically I used with version 2.1.1 just
`new MaterialCheckBox("my label");`
But now I updated to 2.2-SNAPSHOT and now it crashes in `setText` because the directionTextHelper is not set in the constructors.

Any ideas please?

**Comment by wassx** [comment]
Current workaround:
`MaterialCheckBox checkBox = new MaterialCheckBox();
   checkBox.setText("mylabel");`

**Comment by kevzlou7979** [comment]
Thanks for the catch, on 2.2 we have migrated our MAterialCheckbox to extend MaterialWidget, so We need to update also the default BaseCheckBox property on it's constructors. Let me update the 2.2 Checkbox.
