### ISSUE TITLE
MaterialFAB issue when FABType is set to CLICK_ONLY

### ISSUE THREAD

**Issue by happyhua** [GwtMaterialDesign/gwt-material#909]
MaterialFAB does not open or close when FABType is set to CLICK_ONLY.

https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialFAB.java#L109

When lines 109 and 128 are removed, the click handler works. So it seems that  these two lines should be removed.

**Comment by kevzlou7979** [comment]
Can't reproduce with 2.2-SNAPSHOT, the code `$(getElement()).openFAB();` will be needed for Internal js command to open up the fab. Can you post me the GMD Version and a small code snippet.

**Comment by kevzlou7979** [comment]
![gmd2](https://user-images.githubusercontent.com/3138071/57270978-1c292100-70c0-11e9-8640-a4085396b3b7.gif)

**Comment by happyhua** [comment]
Hmm, I see the problem. The click does not work if the main button is MaterialAnchorButton instead of MaterialButton.

**Comment by kevzlou7979** [comment]
Oh i see, will check this out.

**Comment by jswart** [comment]
I just ran into the same issue. I used the following example in the online documentation:

![image](https://user-images.githubusercontent.com/1425104/59935671-4f2f3600-941c-11e9-8b42-a9cb50e7e145.png)

Switching to MaterialButton and away from MaterialAnchorButton solved the problem. I am not sure if the documentation is incorrect, or if there is a bug.
