### ISSUE TITLE
MaterialNavBar menu button visible when unused

### ISSUE THREAD

**Issue by shadeMe** [GwtMaterialDesign/gwt-material#910]
When using MaterialNavBar widget without an attached SideNav, the embedded `navMenu` MaterialLink widget in the `navWrapper` div is always visible on all non-large screen devices.

Trying to remove the widget manually (using `getMenu().removeFromParent()`) does not work. I'm currently working around it by setting the HideOn property to `MED_DOWN`.

Version: GMD 2.1

![gmd bug](https://user-images.githubusercontent.com/214450/56955291-453a3680-6b41-11e9-9bf6-e2d628828723.JPG)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/8c3c4b55a237c4fa6e93e860f76b1c3b6d53df57
