### ISSUE TITLE
Small IconMorphs in NavBar get clipped

### ISSUE THREAD

**Issue by shadeMe** [GwtMaterialDesign/gwt-material#911]
```
<m:MaterialNavBar ui:field="navMainUI" backgroundColor="ORANGE_ACCENT_3">
                <m:MaterialLink ui:field="tglSettingsPaneUI" waves="LIGHT" paddingLeft="10" paddingRight="5">
                    <m.morph:MaterialIconMorph ui:field="icoSettingsMorphUI" iconSize="SMALL">
    					<m:MaterialIcon iconType="ARROW_BACK"/>
    					<m:MaterialIcon iconType="SETTINGS"/>
					</m.morph:MaterialIconMorph>
				</m:MaterialLink>
            </m:MaterialNavBar>
```
I'm using the above code to display a custom menu icon on the NavBar. This causes the clipping shown below. Also, it appears that the morphing animation is also affected, i.e., instead of swirling in-place into the alternate icon, you can see the first icon rotating around to reveal the second.

Version: GMD 2.1

![gmd bug](https://user-images.githubusercontent.com/214450/56956235-dca08900-6b43-11e9-9faf-121d20c3a637.JPG)

**Comment by kevzlou7979** [comment]
Thanks for the catch will be gathering more bugs then i can do a bug fixed
on weekends. Also will prioritized a release of 2.2

**Comment by kevzlou7979** [comment]
![gmd1](https://user-images.githubusercontent.com/3138071/57257540-524cad80-708c-11e9-9ac8-baa0d083dba0.gif)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-addins/commit/2aa149d6acf96bcb0a1665cc2a7ecce1d13b1beb
