### ISSUE TITLE
SideNav only draggable at the margin

### ISSUE THREAD

**Issue by shadeMe** [GwtMaterialDesign/gwt-material#912]
Unless, I'm much mistaken, none of the implementations of the SideNav support dismissal by dragging/swiping from inside the bar itself (only a small section close to the margin is set as the drag target. 

The current behaviour is not very consistent/intuitive on mobile devices. It would be great if the width of the section could be increased or, better yet, exposed in the public API.

**Comment by kevzlou7979** [comment]
We can add this and discuss further on 2.3
