### ISSUE TITLE
Revert to default MaterialCollapsible style inside SideNavs

### ISSUE THREAD

**Issue by shadeMe** [GwtMaterialDesign/gwt-material#913]
EDIT: According to [this page](https://gwtmaterialdesign.github.io/gmd-core-demo/#collapsible_items), this is the expected behaviour. Could we have the option to disable it?

MaterialCollapsible components inside SideNavs (wrapped inside a MaterialSideNavContent) are broken.

What they look like:
![gmd bug](https://user-images.githubusercontent.com/214450/57041321-3dbe7e80-6c62-11e9-98c3-c2e8ac7d0dae.JPG)

What they should look like:
![gmd bug 1](https://user-images.githubusercontent.com/214450/57041338-42833280-6c62-11e9-88c0-7c10912f7d11.JPG)

**Comment by kevzlou7979** [comment]
Yeah youre right, this was an intended and inherited behaviour on Materialize, Collapsibles are being reused on Sidenav to support  nested levels. But as i can forsee we can make use of the SideNavContent to say, we need to override all default sidenav inheritance styles to the collapsibles. 

I Should standardized this on 2.3
