### ISSUE TITLE
MaterialCarousel throws IllegalStateException in UiBinder

### ISSUE THREAD

**Issue by shadeMe** [GwtMaterialDesign/gwt-material#914]
Attempting to use UIBinder to initialize a MaterialCarousel widget causes it to throw an IllegalStateException due to the parent container being detached. The bug can be easily reproduced by simply using any of the example code found in the demo.

Version: 2.1.1

**Comment by kevzlou7979** [comment]
Migrated to https://github.com/GwtMaterialDesign/gwt-material-addins/issues/385
