### ISSUE TITLE
AbstractPageSelection overrides setLabel to hardcoded set the label to "Page"

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#916]
This is a no go for i18n and the implementation makes zero sense to me. Why wouldn't you allow to set the label?

**Comment by kevzlou7979** [comment]
This is a typo, i think. Will update this asap.

**Comment by kevzlou7979** [comment]
The correct code is `pageLabel.setText(label);` instead of hardcoded `pageLabel.setText("Page");` again thanks for the catch. Will be patching 2.2-SNAPSHOT

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-table/commit/eed933cafe77665cd10cb9942f866441f66ca191
