### ISSUE TITLE
RowSelection hardcoded sets the label to "Rows per page"

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#917]
This is a no go for i18n. I can create my own implementation and add a setLabel method that calls rowsPerPageLabel.setText but why do I even have to do this...

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material-table/commit/a6f6f7ee1bf62f7d3e2c24310a1bdb4b70f2194d
