### ISSUE TITLE
Wrong Tab-Indicator width at the first Tab-load

### ISSUE THREAD

**Issue by HoochSDS** [GwtMaterialDesign/gwt-material#924]
Hi, The Tab-Indicator has always the s12 width, if you load the GMD-Tab Widget.
I tried the Workaround (Reload to update indicator position), with the GWTP onReveal() Function. 

```
tabBasic.reload();
```
but this has no effect.

You can see this issue on the core GMD 2.2 Demo as well.
https://gwtmaterialdesign.github.io/gmd-core-demo/#tabs

![TabIndicator](https://user-images.githubusercontent.com/24357072/61239680-c5833780-a73f-11e9-8e89-e0f670095b3c.png)

For reproduction:
1) Clear Browser Cache
2) Go to https://gwtmaterialdesign.github.io/gmd-core-demo
3) Click Tabs

Is there a workaround for this. 
Many thanks

**Comment by kevzlou7979** [comment]
This has been fixed on GMD 2.3.x . See https://github.com/GwtMaterialDesign/gmd-core-demo/blob/master/src/main/java/gmd/core/demo/client/application/page/tabs/TabsPresenter.java#L63
