### ISSUE TITLE
Feature Request - add setAltText to ImageMixin

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#925]
Standard GWT Images offer the option to set the alt attribute on the image.
It would be nice to have a shorthand method to do that on MaterialImage/ImageMixin too instead of having to call getElement().setAttribute("alt", "some alt text").

**Comment by kevzlou7979** [comment]
This was added to GMD 2.2 https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialImage.java#L157
