### ISSUE TITLE
MaterialSearch close icon has MouseDownHandler instead of ClickHandler

### ISSUE THREAD

**Issue by chamgda** [GwtMaterialDesign/gwt-material#926]
MaterialSearch adds a MouseDownHandler on the close icon instead of a click handler for whatever reason. This makes its behaviour inconsistent with other controls and also makes it harder to make the widget keyboard controllable (can't just call click() on the element as you can when the element has a ClickHandler).

**Comment by kevzlou7979** [comment]
Will revalidate this and will patch on GMD 2.3

**Comment by kevzlou7979** [comment]
Fixed https://github.com/GwtMaterialDesign/gwt-material/commit/52c1a7a1abeb524ce3b6fd54186386d37e61d053
