### ISSUE TITLE
MaterialSeach KeyDown/KeyUp error

### ISSUE THREAD

**Issue by happyhua** [GwtMaterialDesign/gwt-material#932]
There is a bug (IndexOutofbounds exception) in MaterialSeach, which handles key down or key event.

This happens when you are on the top of suggestion list and press key up button. Or you are on the bottom of suggestion list and press key down button.

The code which handles key up or key down event can be found here.

https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialSearch.java#L215

**Comment by kevzlou7979** [comment]
Oh I see, will be patching this on 2.3-SNAPSHOT

**Comment by happyhua** [comment]
Do you accept PR or not?
I made a PR 3 weeks ago, but never get a response.

https://github.com/GwtMaterialDesign/gwt-material/pull/934

**Comment by kevzlou7979** [comment]
Will be adding this on 2.4.1 release.

**Comment by kevzlou7979** [comment]
This has been merged on 2.4.1 release https://github.com/GwtMaterialDesign/gwt-material/pull/978
