### ISSUE TITLE
MaterialDatatable cause UmbrellaException

### ISSUE THREAD

**Issue by simontosser** [GwtMaterialDesign/gwt-material#933]
Hi,
I have some MaterialDatatable in my Web apps.
When I access to my webapps by main URL, all work fine, but if I access by URL with tokken (for example : http://localhost:8080/#commandes) MaterialDatatable cause this error : Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : $wnd.$ is not a function

**Comment by kevzlou7979** [comment]
Make sure JQuery is loaded to your application, can you give us the version of GMD you are using and what modules you inherit in your `***.gwt.xml` module

**Comment by kevzlou7979** [comment]
This was solved recently on datatable closing now on 2.3.
