### ISSUE TITLE
Inconsistencies between materialize.js and materialize.min.js?

### ISSUE THREAD

**Issue by gevaerts** [GwtMaterialDesign/gwt-material#936]
I was looking at the commit logs, and I noticed that 6b118303 changes materialize-0.97.5.js but not materialize-0.97.5.min.js. There doesn't seem to be a follow-up commit to materialize-0.97.5.min.js. The corresponding changes might of course appear in a later commit without mentioning it (I'm not sure, I'm bad at reading minified javascript diffs...), but even if so, at least releases 2.0, 2.0.1, 2.1 might have inconsistent code between debug and release builds.

I don't know if there is an actual bug, but I think this should be checked.

**Comment by kevzlou7979** [comment]
I just reviewed the `materialize.min.js` on release 2.3-SNAPSHOT and it seems it has been updated. and also 2.2. Might need to do a patch release for 2.1 though like 2.1.1 (For this update only)
