### ISSUE TITLE
Bind OrderedSlot to MaterialPanel with GWTP

### ISSUE THREAD

**Issue by mitrakov** [GwtMaterialDesign/gwt-material#939]
I am trying to bind an `OrderedSlot` to a `MaterialPanel` in GWTP. 
```
@UiField
MaterialPanel subitems;
...
bindSlot(MyPresenter.ORDERED_SLOT, subitems);
```
But it throws:
```
method com.gwtplatform.mvp.client.ViewImpl.<T>bindSlot(com.gwtplatform.mvp.client.presenter.slots.OrderedSlot<?>,T) is not applicable
      (inferred type does not conform to upper bound(s)
        inferred: gwt.material.design.client.ui.MaterialPanel
        upper bound(s): com.google.gwt.user.client.ui.HasWidgets,com.google.gwt.user.client.ui.InsertPanel)
```

which means that `MaterialPanel` does not implement `InsertPanel`.

What do you think of making `MaterialPanel` derived from `InsertPanel`?

**Comment by kevzlou7979** [comment]
We need to review this with our team.

**Comment by BenDol** [comment]
Implementing `InsertPanel` on the MaterialPanel isn't a bad idea actually, given that MaterialWidget is technically a `ComplexPanel`. Although I wonder why bindSlot doesn't accept `Panel` and rather expects `InsertPanel`.
