### ISSUE TITLE
What version of materializecss is being used in 2.3.0?

### ISSUE THREAD

**Issue by jeff-sweetjacket** [GwtMaterialDesign/gwt-material#948]
I'm having some issues as I'm using materializecss 1.0.0 and including it myself in html pages.  And effectively excluding it from loading via gwt as my module file looks like:

`<?xml version="1.0" encoding="UTF-8"?>
<module>

	<inherits name="com.google.gwt.user.User" />

	<inherits name="org.fusesource.restygwt.RestyGWT" />

	<inherits name="gwt.material.design.GwtMaterialDesignBase"/>

	<replace-with class="gwt.material.design.client.JQueryProvider.JQueryCompressed">
		<when-type-is class="gwt.material.design.client.JQueryProvider"/>
	</replace-with>
    
    <inherits name="org.apache.commons.GWTCommonsLang3" />
    
	<source path="client" />

	<source path="shared" />

	<add-linker name="xsiframe" />

</module>`

The current error I'm seeing is 
`$wnd.$(...).openModal is not a function`

And I'm just trying to open a material modal by

```
MaterialDialog md = new MaterialDialog();
				
RootPanel.get().add(md);
				
md.open();

```
So looks like it's trying to call openModal but in materializecss 1.0.0 the function is now just called open.

https://materializecss.com/modals.html

If gmd is using an older version of materializecss are there plans to support 1.0.0?

**Comment by kevzlou7979** [comment]
We use v0.97.5. We dont have a plan yet to support 1.0.0

**Comment by jeff-hrapplabs** [comment]
Cool.  Thanks for the response.  I've got it working by adding my own class:

`@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class GmdExtensionsJs extends JQueryElement {

    @JsMethod(name = "$", namespace = JsPackage.GLOBAL)
    public static native GmdExtensionsJs $(JQueryElement element);

    @JsMethod(name = "$", namespace = JsPackage.GLOBAL)
    public static native GmdExtensionsJs $(Element element);

    @JsMethod(name = "$", namespace = JsPackage.GLOBAL)
    public static native GmdExtensionsJs $(String selector);
    
    @JsMethod
    public native JQueryElement modal();
    
    @JsMethod
    public native JQueryElement modal(String method);
    
}

And then extending MaterialDialog with methods

`@Override
	public void open() {
		
		$(getElement()).modal("open");
		
        Scheduler.get().scheduleDeferred(() -> $(getElement()).focus());
	}
	
	@Override
	public void close() {
		
		$(getElement()).modal("close");
	}`

I'm happy to help with moving to materializecss 1.0.0.  I'm sure you'll know more than me about what it would entail!  Anyway - happy to help.
