### ISSUE TITLE
Error calling addBlurHandler on gwt material 2.3.0 when compiling with GWT 2.8.2

### ISSUE THREAD

**Issue by andreififiita** [GwtMaterialDesign/gwt-material#952]
GWT Material version: 2.3.0
I am trying to use the addBlurHandler method of the MaterialTextBox on gwt 2.8.2, but i get this error (in superdevmode):

Exception: com.google.gwt.core.client.JavaScriptException: (ReferenceError) : Xzq_g$ is not defined
ReferenceError: Xzq_g$ is not defined
    at FMf_g$.hJf_g$ [as addBlurHandler_0_g$] (MaterialValueBox.java:709) 

This issue does not appear when compiling with GWT 2.8.1. I tried multiple cleanings of the gwt output but no luck

**Comment by kevzlou7979** [comment]
I tried to reproduce but on `GWT 2.8.2` its working fine.
![image](https://user-images.githubusercontent.com/3138071/77601378-90bdb600-6f45-11ea-86c2-198c676edd45.png)

![image](https://user-images.githubusercontent.com/3138071/77601403-9ddaa500-6f45-11ea-9794-c862bef1a3dd.png)

Have you tried to clean GWT cache?

![image](https://user-images.githubusercontent.com/3138071/77601429-b21ea200-6f45-11ea-8d59-6d5f652d3da2.png)

**Comment by andreififiita** [comment]
Hi. I tried clearing cache a few times and it didn't work , but after now I tried that again it was ok. Thank you
