### ISSUE TITLE
When i aam trying to install i am getting [INFO]       [ERROR] Unable to find 'com/gwtmaterial/tutorial/com/gwtmaterial/tutorial.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

### ISSUE THREAD

**Issue by sanoobdesign008** [GwtMaterialDesign/gwt-material#957]
I am using this code for create a project 
mvn archetype:generate -DarchetypeGroupId=com.github.gwtmaterialdesign -DarchetypeArtifactId=gwt-material-archetype -DarchetypeVersion=2.3.0
this is the code which try to generate project from github

Please advice me

**Comment by kevzlou7979** [comment]
Was this solved already? Im thinking you have an  issue with your jdk as i remember from the previous discussion.
