### ISSUE TITLE
MaterialListBox html item

### ISSUE THREAD

**Issue by andreififiita** [GwtMaterialDesign/gwt-material#959]
Is it possible to add an item into a list box as html and not plain text?

**Comment by kevzlou7979** [comment]
On MaterialCombobox 2.3.1 we have added a way to template your item list with html element. On MaterialListBox we just support a pretty basic text option.

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/81791605-82e5e380-9539-11ea-8092-b70984c8677e.png)
