### ISSUE TITLE
Material Nav Bar : Tabs implementation (Multi tab panels)

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#96]
Tabs above material nav bar 
<h3>Screenshot</h3>
![image](https://cloud.githubusercontent.com/assets/3138071/10062887/3072a312-629a-11e5-8439-6ac048c5e2da.png)

**Comment by niveo** [comment]
when can I use Material 2.0 with "Multi tap panels"?
Nice component.

**Comment by kevzlou7979** [comment]
This implemented on gwt material patterns
