### ISSUE TITLE
Wrong disabled style in dark mode sidenav

### ISSUE THREAD

**Issue by beppino** [GwtMaterialDesign/gwt-material#960]
In Dark Mode, I found strange the situation in the attached image. The first two items are enabled but the last three are disabled. The color of the icons seems to be inverted and the labels not affected.
Find a "solution" inserting in app-dark.css this:

```
.side-nav a {
    color: #9f9f9f;
}

i.disabled, a.disabled, a.disabled i, a.disabled span {
    color: #444!important;
}
```

<img width="240" alt="Screenshot 2020-04-24 at 08 56 34" src="https://user-images.githubusercontent.com/333788/81793907-44850000-950a-11ea-89b1-f31118513fc1.png">

**Comment by kevzlou7979** [comment]
Ok come up with the right styles - will be patching this on 2.3.1-SNAPSHOT 
![image](https://user-images.githubusercontent.com/3138071/82020058-fb27e280-96ba-11ea-8f20-04437f8fab04.png)

**Comment by kevzlou7979** [comment]
Here's the patch outcome.
![image](https://user-images.githubusercontent.com/3138071/82020151-2e6a7180-96bb-11ea-8fb3-2fe8b6470a7f.png)

**Comment by kevzlou7979** [comment]
For now you can patch and include this snippet to your `app-dark.css`:

```
ul.side-nav i {
    color: rgba(255, 255, 255, .9);
}

ul.side-nav li.active i,
ul.side-nav li:hover i {
    color: #b180ed;
}
```

**Comment by kevzlou7979** [comment]
Fixed
