### ISSUE TITLE
Calling setRequired(false) makes the field required

### ISSUE THREAD

**Issue by Fl0w3D** [GwtMaterialDesign/gwt-material#961]
https://github.com/GwtMaterialDesign/gwt-material/blob/580869fd46ed49ba9715b70b2b68368cc8ed5c84/gwt-material/src/main/java/gwt/material/design/client/base/mixin/RequiredFieldMixin.java#L55

If I call setRequired with the parameter "false", setAllowBlank is also called with the value false instead of !required, resulting in a required value.
I can't see why validateOnBlur is called at all, nor why allowBlank is called with false.

**Comment by kevzlou7979** [comment]
Ok will be looking into this on weekend.

**Comment by kevzlou7979** [comment]
Can you reproduce this issue on 2.4.0-rc1 ?

**Comment by Fl0w3D** [comment]
Yes, as soon as I call setRequired with the parameter false, blank value is not allowed anymore.
The explanation I wrote in my first message is still true: no matter what value is given to setRequired, the methods setValidateOnBlur and setAllowBlank are called, the first one with hard-coded parameter true, the second one with hard-coded parameter false, which disallow blank value.

**Comment by kevzlou7979** [comment]
Ok fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/cce5107101e48cb55b46b0d4f6310003a82b1b11. Added also a Unit Test
