### ISSUE TITLE
Safari needs old api support

### ISSUE THREAD

**Issue by beppino** [GwtMaterialDesign/gwt-material#962]
I've found a (maybe) bug.
If I load my webapp (structure like gmd-core-demo) in safari for iOs (last version of safari and iOs), my app show the splash screen and nothing else. 
If I remove the Notification.requestPermission(callback); call all seems to be ok.
Thanks for your attention
-g

**Comment by kevzlou7979** [comment]
The PWA might not be support on older safari I think. 

What you can is to check it with `PwaManager.isPwaSupported()` then call your method.
