### ISSUE TITLE
GWT 2.9 compatibility

### ISSUE THREAD

**Issue by gkresic** [GwtMaterialDesign/gwt-material#964]
Is GMD 2.3.0 compatible with recently released GWT 2.9?

For example, `MaterialDatePicker.load()` throws `ClassCastException` in [line 143](https://github.com/GwtMaterialDesign/gwt-material/blob/3a80499d45c549512716937d4e1ecfa43bbdf706/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialDatePicker.java#L143) which suggest incomatibilities with changes in JsInterop GWT 2.9 introduced.

**Comment by kevzlou7979** [comment]
I'll look into it furst thing tomorrow.

**Comment by kevzlou7979** [comment]
Released on 2.4.0-rc1
