### ISSUE TITLE
Checkbox in datatable not clickable

### ISSUE THREAD

**Issue by Frintrop** [GwtMaterialDesign/gwt-material#966]
Hi .. in gwt material demo we can not click checkboxes in datatable ... only if we click in row somewhere else, checkbox gets selected.
"infinite" datatable´s checkbox is working fine.. any idea to solve this ? 
as checkboxes are a very important feature in datatables, would fine to get a fix for that.

**Comment by kevzlou7979** [comment]
Ok will take a look today.

**Comment by kevzlou7979** [comment]
Try setting the RowCooldown to 0 like:
`table.setRowClickCooldown(0);`

**Comment by kevzlou7979** [comment]
Try setting the `table.setRowClickCooldown(0);` It seems that having two checkboxes on the datatable causes the issue. Will take a look for this deeper.
