### ISSUE TITLE
Two checkBoxes appearing in GWT Material Table

### ISSUE THREAD

**Issue by junaidp** [GwtMaterialDesign/gwt-material#967]
![image](https://user-images.githubusercontent.com/747843/85709705-d07f6f80-b6e5-11ea-8444-d37bf07aadf7.png)

When upgraded to GMD 2.9  ,  We see two checkboxes in the table when we do only 
  
table.setSelectionType(SelectionType.SINGLE);

I am not adding any separate column for adding the CheckBox , If i remove the above line , We dont see Any checkBox.

**Comment by kevzlou7979** [comment]
I can't reproduce this with the demo project on https://github.com/GwtMaterialDesign/gwt-material-table

![image](https://user-images.githubusercontent.com/3138071/85805926-3ae4ee00-b780-11ea-81e5-e85f3c0e1ef2.png)

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/85806060-9a42fe00-b780-11ea-90ba-170c5533a425.png)

**Comment by junaidp** [comment]
Thanks for pointing out, Yes i found , we have removed this left:-9999px, So we can use the existing checkboxes wherever they are ..

So is there a way i can remove the old default CheckBox only for the grid  , and not for the whole application

**Comment by junaidp** [comment]
ok, its done 

i did this (left:-999px) in  a separate css for only material tables
