### ISSUE TITLE
MIgration of Jquery from 2.x to 3.5 

### ISSUE THREAD

**Issue by two10** [GwtMaterialDesign/gwt-material#968]
we are a enterprise company and we use Gwt material.

In our VAPT scan we are getting jquery error that jquery version 2.2 has vulnerabilities , we need to upgrade to 3.5 or above in gwt .

is this in current roadmap or is there any workaround for those   [vulnerabilities](https://snyk.io/vuln/npm:jquery@2.2.0) . 

or can somebody guide us onto how to migrate that , may be our dev can help in this.

**Comment by kevzlou7979** [comment]
We are migrating currently the JQuery version to 3.x https://github.com/GwtMaterialDesign/gwt-material/pull/969
