### ISSUE TITLE
MaterialCheckBox no longer applies gwt-CheckBox class

### ISSUE THREAD

**Issue by Medo42** [GwtMaterialDesign/gwt-material#973]
Seen in GwtMaterialDesign 2.2

The "gwt-CheckBox" styleclass was still being applied to the main div element of a CheckBox in version 2.1.1. In v2.2, the class is missing, which breaks some of our css stylesheets.

I believe the issue was introduced in this commit:
https://github.com/GwtMaterialDesign/gwt-material/commit/c4c7dda2a69704b5acb94c71e131c81de3e924a2

As you can see, the style class used to be applied immediately in the constructor of BaseCheckBox, but that line was removed. Now, the code appears to rely on MaterialWidget setting the class as one of the initialClasses in the onLoad method. However, BaseCheckBox overrides onLoad and does not call super.onLoad in turn, so the MaterialWidget implementation of onLoad never runs for BaseCheckBox instances (possibly a bug in its own right, but I don't know the code well enough to judge that), and thus the gwt-CheckBox initalClass is never set.

**Comment by kevzlou7979** [comment]
Will try to reproduce first thing tomorrow.

**Comment by kevzlou7979** [comment]
This will be added on 2.4.1 - For bug fixes.

**Comment by kevzlou7979** [comment]
![image](https://user-images.githubusercontent.com/3138071/89836686-e237ac00-db99-11ea-8187-a174eb340236.png)

**Comment by kevzlou7979** [comment]
Fixed via https://github.com/GwtMaterialDesign/gwt-material/pull/976/commits/0978e2bfc1b8c27a1f9418e8b5aeb142b8e834fd
