### ISSUE TITLE
Removing tooltip from a widget

### ISSUE THREAD

**Issue by andreififiita** [GwtMaterialDesign/gwt-material#979]
It seems there is no way to remove a tooltip of a MaterialWidget from DOM once it has been set.
Is there a workaround for this?

**Comment by kevzlou7979** [comment]
Will take a look on this and will be adding to release 2.5.0

**Comment by kevzlou7979** [comment]
I think you can do this currently `delete.getTooltipElement().remove();`

**Comment by kevzlou7979** [comment]
Added via https://github.com/GwtMaterialDesign/gwt-material/issues/979

**Comment by andreififiita** [comment]
Seems it is not working correctly. After calling tooltipElement.remove(); calling setTooltip() again does not re-create the tooltip element
