### ISSUE TITLE
MaterialTab stays light

### ISSUE THREAD

**Issue by edmiikk** [GwtMaterialDesign/gwt-material#984]
V2.3.0 app. MaterialTab widget stays light them when rest of widgets are dark theme.
![tab_light](https://user-images.githubusercontent.com/26163153/91631752-d63e4d80-e9d3-11ea-8e57-764b7af6e4d2.png)

App based on the demo app with gin modules. One factor might be the use of padding in the TabPanel, otherwise the tabs are hidden behind the MaterialNavBar. Screen shot shows the Files module, ui xml below.

ApplicationView.ui.xml:
-----------------------------------------------------------------------------
<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:g='urn:import:com.google.gwt.user.client.ui'
             xmlns:m="urn:import:gwt.material.design.client.ui">
    <m:MaterialPanel>
        <m:MaterialHeader>
            <m:MaterialNavBar ui:field="navBar" activates="sidenav" backgroundColor="INDIGO">
                <m:MaterialNavBrand fontSize="1.2em" text="Admin ECgate" />
                <m:MaterialNavSection float="RIGHT" hideOn="NONE">
                    <m:MaterialDarkModeToggle/>
		            <m:MaterialImage ui:field="ocslogoImage" url="images/ocslogo.png" />
                </m:MaterialNavSection>
            </m:MaterialNavBar>
        </m:MaterialHeader>

        <m:MaterialSideNavPush m:id="sidenav" width="280">
            <m:MaterialLink text="Home" href="#"/>
            <m:MaterialLink text="Files" href="#files"/>
            <m:MaterialLink text="Shippers" href="#shippers"/>
        </m:MaterialSideNavPush>

        <m:MaterialContainer ui:field="container"/>

        
    </m:MaterialPanel>
</ui:UiBinder>
---------------------------------------------------------------------
FilesView.ui.xml
---------------------------------------------------------------------
<ui:UiBinder xmlns:ui='urn:ui:com.google.gwt.uibinder'
             xmlns:m='urn:import:gwt.material.design.client.ui'
			 xmlns:table="urn:import:gwt.material.design.client.ui.table">
<ui:with field='i18n' type='uk.co.nv.ag.client.i18n.AdmingateMessages' />
    <m:MaterialContainer>
	    <m:MaterialPanel paddingTop="70" m:id="tabPanel"> 
	    	<m:MaterialRow >
	    	<m:MaterialColumn grid="s4 m2 l2">
		        <m:MaterialTab ui:field="filesTab"  backgroundColor="BLUE" indicatorColor="YELLOW">
					<m:MaterialTabItem ui:field="filesTabItem" waves="YELLOW" grid="l4">
						<m:MaterialLink  ui:field="filesLink" text="{i18n.fileSearch}" href="#fileSearchTab" textColor="WHITE"/>
					</m:MaterialTabItem>
					<m:MaterialTabItem ui:field="fileDetailsTabItem" waves="YELLOW" grid="l4">
						<m:MaterialLink  ui:field="fileDetailsLink"  text="{i18n.fileDetails}" href="#fileDetailsTab" textColor="WHITE"/>
					</m:MaterialTabItem>
				</m:MaterialTab>
			</m:MaterialColumn>
			</m:MaterialRow>
		</m:MaterialPanel>
		<m:MaterialPanel m:id="fileSearchTab" >
			<m:MaterialCollapsible grid="s12 m6 l8">
				<m:MaterialCollapsibleItem ui:field="fileSearchPanel">
					<m:MaterialCollapsibleHeader ui:field="filesCollapsibleHeader" >
						<m:MaterialLink text="{i18n.search}" iconType="SEARCH" iconPosition="LEFT" textColor="BLACK"/>
					</m:MaterialCollapsibleHeader>
					<m:MaterialCollapsibleBody>
					
					<m:MaterialRow height="35">
				        <m:MaterialColumn grid="s4 m2 l2"><m:MaterialListValueBox ui:field="rootListBox"  width="8em" placeholder="{i18n.rootFolder}"/></m:MaterialColumn>
				        <m:MaterialColumn grid="s4 m2 l2"><m:MaterialListValueBox ui:field="subListBox"  width="8em" placeholder="{i18n.subFolder}"/></m:MaterialColumn>
				        <m:MaterialColumn grid="s2"><m:MaterialAnchorButton ui:field="searchOrdersButton" type="FLOATING" iconType="SEARCH" backgroundColor="WHITE" iconColor="GREEN" verticalAlign="BOTTOM" iconPosition="RIGHT" shadow="2"/></m:MaterialColumn>
					    <m:MaterialColumn grid="s2"><m:MaterialAnchorButton ui:field="resetSearchButton" type="FLOATING" title="{i18n.reset}" iconType="CLEAR"  backgroundColor="WHITE" iconColor="AMBER" waves="DEFAULT" verticalAlign="BOTTOM" iconPosition="RIGHT"  shadow="2"/></m:MaterialColumn>
				    </m:MaterialRow>
				    <m:MaterialRow height="35">
				   		<m:MaterialColumn grid="s2"><m:MaterialDatePicker ui:field="fromDatePicker"  placeholder="{i18n.fromDate}" /></m:MaterialColumn>
				    	<m:MaterialColumn grid="s2"><m:MaterialDatePicker ui:field="toDatePicker"  placeholder="{i18n.toDate}" /></m:MaterialColumn>
					    <m:MaterialColumn grid="s4 m2 l2"><m:MaterialTextBox ui:field="cwbNoTextBox"  placeholder="{i18n.cwbNo}"/></m:MaterialColumn>
					    <m:MaterialColumn grid="s4 m2 l2"><m:MaterialTextBox ui:field="orderNoTextBox"  placeholder="{i18n.orderNo}"/></m:MaterialColumn>
				    </m:MaterialRow>	
					</m:MaterialCollapsibleBody>
				</m:MaterialCollapsibleItem>
			</m:MaterialCollapsible>		
			<table:MaterialDataTable ui:field="filesTable" 
								 shadow="1"  
								 height="calc(60vh - 131px)"
	                             useLoadOverlay="false"
	                             useStickyHeader="true"
	                             useCategories="false"
	                             selectionType="NONE"
	                             rowHeight="35"
			/>
		</m:MaterialPanel>
		<m:MaterialPanel m:id="fileDetailsTab" >
			<m:MaterialRow height="35">
				<m:MaterialColumn grid='s4 m2 l2'>	<m:MaterialLabel text="{i18n.name}"/></m:MaterialColumn>
				<m:MaterialColumn grid='s5 m3 l3'>	<m:MaterialLabel ui:field="nameLabel"/></m:MaterialColumn>
				<m:MaterialColumn grid='s4 m2 l2'>	<m:MaterialLabel text="{i18n.createDate}"/></m:MaterialColumn>
				<m:MaterialColumn grid='s4 m2 l2'>	<m:MaterialLabel ui:field="createdLabel"/></m:MaterialColumn>
				<m:MaterialColumn grid='s1 m1 l1'>	<m:MaterialLabel text="{i18n.size}"/></m:MaterialColumn>
				<m:MaterialColumn grid='s1 m1 l1'>	<m:MaterialLabel ui:field="sizeLabel"/></m:MaterialColumn>		
			</m:MaterialRow>
			<m:MaterialRow height="35">
				<m:MaterialColumn grid='s4 m2 l2'>	<m:MaterialLabel text="{i18n.mime}"/></m:MaterialColumn>
				<m:MaterialColumn grid='s4 m2 l2'>	<m:MaterialLabel ui:field="mimeLabel"/></m:MaterialColumn>
			</m:MaterialRow>
			<m:MaterialRow>
				<m:MaterialTextArea ui:field="detailsTextArea" />
			</m:MaterialRow>
		</m:MaterialPanel>
    </m:MaterialContainer>
</ui:UiBinder>

---------------------------------------------------------------------

**Comment by kevzlou7979** [comment]
Check this `m:MaterialTab ui:field="filesTab" backgroundColor="BLUE" indicatorColor="YELLOW">` You have predefined the backgroundColor by blue so it overrides the default dark theme. Dark theme is only be applied on default styles installed to your GMD Application using GwtMaterialThemes.

**Comment by kevzlou7979** [comment]
Remove the backgroundColor=BLUE because by default it uses the materialize.blue.min.css so no need to define it.

**Comment by kevzlou7979** [comment]
There's a way also if you want a custom color in light mode but it will stay black in dark mode.

```java

   @Override
    protected void onAttach() {
        super.onAttach();

        // This will update initial theme if its dark or not
        updateTabColor(DarkThemeManager.get().isDarkMode());
        // Will register a handler to check whether dark theme is turned on or off
        DarkThemeManager.get().addColorSchemeChangeHandler(event -> updateTabColor(event.getColorScheme() == ColorScheme.DARK));
    }

    protected void updateTabColor(boolean dark) {
        filesTab.setBackgroundColor(dark ? Color.GREY_DARKEN_3 : Color.BLUE);
    }
```

**Comment by kevzlou7979** [comment]
![1](https://user-images.githubusercontent.com/3138071/91911894-997c9a00-ece4-11ea-9aef-c6dfe2004d2d.gif)

**Comment by edmiikk** [comment]
Thanks, comprehensively answered.
