### ISSUE TITLE
ServiceWorkerManager.setupRegistration() fails when FCM starts to use the ServiceWorkerRegistration object

### ISSUE THREAD

**Issue by LetsCloud** [GwtMaterialDesign/gwt-material#986]
In the **setupRegistration()** method, of the **ServiceWorkerManager** class, calling the **Navigator.serviceWorker.register()** method waits for TWO parameters in the "**then**" branch of the returned value. However, in MDN Web Docs, there is only ONE parameter in the "**then**" branch of the return value of **ServiceWorkerContainer.register()** method. 
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register

This causes problem for Firebase Messaging because when it starts to use the **ServiceWorkerRegistration** object, the **ServiceWorkerManager.setupRegistration()** method runs on the fail branch (_ServiceWorker registration failed: undefined_).

Since FCM works well with 2.3.1SNAPSHOT, I compared 2.3.1 SNAPSHOT and 2.4.0 RELEASE. In 2.3.1SNAPSHOT, there is only ONE parameter (object) in the **"then"** branch of the returned value of the **Navigator.serviceWorker.register()** method. As a test in 2.4.0 RELEASE, I deleted the parameter **"e"** and everything works fine.
Please delete the parameter **"e"**.
``` java
   /**
     * Initial setup of the service worker registration.
     */
    protected void setupRegistration() {
        if (isServiceWorkerSupported()) {
//          Navigator.serviceWorker.register(getResource(), getOption()).then((e, object) -> {
            Navigator.serviceWorker.register(getResource(), getOption()).then((object) -> {
                logger.info("Service worker has been successfully registered");
                registration = (ServiceWorkerRegistration) object;

                onRegistered(new ServiceEvent(), registration);

                // Observe service worker lifecycle
                observeLifecycle(registration);

                // Setup Service Worker events events
                setupOnControllerChangeEvent();
                setupOnMessageEvent();
                setupOnErrorEvent();
                return null;
            }).fail((e, error) -> {
                logger.info("ServiceWorker registration failed: " + error);
                return null;
            });
        } else {
            logger.info("Service worker is not supported by this browser.");
        }
    }
```
Many thanks,
Robert

**Comment by kevzlou7979** [comment]
We will be releasing 2.4.1 this comming weekend for this and other related
fixes.

**Comment by LetsCloud** [comment]
Thanks!

**Comment by kevzlou7979** [comment]
Confirmed and Reproduced the issue.
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/64f767d415ca59a219c5d4f046e79a8ff29e6b80

**Comment by kevzlou7979** [comment]
As discussed with the Team we will be releasing this next weekend for double checking all instances of the Promise API, and PR will be made so feel free to test it out.

**Comment by kevzlou7979** [comment]
Here's the PR for the hotfixes https://github.com/GwtMaterialDesign/gwt-material/pull/987

**Comment by kevzlou7979** [comment]
2.4.1 is no released
