### ISSUE TITLE
clearHelperText() not working

### ISSUE THREAD

**Issue by c-kob** [GwtMaterialDesign/gwt-material#996]
The clearHelperText() method in the StatusTextMixin is not working, i.e. the helper text is not being removed (whether called directly or through clearStatusText())
The code for this method differs from clearErrorText() and clearSuccessText(), both of which are working as expected (but call applyHelperText() at the end).

**Comment by kevzlou7979** [comment]
Will review this, as the helper text must be visible all the time but yeah it might be good for us to be able to remove the helper text.

**Comment by c-kob** [comment]
Thanks. Maybe just set to empty string (which of course can also be done explicitly)? Or remove the method to avoid confusion.

**Comment by kevzlou7979** [comment]
Yeah, we are accepting pull request feel free to create one

**Comment by kevzlou7979** [comment]
Patched via https://github.com/GwtMaterialDesign/gwt-material/commit/6a7aa5254340de2b452e7b8be1317592b834db45

**Comment by kevzlou7979** [comment]
Will be adding a unit test for this change.

**Comment by kevzlou7979** [comment]
Test Case was added via https://github.com/GwtMaterialDesign/gwt-material/commit/f26f37d0f60187609eb38d81718a520087270c7d
