### ISSUE TITLE
MaterialCollapsible setting active index with 1 as start

### ISSUE THREAD

**Issue by wassx** [GwtMaterialDesign/gwt-material#998]
It seems pretty uncommon why there is a range start from 1 for the index.
`GWT.log("The active index must be a one-base index to mark as active.", new IndexOutOfBoundsException());`
What is the reason for this design please?

**Comment by kevzlou7979** [comment]
Patched the issue and standardized the collapsible item to have a 0-starting based index. https://github.com/GwtMaterialDesign/gwt-material/commit/60d3d2137aa45e4af9f3b5501d774f86e3d364e8

Please review the changes and might be good to test it out too.

**Comment by ingosch** [comment]
setActive(0) is not working cause of condition "index > 0" in line 258. Must be "index >= 0".
